SUSE-Cloud/automation

scripts/mkcloud

separate controller node memory and compute node memory

repair assign controlle_node memory

---

scripts/qa_crowbarsetup.sh

The messing creates unsigned repositories, which is quite
annoying.

qa_crowbarsetup.sh: Don't mess with Cloud-PTF by default

---

scripts/qa_crowbarsetup.sh

This is done by setting hacloud to 2.
(submitting on behalf of Alexandru)

Make it possible to not use test updates for HAE

---

scripts/jenkins/qa_openstack.sh

Needed to setup the right repositories for SLES12.

qa_openstack: detect SLES12 host

---

scripts/mkcloud

same problem with qemu-kvm as admin node is in definition of compute nodes

use variable $emulator in the compute node definition

---

scripts/crowbar-prep.sh
scripts/qa_crowbarsetup.sh

Required for https://github.com/crowbar/crowbar/pull/2080

 	Adapt for repo directory change in Cloud 5

---

scripts/qa_crowbarsetup.sh

**UNTESTED**. And must definitly merged after https://github.com/crowbar/barclamp-neutron/pull/175 and https://github.com/crowbar/barclamp-nova/pull/419 .
Due to changes in barclamp-neutron, new attribute names must be used.
Also enable gre and vlan ml2 type drivers in parallel when using
openvswitch.

qa_crowbarsetup: Adjust neutron proposals for Cloud5+

---

scripts/qa_crowbarsetup.sh

Remove all existing repos: no more and no less.

qa_crowbarsetup.sh: improve removal of zypp repos

---

scripts/mkcloud

Since mkcloud isn't (yet) gated on itself (BTW it should be),
this needs more testing before merge, but it's ready for review.

miscellaneous refactorings and bug fixes

---

scripts/mkcloud

I have a lot of these but I'm going to drip-feed them to avoid overwhelming people with giant PRs.

Misc cleanups

---

scripts/qa_crowbarsetup.sh

Fix adding Cloud 3 Pool repo

---

scripts/mkcloud

Waiting is boring. Just continue...

mkcloud: remove sleep before hacloud setup

---

scripts/qa_crowbarsetup.sh

This is a universally adopted convention.

qa_crowbarsetup.sh: make local variables lowercase

---

scripts/qa_crowbarsetup.sh

Proposed instead of: https://github.com/SUSE-Cloud/automation/pull/216

qa_crowbarsetup: rewrite onadmin_get_ip_from_dhcp in awk

---

scripts/qa_crowbarsetup.sh

This will really matter, because of https://github.com/crowbar/crowbar/pull/2086 and https://github.com/SUSE-Cloud/suse-cloud-upgrade/pull/43

qa_crowbarsetup: Always properly setup SUSE-Cloud-5-{Pool,Updates} repos

---

scripts/mkcloud

otherwise there would be an `Error:` for every line

mkcloud: complain only once per line

---

README.md

README.md: make mkcloud documentation more visible

---

scripts/mkcloud

Reverts SUSE-Cloud/automation#226
It introduces a rather arbitrary indentation. See https://github.com/SUSE-Cloud/automation/pull/204#discussion_r25132812

Revert "mkcloud: complain only once per line"

---

scripts/qa_crowbarsetup.sh

These steps should really not belong to the crowbar-backup script, so
import them here instead.

[untested] mkcloud: Do not rely on crowbar-backup for purge and installing packages

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

this allows it to be used separately

qa_crowbarsetup: split purge from restore function

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

and crowbarbackup fixes+cleanup

better wait on volume attach

---

scripts/qa_crowbarsetup.sh

this allows to test gre again on cloud5 (might be broken atm from
https://bugzilla.suse.com/show_bug.cgi?id=917328 )

make use of networkingmode variable

---

scripts/qa_crowbarsetup.sh

These assignments have no impact on behaviour.

qa_crowbarsetup.sh: remove pointless assignments

---

scripts/qa_crowbarsetup.sh

In HA mode these variables had the cluster alias name until now. Setting it to the first node now, to fix the renaming of a machine (via set_node_alias) to finally allow something like "ssh dashboard".

resolve nova{controller,dashboardserver} variables to first node in HA mode

---

scripts/qa_crowbarsetup.sh

we had 12x duplicated ruby json parser code
which is now moved to a single place in the rubyjsonparse function

qa_crowbarsetup: DRY rubyjsonparse function

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

* debug_mkcloud
* debug_qa_crowbarsetup
* debug_openstack

mkcloud/qa_crowbarsetup: add debug options

---

scripts/mkcloudhost/correlatevirsh
scripts/mkcloudhost/fixlibvirt

Add remaining tools that we use on the mkcloud hosts

Remaining mkcloud tools

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

This also works when the host has 127.0.0.1 in its resolv.conf
This is an alternative to pull-request #273

mkcloud: simpler resolv.conf handling

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

Neutron roles are renamed in https://github.com/crowbar/barclamp-neutron/pull/210

neutron-l3 role is renamed to neutron-network

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

we also enable cinder+neutron SSL now, if requested by mkcloud user

SSL refactoring + updates for Cloud 4+5

---

scripts/jenkins/qa_openstack.sh

Add option to be able to run Kilo packaged version.

qa_openstack: Prepare for Kilo tests

---

scripts/qa_crowbarsetup.sh

enable simultaneous deployment of netapp nfs and iscsi storage protocol via:
* cinder_backend=netapp
* want_cindermultibackend=1
QA:
``` bash
export cinder_backend=netapp
export cinder_netapp_login=openstack
export cinder_netapp_password="[SECRET]"
export want_cindermultibackend=1
```

qa_crowbarsetup: cinder netapp multi-backend

---

scripts/lib/mkcloud-libvirt.sh
scripts/mkcloud

This split-off would be a first step for refactoring

mkcloud: extract VM and network creation into a separate script

---

Makefile
README.md
scripts/repochecker

When checking a :Staging project, also add the non-staging version to
solve dependencies.

repochecker: Fix :Staging case

---

scripts/mkcloud

This code is already being executed in [lib/mkcloud-libvirt.sh](https://github.com/SUSE-Cloud/automation/blob/master/scripts/lib/mkcloud-libvirt.sh#L24)

mkcloud: remove duplicate file cleanup

---

scripts/lib/libvirt/cleanup.py
scripts/lib/libvirt/net-start.py
scripts/lib/libvirt/vm-start.py

We need to set some order of the string interpolation
otherwise we get a ValueError: zero length field name in format

fix format function for python < 2.7

---

docs/mkcloud.md

This depends on #318 and #323, and maybe also #325.

mkcloud.md: document use of PTF packages

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

this is already added by the complain function

mkcloud: drop redundant Error: string

---

scripts/mkcloud

1. drop transitioning code
2. use wrapper to create LVs to be able to handle VGs which have PVs of different sizes (otherwise they are limited to the size of the smallest PV).

Lvcreate wrapper

---

scripts/qa_crowbarsetup.sh

qa_crowbarsetup: add SLE-12-Updates

---

scripts/lib/libvirt/fixtures/cloud-node1.xml
scripts/lib/libvirt/libvirt_setup.py
scripts/lib/libvirt/test_libvirt_setup.py

only the dashboard/controller node should get extra memory
which is needed for tempest etc.

fixup! libvirt_setup.py: a python module for libvirt resource handling

---

scripts/lib/libvirt/libvirt_setup.py

Superseeds  #364
Breaks down the patch into multiple commits.

Refactors libvirt_setup.py

---

scripts/github-status/Gemfile
scripts/github-status/github-status.rb

The tool to interact with the github api, needed for the mkcloud self-gating.

github-status: initial script to fetch and set github pr status

---

scripts/qa_crowbarsetup.sh

This task was defined in 
https://trello.com/c/qg2oVp3W/400-3-p5-bnc-932270-image-creating-stuck-at-queued-when-using-ceph-and-openstack-client-command

Replace glance with openstack client

---

scripts/github-status/github-status.rb

no not trigger automatic builds of anybodys PR for obvious reason

only trigger builds of our own PRs

---

scripts/mkcloud

add support for setup of mixed Physical and Virtual cloud

---

scripts/qa_crowbarsetup.sh

Also deploy ceilometer-swift-proxy-middleware if swift is being deployed.

Deploy ceilometer-server role to SLE12 controller if there's one.

---

scripts/qa_crowbarsetup.sh

See http://bugzilla.opensuse.org/show_bug.cgi?id=934642

Revert cinder on sle12 - does not work

---

scripts/qa_crowbarsetup.sh

needs fixed https://bugzilla.suse.com/show_bug.cgi?id=927174
we also want to verify the HTTPS cert,
so we use the cert repo+rpm
which is verified by a build key that is not part of SP3,
so we add and verify that first.

qa_crowbarsetup: use real qa-automation repo

---

scripts/qa_crowbarsetup.sh

We need to wait for openstack services to be back online
before talking to them. This used to work before apparently
by accident because reboot is a lot slower with SLE11.

qa_crowbarsetup.sh: Make reboot_nodes more robust

---

scripts/qa_crowbarsetup.sh

We would like to test Glance scrubber 
https://bugzilla.suse.com/show_bug.cgi?id=930739
It depends on 
https://github.com/crowbar/barclamp-glance/pull/268
https://github.com/crowbar/barclamp-glance/pull/269

Add test for Glance scrubber service, (bnc#930739)

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

Remove Cloud 3.x related cloudsources, add susecloud6/Milestone
targets.

Start cloud 6.x development

---

Makefile
scripts/jenkins/jenkinslog

plus fix some newly discovered warnings

enable more syntax checking with warnings

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

This a proposal for the cct support like we discussed during our meeting on 2015-07-02.
extended by rick

CCT Support

---

scripts/jenkins/japi

pushing jobs to jenkins was broken
as explained in the 2nd commit

japi fixes

---

scripts/mkcloud

@nkrinner had this idea and I like it as it saves you a lot of scrolling time.

Add a command to print only usage info about steps

---

scripts/mkcloud

this means we no more need to use the offset of partitions
code worked for me in simple tests

mkcloud: stop using loop devices for partition access

---

scripts/mkcloud

https://trello.com/c/xXhjGZzs/859-3-sle12-prepare-mkcloud-to-start-sle12-for-admin-server

preparations for crowbar on sle12

---

scripts/jenkins/ci.suse.de/cloud-mkcloud6-docker-trigger.xml
scripts/jenkins/ci.suse.de/cloud-mkcloud6-ha-trigger.xml
scripts/jenkins/ci.suse.de/cloud-mkcloud6-ssl-trigger.xml
scripts/jenkins/ci.suse.de/cloud-mkcloudGM4-trigger.xml
scripts/jenkins/ci.suse.de/cloud-mkcloudGM5-trigger.xml

This way one can at least see that the trigger is still
running.

Switch to a build-trigger instead of a post-build-trigger

---

scripts/qa_crowbarsetup.sh

Not tested yet, waiting for admin node to get sle12.

Make cct run for cloud 5 and 6

---

scripts/qa_crowbarsetup.sh

SLE11 media is no longer available for Cloud 6.

Use SLE12 only media for Cloud 6

---

scripts/github-status/github-status.rb

This could come in handy in scripting scenarios.

add get-pr-info action

---

docs/mkcloud.md
scripts/mkcloud

This should prevent confusion when newbies start to work with mkcloud.

mkcloud: documenting that the last version is the devel version

---

scripts/qa_crowbarsetup.sh

We used SLE11_SP3 repos on SLE12, this change fixed this behavior.

Fix testsetup on cloud 6plus

---

scripts/qa_crowbarsetup.sh

This is just very convulved dead code.

Code cleanup

---

scripts/qa_crowbarsetup.sh

On SLE12, named is a compat sysv init script which relies on
$remote_fs to finish starting. if we have remote mounts
that depends on DNS resolution, we don't get it started automatically
since the remote mounting fails.

qa_crowbarsetup.sh: mount remote nfs mounts by IP address

---

scripts/qa_crowbarsetup.sh

Please do not merge this until the mkcloud gating job turns green.

Reenable test update channel

---

scripts/qa_crowbarsetup.sh

Based on jsuchome's work, extract the DNS nameserver from the
subnet information, using neutron.
The DNS server is the first IP of the allocation pool (method
used here) or the second from the network range.

Set dns-nameserver for subnet for docker instances

---

scripts/github-status/github-status.rb

Support to filter the PR listing by branch name.
If not filtered all PRs with all target branch names are listed, otherwise its filtered by target branch name.

github-status: allow to filter pr lists by branch name

---

scripts/qa_crowbarsetup.sh

With this change the environment variable "want_mtu_size" can be used to set desired MTU size for Admin and Storage nodes. Setting want_mtu_size value to "jumbo" makes it to take the maximum MTU size feasible (8900) for these nodes. The qa_crowbarsetup.sh is modified to change the 'network' proposal to set the MTU value.

Changes to allow setting of MTU size and jumbo frames.

---

scripts/qa_crowbarsetup.sh

See commit 76915919a613cdc4a70257a6394f06395df3bc2e for more details.

Raise timeout to 1000 to avoid test failures for now

---

scripts/jenkins/ci.suse.de/cloud-crowbar-testbuild-pr-trigger.xml

I just love refactoring. Really.

Fix PR testing again

---

scripts/jenkins/ci.suse.de/cloud-mkcloud4-crowbar_register-trigger.xml
scripts/jenkins/ci.suse.de/cloud-mkcloud4-ovsvlan-trigger.xml
scripts/jenkins/ci.suse.de/cloud-mkcloud4-tempestfull-trigger.xml
scripts/jenkins/ci.suse.de/cloud-mkcloud4-trigger.xml
scripts/jenkins/ci.suse.de/cloud-mkcloudGM4-trigger.xml

They all need to be changed to block for the triggered job result in order to have the weather report working.

Fix cloud4.x related triggers

---

scripts/jenkins/qa_openstack.sh

glanceclient from liberty no longer outputs a status field when
calling "glance image-create". This leads to a long (60*5 s) waiting
time after creating a glance image due to our current wait loop.
Use the "--poll" option to wait until the image creation process is done
instead of the loop.

qa_openstack: Fix glance image-create wait

---

scripts/jenkins/ci.opensuse.org/openstack-repocheck.xml

Noone tests it, noone fixes it, noone cares about it.

Remove repochecks for openSUSE 13.1

---

scripts/qa_crowbarsetup.sh

There's a Manila barclamp for Cloud 5 available. Deploy it.

Also deploy manila on Cloud 5

---

scripts/qa_crowbarsetup.sh

/var/lib/Cloud-Testing is a better place.

Don't use /tmp to mount test iso

---

scripts/lib/libvirt/compute-config
scripts/lib/libvirt/libvirt_setup.py
scripts/lib/libvirt/test_libvirt_setup.py
scripts/mkcloud
scripts/qa_crowbarsetup.sh

tested with 2 nodes: controller gets RAID

create RAID just for the controller node

---

scripts/qa_crowbarsetup.sh

Editing autoyast.xml is no longer required as the bug is fixed. Changing
a few things in the autoyast.xml.erb for addressing this bug
(bnc#935283) will eventually break this.

Disable setting partitions in autoyast.xml.erb (bsc#770083 is fixed)

---

scripts/qa_crowbarsetup.sh

Depends on https://github.com/crowbar/crowbar-openstack/pull/21

Rename barclamp nova_dashboard to horizon

---

scripts/qa_crowbarsetup.sh

When doing HA, we can't reboot all nodes in a cluster in parallel as
pacemaker can't figure out by itself what to do when they all boot
together.
So instead, we reboot one by one each node of each cluster. And then, we
reboot all the other nodes in parallel.
This doesn't simulate a power failure for the whole cloud, but that
would be another test case (that won't work for HA).

qa_crowbarsetup: Fix rebootcloud for HA

---

scripts/qa_crowbarsetup.sh

If we reboot nodes of a HA cluster using drbd and some drbd devices are
not synchronized, then the drbd master won't be migrated.

qa_crowbarsetup: Wait for drbd devices to be synchronized before reboot

---

scripts/qa_crowbarsetup.sh

qa_crowbarsetup: avoid ssh warnings

---

scripts/qa_crowbarsetup.sh

The basic test to attach a volume, create a fs, write something detach it
and attach it again needs some more time to not error out.
Use the already available "wait_for" function to check for the current
volume state before doing the next step.

qa_crowbarsetup: Wait longer for volume detach/attach

---

scripts/mkcloud

Depends on https://review.openstack.org/#/c/223569/

Update Rally call using the CLI from upstream

---

scripts/qa_crowbarsetup.sh

cleaning up all while loops and endless loops in qa_crowbarsetup to prevent hanging mkcloud runs due to loops that never finish

while loop cleanup and wait_for function improvements

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

First part is based on user's input.
Aliases are needed for referencing the nodes in scenario files.
In next steps, we'll like to have some logic to assign aliases automatically.

Added mkcloud step for assigning aliases to the nodes

---

scripts/qa_crowbarsetup.sh

This was forgotten in 998e3081.

qa_crowbarsetup: Remove test for undefined variable

---

scripts/mkcloud

(batch step replaces proposal with custom scenario setup)

added aliases for build with batch step

---

scripts/jenkins/ci.suse.de/openstack-mkcloud.xml
scripts/qa_crowbarsetup.sh

We need at least two nodes for Ceph/SES2 deployment.

Test linuxbridge on develcloud6 with 4 nodes

---

scripts/mkcloud

This avoids not being able to write to block 0 on newer
qemu's

mkcloud: specify output format to raw

---

scripts/qa_crowbarsetup.sh

Another fix to unbreak ci for cloud 5

Fix crowbar_register on sles12 for cloud 5 setups

---

scripts/qa_crowbarsetup.sh

description update:
because we need to be able to test liberty before breaking everything for everyone

support cloudsource=libertycloud6

---

scripts/qa_crowbarsetup.sh
scripts/scenarios/cloud6/cloud6-2nodes-default.yml

See https://github.com/crowbar/crowbar-openstack/pull/68

qa_crowbarsetup: Update after change of nova roles names

---

scripts/qa_crowbarsetup.sh

--copy-from was deprecated in Kilo and got removed in Liberty, so
we need to upload the image now differently

Fix image upload for Liberty and newer

---

scripts/qa_crowbarsetup.sh

For Cloud 6 (after M6), we don't specify custom repositories in the
provisioner barclamp, but in /etc/crowbar/repos.yml.
This is needed for the changes in https://github.com/crowbar/crowbar-core/pull/102

qa_crowbarsetup.sh: Create /etc/crowbar/repos.yml for Cloud 6

---

scripts/mkcloud

make a failure more prominent by using the complain function on failure

use complain in setuphost function instead of exit

---

scripts/qa_crowbarsetup.sh

Added options to set intended roles and target OS (platform) of the nodes.
Tested with
want_node_roles=controller=2,compute=2,storage=3
want_node_os=suse-12.1=4,suse-12.0=3
want_node_aliases=controller=2,compute=2,ceph=3

Let user decide nodes platforms and roles. (+ fix for aliases)

---

scripts/qa_crowbarsetup.sh

Support for multiple architectures

Multi arch

---

scripts/qa_crowbarsetup.sh

I've seen it fail in recent builds at ceilometer step...

increase the timeout for crowbar_batch command

---

scripts/scenarios/cloud6/qa-scenario-6a-ipmi-kvm-docker.yaml

Needs manual SBD setup as described in https://etherpad.nue.suse.com/p/cloud-setup-qa-scenarios
and also manual setup of an nfs server for shared storage. The servers ip address needs to be added in yaml

Scenario 6a

---

scripts/qa_crowbarsetup.sh

With Liberty, the openstack CLI is not able to retrieve and image by
its name, as it is used in qa_crowbarsetup.sh. This patch substitutes
those calls to glance image commands.

Using glance image instead of openstack image

---

README.md
scripts/jenkins/jobs-obs/macros.yaml
scripts/jenkins/jobs-obs/openstack-cleanvm.yml

This commit uses a yaml file to describe the openstack-cleanvm job.

jenkins: Introduce jenkins-job-builder for jobs

---

scripts/scenarios/cloud6/qa-scenario-2b-sbd-kvm-vmware.yaml

More details at https://trello.com/c/6r85jCnr/641-5-s29p1-qa-infra-mkcloud-ha-sbd-scenario-with-kvm-vcenter-config-2b

Add 2b scenario with kvm and vmware compute nodes

---

scripts/mkcloud

This should avoid issues during shutdown caused by
https://bugzilla.suse.com/show_bug.cgi?id=955770

Increase controller memory to 6GB

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

small refactoring, needed for the next PR to support the new installer

Installer refactoring

---

scripts/qa_crowbarsetup.sh

qa_crowbarsetup: fix milestone regexp

---

scripts/qa_crowbarsetup.sh

Supporting the new crowbar installer in mkcloud and qa_crowbarsetup.

Support new crowbar installer

---

scripts/qa_crowbarsetup.sh

the route has changed in the last minute and we forgot to change it here

the route has changed

---

scripts/qa_crowbarsetup.sh

qa_crowbarsetup: Fix installer call

---

scripts/qa_crowbarsetup.sh

should make mkcloud more accessible to non-R&D employees

Repo rework

---

scripts/qa_crowbarsetup.sh

These regressions were merged in https://github.com/SUSE-Cloud/automation/pull/654
and ignored in the review comments

Fix issues in installer refactoring

---

scripts/scenarios/cloud6/qa-scenario-2a-sbd-kvm.yaml

Contains yaml config for crowbar batch.
More on this at https://trello.com/c/Y4pfBThl/680-3-s32p3-qa-infra-mkcloud-ha-scenario-with-kvm-config-2a

Add 2a scenario with HA, sbd and kvm

---

scripts/scenarios/cloud6/qa-scenario-1b-ipmi-kvm-xen.yaml
scripts/scenarios/cloud6/qa-scenario-2a-sbd-kvm.yaml
scripts/scenarios/cloud6/qa-scenario-2b-sbd-kvm-vmware.yaml
scripts/scenarios/cloud6/qa-scenario-2c-sbd-kvm.yaml
scripts/scenarios/cloud6/qa-scenario-6a-ipmi-kvm-docker.yaml

Wrong value "de-de" is replaced with correct one "de".

Fix vnc_keymap in scenario files

---

scripts/qa_crowbarsetup.sh

Install python-manilaclient-test on Control node during mkcloud testsetup

install python-manilaclient-test

---

scripts/qa_crowbarsetup.sh

cct needs bundler-deps installed, which we can get from SDK.

Use SLE12 SP1 SDK for installing ruby2.1/bundler

---

scripts/qa_crowbarsetup.sh

to run it just once.
Before this it ran for every proposal
This is a refinement of c31b7ecc01799bdee5bd1d72cc7d754f0a2d17d6

qa_crowbarsetup: move ceilometer detection code

---

scripts/crowbar-testbuild.py

We'd like to test those in a hyperv enabled environment.

Fix PR trigger for hyperv related repositories

---

scripts/mkcloud

I guess that it can slow down or crash the host

mkcloud: make ksm honor NUMA boundaries

---

scripts/scenarios/cloud6/cloud6-2nodes-default.yml

Regression from the switch to crowbar_batch

Deploy in CustomRegion again to test multi-region capability

---

scripts/qa_crowbarsetup.sh

Nova volume is deprecated at least since Grizzly, and
meanwhile it spits out deprecation warnings.

Switch to cinderclient instead of using nova volume

---

scripts/jenkins/ci.suse.de/openstack-mkcloud.xml

The hybrid backend was ported to Liberty, so start testing
it.

Reenable ldap testing in non-batch

---

scripts/qa_crowbarsetup.sh

This is needed for the s390x compute node support

Mount s390x related SLES media

---

scripts/iscsictl.py

This try to fix some weird connection issues seems in QA2

iSCSI: Add --no-key option

---

scripts/scenarios/cloud6/qa-scenario-1b-ipmi-kvm-xen.yaml
scripts/scenarios/cloud6/qa-scenario-2a-sbd-kvm.yaml
scripts/scenarios/cloud6/qa-scenario-2c-sbd-kvm.yaml
scripts/scenarios/cloud6/qa-scenario-6a-ipmi-kvm-docker.yaml

and add empty lines between sections for better visual parsing.

Remove swift attributes for trove

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

to make it easy to find the job that created a cloud the /etc/motd shows the relevant jenkins information incl. the job URL

mkcloud, qa_crowbarsetup: show info about jenkins job in /etc/motd

---

scripts/qa_crowbarsetup.sh
scripts/scenarios/cloud6/cloud6-2nodes-default.yml

This requires the scenarios to be updated with the right config values
and placeholders.

qa_crowbarsetup: Make manila with generic driver work with scenarios

---

scripts/qa_crowbarsetup-test.sh
scripts/qa_crowbarsetup.sh

allow to use tests like iscloudver 6M8plus
compared to the old method, this will also work well with milestones >= 10

Cloudver improvements

---

scripts/scenarios/cloud6/qa-scenario-2b-sbd-kvm-vmware.yaml

The insecure attribute got added end of November...
cc @mjura @vmoravec

Update scenario-2b for vmware-related attributes that got added

---

scripts/scenarios/cloud6/qa-scenario-1b-ipmi-kvm-xen.yaml
scripts/scenarios/cloud6/qa-scenario-2a-sbd-kvm.yaml
scripts/scenarios/cloud6/qa-scenario-2b-sbd-kvm-vmware.yaml
scripts/scenarios/cloud6/qa-scenario-2c-sbd-kvm.yaml
scripts/scenarios/cloud6/qa-scenario-6a-ipmi-kvm-docker.yaml

Change scenarios to not be impacted by SSL issues with insecure option

---

scripts/qa_crowbarsetup-test.sh
scripts/qa_crowbarsetup.sh

5minus is pretty much equivalent to ! 6plus
but might be easier to read

qa_crowbarsetup: add iscloudver 5minus

---

scripts/qa_crowbarsetup.sh

The latest changes to the installer require changes to the automation.
The path of the installer changed. This PR checks for the availability of the new path and falls back to the old path if this fails.

qa_crowbarsetup: support final installer path in parallel

---

scripts/qa_crowbarsetup.sh

The image doesn't launch on Xen HVM, so don't even bother trying..

Launch the SP3-64.qcow2 file on KVM nodes only

---

scripts/qa_crowbarsetup.sh

only when requested with want_s390=1

qa_crowbarsetup: add s390 repos

---

scripts/scenarios/cloud6/qa/no-ssl/qa-scenario-1b-ipmi-kvm-xen.yaml
scripts/scenarios/cloud6/qa/no-ssl/qa-scenario-6a-ipmi-kvm-docker.yaml
scripts/scenarios/cloud6/qa/ssl-insecure/qa-scenario-1b-ipmi-kvm-xen.yaml
scripts/scenarios/cloud6/qa/ssl-insecure/qa-scenario-6a-ipmi-kvm-docker.yaml

The tests are run on QA2 hardwre, and using QA3 shares is
going to fail..

Don't hardcode QA3 shared filesystems

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

Adds backup and restore for Cloud6.
This will allow to test the functionality of the upgrade process earlier (upgrade will folllow as part or PR #716 ).

Backup restore cloud 6

---

scripts/jenkins/jobs-ibs/cloud-mkcloud6-job-backup-restore.yaml

This is slightly temporary, to be included in cloud6 gating
job.

Add JJB for backup+restore on cloud6

---

scripts/qa_crowbarsetup.sh

Adding a few more sleeps hopefully makes things more reliable.

Be more gentle to slower IPMI controllers

---

scripts/qa_crowbarsetup.sh

If any of them is in failed state, something is wrong..

Verify that no neutron port is in failed state

---

scripts/qa_crowbarsetup.sh

Horrible workaround for crowbar bug. Crowbar first sets
the node state to "discovered", and then goes through and
calls the transition hooks over all barclamps, which can take
quite a while. However, if we move forward already we're causing
tons of stress on crowbar with the node rename, and then it will
just run into races. Actual fix would be to only change the
state once the state is actually changed. (d'oh!)

Avoid node update races on allocation

---

scripts/qa_crowbarsetup.sh

when we run a scenario with less than the total number of nodes,
the extra nodes need to be powered down to not disturb the scenario.

Power off extra nodes in a physical environment

---

scripts/qa_crowbarsetup.sh

this prevents useless warning messages in wait_for loops

prevent useless logging when parsing empty string as json

---

scripts/scenarios/cloud6/qa/no-ssl/qa-scenario-1a-ha-kvm-swift.yaml
scripts/scenarios/cloud6/qa/ssl-insecure/qa-scenario-1a-ha-kvm-swift.yaml

The previous scenario file was not deploying services
like requested in the trello card.

Fix node alias names and deploy services properly

---

scripts/qa_crowbarsetup.sh

this is a cleaner approach, reflecting the way a customer would set this.

qa_crowbarsetup: set rootpw via proposal (bsc#964624)

---

scripts/jenkins/jenkins_jobs.ini.sample
scripts/jenkins/jobs-ibs/cloud-mkcloud6-job-hyperv.yaml

jenkins: add cloud-mkcloud6-job-hyperv

---

scripts/qa_crowbarsetup.sh

When testing manila, use the floating network instead of a dedicated
network for the connection between the manila-share service and the
manila service instance.
Using a dedicated network worked fine with linuxbridge+vlan but there
are problems with openvswitch+vlan so simplify the setup to workaround
the current problems.

qa_crowbarsetup: Use floating network for manila

---

scripts/scenarios/cloud6/qa/no-ssl/qa-scenario-3a-kvm-hyperv.yaml
scripts/scenarios/cloud6/qa/no-ssl/qa-scenario-6a-ipmi-kvm-docker.yaml
scripts/scenarios/cloud6/qa/ssl-insecure/qa-scenario-6a-ipmi-kvm-docker.yaml

The images need to be on shared storage.

Fix glance image hosting in HA cluster

---

scripts/scenarios/cloud6/qa/no-ssl/qa-scenario-1a-ha-kvm-swift.yaml
scripts/scenarios/cloud6/qa/no-ssl/qa-scenario-3a-kvm-hyperv.yaml
scripts/scenarios/cloud6/qa/ssl-insecure/qa-scenario-1a-ha-kvm-swift.yaml

QA scenarios: Fix use of wrong vnc keymap (bsc#966050)

---

scripts/jenkins/jobs-ibs/cloud-mkcloud4-gating.yaml
scripts/jenkins/jobs-ibs/cloud-mkcloud5-gating.yaml
scripts/jenkins/jobs-ibs/cloud-mkcloud6-gating.yaml
scripts/jenkins/jobs-ibs/cloud-mkcloud6-suse.yaml

More consistent with the rest of the JJB managed jobs

Remove -trigger suffix

---

scripts/qa_crowbarsetup.sh

this should make error output more readable

qa_crowbarsetup: fail on manila instance failure

---

scripts/qa_crowbarsetup.sh

This should fix the errors we see with the backup and restore tests, because the restore is now happening in background and the current code did not wait for the restore to finish.

add wait_for loop for restore procedure

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

Upgrade workflow for Cloud5 to Cloud6 upgrade (except node upgrade)

Upgrade support Cloud5 to Cloud6

---

scripts/qa_crowbarsetup.sh

drop another static wait and two curl requests with 60s timeout in favor of a wait_for loop to wait until the crowbar api is available

replace sleep with a wait_for loop

---

scripts/jenkins/jobs-obs/openstack-trackupstream.yaml

Lets start working on cloud 7.

Reenable trackupstream for Master

---

scripts/scenarios/cloud6/cloud6-4nodes-compute-ha.yml

default_share_type was missing;

batch: Fix manila setup in cloud6-4nodes-compute-ha.yml

---

scripts/qa_crowbarsetup.sh

this got broken in refactoring commit e1a090728

qa_crowbarsetup: dont continue on crowbar install failure

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

The upgrade workflow with an upgrade differs from the one without upgrade (backup and restore on the same cloud release).
This PR implements the restore for the upgrade case.

fix upgrade restore workflow

---

scripts/github-status/github-status.rb

to allow multiple builds per PR
or
to allow other teams to use this script

github-status: support dynamic context string

---

scripts/jenkins/jobs-obs/openstack-cleanvm.yaml
scripts/jenkins/jobs-obs/openstack-repocheck.yaml
scripts/jenkins/jobs-obs/openstack-submit.yaml

Not updating trackupstream yet because Mitaka is still a copy
of Master

Add Jenkins jobs for Mitaka

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

Use consistent parameter (same as for restore) in upgrade mode.

differentiate backupmodes on cloud5

---

scripts/qa_crowbarsetup.sh

now a want_all_debug=1 should end up in a deployment with
debug enabled.

Add option to enable proposal debug setting

---

scripts/crowbar-testbuild.py
scripts/mkcloud
scripts/qa_crowbarsetup-test.sh
scripts/qa_crowbarsetup.sh

Also remove susecloud6 (no longer supported).

mkcloud: add develcloud7/susecloud7

---

scripts/jenkins/jobs-obs/openstack-repocheck.yaml

There is no 13.2 anymore for mitaka, don't try to run it

Fix filter for Mitaka

---

scripts/jenkins/qa_devstack.sh

qa_devstack: Fix C:O:Master repo for SLE-SP1

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

during cloudupgrade step also trigger the nodeupgrade
with this also the testsetup step after cloudupgrade will be possible

support crowbar node upgrade

---

scripts/qa_crowbarsetup.sh

In order to allow mkcloud to be run with a custom clouddata mirror
(using $clouddata variable) the admin node image needs to forget all
repos and add back the repos using $clouddata.

qa_crowbarsetup: consistent admin node repos

---

scripts/qa_crowbarsetup.sh

to allow for offline operation

qa_crowbarsetup: dont hardcode suse.de addrs

---

scripts/qa_crowbarsetup.sh

depends on ~~https://github.com/crowbar/crowbar-core/pull/428~~ https://github.com/crowbar/crowbar-core/pull/420

use json route to avoid redirection

---

scripts/jenkins/jobs-ibs/cloud-mediacheck.yaml

~~Depends on https://github.com/SUSE/cloud/pull/101 to fully work.~~

mediacheck: Add support for Cloud 6 deps ISO

---

scripts/qa_crowbarsetup.sh

also don't use progress, and be more verbose when logging the error

handle other error cases when downloading manila image

---

scripts/qa_crowbarsetup.sh

Needed for qa cloud hw upgrade process

Add function to reapply openstack proposals (refactoring)

---

scripts/jenkins/qa_openstack.sh

Let openstack-loopback-lvm from openstack-quickstart do the
LVM volume group setup.

qa_openstack: Adjust VG setup

---

scripts/jenkins/jobs-ibs/cloud-mkphyscloud-qa-scenario-0a.yaml
scripts/jenkins/jobs-ibs/cloud-mkphyscloud-qa-scenario-1a.yaml
scripts/jenkins/jobs-ibs/cloud-mkphyscloud-qa-scenario-1b.yaml
scripts/jenkins/jobs-ibs/cloud-mkphyscloud-qa-scenario-2a.yaml
scripts/jenkins/jobs-ibs/cloud-mkphyscloud-qa-scenario-2b.yaml
scripts/jenkins/jobs-ibs/cloud-mkphyscloud-qa-scenario-2c.yaml
scripts/jenkins/jobs-ibs/cloud-mkphyscloud-qa-scenario-3a.yaml
scripts/jenkins/jobs-ibs/cloud-mkphyscloud-qa-scenario-6a.yaml
scripts/jenkins/jobs-ibs/macros.yaml

This is mostly copy&paste of the currently available jobs.
Only a single macro was added for unification.

Convert QA scenario jobs to JJB

---

scripts/jenkins/jobs-obs/openstack-cleanvm.yaml

Icehouse is no longer maintained.

Remove cleanvm Icehouse job

---

scripts/jenkins/qa_openstack.sh

Use /tmp/openstackquickstartrc when debugging qa_openstack.

qa_openstack: Also install openstackquickstartrc

---

scripts/qa_crowbarsetup.sh

~~depends on https://github.com/crowbar/crowbar-core/pull/453 (and its backport, https://github.com/crowbar/crowbar-core/pull/454 which doesn't exist yet)~~

use json endpoints to avoid redirection

---

scripts/jenkins/jobs-ibs/templates/cloud-mkcloud-job-mitaka-template.yaml

We want the mitaka job to run whenever a new media is being built.

Fix triggering condition for mitaka job

---

scripts/qa_crowbarsetup.sh

During the upgrade the manila service vm is shutdown. So when before
re-applying the manila barclamp check for the state of the manial-service
instance. If it exists and is in state "SHUTOFF" restart it. If it does not
exist boot a new instance. Otherwise assume it's running.
Additional fix: Set OS_TENANT_NAME to "manila-service" also if the Project
already exists.

Fix handling of manila service instance during upgrade

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

This currently does not adapt the pacemaker proposal, but if you're running mkcloud with 'instonly', it already saves some manual steps...
Update: now it also modifies pacemaker proposal.

Added option to prepare SBD setup for cluster nodes.

---

scripts/qa_crowbarsetup.sh

Cloud 5 jobs fails because of this issue.

Fix syntax error

---

scripts/qa_crowbarsetup.sh

The old nova-manage command is deprecated

Use nova service-list for newer Cloud versions

---

scripts/qa_crowbarsetup.sh

Detecting the uuid and floating IP of the VM is now handled
in a single place.

qa_crowbarsetup: Remove duplicated manila code

---

scripts/jenkins/qa/cloud-mkphyscloud-qa-scenario-1a.yaml
scripts/jenkins/qa/cloud-mkphyscloud-qa-scenario-1b.yaml
scripts/jenkins/qa/cloud-mkphyscloud-qa-scenario-2a.yaml
scripts/jenkins/qa/cloud-mkphyscloud-qa-scenario-2b.yaml
scripts/jenkins/qa/cloud-mkphyscloud-qa-scenario-3a.yaml
scripts/jenkins/qa/cloud-mkphyscloud-qa-scenario-6a.yaml

The nfs server on the cloud QA jenkins node will be used.

Change nfs storage for QA scenario jobs

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

via want_sles12sp2=1
based on #999

support SP2 in cloud7 as an option

---

scripts/lib/mkcloud-libvirt.sh

On port 5000 we have the crowbar development server running so we
should also forward this port automatically.

Port 5000 forwarding

---

scripts/qa_crowbarsetup.sh

qa_crowbarservice: fix service-list command in nova.

---

scripts/jenkins/qa/cloud-mkphyscloud-qa-test-cct-job.yaml
scripts/jenkins/qa/cloud-mkphyscloud-qa-test-tempest-defcore.yaml
scripts/jenkins/qa/cloud-mkphyscloud-qa-test-tempest-full.yaml
scripts/jenkins/qa/cloud-mkphyscloud-qa-test-tempest-smoke.yaml
scripts/jenkins/qa/cloud-mkphyscloud-qa-tests-trigger.yaml

The jobs were already in use for some time, this PR converts them into JJB

Convert qa tests trigger and jobs for tempest and cct to jjb

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

This changes makes it easy for all crowbar developers to use the crowbar
development setup. Specially for newcommers this change is important.

Add mkcloud step to presetup the crowbar development setup

---

scripts/qa_crowbarsetup.sh

split out repo changes and use it in addupdaterepo
so that we can install createrepo from an existing repo
dont append a trailing slash to UPDATEREPOS so that we can use it to fetch a single rpm.

improve addupdaterepo to work offline and for single rpms

---

scripts/qa_crowbarsetup.sh

This depens on https://github.com/crowbar/crowbar-openstack/pull/424

qa_crowbarsetup: Allow vxlan for linuxbridge

---

scripts/lib/libvirt/fixtures/cloud-node1-raid.xml
scripts/lib/libvirt/fixtures/cloud-node1.xml
scripts/lib/libvirt/templates/compute-node.xml
scripts/qa_crowbarsetup.sh

We need to use a node-specific file

Fix duplicate usage of nvram

---

scripts/scenarios/cloud5/qa/no-ssl/qa-scenario-0a.yaml
scripts/scenarios/cloud6/qa/no-ssl/qa-scenario-1a.yaml
scripts/scenarios/cloud6/qa/no-ssl/qa-scenario-1b.yaml
scripts/scenarios/cloud6/qa/no-ssl/qa-scenario-2a.yaml
scripts/scenarios/cloud6/qa/no-ssl/qa-scenario-2b.yaml
scripts/scenarios/cloud6/qa/no-ssl/qa-scenario-2c.yaml
scripts/scenarios/cloud6/qa/no-ssl/qa-scenario-3a.yaml
scripts/scenarios/cloud6/qa/no-ssl/qa-scenario-6a.yaml
scripts/scenarios/cloud6/qa/ssl-insecure/qa-scenario-1a.yaml
scripts/scenarios/cloud6/qa/ssl-insecure/qa-scenario-1b.yaml
scripts/scenarios/cloud6/qa/ssl-insecure/qa-scenario-2a.yaml
scripts/scenarios/cloud6/qa/ssl-insecure/qa-scenario-2b.yaml
scripts/scenarios/cloud6/qa/ssl-insecure/qa-scenario-2c.yaml
scripts/scenarios/cloud6/qa/ssl-insecure/qa-scenario-6a.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-1a.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-1b.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-2a.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-2b.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-2c.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-3a.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-6a.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-1a.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-1b.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-2a.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-2b.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-2c.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-6a.yaml

Comment shortly describes the configuration that
scenario will deploy.

Add comments to scenario files

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

Creates magnum proposals and sets up service image. 
Depends on barclamp for Magnum to get the proposal running: https://github.com/crowbar/crowbar-openstack/pull/360 and pass gating tests.

Setup Openstack Magnum service

---

scripts/qa_crowbarsetup.sh

This change moves some crowbar cli calls to crowbarctl to test the new
cli more actively.

Move some crowbar cli calls to new crowbarctl

---

scripts/qa_crowbarsetup.sh

The crowbarctl proposal * commands are broken by design.

Partly revert move to crowbarctl

---

scripts/jenkins/jobs-ibs/templates/cloud-mkcloud-job-devel-storage-template.yaml
scripts/jenkins/jobs-ibs/templates/cloud-mkcloud-job-devel-virt-template.yaml
scripts/qa_crowbarsetup.sh

I haven't pushed the jenkins jobs from this PR; is this something we should do before merging to check they're fine?
cc @cbosdo

Add ability to use devel projects for other products + fix handling of repos.yml

---

scripts/qa_crowbarsetup.sh

When "want_barbican" is set, also deploy the barbican proposal.

qa_crowbarsetup: Setup Barbican service

---

scripts/mkcloud

Only restore cloud if the necessary snapshots exist. Otherwise abort.

Cloud restore

---

scripts/qa_crowbarsetup.sh

We need this to pass current SP2 gating before the final switch to SP2 (than want_sles12sp2 will be removed)

Properly set OS of nodes when want_sles12sp2 is set

---

scripts/jenkins/jobs-ibs/templates/cloud-mkcloud-job-sle12sp2.yaml

Just to be able to assess the state where we are with
doing the flip

Run all gating scenarios with want_sles12sp2=1

---

scripts/jenkins/jobs-obs/openstack-gerrit-rpm-packaging.yaml

This should hopefully speed up the build

Prefer kicking the scheduler over waiting

---

scripts/jenkins/jobs-ibs/cloud-mkcloud6.yaml
scripts/jenkins/jobs-ibs/cloud-mkcloud7-suse.yaml
scripts/jenkins/jobs-ibs/cloud-mkcloud7.yaml
scripts/jenkins/jobs-ibs/templates/cloud-mkcloud-gating-template.yaml
scripts/jenkins/jobs-ibs/templates/cloud-mkcloud-job-backup-restore-template.yaml
scripts/jenkins/jobs-ibs/templates/cloud-mkcloud-job-crowbar_register-template.yaml
scripts/jenkins/jobs-ibs/templates/cloud-mkcloud-job-devel-storage-template.yaml
scripts/jenkins/jobs-ibs/templates/cloud-mkcloud-job-devel-virt-template.yaml
scripts/jenkins/jobs-ibs/templates/cloud-mkcloud-job-docker-template.yaml
scripts/jenkins/jobs-ibs/templates/cloud-mkcloud-job-dvr-template.yaml
scripts/jenkins/jobs-ibs/templates/cloud-mkcloud-job-ha-compute-template.yaml
scripts/jenkins/jobs-ibs/templates/cloud-mkcloud-job-ha-template.yaml
scripts/jenkins/jobs-ibs/templates/cloud-mkcloud-job-hyperv-template.yaml
scripts/jenkins/jobs-ibs/templates/cloud-mkcloud-job-magnum-template.yaml
scripts/jenkins/jobs-ibs/templates/cloud-mkcloud-job-raid-template.yaml
scripts/jenkins/jobs-ibs/templates/cloud-mkcloud-job-sle12sp2.yaml
scripts/jenkins/jobs-ibs/templates/cloud-mkcloud-job-ssl-template.yaml
scripts/jenkins/jobs-ibs/templates/cloud-mkcloud-job-tempestfull-template.yaml
scripts/jenkins/jobs-ibs/templates/cloud-mkcloud-job-upgrade-template.yaml
scripts/jenkins/jobs-ibs/templates/cloud-mkcloud-job-xen-template.yaml

continue of https://github.com/SUSE-Cloud/automation/pull/1063

Aarch64 jobs

---

scripts/qa_crowbarsetup.sh

See also https://github.com/SUSE-Cloud/automation/pull/1077

Cleanup syntax

---

scripts/qa_crowbarsetup.sh

Depends-on: https://github.com/crowbar/crowbar-openstack/pull/445

enable ssl on manila proposal

---

scripts/mkcloud

I would like to fix undocumented wipe option and prevent to removing all LVM volumes from VG.

Fix undocumented wipe option

---

scripts/mkcloud

a test in #1086 found that mkcloud would continue after an upgrade error

mkcloud: stop on failing upgrade

---

scripts/clouddata/syncSLErepos

later there needs to be some way to test and copy this image
to do staging on SLE changes

clouddata: sync latest SP2 admin kiwi image

---

scripts/mkcloudhost/mkcloud_free_pool
scripts/mkcloudhost/mkcloud_reserve_pool

mkcloud_reserve_pool has a reminder (xmessage) to free the pool again
@bmwiedemann I more or less copied the code from https://build.opensuse.org/package/show/home:m_meister/clonky here to get rid of the dependency

adding scripts to reserve and free mkcloud host pools

---

scripts/jenkins/jobs-obs/heat-templates/README.md
scripts/jenkins/jobs-obs/heat-templates/openstack-cleanvm.yaml
scripts/jenkins/qa_openstack.sh

This adds a Heat template that can build the cleanvm VM in a Heat enabled OpenStack cloud.

Cleanvm heat

---

scripts/qa_crowbarsetup.sh

refactor requests to crowbar upgrade api
followup of PR #1086

qa_crowbarsetup: unify crowbar upgrade api requests

---

scripts/qa_crowbarsetup.sh

was merged too quick - gating not passing yet - so reverting to not break more

Revert "qa_crowbarsetup: unify crowbar upgrade api requests"

---

scripts/qa_crowbarsetup.sh

Fix for https://ci.suse.de/job/openstack-mkcloud/28799/console

No role nova-multi-compute-lxc exists

---

scripts/qa_crowbarsetup.sh

AArch64 fixes

---

scripts/qa_crowbarsetup.sh

This should prevent failures like this one: https://ci.suse.de/job/openstack-mkcloud/30594/console

With mixed SP1 and SP2 setup, use SP2 compute nodes

---

scripts/qa_crowbarsetup.sh

This gives the daily current build not only the last milestone

Switch to the SLE12 SP2 -TEST media

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

Rebased work from https://github.com/SUSE-Cloud/automation/pull/1033

Set SLES12SP2 as default platform for Cloud7+

---

scripts/jenkins/jobs-ibs/cloud-mkcloud7.yaml
scripts/jenkins/jobs-ibs/templates/cloud-mkcloud-job-many_compute-template.yaml

This is job to test 100+ nodes with Crowbar in virtualized test environment.
Currently reserved to be run on uv300x.arch.suse.de machine.

Add a 96+ VMs job

---

scripts/qa_crowbarsetup.sh

With the switch to SP2 this shouldn't be needed anymore.

Remove hack to add cloud repos to SP1 directory

---

scripts/qa_crowbarsetup.sh

Previously we alway picked the 2nd and 3rd node to deploy ceph on (in cloud 7).
With the switch of Cloud to SP2 this doesn't work anymore in an HA case.  The
2nd node will also get a pacemaker role assinged and we get conflicted OS
requirements for that node.
This change now takes the cluster assignment into account and only assigns the
storage roles to nodes that are not part of any cluster (which is a bad choice
regardless of the OS conflict anyway).

Rework the automatic selection of storage nodes

---

scripts/qa_crowbarsetup.sh

See e.g. https://ci.suse.de/job/openstack-mkcloud/31710/

Make sure we do not use SP1 node for cinder-volume

---

scripts/jenkins/qa/cloud-mkphyscloud-qa-scenario-1a.yaml
scripts/jenkins/qa/cloud-mkphyscloud-qa-scenario-1b.yaml
scripts/jenkins/qa/cloud-mkphyscloud-qa-scenario-2a.yaml
scripts/jenkins/qa/cloud-mkphyscloud-qa-scenario-2b.yaml
scripts/jenkins/qa/cloud-mkphyscloud-qa-scenario-2c.yaml

* add `bootstrapcrowbar` into `commands`  jobs' params
* use `want_node_os=suse-12.2=4,suse-12.1=3` for 2c scenario
* use devel:/languages:/python/SLE_12_SP2 repo

Update qa jenkins jobs

---

scripts/qa_crowbarsetup.sh

This should fix failures like https://ci.suse.de/job/openstack-mkcloud/31941/console

Make sure we do not use SP1 nodes for ceilometer-agent

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

We need the right crowbar_register script so that we get the proper
repositories mapped.

Fix crowbar_register for s390x

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

mkcloud will need to use new upgrade methods for Cloud6-7 upgrade. 
Requires 
- ~~https://github.com/crowbar/crowbar-init/pull/32~~
- ~~https://github.com/crowbar/crowbar-core/pull/618~~
- ~~https://github.com/crowbar/crowbar-openstack/pull/514~~

Upgrade the admin server during Cloud 6-7 Upgrade

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

instead of [[ -n "$var" ]] etc

mkcloud: consistently use [[ $var ]]

---

scripts/jenkins/jobs-ibs/cloud-mkcloud7-suse.yaml

Commit 45a66ee9 missed to update cloud-mkcloud7-suse.yaml.

Increase number of nodes for HA setup

---

scripts/jenkins/jobs-obs/openstack-cleanvm.yaml

cleanvm needs to run for Newton. Do this for SLE_12_SP2, Leap_42.1
and Leap_42.2 .

openstack-cleanvm: Run job for Newton

---

scripts/qa_crowbarsetup.sh

some minor enancements for https://github.com/SUSE-Cloud/automation/pull/1156

Upgrade fixup

---

scripts/clouddata/syncSLErepos

Image needed for UEFI boot of admin node.

Sync UEFI admin image to SLE repos

---

scripts/jenkins/jobs-ibs/cloud-crowbar-testbuild-pr-trigger.yaml

Fix indentation issues to make the code more readable.
Signed-off-by: Markos Chandras <mchandras@suse.de>

cloud-crowbar-testbuild-pr-trigger.yaml: Fix indentation

---

scripts/qa_crowbarsetup.sh

The message is about cinder-volume, not ceilometer-agent.

fix copy'n'paste error

---

scripts/mkcloud

proposed alternative to PR #1234

mkcloud: prepare for the nondisruptive upgrade

---

scripts/jenkins/jobs-ibs/cloud-mkcloud7.yaml
scripts/jenkins/jobs-ibs/templates/cloud-mkcloud-job-upgrade-nondisruptive-ha-template.yaml
scripts/jenkins/jobs-ibs/templates/cloud-mkcloud-job-upgrade-nondisruptive-template.yaml

~~Depends on https://github.com/SUSE-Cloud/automation/pull/1234~~
Uses  https://github.com/SUSE-Cloud/automation/pull/1237

Added jobs for testing non-disruptive upgrade from 6 to 7

---

scripts/mkcloud

refactoring this is a first step to change the handling lonely nodes (which is required for better s390 support)

refactoring node ids and number handling

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

Grepping for result looks ugly, I think it would be better if crowbarcrl exits with non-0 in the failed check cases. Or is there any better option?

Execute crowbar upgrade prechecks

---

scripts/qa_crowbarsetup.sh

following the principle of Single Point of Truth
change was split out of #1120 by tpatzig

qa_crowbarsetup: list architectures only in one place

---

scripts/jenkins/qa_openstack.sh

Following fixes for cleanvm
* [cleanvm] Import or create Nova ssh testkey
* [cleanvm] Use openstack cli client if is it possible

Cleanvm fixes

---

scripts/jenkins/ci.suse.de/openstack-mkcloud.xml

to match what we set in https://ci.suse.de/view/Cloud/view/Cloud7/job/cloud-mkcloud7-job-btrfs-x86_64/

jenkins/mkcloud: fix btrfs option

---

scripts/jenkins/jobs-ibs/cloud-mkcloud7.yaml

This was already done for C6 and was missing here.

Added gating C7 subjobs to nightlies

---

scripts/qa_crowbarsetup.sh

We want to fail if the crowbar server is not responding.

Wrap api request in safely

---

scripts/jenkins/jobs-ibs/cloud-mediacheck.yaml
scripts/jenkins/jobs-ibs/cloud-mkcloud7.yaml
scripts/jenkins/jobs-ibs/templates/cloud-mkcloud-job-newton-template.yaml
scripts/mkcloud
scripts/qa_crowbarsetup.sh

Temporary useful while switching to the Newton release.

Add newtoncloud7 cloudsource

---

scripts/jenkins/jobs-obs/templates/openstack-rpm-packaging-update.yaml
scripts/jenkins/zuul/layout.yaml

Rather than triggering stuff at arbitrary intervals, just
trigger the update job when a git commit merges

Trigger the upgrade job on git merge

---

scripts/lib/libvirt/fixtures/cloud-node1-xen.xml
scripts/lib/libvirt/libvirt_setup.py

https://bugzilla.suse.com/show_bug.cgi?id=1003620
https://trello.com/c/1zhuA44m/46-debug-memballoon-xen

mkcloud: test fix xen reboot bug

---

scripts/jenkins/jobs-obs/openstack-cleanvm.yaml
scripts/jenkins/jobs-obs/openstack-repocheck.yaml

Packages are there and Leap42.2 is not yet released so check
also the current stable release Leap42.1 .

Enable cleanvm and repocheck for Leap42.1 and Newton

---

scripts/qa_crowbarsetup.sh

It's https://bugzilla.novell.com/show_bug.cgi?id=997293

Do not use crowbarctl upgrade prepare until the timeout bug is fixed

---

scripts/lib/mkcloud-common.sh
scripts/mkcloud
scripts/qa_crowbarsetup.sh

This cleanup is based on jdsn's commit 28849ac93ea117471c1ca293e4d55e3e2f8536f0
but split into two independent parts and some bugs in it fixed

jdsn cleanup - copy whole scripts dir

---

scripts/qa_crowbarsetup.sh

Depends on https://github.com/crowbar/crowbar-openstack/pull/538

bsc#988980 is patched, re-add ssl for cinder

---

scripts/mkcloud

This was forgotten in 89751aab738c6187248d43453f713acedc3867f6.

mkcloud: Replace remaining usage of mkcloud_dir with SCRIPTS_DIR

---

scripts/jenkins/update_automation

to not require SDK repo in cloud nodes
and allow to override repo and branch

update_automation: make it work without git

---

scripts/jenkins/update_automation

by using a direct pipe and thus avoid associated problems
worked fine in manual test.

update_automation: drop usage of temp tarballs

---

scripts/clouddata/syncSLErepos

Needed for further SES4 integration into SOC7.

clouddata: Also sync SES4

---

scripts/mkcloud

this is helpful when figuring out if a failure might be related to
an old version of the automation scripts

add git HEAD to the environment details

---

scripts/qa_crowbarsetup.sh

SOC7 should support SES4 so setup the correct repos. (UNTESTED)

qa_crowbarsetup: Support SES4 for SOC7

---

scripts/qa_crowbarsetup.sh

This provides a more genereic output parsing than previous proposed solution based on bash.

Parse crowbarctl upgrade prechecks with ruby

---

scripts/qa_crowbarsetup.sh

We keep running into a conflict between array and string use of some variables. This patch hopes to clean that up a bit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/suse-cloud/automation/1362)

Bash arrays

---

scripts/mkcloud

run all onadmin and onhost functions with safely
Could be alternative fix to PR #1338

mkcloud: safely onadmin and onhost

---

scripts/jenkins/qa_openstack.sh

in order to run this in other places

qa_openstack: allow to override $mirror

---

scripts/mkcloud

Set LC_ALL=C to avoid problems with i18n.

mkcloud: Fix virsh command to check for vm state

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

For example, check for maintenance update should be done
before we add Cloud7 repos...

Call the upgrade prechecks at correct time.

---

scripts/jenkins/qa_openstack.sh

by setting repomirror=http://ownserver/path

qa_openstack: allow to use repo mirror

---

scripts/qa_crowbarsetup.sh

this function is already called only on cloud6+

cleanup unnecessary condition

---

scripts/qa_crowbarsetup.sh

This will add a function to filter the compute nodes out from
all the sles12 nodes which fixes the problem of the controller
node being assigned compute role.

Add function to return only compute nodes

---

Makefile
README.md
jenkins/ci.suse.de/cloud-update-ci.yaml

make cisd_deploy # to deploy to ci.suse.de
make cioo_deploy # to deploy to ci.opensuse.org

ci: Makefile targets to deploy jenkins jobs

---

scripts/qa_crowbarsetup.sh

This reverts commit 2d7f49ad7192b91aa65e40cc54b41407d52f568d.

Revert "qa_crowbarsetup: Move -test pkg installation"

---

scripts/qa_crowbarsetup.sh

This was the old school of doing things. use the more standardized
approach of using [[ want_XXX  = 1 ]] that is used elsewhere

Clean up wanttempest

---

scripts/qa_crowbarsetup.sh

Now call the function oncontroller_foobar on the controller via: `oncontroller foobar`
Its now the same as with onadmin.
Furthermore this makes it explicit which functions are supposed to run on the controller (they who have the 'oncontroller_' prefix).

qa_crowbarsetup: call oncontroller the same way as onadmin and onhost

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

untested, and no longer needed

Remove support for SLES12 SP1 admin node on Cloud 7

---

jenkins/ci.suse.de/cloud-mkcloud7.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-newton-job-2nodes-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-newton-job-4nodes-linuxbridge-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-newton-job-ha-compute-template.yaml

Copied the jobs we use for gating but run them with the
"newtoncloud7" cloudsource.

Add new Newton jobs

---

scripts/qa_crowbarsetup.sh

The testsuite from the storage3 branch needs to be configured
differently. So split out the configuration into different functions.

qa_crowbarsetup: Configure ceph testsuite for SES4

---

jenkins/ci.opensuse.org/openstack-diskimage-builder.yaml

Add diskimage-builder job to build openSUSE images.

jenkins: opensuse: Add diskimage-builder job

---

jenkins/ci.suse.de/cloud-mkcloud7.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-newton-job-ha-template.yaml

Use the standard gating HA job instead of the compute HA job
for testing Newton.

Fix Newton HA job

---

jenkins/ci.suse.de/openstack-mkcloud.yaml

This fixes the remainings from issue #759
https://github.com/SUSE-Cloud/automation/issues/759
that was not fixed with the pull request #760
https://github.com/SUSE-Cloud/automation/pull/760

jjb: show job_name in motd

---

scripts/qa_crowbarsetup.sh

The role is barbican-controller, not barbican-server .

qa_crowbarsetup: Fix barbican HA deployment

---

scripts/qa_crowbarsetup.sh

depends on: https://github.com/crowbar/crowbar-init/pull/43

adapt to new crowbar-init api namespace

---

scripts/lib/mkcloud-libvirt.sh
scripts/mkcloud

Use of `rsync` should speed things up for us remoters.

streamline mkcloud downloads for remote workers

---

scripts/lib/mkcloud-common.sh
scripts/lib/mkcloud-libvirt.sh
scripts/mkcloud

Some of our loop variables were not local.
This PR makes them local variables.

mkcloud: make local variables local

---

scripts/qa_crowbarsetup.sh

We need to set the user to fix the ssh access. This needs to be merged once https://gitlab.suse.de/ceph/qa-automation/merge_requests/28 is in the product

qa_crowbatsetup: add user in ceph validation template

---

jenkins/ci.suse.de/cloud-mkcloud7.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-uefi-template.yaml

Depends on merging of https://github.com/SUSE-Cloud/automation/pull/1141

Add job for UEFI test

---

LICENSE
README.md

to make it most compatible with licenses of the OpenStack project
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/suse-cloud/automation/1329)

Add explicit Apache 2.0 license

---

scripts/github-status/github-status.rb

PRs that only touch other files do not need to be gated.
This should reduce the amount of our gating jobs a bit.
Example: This script successfully set the status on this PR: https://github.com/SUSE-Cloud/automation/pull/1448
Update: and on this PR: https://github.com/SUSE-Cloud/automation/pull/1450

github-status: only gate PRs that affect mkcloud runs

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

We need to call the crowbarctl commands in the right order
UPDATE: I've added commit from https://github.com/SUSE-Cloud/automation/pull/1449 to see if it gets us further in the upgrade gating path

Make use of the progress library during the upgrade

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-1a.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-1b.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-test-tempest-defcore.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-test-tempest-full.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-test-tempest-smoke.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-tests-trigger.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-1a.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-1b.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-1a.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-1b.yaml

This includes changes for jobs and scenarios 1a and 1b, and additionally includes fixes for test jobs and triggers.

Update QA jenkins jobs - part 1

---

scripts/qa_crowbarsetup.sh

* https://github.com/crowbar/crowbar-init/pull/49
merge + trackupstream
* https://github.com/crowbar/crowbar-client/pull/119
merge + rubygem release + updating the package to the new gem version + trackupstream

use crowbarctl to create the database

---

jenkins/ci.suse.de/templates/cloud-mkcloud-job-btrfs-template.yaml

This should help with overall load and also with the -aarch64 job

Switch btrfs test job to non-HA

---

hostscripts/clouddata/syncSLErepos

The IBS repos are incomplete, and since the proper ones
are there, lets use those..

Also disable syncing from IBS for Cloud7

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-2a.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-2b.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-2c.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-9.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-2a.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-2b.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-2c.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-9.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-2a.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-2b.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-2c.yaml

We need to update our qa scenarios to reflect mkcloud script chnages

Update qa 2a, 2b, 2c and 9 scenarios

---

Makefile
hostscripts/soc-ci/README.soc-ci.md
hostscripts/soc-ci/soc-ci

This is useful to answer some questions that I usually
have when I work with our CI system.

Add soc-ci as command line interface to our CI

---

hostscripts/soc-ci/soc-ci

append a space to input prompts

---

hostscripts/soc-ci/README.soc-ci.md

@toabctl Why does the code even prompt for a URL?  Is this script ever going to be useful with any other Jenkins server?

clarify how to configure soc-ci

---

scripts/qa_crowbarsetup.sh

The current approach with using crudini for modifying tempest.conf
is racy because the next chef-client run overrides the modifications.
So just upload the image and use the standard image name for the
heat image which is set within the tempest barclamp.

qa_crowbarsetup: Update handling of heat cfn image

---

jenkins/ci.opensuse.org/openstack-trackupstream.yaml

Track a new pkg called openstack-horizon-plugin-neutron-lbaas-ui.

trackupstream: Add openstack-horizon-plugin-neutron-lbaas-ui

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-9.yaml

Without these fixes 9 qa scenario can't be deployed

Fix 9 qa scenario

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-1a.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-1b.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-2a.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-2b.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-2c.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-3.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-6a.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-9.yaml

It will be helpful for us to have results of more jobs in Jenkins, especially during milestone testing.

Increase the number of saved job results

---

jenkins/ci.suse.de/cloud-mkcloud7-job-simpletest-s390x.yaml
jenkins/ci.suse.de/openstack-mkcloud.yaml

make sure that it runs a sensible setup for s390x

More hammering for s390x job

---

scripts/iscsictl.py

This reverts commit f6ff81d1a4c3cc5817cf392dfb82259a6e7a955f.

Revert "Add ZYPP_LOCK_TIMEOUT=120 variable"

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-2a.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-2b.yaml

Nodes should be installed before setting aliases. Update jenkis job template command parameter order put setup_aliases after waitcloud

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-2a.yaml

2a scenario cannot be deployed without these fixes

Fix 2a qa scenario

---

jenkins/ci.suse.de/cloud-mkcloud7.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-nondisruptive-ha-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-nondisruptive-ha-without-nodes-upgrade-template.yaml

Uses option introduced by https://github.com/SUSE-Cloud/automation/pull/1516

Do not deploy ceph with upgrade job, create "upgrade" job without nodes upgrade

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-6a.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-6a.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-6a.yaml

Update  scenario 6a to use parameters from job for neutron setup.

Update jenkins job for 6a scenario add parameters networkingplugin,networkingmode

---

jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-nondisruptive-ha-without-nodes-upgrade-template.yaml

this has been forgotten in #1518

jjb: also rename the job_name

---

jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-nondisruptive-ha-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-nondisruptive-ha-without-nodes-upgrade-template.yaml

setting want_ceph is useless, as it is overwritten by storage_method

jjb: correctly set the storage method

---

jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-nondisruptive-ha-template.yaml

We know that ceilometer upgrade does not work now and want to have
the job to cover at least non-ceilometer cases
BTW, we have the card for fixing aodh problem, and this should be reverted after we solve that one

skip ceilometer proposal until we fix the problems related to aodh

---

scripts/qa_crowbarsetup.sh

We would like to test Magnum k8s_opensuse_v1 driver in two scenario:
1. TLS and Master Loadbalancer switched off; (1 master 2 minions)
2. TLS and Master Loadbalancer switched on;  (2 masters 1 minion)

magnum: add new test scenarios for Magnum

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

need to enable aodh for the new barclamp

aodh: add aodh proposal

---

scripts/qa_crowbarsetup.sh

It's needed in QA jobs without running `testsetup`. Fix for including milestones as cloudsource also added.

Extract func tests actions into standalone function

---

jenkins/ci.suse.de/cloud-mediacheck.yaml

also as documentation for which deps are needed

jjb/mediacheck: add code for one-time-setup

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-6a.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-test-cct.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-test-tempest-full.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-test-tempest-smoke.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-tests-trigger.yaml
scripts/qa_crowbarsetup.sh
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-6a.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-6a.yaml

* rename, update and fix cct job and how it's being triggered
* improve magnum QA job
* activate testing ISOs for milestones in qa_crowbarsetup.sh
* improve QA tempest jobs

Updates to QA jenkins jobs

---

jenkins/ci.suse.de/cloud-mkcloud7.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-2nodes-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-4nodes-linuxbridge-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-template.yaml

This saves roughly 20% of time, and seems to pass in testing.

Use parallel tempest for Cloud7

---

jenkins/ci.suse.de/cloud-mkcloud6.yaml
jenkins/ci.suse.de/cloud-mkcloud7.yaml
scripts/crowbar-testbuild.py

so that we can schedule more smaller jobs on all other nodes

crowbar-testbuild: schedule HA jobs on dedicated workers

---

scripts/qa_crowbarsetup.sh

Oh, which can of worms, how beautiful you are

Don't trigger new problems with swift in C5/C6

---

scripts/qa_crowbarsetup.sh

@MaximilianMeister maybe you can actually include this commit in your automation PR

correctly check for the 'nodes' step progress

---

scripts/qa_crowbarsetup.sh

https://github.com/crowbar/crowbar-core/pull/981
https://github.com/crowbar/crowbar-client/pull/138

upgrade: upgrade crowbar subcommand got renamed to upgrade admin

---

scripts/mkcloud

Since it's such an awesome feature we should advertise it more :)

Add usage for `log_dir` variable

---

scripts/cloud-stats.sh

to report on current cloud usage
for https://trello.com/c/SrGuceiv

add cloud-stats.sh

---

scripts/lib/mkcloud-libvirt.sh

sometimes the host kernel/udev grabbed devices belonging to VMs
and then lvremove failed, so we need to release the using devs first
this version still has an echo to not break anything unexpected

better lvm cleanup

---

jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-nondisruptive-ha-dvr-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-nondisruptive-ha-without-nodes-upgrade-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-template.yaml

Currently upgade jobs are onadmin_bootstrapcrowbar....

use the default value for want_postgresql

---

scripts/qa_crowbarsetup.sh

Addressing things that PR #1580 missed.

qa_crowbarsetup: fixes for PR #1580

---

scripts/lib/mkcloud-common.sh
scripts/lib/mkcloud-libvirt.sh
scripts/mkcloud
scripts/qa_crowbarsetup.sh

3 SAP changes

---

scripts/qa_crowbarsetup.sh

Not sure why this was not the case so far...

qa_crowbarsetup: Use HA for swift when HA is enabled

---

scripts/qa_crowbarsetup.sh

Unfortunately it seems
https://github.com/SUSE-Cloud/automation/pull/1626 was completely
untested had a syntax error.

Fix ec2 setup for clusters

---

hostscripts/gatehost/gatevm.xml
hostscripts/gatehost/jenkins-tu-sle12.xml
hostscripts/gatehost/setup.sh

script to setup new gate
as a host that mostly hosts the gatevm
that is doing all the VLAN handling
and running dhcp/dns

gatehost: add setup.sh

---

scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-2c.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-2c.yaml

Adapt manila tempest config for cephfs as backend. Depends on https://github.com/crowbar/crowbar-openstack/pull/825

Update tempest config for ceph QA scenario

---

scripts/qa_crowbarsetup.sh

Co-Authored-By: Michal Jura <mjura@suse.com>

Switch to SUSE OpenStack Cloud Magnum based image

---

scripts/heat/2-instances-pinging.yaml
scripts/heat/ping_template.sh
scripts/qa_crowbarsetup.sh

This is still very primitive - there's no analysis of the ping results, no checking for running out of disk space, and no checking of VM to VM connection.
Also, the ping in cirros image does not allow anything fancy.
Thanks a lot to @jgrassler for help with debugging of script behavior!

Check non-disruption of network connectivity of VM

---

jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-nondisruptive-ha-template.yaml

Requires https://github.com/SUSE-Cloud/automation/pull/1675

Enable pinging running VM's from the outside

---

scripts/github-status/github-status.rb

Reduce the number of api requests to github in order to reduce the chance to hit the rate limit.
This PR is a split off of the refactoring started as part of PR #1664 in order to be able to merge the improvements earlier than the rest of this PR.

github-status: reduce number of API requests

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-1a.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-test-upgrade-ui.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-tests-trigger.yaml

* adapt one scenario with single cluster to test the upgrade
* add upgrade job to run the upgrade
* adapt tests-trigger job

Upgrade job for QA clouds using UI tests in cct

---

Makefile
hostscripts/gatehost/freshadminvm
scripts/jenkins/mkcloudresultcheck.pl
scripts/mkcloudhost/allocpool

forbid tab characters

---

scripts/lib/mkcloud-common.sh
scripts/lib/mkcloud-libvirt.sh
scripts/mkcloud
scripts/qa_crowbarsetup.sh

mkcloud: refactor setuphost

---

scripts/jenkins/qa_openstack.sh

Be able to run against the Ocata repositories.

qa_openstack: Add Ocata

---

scripts/lib/mkcloud-libvirt.sh
scripts/mkcloud

to have one less special-purpose tool

mkcloud: use ip to configure vlan

---

jenkins/ci.opensuse.org/openstack-trackupstream.yaml

We want to get updated packages for Ocata.

trackupstream: Also track Ocata

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-test-upgrade-ui.yaml

[upgrade] Provide repos for cloud 7 in upgrade QA job

---

scripts/qa_crowbarsetup.sh

Removing the magnum image upload as https://github.com/crowbar/crowbar-openstack/pull/838
is merged.

magnum: Cleanup image upload

---

scripts/qa_crowbarsetup.sh

Depends on https://github.com/crowbar/crowbar-openstack/pull/858

barbican: Enable SSL testing

---

jenkins/ci.suse.de/cloud-trackupstream.yaml
scripts/qa_crowbarsetup.sh

Staging itself is a subproject. The base project can be based on anything else.
This is fixing the changes introduced with commit:
16edef1a92c5f731352f09345e004b09a391474c

HCP: fix staging project setup

---

scripts/lib/mkcloud-common.sh
scripts/qa_crowbarsetup-test.sh
scripts/qa_crowbarsetup.sh

support cloudsource=GM7

---

scripts/github-status/github-status.rb

Lower the code complexity in order to allow to easier extend the PR filter rules.

github-status: refactor PR filter with less complexity

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-test-upgrade-ui.yaml

* also add custom cct params
* clean up deps and repos on the admin server before triggering upgrade

Add admin node upgrade step into QA upgrade ui job

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-test-upgrade-ui.yaml

Successful build: https://ci.suse.de/view/Cloud/view/QA/job/cloud-mkphyscloud-qa-test-upgrade-ui/47/console
Using update from https://github.com/SUSE-Cloud/cct/pull/72

Add pgsql db step and nodes' repo check into upgrade QA job

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-test-upgrade-ui.yaml

* test stopping os services page
* test creating os database page

More tests for QA upgrade UI job

---

scripts/github-status/github-status.rb

adapt the github-status filtering to allow PRs to the forks in sap-oc

github-status: allow to build PRs against sap-oc forks

---

jenkins/ci.suse.de/cloud-mkcloud7.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-disruptive-ha-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-disruptive-template.yaml

Somehow I missed that we have it disabled for real...

upgrade: Enable original disruptive job + add HA disruptive job

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-2a.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-2a.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-2a.yaml

Extend scenario 2a to use the both linuxbridge and ovs with vlan + vxlan neutron drivers.

Extend scenario 2a

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-1a.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-1b.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-2a.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-2b.yaml
scripts/scenarios/cloud6/qa/no-ssl/qa-scenario-1a.yaml
scripts/scenarios/cloud6/qa/no-ssl/qa-scenario-1b.yaml
scripts/scenarios/cloud6/qa/no-ssl/qa-scenario-2a.yaml
scripts/scenarios/cloud6/qa/no-ssl/qa-scenario-2b.yaml
scripts/scenarios/cloud6/qa/ssl-insecure/qa-scenario-1a.yaml
scripts/scenarios/cloud6/qa/ssl-insecure/qa-scenario-1b.yaml
scripts/scenarios/cloud6/qa/ssl-insecure/qa-scenario-2a.yaml
scripts/scenarios/cloud6/qa/ssl-insecure/qa-scenario-2b.yaml

* adapt the scenario batch files
* update the jenkins jobs

Use nfs cinder backend in QA scenarios

---

scripts/qa_crowbarsetup.sh

The repository key has changed - make the test pass again

Update CA repository SHA1 checksum

---

scripts/lib/mkcloud-common.sh
scripts/lib/mkcloud-libvirt.sh
scripts/lib/mkcloud-onhost.sh
scripts/mkcloud

to reduce the likelyhood of users screwing up the host

allow to run mkcloud as non-root user

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-test-upgrade-ui.yaml

* triggers cct tests to upgrade cloud nodes https://github.com/SUSE-Cloud/cct/pull/74
* successful build at https://ci.suse.de/view/Cloud/view/QA/job/cloud-mkphyscloud-qa-test-upgrade-ui/60/console

Add upgrade nodes step in UI upgrade job

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-3.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-3.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-3.yaml

Extend 3 scenario to use both linuxbridge and ovs with vlan + vxlan neutron drivers.

Extend 3 scenario

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

See https://www.suse.com/documentation/ses-4/book_storage_admin/data/ceph_upgrade_to4.html for a SES upgrade guide that we try to follow here.

Upgrade SES to 4.0 before upgrading SOC to 7

---

jenkins/ci.suse.de/cloud-mkcloud7.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-nondisruptive-ha-ceph-template.yaml

SES is now upgradable with https://github.com/SUSE-Cloud/automation/pull/1776

Added upgrade job with ceph deployed

---

scripts/qa_crowbarsetup.sh

Depends on https://github.com/crowbar/crowbar-openstack/pull/873

Enable testing SSL for rabbitmq

---

jenkins/ci.opensuse.org/openstack-trackupstream.yaml
jenkins/ci.suse.de/cloud-mediacheck.yaml
jenkins/ci.suse.de/cloud-trackupstream.yaml
scripts/mkcloudhost/mkcloude

by not assuming we have access to /root

jenkins: make it easier to run as non-root

---

hostscripts/clouddata/syncSLErepos

for use by SES team in cloud.suse.de

clouddata: sync SP3 image

---

jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-linuxbridge-template.yaml

It's interesting that this job even succeeded until recently. :)

Fix clusterconfig for linuxbridge HA jobs

---

scripts/qa_crowbarsetup.sh

The services step of the upgrade process wont be able
to pass as long as there are instances running.
We need to stop all instances in case the upgrade method
is disruptive and then resume them afterwards like
a human would do during the disruptive upgrade

upgrade: suspend and resume instances during the disruptive upgrade

---

jenkins/ci.suse.de/openstack-mkcloud.yaml

Allow control of debugging in openstack-mkcloud via job parameters, and improve the default behaviour.

parametrize openstack-mkcloud debugging flags

---

jenkins/ci.suse.de/openstack-mkcloud-log-parser-test.yaml
jenkins/ci.suse.de/openstack-mkcloud.yaml

I forgot to propagate the tidy-ups introduced to `openstack-mkcloud.yaml` in #1801 over to `openstack-mkcloud-log-parser-test`.
Also propagate a couple of cosmetic improvements in the other direction.

sync changes between openstack-mkcloud{,-log-parser-test}

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

for cct to access its repo from behind a corporate firewall

mkcloud: pass proxy variables into admin node

---

scripts/qa_crowbarsetup.sh

For some long commands it would be nice to get some extra output
while they are running. This allows to pass a 6th arg to wait_for
that would get evaluated instead of the usual dots.

automation: wait_for allow custom output while waiting

---

scripts/qa_crowbarsetup.sh

Fixing https://github.com/SUSE-Cloud/automation/pull/1823

Call functions that should be run on controller really on controller

---

scripts/qa_crowbarsetup.sh

This reverts commit 4ada8b7321c7dc4eb6ac5d2d6cf98ce0764b2000.

nova: Enable ec2-api ssl when ssl is enabled

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-1b.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-2a.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-test-upgrade-ui.yaml
scripts/scenarios/cloud6/qa/no-ssl/qa-scenario-2a.yaml
scripts/scenarios/cloud6/qa/ssl-insecure/qa-scenario-2a.yaml

* 2a is a 3 cluster scenario using sbd as stonith - bring the sbd to external server instead of setting it up on the admin node
* fix upgrade UI job
* add update to xen job
* add netapp backend to manila in soc6

Add changes to 3 cluster scenario + minor fixes for other related jobs

---

scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-1a.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-1b.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-2a.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-2b.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-1a.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-1b.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-2a.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-2b.yaml

* additionally add cinder-volume on cluster `services`
* fix compute nodes aliases

Add nfs as shared storage for cinder for cloud7 QA scenarios

---

scripts/lib/mkcloud-common.sh

so that sudo fdisk and such work

mkcloud/non-root: include sbin in PATH

---

scripts/qa_crowbarsetup.sh

Switch to crowbarctl for crowbar proposal commit from cloud6 on.

qa_crowbarsetup: use crowbarctl to commit proposals

---

scripts/qa_crowbarsetup.sh

...to avoid conflicts if test updates channel is enabled.
Follow-up for https://github.com/SUSE-Cloud/automation/pull/1849

Add SDK-SP1-Updates-test repo 

---

scripts/jenkins/log-parser/openstack-mkcloud-rules.txt

Ignore false positives caused by upgrade and errors from bugs in SLES.

fix more log parser false positives

---

scripts/heat/load-balancer-create.sh
scripts/heat/load-balancer-delete.sh
scripts/heat/load-balancer.yaml
scripts/heat/webserver.sh

For load balancer testing (LBaaS2) we are providing a heat template
to create two VMs to be the backends for the load balancer.
Since the Mitaka release does not support heat templates with LBaaS2,
auxiliary scripts have been created to provide this functionality just
for testing.

Added load balancer template and auxiliary scripts

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-2a.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-2c.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-test-upgrade-ui.yaml
scripts/scenarios/cloud6/qa/no-ssl/qa-scenario-2a.yaml
scripts/scenarios/cloud6/qa/no-ssl/qa-scenario-2c.yaml
scripts/scenarios/cloud6/qa/ssl-insecure/qa-scenario-2a.yaml
scripts/scenarios/cloud6/qa/ssl-insecure/qa-scenario-2c.yaml

* automating upgrade for ceph scenario using upgrade UI job
* adapt scenario files around ceph
* add changes for other scenario files (3 cluster scenario 2a)
* add netapp backend for manila instead of default generic driver
* use lbaasv2

Make ceph scenario upgradable

---

jenkins/ci.suse.de/openstack-mkcloud.yaml

This should be happening anyway, but it doesn't do any harm to make sure.

make sure we copy log parser rules into the workspace

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-test-tempest-full.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-test-tempest-smoke.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-test-upgrade-ui.yaml
scripts/qa_crowbarsetup.sh

* fix for keeping the correct cloudsource in UI upgrade job
* use `--insecure` for heat commands in upgrade functions in `qa_crowbarsetup.sh`
* fixes for other QA tempest jobs

QA automation fixes and bit more

---

scripts/qa_crowbarsetup.sh

for that we make a more generic sshrun function

fix cloud6 LDAP

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-6a.yaml
jenkins/ci.suse.de/openstack-mkcloud.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-monasca-template.yaml
mkcloudruns/mkcloudconfig/SUSECloud.mkcloud
scripts/lib/mkcloud-common.sh
scripts/mkcloud
scripts/qa_crowbarsetup.sh

because people can already use e.g. want_aodh_proposal=0

mkcloud: cleanup duplicate want_* proposal vars

---

scripts/mkcloud

mkcloud: use less subshells

---

scripts/lib/mkcloud-common.sh
scripts/lib/mkcloud-libvirt.sh
scripts/mkcloud
scripts/qa_crowbarsetup.sh

change looked good in manual testing

mkcloud: fix HA with RAID

---

scripts/lib/mkcloud-common.sh

without other (disabled) services

mkcloud: dont try to deploy services that cannot work

---

scripts/lib/mkcloud-common.sh
scripts/mkcloud
scripts/qa_crowbarsetup.sh

problem with the current output - especially in local terminals - is that you do not see if it errored or succeeded and if it errored, you have to look through hundreds of extra lines.

create nicer error output

---

scripts/qa_crowbarsetup.sh

with our default self-signed certs

qa_crowbarsetup: allow magnum testsetup with ssl

---

scripts/qa_crowbarsetup.sh

This PR is important for SAP gating.

Revert "Revert "qa_crowbarsetup: use crowbarctl to commit proposals""

---

scripts/qa_crowbarsetup.sh

on admin server, if available
(only when run after crowbar is setup)

qa_crowbarsetup: import PTF key

---

jenkins/ci.opensuse.org/openstack-trackupstream.yaml

With Mitaka effectively EOL, it is time to remove Liberty

Remove Liberty from trackupstream

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

Since Cloud 5 is EOL we can drop the support for Cloud 4.

mkcloud: Remove cloud4 support

---

jenkins/ci.suse.de/templates/cloud-mkcloud-job-4nodes-linuxbridge-template.yaml

This reverts commit 52b47afeca5b2a45a486725b60378aa17ee11b99.

Revert "Temporally disable test repo for 4nodes-linuxbrige jobs"

---

jenkins/ci.suse.de/templates/cloud-mkcloud-job-magnum-template.yaml

Currently magnum job is not deploying magnum due to this missing part.

mkcloud: Change last remain of want_magnum to want_magnum_proposal

---

scripts/lib/mkcloud-common.sh
scripts/mkcloud
scripts/qa_crowbarsetup.sh

as it is mixing use cases
and directory layout might be different elsewhere.
Also, by using URLs, we allow for HTTP on custom port numbers

mkcloud: do not use $reposerver for image downloads

---

hostscripts/clouddata/syncSLErepos
jenkins/ci.suse.de/cloud-mkcloud7-suse.yaml
scripts/lib/mkcloud-common.sh
scripts/mkcloud
scripts/qa_crowbarsetup.sh

Add cloudsource=susecloud8/develcloud8 support, remove susecloud7
leftovers.

Start cloud8 development

---

scripts/jenkins/update_automation

in case parallel mkcloud jobs run update_automation at the same time
https://trello.com/c/q8QfAOq3

update_automation: wait for git lock to be released

---

jenkins/ci.suse.de/cloud-mkcloud7.yaml
jenkins/ci.suse.de/openstack-mkcloud.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-vproduction-template.yaml

to be similar to what we want to deploy as production cloud
(cloud.suse.de)
with HA, LDAP, SSL, Ceph

jenkins/mkcloud: add vproduction job

---

scripts/qa_crowbarsetup.sh

Needs to be tested together https://github.com/crowbar/crowbar-openstack/pull/883

qa_crowbarsetup: testing cinder setting rbd_flatten_volume_from_snaps

---

jenkins/ci.suse.de/openstack-mkcloud.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-magnum-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-monasca-template.yaml
mkcloudruns/mkcloudconfig/SUSECloud.mkcloud
scripts/mkcloud

The parameter was not doing anything and the documentation was misleading.

removed obsolete nodenumbercompute

---

scripts/jenkins/japi

because jenkins requires POST requests now for submitDescription

update japi to fix mkcloudresultcheck

---

scripts/qa_crowbarsetup.sh

There might be some SP2 nodes for ceph present.

Do not deploy nova-compute and ceilometer agent nodes to SP2 nodes

---

scripts/scenarios/cloud8/cloud8-ironic-basic-ha.yml

Cloud8 ironic scenario was copied before original Cloud7 version was
fully working. Bug fixes from Cloud7 are ported co Cloud8 here.
Port of #1979 and #1976 to Cloud8.

ironic: port cloud7 scenario fixes to cloud8

---

jenkins/ci.suse.de/cloud-mkcloud7.yaml
jenkins/ci.suse.de/cloud-mkcloud8.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-ironic-agent-template.yaml
scripts/scenarios/cloud7/cloud7-ironic-swift-ha.yml
scripts/scenarios/cloud8/cloud8-ironic-swift-ha.yml

agent_* drivers require specific swift setup and some changes in glance.

ironic: Added job for deployment with agent_* drivers

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-1a.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-1b.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-2a.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-2b.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-2c.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-3.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-6a.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-9.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-tests-trigger.yaml

Add rally-tests parameter as option to all qa jobs

Add rally-tests execution to qa tests trigger

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-1a.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-1b.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-2a.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-2b.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-2c.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-3.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-6a.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-9.yaml
scripts/scenarios/cloud8/qa/no-ssl/qa-scenario-1a.yaml
scripts/scenarios/cloud8/qa/no-ssl/qa-scenario-1b.yaml
scripts/scenarios/cloud8/qa/no-ssl/qa-scenario-2a.yaml
scripts/scenarios/cloud8/qa/no-ssl/qa-scenario-2b.yaml
scripts/scenarios/cloud8/qa/no-ssl/qa-scenario-2c.yaml
scripts/scenarios/cloud8/qa/no-ssl/qa-scenario-3.yaml
scripts/scenarios/cloud8/qa/no-ssl/qa-scenario-6a.yaml
scripts/scenarios/cloud8/qa/no-ssl/qa-scenario-9.yaml
scripts/scenarios/cloud8/qa/ssl-insecure/qa-scenario-1a.yaml
scripts/scenarios/cloud8/qa/ssl-insecure/qa-scenario-1b.yaml
scripts/scenarios/cloud8/qa/ssl-insecure/qa-scenario-2a.yaml
scripts/scenarios/cloud8/qa/ssl-insecure/qa-scenario-2b.yaml
scripts/scenarios/cloud8/qa/ssl-insecure/qa-scenario-2c.yaml
scripts/scenarios/cloud8/qa/ssl-insecure/qa-scenario-3.yaml
scripts/scenarios/cloud8/qa/ssl-insecure/qa-scenario-6a.yaml

This is still very much a WIP. first pr is to setup directory structure and yaml files

Update QA test scenarios to Cloud 8

---

docs/mkcloud.md
scripts/mkcloud

mkcloud: discontinue SLE-11 support

---

scripts/jenkins/update_automation

to avoid a mitm attack that injects untrusted code

update_automation: use https repos by default

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-8a.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-8b.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-8a.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-8b.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-8a.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-8b.yaml

* 8a - with 3 nodes HA cluster (cloud with 7 nodes)
* 8b - 2 nodes HA cluster with ceph cluster (cloud with 8 nodes)
* both no-ssl and ssl-insecure scenarios

Add monasca QA scenarios

---

scripts/jenkins/qa_devstack.sh

to not have ssh session stuck
from those non-daemonized services

devstack: kill swift on exit

---

scripts/qa_crowbarsetup.sh

to work with IPMI on non-admin VLANs

qa_crowbarsetup: allow to specify ipmi_ip_addrs

---

jenkins/ci.suse.de/openstack-submit-project.yaml

Without that, cloud8 is never going to get updated

Add support for cloud8 Staging merge

---

jenkins/ci.suse.de/cloud-mkcloud8.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-2nodes-ocata-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-4nodes-linuxbridge-ocata-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-ocata-template.yaml

This is used for bootstrapping Ocata on Cloud8.

ci.suse.de: Add new job with cloudsource=ocatacloud8

---

scripts/lib/mkcloud-libvirt.sh

3rd commit should help against mkcloud host slowness

mkcloud: disk wipe improvements

---

jenkins/ci.suse.de/openstack-mkcloud.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-4nodes-linuxbridge-tempestfull-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-4nodes-linuxbridge-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-linuxbridge-bonding-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-template.yaml
scripts/mkcloud

making it easier to do a run with crowbar_networkingmode=team

mkcloud: cleanup handling of nics

---

jenkins/ci.suse.de/cloud-mkcloud7.yaml
jenkins/ci.suse.de/cloud-mkcloud8.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-mariadb-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-mariadb-template.yaml
scripts/qa_crowbarsetup.sh

- We want SOC7 as well
- HA jobs for both (disabled for now; HA is not implemented)

Allow mysql backend for SOC7 + More jobs with MariaDB

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-8a.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-8b.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-8a.yaml

Removed redundant actions and fixed ssl scenario.

Update monasca QA scenarios for SOC7

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-1a.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-1b.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-2a.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-2b.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-3.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-6a.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-8a.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-8b.yaml
jenkins/ci.suse.de_xml/cloud-mkphyscloud-qa.xml
scripts/lib/mkcloud-common.sh
scripts/qa_crowbarsetup.sh

when deploying p3.cloud
it defaulted to 'manual' because I have neither libvirt nor sbd

qa_crowbarsetup: support ipmi stonith and some cleanup

---

jenkins/ci.suse.de/templates/cloud-mkcloud-job-btrfs-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-ceph-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-linuxbridge-bonding-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-linuxbridge-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-mariadb-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-mariadb-template.yaml

QA Maintenance does an evil thing: they're testing whether a HA cloud
can be rebooted successfully.  I know this sounds crazy and unsupported, but
lets run it in our CI so that we find the issues before them.

Actually test the reboot case

---

scripts/qa_crowbarsetup.sh

In newer python-novaclient versions, some floating-ip commands are no
longer available. This fixes:
error: argument <subcommand>: invalid choice: u'add-floating-ip'
when running with a client from Ocata.

qa_crowbarsetup: Use openstack CLI for some floating-ip cmds

---

jenkins/ci.suse.de/templates/cloud-mkcloud-job-btrfs-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-ceph-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-linuxbridge-bonding-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-linuxbridge-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-mariadb-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-mariadb-template.yaml

Reverts SUSE-Cloud/automation#2077 . This currently breaks gating.

Revert "Actually test the reboot case"

---

jenkins/ci.suse.de/cloud-mkcloud8-suse.yaml

This is needed in preparation of milestone 1

Add cloud8 suse jobs

---

jenkins/ci.suse.de/cloud-mediacheck.yaml

Those medias don't change anymore, no point in checking them

Remove checking of GM6/GM7

---

hostscripts/clouddata/syncSLErepos

This saves about 40GB of storage (17%).

Avoid storing maintenance updates multiple times

---

scripts/lib/mkcloud-libvirt.sh
scripts/mkcloud

That makes it easier to understand what's going on

Move setup of cache_dir after the debug logging got enabled

---

scripts/qa_crowbarsetup.sh

We add a separate conduit map one that covers the crowbar and as well
the hardware nodes.

Tweak conduit map for provo

---

docs/mkcloud.md

Add want_cached_images environment variable to the sample script.

Improve instructions for using local repositories

---

hostscripts/clouddata/syncSLErepos

We moved all of the install medias under install/, so sync it there

syncSLErepos: fix sync location for install repos

---

jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-mariadb-template.yaml
scripts/mkcloud
scripts/qa_crowbarsetup.sh

Which means that nothing (database/rabbitmq) could rely on DRBD
based cluster (which needs to be of size 2).

MariaDB cluster needs to have (at least) 3 nodes.

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-1a.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-1b.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-2a.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-2b.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-2c.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-3.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-6a.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-8a.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-8b.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-9.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-test-tempest-full.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-test-tempest-smoke.yaml

* fix missing adminip in tempest jobs
* add `want_test_updates` params into all jobs
* add missing params' exports for `networkingplugin` and `networkingmode` where needed

Add missing params into QA jenkins jobs

---

scripts/ceph/create_separate_network.py
scripts/lib/mkcloud-common.sh
scripts/mkcloud
scripts/qa_crowbarsetup.sh

Add a new mkcloud flag
Set networking mode to team
Set default NIC count to 4
Add conduit intf3
Add a configurable ceph network onto conduit intf3 (aka bond1)

Create a separate ceph network from bonded interfaces

---

jenkins/ci.opensuse.org/openstack-cleanvm.yaml

We want to do initial testing for the Pike packages so run cleanvm there.

cleanvm: Run for Pike

---

hostscripts/clouddata/syncSLErepos

several syncSLErepos improvements

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-1a.yaml
scripts/scenarios/cloud8/qa/no-ssl/qa-scenario-1c.yaml

Remove nfs setup for mariadb database

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-8a.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-8b.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-8a.yaml
scripts/scenarios/cloud8/qa/no-ssl/qa-scenario-8a.yaml
scripts/scenarios/cloud8/qa/no-ssl/qa-scenario-8b.yaml
scripts/scenarios/cloud8/qa/ssl-insecure/qa-scenario-8a.yaml
scripts/scenarios/cloud8/qa/ssl-insecure/qa-scenario-8b.yaml

Add monasca scenarios for QA jobs in cloud8

---

scripts/qa_crowbarsetup.sh

The idea is to switch the database default to mariadb but this is not
yet working for HA.

jenkins: Enforce postgresql as a database in HA

---

scripts/crowbar-testbuild.yaml

Run testbuild HA jobs with nodenumber=5 again

---

scripts/qa_crowbarsetup.sh

This will speedup the deployment process for Pike deployments. It
requires https://github.com/crowbar/crowbar-openstack/pull/1254 .

qa_crowbarsetup: Lower password hash rounds for keystone deployments

---

docs/mkcloud.md

Add reminder to install libvirt.

mkcloud-docs: remember to install libvirt

---

scripts/qa_crowbarsetup.sh

~~Requires https://github.com/crowbar/crowbar-openstack/pull/1280~~

Enable SSL setup for database

---

jenkins/ci.opensuse.org/openstack-cleanvm.yaml
jenkins/ci.opensuse.org/openstack-repocheck.yaml
jenkins/ci.opensuse.org/openstack-trackupstream.yaml
jenkins/ci.suse.de/cloud-mediacheck.yaml
jenkins/ci.suse.de/macros.yaml
scripts/jtsync/jtsync.rb

- cloud-mediacheck
- cloud-trackupstream
Signed-off-by: Jürgen Löhel <jloehel@suse.com>

Fix the execution of jtsync in some Matrix-Jobs

---

hostscripts/gatehost/bootstrapp2.xml
hostscripts/gatehost/freshadminvm
hostscripts/scale-cloud/setup-baremetal.sh
scripts/mkcloud

Commit includes config for bootstrap VM which will be used for installation
of baremetal admin host and copy of setup.sh for this variant.

Added config for baremetal admin host in scale-cloud

---

jenkins/ci.opensuse.org/openstack-cleanvm.yaml
jenkins/ci.opensuse.org/openstack-repocheck.yaml
jenkins/ci.opensuse.org/openstack-trackupstream.yaml
scripts/jtsync/jtsync.rb

Fixes some issues which were introduced in #2195

Wip jtsync matrix jobs fix

---

scripts/qa_crowbarsetup.sh

This patch adds a test to ensure that changing the keystone admin
password via the keystone barclamp can be applied successfully and that
the admin user can continue to function afterward.

keystone: Add test for updated_password

---

scripts/qa_crowbarsetup.sh

Commit e0c50fda50413f910cd7ccdb885923a3e480dd46 broke the Cloud 6 CI
jobs.

keystone: Ony test update_keystone_password for Cloud 7+

---

hostscripts/scale-cloud/batches/01_pacemaker.batch
hostscripts/scale-cloud/batches/02_nfs_client.batch
hostscripts/scale-cloud/batches/03_database.batch
hostscripts/scale-cloud/batches/04_rabbitmq.batch
hostscripts/scale-cloud/batches/09_nova.batch

Changes:
- cluster layout closer to final target
- RabbitMQ active-active
- MariaDB database
- systemd based stateless services

scale-cloud: updated batches for 4x3 cluster setup

---

scripts/jenkins/track-upstream-and-package.pl

Basically the script needs to adjust to look for the new
service name ("obs_scm" instead of "tar_scm") and treat files
ending in *obscpio similar to existing tar file matching logic.
Last point is that the recompress service might not exist, so
make that one optional and try to guess differently if it
is not configured.

Add obscpio support to trackupstream

---

scripts/lib/mkcloud-common.sh
scripts/mkcloud
scripts/qa_crowbarsetup.sh

Also tee the timing information on the job output
edit1:
this patch adds a script, timeit.py. This python script reads the
mkcloud-shortlog generated for each mkcloud job and looks for specific
logs and using regex parses out the start and finish times.
Then spits out the collected information and duration.
edit2:
```
scripts/timeit.py ../88476/mkcloud_short_stdout.log
PROPOSAL,    crowbar(default),   14,Fri Oct 13 08:27:03 UTC 2017,Fri Oct 13 08:27:17 UTC 2017
PROPOSAL,provisioner(default),   25,Fri Oct 13 08:27:27 UTC 2017,Fri Oct 13 08:27:52 UTC 2017
PROPOSAL,        dns(default),   49,Fri Oct 13 08:47:05 UTC 2017,Fri Oct 13 08:47:54 UTC 2017
PROPOSAL,    nfs_client(data),   16,Fri Oct 13 08:48:07 UTC 2017,Fri Oct 13 08:48:23 UTC 2017
PROPOSAL,     pacemaker(data),  120,Fri Oct 13 …
```

timeit: script to extract timing information from shortlog

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-rally-test.yaml
scripts/jenkins-support.sh
scripts/qa_crowbarsetup.sh
scripts/scenarios/rally/rally-failover-test.yml

Steps:
1.SSH to one of cluster nodes "pkill nova-api" process
2.Start rally test which will boot instance change instance status delete it
3.Check that service running on other cluster nodes
4.Check that service recover on node where it was killed

Test cluster failover for one of openstack services

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

Base it on the initial value of $cloudsource.

upgrade: Initialize correct value for the progress file.

---

ardana/ansible/init.yml
jenkins/ci.suse.de/ardana-job.yaml

Put the input model in place and update the IP Adresses with the ones
from the heat template
Next steps:
- commit the changes to git
- create "ardana" users on all nodes and distribute keys
- On the deployer run:
ansible-playbook -i hosts/localhost config-processor-run.yml",
ansible-playbook -i hosts/localhost ready-deployment.yml",
cd /var/lib/ardana//scratch/ansible/next/ardana/ansible",
ansible-playbook -i hosts/verb_hosts site.yml",

ardana: Update the model with heat data

---

scripts/qa_crowbarsetup.sh

This can be used to control whether we want to deploy with or without
clustered rabbitmq support in 7+. It also respects the default (which is
different between 7 and 8).

qa_crowbarsetup.sh: Introduce want_clustered_rabbitmq variable

---

scripts/jenkins/ardana/ansible/init.yml

- add cloud model changes to git
- run the configuration-processor play
- run ready-deployment play
- start the actual deployment

ardana: Execute more steps in the deployment process

---

scripts/jenkins/ardana/ansible/init.yml
scripts/jenkins/ardana/ansible/repositories.yml

Create a ssh key for the ardana user on the deployer and use that on
the computes to ssh into.

ardana: Setup ssh for compute nodes

---

hostscripts/clouddata/syncSLErepos

to not waste too much bandwidth

syncSLErepos: do not sync aarch64 to provo

---

scripts/jenkins/ardana/ansible/init.yml

Update Model to use DNS servers from management network.

ardana: Update DNS servers in Model

---

hostscripts/clouddata/syncSLErepos

to reduce bandwidth requirements

syncSLErepos: exclude debug packages

---

jenkins/ci.suse.de/ardana-job.yaml
scripts/jenkins/ardana/ansible/files/input-model-nic-mappings.yml
scripts/jenkins/ardana/ansible/init.yml
scripts/jenkins/ardana/ansible/templates/input-model-servers.yml

To be able to use ansible files and templates in init.yml, clone the
whole git tree. Otherwise all theses files need a manual download.

ardana: Clone whole git tree

---

jenkins/ci.suse.de/ardana-job.yaml
scripts/jenkins/ardana/ansible/files/input-model-net-global.yml
scripts/jenkins/ardana/ansible/init.yml
scripts/jenkins/ardana/ansible/templates/input-model-servers.yml
scripts/jenkins/ardana/heat-template.yaml

This reverts commit cc97c4b4b3c43410cb8829406879f95523bb848f.

Revert "ardana: Restructure network config"

---

hostscripts/clouddata/syncSLErepos
scripts/qa_crowbarsetup.sh

will only do anything on clouds that have
https://github.com/crowbar/crowbar-core/pull/1464

qa_crowbarsetup: add salt testing

---

scripts/jenkins/ardana/ansible/init.yml
scripts/jenkins/ardana/heat-template.yaml

This is needed to deploy swift properly

Add more disks to the controller

---

scripts/qa_crowbarsetup.sh

qa_crowbarsetup: make sure adminip is set

---

hostscripts/gatehost/freshadminvm
scripts/lib/mkcloud-driver-libvirt.sh
scripts/qa_crowbarsetup.sh

All these small enhancements are designed in a way that the old default behaviour is conserved, unless new configuration variables are set.

Small improvements to allow usage of mkphyscloud outside of the SUSE environment

---

Makefile

This is basically for travis as they only offer newer versions.

update pbr requirement

---

jenkins/ci.opensuse.org/openstack-trackupstream.yaml

Remove Newton from trackupstream

---

scripts/jenkins/ardana/ansible/init.yml

The maintenance situation around powerdns is still unclear.

ardana: Switch designate backend to bind

---

scripts/jenkins/ardana/ansible/init.yml

this helps in reusing already created heat stack

ignore erros if unable to grow size of disk for ardana stacks

---

jenkins/ci.suse.de/cloud-mkcloud7.yaml

Reverts SUSE-Cloud/automation#2336 since it didn't help and was fixed other way

Revert "jenkins: force --serial tempest in SOC7"

---

scripts/github_pr/github_pr_cloud.yaml
scripts/github_pr/github_pr_crowbar.yaml
scripts/github_pr/interactions/ia_cloud.rb
scripts/github_pr/interactions/ia_crowbar.rb

These are the configs for the new github-pr tool which is now in its own repository:
https://github.com/openSUSE/github-pr
This PR replaces this one: https://github.com/SUSE-Cloud/automation/pull/2256

configs for github_pr for automation and crowbar

---

docs/ardana/README.md
docs/ardana/testing.md

Various simple tweaks to this new Ardana automation docs area.

improve Ardana testing docs

---

hostscripts/gatehost/newclouddata.xml
hostscripts/gatehost/setup.sh

update / document more setup parts of
gatehost1 and gatehost2 Nuremberg infrastructure nodes

gatehost: document deployment

---

scripts/jenkins/ardana/ardana-init.bash

The package uses this script as source so it is still needed.
Reverts SUSE-Cloud/automation#2394

Revert "Remove ardana-init.bash script"

---

jenkins/ci.suse.de/ardana-job.yaml

Site.yml of "standard" takes more than 120 min these days without
output, so increase timeout.
Also fix typo in url.

Ardana-job: Increase timeout

---

scripts/jenkins/ardana/ardana-init.bash

- Also update copyright
- Remove various leftover deletes/mkdirs

Update ardana-init.bash version

---

scripts/jenkins/ardana/ansible/init.yml

There are subtle differences in POOL and ISO medias, handle
both variants.

Handle key import from Cloud ISO as well

---

jenkins/ci.suse.de/openstack-submit-project.yaml

* refactoring of the job
* adding ardana package submission to OBS

jjb: submit-project: also submit ardana packages

---

scripts/jenkins/qa_openstack.sh

* reduce code duplication
* drop dead code

qa_openstack cleanup

---

scripts/jenkins/ardana/ansible/init.yml
scripts/jenkins/ardana/ansible/repositories.yml

This shouldn't be necessary anymore - use the ardana support
for forwarding repositories instead.

Remove manual repository setup quirks

---

scripts/qa_crowbarsetup.sh

This patch fixes bug 1053012, where the qamcloud's ceph tests
fail due to a routing problem from the crowbar node to the
public interface on the ceph nodes.
If deploying ceph the testsetup step had some ceph and radowgw
tests that would run on the admin node. These tests have now
been moved to ceph nodes.
The ceph tests are run on the first monitor node and the
radosgw tests are run on the first radosgw node, where if
network routing is a problem.. then there really is a
deployment problem.

Move the ceph onadmin tests to ceph nodes

---

scripts/qa_crowbarsetup.sh

The SES version we are using is EOL and the testsuite failes.

Remove Cloud 6 Ceph testing

---

jenkins/ci.suse.de/cloud-suse-cloud-specs.yaml
scripts/github_pr/github_cloud-specs.yaml
scripts/github_pr/suse.cloud-specs.helper.sh
scripts/jenkins/update_automation

This will create a job that will run tox tests on PRs to SUSE/cloud-specs
The dependency is already merged:
https://github.com/openSUSE/github-pr/commit/712fe2bd13d0ceb92cf2e72329bb437dc642a904

Tox testing for SUSE/cloud-specs

---

jenkins/ci.suse.de/openstack-ardana.yaml
scripts/jenkins/ardana/ansible/repositories.yml
scripts/jenkins/ardana/ansible/update.yml

This can be used for automated update testing.

Add an update_cloudsource parameter

---

scripts/qa_crowbarsetup.sh

testpreupgrade now requires the ability to also work on SOC7
deployments, and currently prints out a large amount of deprecation
warnings, and then fails to ping the IP due to openstackclient changes.
Update the commands ran if on 7plus.

Move testpreupgrade to openstack commands for 7plus

---

jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-disruptive-ha-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-nondisruptive-ha-mariadb-template.yaml

we need to set 3 node cluster explicitely

fix job name and clusterconfig setup

---

jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-nondisruptive-ha-without-nodes-upgrade-template.yaml

MariaDB setup was complaining about not enough cluster nodes

upgrade: Set the correct size of the HA cluster

---

jenkins/ci.suse.de/cloud-mkcloud-qam.yaml

The QAM team is struggling to setup and pass the tests in
these configurations, so lets see if the issue is reproducible
in our CI system somehow.

Add QAM test scenarios that to our jenkins

---

scripts/qa_crowbarsetup.sh

When `lonelynode_nfs_server` step is run to set up NFS server on a lonely node, it makes sense to set up NFS share for rabbitmq as well as for cinder. This prevents the problems of upgrade failures when NFS server is located on admin server.

Use NFS server set up at lonely node for rabbitmq shared storage.

---

hostscripts/clouddata/syncSLErepos
jenkins/ci.suse.de/cloud-mediacheck.yaml
jenkins/ci.suse.de/cloud-mkcloud8-suse.yaml
jenkins/ci.suse.de/openstack-submit-project.yaml
scripts/lib/mkcloud-common.sh
scripts/mkcloud
scripts/qa_crowbarsetup-test.sh
scripts/qa_crowbarsetup.sh

susecloud8 -> susecloud9, and update references for GM8/GM8+up

Initial plumbing for Cloud 8 GM / Cloud9 development

---

scripts/qa_crowbarsetup-test.sh

have just a single point of truth in this file
so that next time it will be 1 update instead of 10+

qa_crowbarsetup-test: make updating versions easier

---

jenkins/ci.suse.de/templates/cloud-mkcloud-job-monasca-template.yaml
scripts/mkcloud

Add tempest tests for monasca.

monasca: Add tempest tests

---

hostscripts/clouddata/syncSLErepos

syncSLErepos: sync HOS only for cloud 8, sync crowbar-c9 for cloud9 as

---

jenkins/ci.opensuse.org/openstack-repocheck.yaml

In preparation for OpenStack Rocky upgrade, we need to first
enable it on Master and get it tested.
Jira: https://jira.prv.suse.net/browse/SCRD-4288

Enable SLE_12_SP4

---

jenkins/ci.suse.de/cloud-mkcloud9-suse.yaml
jenkins/ci.suse.de/cloud-mkcloud9.yaml
scripts/crowbar-testbuild.yaml
scripts/github_pr/github_pr_crowbar.yaml

The master testing is not yet changed to develcloud9
as the setup for that isn't complete.

Implement PR testing for stable/5.0-pike

---

jenkins/ci.suse.de/openstack-mkcloud.yaml

Cleanup some dead code from openstack-mkcloud

Openstack mkcloud cleanup

---

jenkins/ci.suse.de/cloud-ardana8-suse.yaml

This job tests the released codebase which is avalible to the customers.

Add Ardana8 SUSE Job

---

jenkins/ci.suse.de/cloud-ardana8.yaml

There is no requirement to have seperate projects per job.

Cleanup cloud-ardana8.yaml

---

jenkins/ci.suse.de/macros.yaml

And change to SLE_12_SP3 in case of finding Cloud8

automation: use SLE_12_SP4 by default for trackupstream

---

scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/README.md

Changed the references from `gitlab/ardana-deploy` repo to `github/atuomation`

Update ardana_qe_tests role README

---

jenkins/ci.suse.de/cloud-mkcloud8.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-nondisruptive-ha-mariadb-no-clones.yaml
scripts/scenarios/cloud7/cloud8-upgrade-non-disruptive-no-clones.yml

So that we can monitor the upgrade where pacemaker does not handle
OpenStack services.

Upgrade job which has clone_stateless_services=false

---

scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/templates/tests/neutron.sh.j2
scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/vars/neutron.yml

- Integrate neutron tests into the automation.
- This change has been tested using qe jenkins job.

Added support for neutron tests on ardana_qe_role

---

scripts/jenkins/ardana/ansible/inventory
scripts/jenkins/ardana/ansible/roles/input_model_generator/templates/input_model/data/network_groups.yml

Also, updated the IP address of gate-qe102.

 Removed rabbitmq from internal-lb component on ardana input model genrator

---

scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/templates/tests/monasca.sh.j2
scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/vars/monasca.yml

Merging monasca CLI tests into QE automation framework

Ardana qe tests monasca

---

scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/templates/tests/monasca.sh.j2

had 1 too many var's in the path.

fixed log path

---

jenkins/ci.suse.de/openstack-ardana.yaml
scripts/jenkins/ardana/ansible/deploy-caasp.yml
scripts/jenkins/ardana/ansible/roles/heat-generator/vars/caasp.yml

This adds an option for deploy CaaSP with ardana in jenkins.

SCRD-2814 Add CI coverage for CaaSP

---

scripts/jenkins/track-upstream-and-package.pl

This change properly indents the main part of the program.

Properly indent main

---

scripts/scenarios/cloud7/cloud8-upgrade-non-disruptive-no-clones.yml

(mkcloud always tries to execute tempest from 1st controller node)

Put tempest on first controller node

---

scripts/qa_crowbarsetup.sh

For the upgrade purposes, old database-server role is intended for PostgreSQL.

For SOC7 deployment with MariaDB, we must assign new mysql-server role

---

scripts/scenarios/cloud7/cloud8-upgrade-non-disruptive-no-clones.yml

See https://github.com/crowbar/crowbar-openstack/pull/1746

Use the new mysql specific role that was just introduced in SOC7

---

scripts/jenkins/qa_openstack.sh

Remove some outdated code paths and add timeouts to wget(1) -
for some reason networking is dodgy inside the VM. we need
to isolate the real cause still

qa_openstack: small cleanups

---

hostscripts/clouddata/syncSLErepos
jenkins/ci.opensuse.org/openstack-trackupstream.yaml
jenkins/ci.suse.de/cloud-mediacheck.yaml
jenkins/ci.suse.de/openstack-mkcloud.yaml
scripts/jenkins/mkcloud/openstack-mkcloud.builder.sh
scripts/mkcloud
scripts/qa_crowbarsetup.sh

This provides some support for deploying cloud9 with the rocky packages
for testing.

Add support for cloudsource=rockycloud9

---

scripts/jenkins/ardana/gerrit/build_test_package.py

This set of commits implements a version of cross repo dependencies for building changes from gerrit in OBS.
Both formats of Depends-On work meaning you can use the gerrit change id (Iaaa..ff) or a URL to the change itself.
This only works for dependencies within our gerrit. It does not allow cross-gerrit or github dependencies.

SCRD-4282 Implement a basic version of cross-repo depends-on

---

jenkins/ci.opensuse.org/openstack-trackupstream.yaml

Change-Id: I3b4ccdaaab7c00ca7e12ef02e0a35f98f5606a34

Add build dist support for rocky

---

scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/tasks/prepare_test_env.yml

fixed typo
added root privileges for repo removal

install packages needed for QE tests and cleanup after

---

scripts/jenkins/ardana/ansible/roles/rocketchat_notify/vars/ardana-qe-tests.yml

skipped attribute is now optional

Fix Notify RocketChat for skipped tests

---

scripts/jenkins/ardana/gerrit/build_test_package.py

There are  repos that don't have RPMs, these should be
ignored in the RPM based tests. Right now we see the issue with a-d-t, but
in the furtue it is possible that we have product changes that
require infr changes to land. It would be good to be able to record
that code dependency. We may also see this bewteen test/QA repos
and changes in product code.

SCRD-5000 ignore depends on repos that don't have RPMS

---

scripts/jenkins/ardana/ansible/roles/rocketchat_notify/tasks/main.yml

Fix the rocketchat role logic looking for the cloud build file
to be able to run on localhost.

openstack-ardana: fix the rocketchat messaging

---

scripts/jenkins/ardana/ansible/roles/input_model_generator/defaults/main.yml

Added manila input-model change:
- **manila-client** to clm
- **manila-api** to controller
- **manila-share** to compute

manila: add manila change to jenkin's input-model-generator

---

scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/templates/tests/freezer.sh.j2
scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/vars/freezer.yml

Integrating feezer tests into automation

Added support for Freezer Tests

---

scripts/jenkins/ardana/ansible/files/rpm-verify-modification-whitelist.txt

Reverts SUSE-Cloud/automation#2784

Revert "openstack-ardana: update monasca RPM file permissions check"

---

scripts/jenkins/ardana/ansible/group_vars/all/ssh_pub_keys.yml

Updated ssh_pub_keys.yml with my pub key

Updated ssh_pub_keys.yml with my pub key

---

scripts/jenkins/ardana/ansible/roles/ardana_tempest/defaults/main.yml
scripts/jenkins/ardana/ansible/roles/ardana_tempest/tasks/import_octavia_image.yml

- Tested this change in virtual environment.

Import octavia image before running lbaas tests

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

to CI-test patches without jenkins

mkcloud: allow to monkey-patch crowbar

---

scripts/jenkins/ardana/ansible/roles/send_to_os_health/vars/tempest.yml

Tested this change in qe007 env - https://ci.suse.de/job/openstack-ardana-tempest/516/

Remove extra quote that causes tempest job to fail.

---

scripts/jenkins/ardana/ansible/roles/rocketchat_notify/defaults/main.yml
scripts/jenkins/ardana/ansible/roles/rocketchat_notify/vars/ardana-qe-tests.yml
scripts/jenkins/ardana/ansible/roles/rocketchat_notify/vars/tempest.yml
scripts/jenkins/ardana/ansible/roles/send_to_os_health/vars/ardana-qe-tests.yml

Add the test result(success/failed) into the message title.

openstack-ardana: better formating for rocketchat test reports

---

scripts/qa_crowbarsetup.sh

tempest in cloud9+ switched away from testr to stestr, so
use that when it is available and configured.

qa_crowbarsetup.sh: prefer stestr if available

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-1a.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-1b.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-2a.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-2b.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-2c.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-3.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-6a.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-8a.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-8b.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-9.yaml

cct is not part of the qa testing suit anymore. See the testing plan
https://github.com/SUSE/cloud-specs/blob/master/specs/cloud9/testing_plan.adoc

Remove a cct parameter from qa scenario jobs

---

hostscripts/clouddata/syncSLErepos
scripts/qa_crowbarsetup.sh

The script accidentally configured the ardana media, which doesn't
provide the correct content.

qa_crowbarsetup.sh: mount the crowbar flavor media for cloud8

---

scripts/jenkins/ardana/ansible/bootstrap-vcloud-nodes.yml

This will help on debugging issues like [1].
1. https://ci.suse.de/blue/organizations/jenkins/cloud-ardana9-job-demo-x86_64/detail/cloud-ardana9-job-demo-x86_64/80/pipeline/69/

openstack-ardana: print node ip when creating vcloud inventory

---

scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/templates/tests/remove_compute_node.sh.j2

Update the incorrect variable passed to the cobbler name

 Updated Remove node script to pass the cobbler name to the script

---

scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/templates/tests/remove_compute_node.sh.j2

path for the ardana-qe-tests was incorrect it was missing the subdirectory. Updated the correct path for test script

path for the ardana-qe-tests was incorrect it was missing the subdirectory. Updated the correct path for test script

---

jenkins/ci.suse.de/openstack-ardana-qa-tests.yaml
jenkins/ci.suse.de/templates/cloud-ardana-pipeline-template.yaml
scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/templates/tests/enable_tls.j2
scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/vars/enable_tls.yml

Added support for enable_tls on ardana-qa-test role

---

scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/vars/enable_tls.yml

Ardana qe tests enable tls

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

export hacloud=0 passes this step and complains about clusterconfig not
being set

fix checking hacloud variable

---

scripts/jenkins/ardana/gerrit/build_test_package.py

Packages in the mirrored cloud installation image might be a bit older
due to mirror lag. The repo from the patch under test and its declared
dependencies are build from Git. Also building the other Ardana packages
from Git ensures that the mirror lag doesn't affect them.
Skip packages whose git commit is the same as what is requested to avoid
rebuilding them.

SCRD-4496 build from HEAD to avoid older packages for ardana

---

scripts/jenkins/ardana/ansible/group_vars/all/ssh_pub_keys.yml

upload mu public key to automation repo

upload public key on automation repo

---

jenkins/ci.suse.de/cloud-ardana.yaml
jenkins/ci.suse.de/cloud-ardana9.yaml
jenkins/ci.suse.de/openstack-ardana-tempest.yaml
jenkins/ci.suse.de/openstack-ardana-update-and-test.yaml
jenkins/ci.suse.de/pipelines/openstack-ardana-gerrit.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana-tempest.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana-update-and-test.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana.Jenkinsfile
jenkins/ci.suse.de/templates/cloud-ardana-job-gerrit-template.yaml
jenkins/ci.suse.de/templates/cloud-ardana-pipeline-template.yaml
scripts/jenkins/ardana/ansible/clone-input-model.yml
scripts/jenkins/ardana/ansible/generate-heat-template.yml
scripts/jenkins/ardana/ansible/generate-input-model.yml
scripts/jenkins/ardana/ansible/load-job-params.yml
scripts/jenkins/ardana/ansible/roles/jenkins_artifacts/defaults/main.yml
scripts/jenkins/ardana/ansible/roles/jenkins_artifacts/tasks/main.yml
scripts/jenkins/ardana/ansible/run-ardana-qe-tests.yml
scripts/jenkins/ardana/ansible/run-tempest.yml

This change add support for running tempest multiple times with
different filters on the same jenkins job.
https://jira.suse.de/browse/SCRD-6101

openstack-ardana: add support for running tempest multiple times with diff filters

---

scripts/mkcloud

currently its being done serially.
which is no good

run crowbar_register in parallel for all nodes

---

jenkins/ci.suse.de/pipelines/openstack-ardana-qa-tests.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana-tempest.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana-update-and-test.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana-update.Jenkinsfile
scripts/jenkins/ardana/ansible/roles/ardana_tempest/tasks/post_defcore.yml
scripts/jenkins/ardana/ansible/roles/rocketchat_notify/vars/tempest.yml

This PR includes some fixes for the downstream test jobs:
- Fix artifacts folder link
- Add deployer IP address on job name
- Fix test artifacts link sent to rocketchat

 openstack-ardana: fix downstream test jobs artifacts

---

scripts/jenkins/ardana/ansible/group_vars/all/vcloud.yml
scripts/jenkins/ardana/ansible/roles/input_model_generator/defaults/main.yml
scripts/jenkins/ardana/gerrit/gerrit.py

Disable provisioning LVM volumes (disk models) until all issues
with this approach are identified and resolved.

openstack-ardana: disable LVM volumes

---

jenkins/ci.suse.de/pipelines/openstack-ardana-gerrit.Jenkinsfile

If a `cloud-ardana-gerrit-slot` lockable resource slot isn't
immediately available, the `openstack-ardana` job will keep a
`cloud-ardana-ci` worker unnecessarily busy while waiting for
a slot to become available. When there are many Gerrit jobs
waiting in the queue, this can quickly fill up all available
`cloud-ardana-ci` workers, causing a deadlock.
Reserving a 'cloud-ardana-gerrit-slot' lockable resource slot
early, in the `openstack-ardana-gerrit` job instead of the
downstream `openstack-ardana` job, will avoid deadlocks.

openstack-ardana-gerrit: reserve Gerrit slot early

---

scripts/jenkins/ardana/ansible/roles/rocketchat_notify/vars/deploy.yml
scripts/jenkins/ardana/ansible/roles/rocketchat_notify/vars/update.yml

Set MU value only when MU is defined.

openstack-ardana: fix announcement when no maint updates

---

scripts/jenkins/ardana/gerrit/gerrit-settings.json

Add the ardana/ardana-extensions-apicaci repo to the file
so that gate jobs can run.

Add ardana-extensions-apicaci gerrit-settings.json

---

hostscripts/clouddata/syncSLErepos

we need the jenkins swarm client for the matching service pack
that is installed on mkchX.

Mirror devel:tools:building for SLE_12_SP4

---

scripts/mkcloud

this is needed when all nodes are to be created on the same pv

allow exporting pvlist

---

jenkins/ci.suse.de/openstack-ardana-tests.yaml
jenkins/ci.suse.de/openstack-ardana-update-and-test.yaml
jenkins/ci.suse.de/templates/cloud-ardana-pipeline-template.yaml
scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/templates/tests/nova_guest_images.sh.j2
scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/vars/nova_guest_images.yml

add nova guest image test into automation repo

Added support for guest image test on ardana_qe_tests role

---

jenkins/ci.suse.de/cloud-ardana8.yaml
jenkins/ci.suse.de/pipelines/openstack-ardana.Jenkinsfile
jenkins/ci.suse.de/templates/cloud-ardana-pipeline-template.yaml
scripts/jenkins/ardana/ansible/ardana-ses-rgw.yml
scripts/jenkins/ardana/ansible/group_vars/all/all.yml
scripts/jenkins/ardana/ansible/host_vars/pcloud001.yml
scripts/jenkins/ardana/ansible/inventory

This change adds a pcloud001 environment to ardana automation. It also
adds a new job that will be triggered on daily basis to deploy cloud8
configured with SES as storage backend and run tests.

openstack-ardana: Add QE environment - pcloud001

---

scripts/jenkins/ardana/ansible/roles/input_model_generator/defaults/main.yml

Correct the spelling of designate in the worker and producer entries of the CORE list.

SCRD-6075 Fix typo in designate spelling

---

docs/ardana/testing.md

Update to the Ardana CI documentation (work in progress)

openstack-ardana: update documentation

---

jenkins/ci.suse.de/cloud-ardana8.yaml
jenkins/ci.suse.de/cloud-ardana9.yaml
jenkins/ci.suse.de/pipelines/openstack-ardana-gerrit.Jenkinsfile
jenkins/ci.suse.de/templates/cloud-ardana-job-gerrit-template.yaml

Reverts SUSE-Cloud/automation#3075  CI now broken trying to unwind recent changes.

Revert "openstack-ardana: enable SES for all cloud8 jobs"

---

scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/templates/tests/horizon.sh.j2

SCRD-6775 Install chrome browser

---

hostscripts/clouddata/syncSLErepos

was missing a trailing slash in the source
so it created another level of subdir

fix dle sync and add SLE15

---

jenkins/ci.suse.de/ccp.yaml
jenkins/ci.suse.de/pipelines/cloud-ccp-full-periodic.Jenkinsfile

This adds a minimum CCP job, running a shell script from the
repository.
This job will run periodically (once per day).

Base CCP job periodic

---

jenkins/ci.suse.de/ccp.yaml
jenkins/ci.suse.de/pipelines/cloud-ccp-full-periodic.Jenkinsfile

This adds the way to "hold" instances when a failure happens, for debugging purposes.

Add hold step on CCP

---

docs/devstack/README.md

Remove URLs that refer to systems that are not publicly visible.

Remove URLs to internal sites

---

scripts/jenkins/qa_devstack.sh

~~This is very much WIP, do not merge!  I'm just posting here in case anyone is curious or can spot mistakes as I go along.~~
It's required in order to develop AMD SEV support on the new lab machines.
It may make sense to split some of the commits out into separate PRs, since they're not all related specifically to SLE support.

get qa_devstack.sh working on SLES12

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-2a.yaml
scripts/scenarios/cloud9/qa/no-ssl/qa-scenario-2a.yaml

The HA scenario with SBD as fencing mechanism stopped working some time ago.
This changes initiators and targets a bit to use the crowbar node.

Scenario2a sbd

---

scripts/qa_crowbarsetup.sh

In HA case `rebootcloud` step would reboot controller clusters first
and continue with other "unclustered" nodes. In non-HA case all nodes
are "unclustered" and there was no distinction between controllers and
computes. This could lead to some timeouts if controllers are rebooting
slower than computes.
This change introduces additional split of "unclustered" nodes into two
categories: "computes" and "the rest". "The rest" is rebooted first and
only after these nodes are ready, the compute nodes are rebooted.

Delay reboot of compute nodes

---

jenkins/ci.suse.de/openstack-ardana-update-and-test.yaml
jenkins/ci.suse.de/openstack-ardana-update.yaml
jenkins/ci.suse.de/templates/cloud-ardana-pipeline-template.yaml
scripts/jenkins/ardana/ansible/roles/setup_zypper_repos/README.md
scripts/jenkins/ardana/ansible/roles/setup_zypper_repos/defaults/main.yml
scripts/jenkins/ardana/ansible/roles/setup_zypper_repos/vars/milestone.yml

Adds support for testing RC1, RC2, RC3 and GMC ISOs

openstack-ardana: RC1/2/3 and GMC cloudsource support

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

Reverts SUSE-Cloud/automation#3156

Revert "Revert "Test SSL""

---

jenkins/ci.suse.de/openstack-mkcloud.yaml
scripts/lib/mkcloud-common.sh
scripts/mkcloud
scripts/qa_crowbarsetup.sh

Adds a want_designate_proposal option that defaults to false.

mkcloud: add support for deploying designate

---

scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/templates/tests/heat.sh.j2

Enabling Heat Autoscale Test

---

jenkins/ci.suse.de/cloud-mkcloud9.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-ipv6-template.yaml

Add an initial template for a IPv6 job against Cloud 9.

ipv6: Add a IPv6 job

---

jenkins/ci.suse.de/pipelines/openstack-ardana-gerrit.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-maintenance-gating.Jenkinsfile

This change makes it easier to understand the code.

jjb: Use toBoolean() function in reserve_env function

---

scripts/lib/mkcloud-driver-libvirt.sh

setuphost is run by CI for every job, and it uses zypper to make sure
certain packages are installed, except that routed.cloud script for
mkch* hosts sets http_proxy unilaterally to an address that won't exist
until the libvirt bridge is created. Unset the variable for the zypper
call.

ipv6: Unset http_proxy in libvirt setuphost

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-1a.yaml
scripts/jenkins-support.sh
scripts/qa_crowbarsetup.sh
scripts/scenarios/cloud9/qa/ssl/qa-scenario-1a.yaml

Fix scenario file
Add missing setup steps to jenkins-support.sh
Update job to perform correct ssl setup

Update ssl scenario

---

hostscripts/rpm-packaging/createproject.py

The ci test projects don't need to be published, all we
care about is the build result. the publishing actually blocks
the project form "completing" which causes timeouts in the ci
run, and we don't need to wait for it.
The script always tried to disable publishing, but the build
service actually ignores that request and enables publishing anyway.
just doing it twice together with a sleep seems to be the magic trick
to let OBS do what we want.

Disable publishing for the ci test projects

---

jenkins/ci.suse.de/cloud-ardana9-gerrit.yaml

Fix cloudsource value for cloud9 Gerrit jobs.

openstack-ardana-gerrit: fix cloud9 cloudsource

---

jenkins/ci.opensuse.org/heat-templates/deploy-cleanvm.sh

Also fix setting variable OSHEAD.

Add SLE_12_SP4 to openstack-cleanvm heat template

---

scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/vars/nova_server.yml

Add timeout on nova_server test

Add timeout for nova test on ardana_qe_tests role

---

scripts/qa_crowbarsetup.sh

Reverts SUSE-Cloud/automation#3242

Revert "qa_crowbarsetup.sh: Run tempest last"

---

scripts/jenkins/ardana/ansible/group_vars/all/ssh_pub_keys.yml

This patch adds the public key for Walt Boring (hemna)

Add hemna credentials

---

scripts/jenkins/ardana/ansible/group_vars/all/all.yml
scripts/jenkins/ardana/ansible/host_vars/pcloud002.yml
scripts/jenkins/ardana/ansible/inventory

Add new hardware environment to the list of available QE environments for deploying ardana.

openstack-ardana: add pcloud002 QE HW environment

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-test-tempest-upload.yaml
scripts/qa_crowbarsetup.sh

Job will connect to controller node and upload latest tempest results.

Create new job  to upload tempest results to openstack health dashboard

---

scripts/jenkins/ardana/ansible/group_vars/all/ssh_pub_keys.yml

Please merge this after 2019-04-04

Remove kbaikov credentials

---

scripts/jenkins/ardana/ansible/roles/setup_zypper_repos/vars/milestone.yml

Besides GMC, we also have GMC1, GMC2...

openstack-ardana: add support for versioned GMC media

---

scripts/jenkins/qa_openstack.sh

As part of enabling the neutron_vpnaas tempest plugin for OpenStack
Rocky we need to ensure that the python-neutron-tempest-plugin package
is installed, which leads to tempest failures during a cleanvm run
for the tests patching the pattern:
neutron_tempest_plugin\.api\.admin\.test_tag\
\.Tag(Filter|)(QosPolicy|Trunk)TestJSON
This patch adds support for blacklisting those tests, specified by
their test ids, when running the qa_openstack.sh script for the
'openstackrocky' cloud source.

Blacklist known to fail neutron_tempest_plugin tests (SCRD-8681)

---

jenkins/ci.suse.de/pipelines/cloud-ccp-full-periodic.Jenkinsfile
scripts/socok8s/run.sh

I'm not sure if this is correct, it's the first time I'm editing this code...

Set the value of INTERNAL_NETWORK for the socok8s runs

---

scripts/socok8s/run.sh

(previous patch added INTERNAL_NETWORK only)

Define INTERNAL_SUBNET value

---

jenkins/ci.suse.de/cloud-crowbar7.yaml
jenkins/ci.suse.de/templates/cloud-crowbar-pipeline-template.yaml
scripts/jenkins/ardana/ansible/roles/crowbar_register/tasks/main.yml
scripts/jenkins/ardana/ansible/roles/heat-generator/defaults/main.yml
scripts/jenkins/ardana/ansible/run-crowbar-tests.yml
scripts/qa_crowbarsetup.sh
scripts/scenarios/cloud7/cloud7-5nodes-default.yml

Update the `openstack-crowbar` core job and ansible scripts to
support deploying cloud 7 in the ECP.

openstack-crowbar: enable cloud7 builds (SCRD-8855)

---

scripts/jenkins/qa_openstack.sh

qa_openstack: Add SLE15 HA product

---

docs/mkcloud.md

This patch modernizes, enhances, and corrects the instructions for using
UPDATEREPOS in mkcloud by:
* Updating the example package and project to current versions
* Adding instructions for using osc directly, since osc is packaged and
doesn't require following manual instructions to install from source
and should already be familiar to everyone
* Removing instructions for serving packages with Apache and instead
using the simple HTTP server in python3
* Adding instructions for pulling package from OBS instead of a local
HTTP server
* Correct the mkcloud usage steps, since 'plain' won't include the
update repo or run the update.

Update UPDATEREPOS documentation

---

jenkins/ci.suse.de/cloud-mkcloud9-suse.yaml
scripts/mkcloud
scripts/qa_crowbarsetup.sh

susecloud9 is no longer a valid cloudsource, implement
GM9 and GM9+up going forward.

Cloud9 is released, switch to maintenance mode

---

scripts/jenkins/track-upstream.sh

- Cloud:OpenStack:Master no longer has SLE_12_SP4 so use SLE_15
- Add Cloud:OpenStack:Stein

track-upstream: Fix Master and add Stein

---

jenkins/ci.suse.de/ardana-trigger-trackupstream.yaml
jenkins/ci.suse.de/cloud-ardana8-gerrit.yaml
jenkins/ci.suse.de/cloud-ardana9-gerrit.yaml
jenkins/ci.suse.de/openstack-ardana-gerrit-events.yaml
jenkins/ci.suse.de/openstack-ardana-testbuild-gerrit.yaml
jenkins/ci.suse.de/templates/cloud-ardana-pipeline-template.yaml
scripts/jenkins/ardana/gerrit/README.md
scripts/jenkins/ardana/gerrit/gerrit.py
scripts/jenkins/ardana/manual/input.yml

Update gerrit url references to use the new gerrit server.

Switch to the new gerrit url

---

hostscripts/clouddata/syncSLErepos

syncSLErepos: Fix SES 6 sync

---

jenkins/ci.suse.de/cloud-socok8s.yaml
jenkins/ci.suse.de/templates/cloud-socok8s-integration.yaml

We want to test pull requests against github so add a job that uses a
Jenkinsfile.integration (see [0]) for testing.
This can be expanded to also add jobs for doc-build, linting, ...
[0] https://github.com/SUSE-Cloud/socok8s/pull/329

socok8s: Add PR testing job

---

jenkins/ci.suse.de/templates/cloud-socok8s-integration.yaml

Instead of using the current HEAD of the PR branch, merge it what is
currently in the target branch. That way we test what we get in the
end when something got merged.

socok8s: Fix merge strategy for PR testing

---

scripts/jenkins/ardana/manual/deploy-crowbar.sh
scripts/jenkins/ardana/manual/input.yml
scripts/jenkins/ardana/manual/lib.sh

This PR adds possibility to run playbooks locally and deploy SUSE Openstack Cloud Crowbar in ecp. 
It is based on modification of @lumirsliva in [repo](https://github.com/lumirsliva/ansible-crowbar).
In short: I added some variables definitions  in `imput.yml` to make it work and I added/modified lib.sh file to handle crowbar related palybooks.

add manual deployment in ecp for crowbar

---

scripts/jenkins/gitlint.ini

We should merge this after some days.

Only allow SOC in Git Commit messages

---

scripts/jenkins/ardana/manual/lib.sh

For debugging it may help if the Heat stack deployment is separated
into its own function.

Split Heat stack deploy into separate function

---

jenkins/ci.suse.de/cloud-socok8s.yaml
jenkins/ci.suse.de/templates/cloud-socok8s-integration.yaml

We want to deploy airship when new PRs are created. So add a second
job to deploy airship.
x

socok8s: Deploy with airship and osh for PRs

---

jenkins/ci.suse.de/cloud-socok8s.yaml
jenkins/ci.suse.de/templates/cloud-socok8s-integration.yaml

Reverts SUSE-Cloud/automation#3433
Sorry, I merged too early.

Revert "socok8s: Deploy with airship and osh for PRs"

---

jenkins/ci.suse.de/pipelines/cloud-gating.Jenkinsfile

Promote changes that were made before the last modified time from the
image instead of also the time before the job started.
While there are still cases where this will be wrong it is an
improvement.

ardana gate: use timestamp from image to promote

---

.gitignore
scripts/maintenance-status/Gemfile
scripts/maintenance-status/maintenance-status.rb

This is part of the story to trigger Gating for OBS release requests automatically.

Add maintenance-status.rb helper

---

scripts/jenkins/cloud/ansible/roles/heat-generator/library/generate_heat_model.py

Replace the Python 2 `itervalues()` with `six.itervalues()` which
translates to `dictionary.itervalues()` for Python 2 and
`dictionary.values()` for Python 3.

Replace `itervalues()` method with `six` equivalent

---

jenkins/ci.suse.de/pipelines/openstack-cloud.groovy
jenkins/ci.suse.de/pipelines/openstack-maintenance-gating.Jenkinsfile

The gating-maintenance-update jenkins job will report its status
(running, success, failure) to the maintenance update request.

openstack-ardana: report gating maint. update job status

---

.travis.yml
Makefile

The travis run is one big blob and it's hard to find what you search
for. Split the run into a language and topic specific matrix.

Split test cases into a Travis matrix job

---

Makefile
scripts/jenkins/workers/roles/jenkins_worker/files/gitconfig
scripts/jenkins/workers/roles/jenkins_worker/tasks/configure_git.yml

instead of copy of file .gitconfig

jenkins worker: use git_config ansible module

---

hostscripts/zuul/layout.yaml
jenkins/ci.opensuse.org/openstack-rpm-packaging-build.yaml
jenkins/ci.opensuse.org/templates/openstack-rpm-packaging-sles15.yaml

Master and Stein use SLE15 to build so adjust accordingly.

rpm-packaging: Adjust zuul layout and build job name

---

scripts/qa_crowbarsetup.sh

If the `onadmin_rebootcloud` function is invoked before tests
have been run, the testvm machine isn't present.
After reboot, the manila-service VM also needs to be started,
if it was shutdown during reboot.

qa_crowbarsetup.sh: onadmin_rebootcloud fixes

---

scripts/jenkins/cloud/ansible/bootstrap-vcloud-nodes.yml

Fix spelling

---

scripts/jenkins/cloud/ansible/setup-ssh-access.yml

Same reason as in e6b4c9de4b6b544785e47abe9d9ba88903eb001a

Replace `wait_for_connection` with `wait_for`

---

scripts/jenkins/cloud/ansible/roles/input_model_generator/templates/barclamps/nova.yml.j2

Fixing failed live migration tests on eng cloud.

Update cpu_mode and cpu_model options on barclamp

---

jenkins/ci.suse.de/cloud-ardana8.yaml
jenkins/ci.suse.de/cloud-ardana9.yaml

We want to have one gating job for ardana and crowbar to prepare this
step let's drop the -ardana name from the slot.

jenkins: Drop -ardana from the gate slot name

---

scripts/jenkins/cloud/ansible/roles/input_model_generator/defaults/main.yml

Make deployment non ha as ha not supported for trove

Fix trove barclamp ( SOC-10005 )

---

scripts/maintenance-status/maintenance-status.rb

In the CI Crowbar is know as SOCC7 it's easier to change the script.

maintenance-status: Report Cloud 7 as SOCC7

---

jenkins/ci.suse.de/pipelines/openstack-cloud.groovy

Prevent the `cloud_env` environments corresponding to Resource
Lockable slots from being used with manually triggered Jenkins
jobs.

openstack-crowbar/ardana: protect lockable resource slots

---

jenkins/ci.suse.de/templates/cloud-socok8s-integration.yaml

Removing arguments which are not defined for scm plugin
https://docs.openstack.org/infra/jenkins-job-builder/scm.html#scm.git

Trying to fix error in tempest daily job execution

---

jenkins/ci.suse.de/templates/cloud-socok8s-integration.yaml

Need this to debug failure in daily integration job.

Making socok8s repo and branch values parameterized

---

hostscripts/clouddata/syncSLErepos

We need to keep them in sync, and they're maintained on NUE
site. so instead of having incredibly outdated stuff in provo,
keep them in sync.

syncSLErepos: sync images and disabled files to provo

---

jenkins/ci.suse.de/cloud-gating.yaml

Have the Crowbar 8 jobs that are candidates to be added to the
unified gating job run periodically, to assess their reliability.

Run ECP Crowbar 8 gate candidate jobs periodically (SOC-10029)

---

scripts/qa_crowbarsetup.sh

Mkcloud adds an extra "controller size" node to host monasca-server.
In HA cases this is not the 2nd one but the (cluster_size+1)th one.

Put monasca-server on last controller

---

jenkins/ci.suse.de/cloud-socok8s.yaml
jenkins/ci.suse.de/templates/cloud-socok8s-integration.yaml

Job was mistakenly deleted, restore it

Restore socok8s integration job (SOC-10434)

---

jenkins/ci.suse.de/templates/cloud-socok8s-integration.yaml

We should clean the workspace on each run to avoid issues like
the ara database growing over time

Clean socok8s daily job workspace (SOC-10438)

---

jenkins/ci.suse.de/cloud-socok8s.yaml
jenkins/ci.suse.de/templates/cloud-socok8s-integration.yaml

Create daily job for OpenStack Helm deployment path of socok8s

---

scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/mkcloud.config.j2

Set want_designate_proposal when deploying designate.

designate:add want_designate_proposal option (SOC-10288)

---

scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/mkcloud.config.j2

Set correct ns for deployments

mkcloudconf: set correct ns for deployments (SOC-10288)

---

scripts/jenkins/cloud/ansible/group_vars/qe_all.yml
scripts/jenkins/cloud/ansible/group_vars/virt_all.yml
scripts/jenkins/cloud/ansible/roles/frontail/defaults/main.yml

Do not download resources (images, tools) from outside, instead download
it from cloudddata.

openstack-ardana: Download resources from clouddata

---

jenkins/ci.opensuse.org/openstack-cleanvm.yaml
jenkins/ci.opensuse.org/openstack-repocheck.yaml
jenkins/ci.opensuse.org/openstack-staging.yaml
jenkins/ci.opensuse.org/openstack-submit.yaml

Add the Train projects to the cleanvm, repocheck, staging and submit
jobs. The Cloud:OpenStack:Train and Cloud:OpenStack:Train:Staging jobs
will need to be created and populated before these will work.

Prepare CI for Train

---

scripts/qa_crowbarsetup.sh

The oncontroller_testpreupgrade() function had hardwired
glance image names for Cloud 8 and Cloud 9 that might not
work, depending on which image URL the Tempest barclamp uses
to create its test images. In that case the function would
be unable to create the Heat stack for upgrade testing and
fail the upgrade on the Cloud 8 side. This commit replaces the
hardwired image name by a heuristic that picks the correct
image name based on the images that are actually present.

Determine pre-upgrade image automatically

---

jenkins/ci.suse.de/pipelines/openstack-ardana.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-crowbar.Jenkinsfile

SES deployments occasionally fails due to [1]. This change makes the
Deploy SES step retry 3 times before failing.
1. https://jira.suse.com/browse/SOC-9990

Retry deploying SES on openstack-[crowbar|ardana]

---

scripts/qa_crowbarsetup.sh

When nfs server was installed on a lonely node, it is registered in
dns as 'nfsserver'. It was used for cinder and rabbit but not for
glance (which used nfs server hosted on the admin node).
For upgrade scenarios, external nfs server is better as it is not
rebooted during the upgrade process.

Use external nfsserver for glance if possible

---

scripts/qa_crowbarsetup.sh

Requires https://github.com/crowbar/crowbar-core/pull/1956

Cloud repo should not be required during and after the upgrade

---

jenkins/ci.suse.de/cloud-mkcloud8.yaml
jenkins/ci.suse.de/cloud-mkcloud9.yaml
jenkins/ci.suse.de/templates/cloud-crowbar-pipeline-template.yaml
scripts/qa_crowbarsetup.sh

- designate: deploy designate on crowbar jobs by default(SOC-10288)
- Apply designate-worker in mkcloud configuration to cluster setup

designate: deploy designate on crowbar jobs by default(SOC-10288)

---

jenkins/ci.suse.de/cloud-gating.yaml

This change adds designate tempest tests to the list of tests that are
executed on Crowbar 8 and 9 gating jobs.

Run designate tempest tests on crowbar8/9 gating jobs (SOC-10288)

---

scripts/iscsictl.py

The iscsictl.py tool sometimes runs into zypper related failures
that look like this:
```
System management is locked by the application with pid yyy (zypper).
Close this application before trying again.
```
This happens because the chef-client may run a zypper command at the
same time on the same target host. Retrying this operation only in
case an error code value of 7 (ZYPPER_EXIT_ZYPP_LOCKED) is returned
helps to avoid such conflicts.

iscsictl.py: fix zypper conflicts

---

scripts/jenkins/cloud/ansible/roles/list_packages/README.md
scripts/jenkins/cloud/ansible/roles/list_packages/defaults/main.yml
scripts/jenkins/cloud/ansible/roles/list_packages/library/parse_xml.py
scripts/jenkins/cloud/ansible/roles/list_packages/tasks/diff-packages.yml
scripts/jenkins/cloud/ansible/roles/list_packages/tasks/list-packages.yml
scripts/jenkins/cloud/ansible/roles/list_packages/tasks/main.yml

Enhance role list-packages to gather packages in yaml format (version,buildurl,release).
Currently zypper repo of package origin is missing.

openstack-deployment: add generate yaml files into list-package role (SOC-10610)

---

scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/mkcloud.config.j2
scripts/jenkins/cloud/ansible/roles/cloud_generator/vars/product/crowbar.yml

Followup after https://github.com/SUSE-Cloud/automation/pull/3814

Fix cloud_iso_name value for upgrade case

---

scripts/lib/mkcloud-onhost.sh

Local repo cache was not replicating the LTSS-Updates-test repo.

Add LTSS test repo to local cache

---

scripts/qa_crowbarsetup.sh

The `onadmin_rebootcloud` logic from qa_crowbarsetup.sh is not
handling rebooting a cloud node correctly when it is part of
an HA setup. According to the official SLE-HA docs [1], the
controller node needs to be put into standby mode, which
effectively moves all crm resources away from the node and
the pacemaker service has to be stopped before the node can
be safely rebooted.
Not following the correct reboot procedure leads to the node
being fenced half-way through the reboot process, which in turn
causes other problems, such as corrupted root partitions (because
we also have disabled ext journaling on the ECP CI images, to
improve IO performance).
[1] https://documentation.suse.com/sle-ha/15-SP1/single-html/SLE-HA-guide/#pro-ha-maint-shutdown-node

qa_crowbarsetup.sh: prepare HA controller node before reboot (SOC-10960)

---

scripts/jenkins/cloud/ansible/roles/list_packages/tasks/list-packages.yml
scripts/jenkins/cloud/ansible/roles/list_packages/tasks/main.yml

* on CentOS nodes zypper command is missing, this will use repoquery
there
* also this should fix set_facts of combine dictionaries in the task
(currently it is not clearing previous values)

fix list-packages role on CentOS

---

scripts/jenkins/cloud/ansible/group_vars/all/all.yml
scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/barclamps/aodh.yml.j2
scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/barclamps/barbican.yml.j2
scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/barclamps/ceilometer.yml.j2
scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/barclamps/cinder.yml.j2
scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/barclamps/designate.yml.j2
scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/barclamps/glance.yml.j2
scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/barclamps/heat.yml.j2
scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/barclamps/horizon.yml.j2
scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/barclamps/keystone.yml.j2
scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/barclamps/magnum.yml.j2
scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/barclamps/manila.yml.j2
scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/barclamps/monasca.yml.j2
scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/barclamps/neutron.yml.j2
scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/barclamps/nova.yml.j2
scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/barclamps/octavia.yml.j2
scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/barclamps/sahara.yml.j2
scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/barclamps/swift.yml.j2
scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/barclamps/trove.yml.j2

If the user requested to debug the CI deployment, also turn on debug
for OpenStack services.

Turn on debug in OpenStack services

---

jenkins/ci.opensuse.org/openstack-cleanvm.yaml

Remove Newton and Queens from cleanvm

---

scripts/jenkins/cloud/ansible/group_vars/all/versioned.yml
scripts/jenkins/cloud/ansible/roles/cloud_generator/defaults/main.yml

Enable neutron ml2 port security extension for ardana input model.

Enable port security extension ardana (SOC-11027)

---

scripts/jenkins/cloud/manual/lib.sh

Going forward we want to use Python 3 rather than Python 2, so we
need to ensure that where possible the ansible-venv is created based
upon the desired Python version, where appropriate, rather than the
system default Python version. Note that for Ansible 2.7 this means
we need at least Python 3.5, or Python 2.6.
Additionally the existing run_python_script() prefers Python 3 over
Python 2, but in the case were a system's Python 3 is not viable for
creating the ansible-venv, would still select python3 to run scripts
such as the build_test_package.py script use to build Gerrit based
packages. However if the ansible-venv was created as a Python 2
based virtualenv, and the host system's Python 3 environment doesn't
have a compatible set of Python modules installed to support running
the …

Use appropriate Python version for ansible-venv (SOC-10914)

---

jenkins/ci.suse.de/cloud-gating.yaml
scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/barclamps/lib/ssl.yml.j2
scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/barclamps/magnum.yml.j2

Enabled magnum tempest filter for SOC7
Deploy magnum with ssl enabled

Enable magnum tests for SOC7

---

scripts/jenkins/cloud/ansible/roles/list_packages/README.md
scripts/jenkins/cloud/ansible/roles/list_packages/library/diff_yaml.py
scripts/jenkins/cloud/ansible/roles/list_packages/tasks/diff-packages.yml
scripts/jenkins/cloud/manual/requirements.txt

Stage 1: enhance diff produced by list_package role.
- change from plain-text output to yaml
- adds ansible module `diff_yaml.py` to the role
- adds python venv requirement deepdiff

openstack deployment: structured diff of installed packages (SOC-11086)

---

jenkins/ci.suse.de/cloud-crowbar.yaml
jenkins/ci.suse.de/cloud-crowbar8.yaml
jenkins/ci.suse.de/cloud-crowbar9.yaml
jenkins/ci.suse.de/cloud-gating.yaml
scripts/jenkins/cloud/ansible/roles/cloud_generator/README.md

Enable SES integration testing in the SOC8 gating jobs.

openstack-crowbar: enable SES in SOC8 gating jobs

---

jenkins/ci.suse.de/cloud-ardana9.yaml

That job is running daily and as IPv6 won't be implemented anymore,
remove that job.

Remove Ardana IPv6 periodic job

---

jenkins/ci.opensuse.org/openstack-trackupstream.yaml

yaml doesn't allow comments inside values
and I can't find the Jenkins documentation for the combination filter.
Depoying this with jenkins-job-builder was throwing an error with
saying: "Oops! A problem occurred while processing the request." And a
logging id. The job was updated, but I doubt it would work.

yaml doesn't allow comments inside values

---

jenkins/ci.suse.de/cloud-ardana8.yaml
jenkins/ci.suse.de/cloud-crowbar8.yaml
jenkins/ci.suse.de/cloud-gating.yaml
jenkins/ci.suse.de/templates/cloud-ardana-pipeline-template.yaml
jenkins/ci.suse.de/templates/cloud-crowbar-pipeline-template.yaml

This should be merged only when [1] reaches D:C:8:Staging.
1. https://build.opensuse.org/request/show/822222
This reverts commit bf8afa3b73d0007f363609cf22de1e282d8256eb.

Revert "Temporarily disable SOC8 jobs"

---

scripts/jenkins/cloud/ansible/roles/list_packages/README.md
scripts/jenkins/cloud/ansible/roles/list_packages/defaults/main.yml
scripts/jenkins/cloud/ansible/roles/list_packages/library/combine_files.py
scripts/jenkins/cloud/ansible/roles/list_packages/tasks/main.yml
scripts/jenkins/cloud/ansible/roles/list_packages/tasks/packages_from_old_jobs.yml

This PR enhances diff of installed packages by doing diff of old job runs.

openstack-deployment: diff installed packages with old job runs

---

scripts/mkcloud

See https://github.com/SUSE-Cloud/automation/pull/3815

Update supportconfig extesion

---

hostscripts/gatehost/crowbaru1.xml
hostscripts/upgrade-scale/README.md
hostscripts/upgrade-scale/batches/00_provisioner.yml
hostscripts/upgrade-scale/batches/01_ipmi.yml
hostscripts/upgrade-scale/batches/02_ntp.yml
hostscripts/upgrade-scale/batches/03_pacemaker.yml
hostscripts/upgrade-scale/batches/04_database.yml
hostscripts/upgrade-scale/batches/05_rabbitmq.yml
hostscripts/upgrade-scale/batches/06a_keystone.yml
hostscripts/upgrade-scale/batches/06b_keystone.yml
hostscripts/upgrade-scale/batches/07_monasca.yml
hostscripts/upgrade-scale/batches/09_glance.yml
hostscripts/upgrade-scale/batches/10_cinder.yml
hostscripts/upgrade-scale/batches/11_neutron.yml
hostscripts/upgrade-scale/batches/12_nova.yml
hostscripts/upgrade-scale/batches/13_horizon.yml
hostscripts/upgrade-scale/batches/14_heat.yml
hostscripts/upgrade-scale/batches/15_manila.yml
hostscripts/upgrade-scale/batches/30_tempest.yml
hostscripts/upgrade-scale/build.sh
hostscripts/upgrade-scale/setup.sh
scripts/qa_crowbarsetup.sh

This originally targeted upgrade-scale branch but it was not needed anymore (and got deleted).
Re-targeting this to master for documentation purposes.

upgrade-scale: updates for 8-9 scale testing

---

hostscripts/soc-ci/soc-ci

Follow-Up: https://github.com/SUSE-Cloud/automation/pull/3834

Add xz support to tar file handling

---

hostscripts/clouddata/syncSLErepos

Also mirror SLE-12-SP4-LTSS

---

scripts/maintainers/README.md
scripts/maintainers/canonicalpac.pl
scripts/maintainers/cloudpackages.py
scripts/maintainers/genmaintainers.sh
scripts/maintainers/parse_maintainers.pl

This commit adds a collection of scripts for generating a list
of maintainers for packages shipped as part of SUSE OpenStack
Cloud 7, 8 and 9.

Add maintainer listing scripts

---

jenkins/ci.suse.de/cloud-crowbar7.yaml
jenkins/ci.suse.de/cloud-gating.yaml
jenkins/ci.suse.de/cloud-mkcloud7.yaml

To reduce unnecessary load on CI disabling mkcloud7 jobs.

Disable all mkcloud7 jobs

---

Jenkinsfile

Also set PATH so it can be found.
It is now available on cloudtrigger hosts.

Enable roundup in CI again

---

Jenkinsfile

It is now available on cloudtrigger hosts.

Enable bashate in CI again

---

scripts/jenkins/cloud/ansible/roles/heat-generator/templates/servers.yml
scripts/jenkins/cloud/ansible/roles/heat-generator/templates/virtual_nic_mappings.yml

indentfirst was renamed to first
See: https://jinja.palletsprojects.com/en/3.0.x/templates/#jinja-filters.indent

Update indent first argument

---

hostscripts/rpm-packaging/createproject.py

Also makes it possible to define a different spec style

Update to work with newer Python/sh versions
