scripts/jenkins/qa_openstack.sh

Do that to fail if listing tests doesn't work for some reason.

qa_openstack: list tests before tempest run

---

scripts/mkcloud

We now need to set CB_BACKUP_IGNOREWARNING to ignore the warning, as the
script is supported. We keep the old variable to keep working on old
versions of SUSE Cloud.
Needed by https://github.com/SUSE-Cloud/cloud-tools/pull/12

Adapt to env var change for crowbar-backup

---

scripts/qa_crowbarsetup.sh

If it's still broken, we'll fix it. But install-suse-cloud requires it
to be valid.

qa_crowbarsetup: Setup SLES12-Pool repo for SLE12 too

---

scripts/qa_crowbarsetup.sh

This ensures the key for the DEPS repo is auto-imported.

qa_crowbarsetup.sh: do zypper refresh earlier

---

scripts/qa_crowbarsetup.sh

It's easier to immediately see the common prefix this way, which avoids overly
long lines.  We can also drop the superfluous quotes.

qa_crowbarsetup.sh: use brace expansion

---

scripts/qa_crowbarsetup.sh

We have some checks in the code now (like in suse-cloud-upgrade) that
require these repos to be configured on the admin server.

qa_crowbarsetup: Add Cloud product repos on admin server

---

scripts/qa_crowbarsetup.sh

There's no way this could have worked, because $slesversion and $slesmilestone
are only ever set for SLES 11.

qa_crowbarsetup.sh: remove broken copy'n'paste code :-/

---

scripts/qa_crowbarsetup.sh

Without a comment, the omission of this optional parameter is easily missed.

qa_crowbarsetup.sh: comment on lack of zypper add

---

scripts/mkcloud

Fix issues with the mechanism for overriding the install-chef-suse.sh 
distributed via the crowbar package:
- mkcloud only works when run from the directory it lives
in.  (This is arguably a bug, but we can fix it separately
later.)  That means that you could only override
install-chef-suse.sh by placing the alternate version in the
same directory as mkcloud, but this requires an extra copy
instead of being able to directly test the version in your
checked out crowbar repo working directory.  It also messes up
the git repository.
- The scp was being run even if the override file didn't exist,
causing a spurious error.
- The same override code was duplicated.

fix install-chef-suse.sh override mechanism

---

scripts/mkcloud

* you can work on `qa_crowbarsetup.sh` in your git clone, and use that one for execution. 
* calling `mkcloud` can happen from anywhere with a script pointing to `mkcloud` in your git clone
this would fix https://github.com/SUSE-Cloud/automation/issues/222

mkcloud: enable calling mkcloud from anywhere

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

This is required so we can set REPOS_SKIP_CHECKS before restoring backup.

mkcloud/qa_crowbarsetup: Move backup/restore code to qa_crowbarsetup.sh

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

prevent it from printing process IDs to stdout
as we just need the exit code

mkcloud: wait_for_if_running readable output

---

scripts/mkcloud

in the past we often hit cases where multiple zypper calls occurred in parallel.
By using rpm which has proper locking (and waits for it)
we ensure that we have the packages
without someone failing from ensuring the same at the same time

mkcloud: avoid zypper errors

---

scripts/qa_crowbarsetup.sh

without this, mkcloud is failing from the repo-check
which is only skipped on cloudsource=develcloud

qa_crowbarsetup: add Cloud5 repos for GMC2 etc

---

scripts/qa_crowbarsetup.sh

instead of us waiting for zypper to finish (which is racy)
we let zypper wait on its lock itself
making our code simpler and more reliable

qa_crowbarsetup: let zypper wait on its lock

---

scripts/qa_crowbarsetup.sh

moving the call of chef-client outside of the loop, otherwise it was called too often

qa_crowbarsetup: move fill back out of loop in order not to call it too often

---

Makefile
scripts/qa_crowbarsetup.sh

Conventional wisdom across the industry is that it is a bad idea to exceed 80 column lines. This is visible in countless areas, from the Linux kernel coding style through to PEP8 and beyond.  Long lines definitely make code harder to read for some people, so even if you don't *personally* feel it increases readability for you, please still be considerate of other people.
It's not just a matter of taste either.  Some user interfaces do not automatically wrap lines, so in those cases long lines can cause significant usability issues.  For example, when viewing diffs on parts of github, the lack of line wrapping means that you have to use a horizontal scroll bar to see the whole line:
This is a major PITA.
In the case where there is an `if` statement with a long conditional, it means that …

qa_crowbarsetup.sh: split long lines

---

scripts/mkcloud

when debugging mkcloud, this is one of the annoyingly slow parts
and this can now be avoided

mkcloud: allow to skip supportconfig gathering

---

scripts/qa_crowbarsetup.sh

This is for testing neutron-l3 role deployment at SLES12.
Maybe there should be specific option to turn this on.

Assign neutron-l3 role to one of SLE12 nodes

---

scripts/qa_crowbarsetup.sh

this is a follow-up on 56c244c56e904305032259d2632a3323da2aff22
to disable it by default because it errors with
Failed to validate proposal: Role neutron-l3 can't be used for suse 12.0

qa_crowbarsetup: dont try neutron-l3 on sles12

---

scripts/mkcloud

add ability to inject user own public key

allow user inject own public keyfile in preparecrowbar

---

scripts/jenkins/qa_openstack.sh

couddata.cloud.suse.de is not accessable from the CI system.

qa_openstack: Fix cirros image url

---

scripts/qa_crowbarsetup.sh

The names of the repos are not SLES12-GA-{Pool,Update}, but
SLES12-{Pool,Update}
Also there's no need to create SLE12-Cloud-Compute-PTF: it's installed
by the crowbar package.

Fix setup of SLE12 repos

---

scripts/qa_crowbarsetup.sh

The set_proposalvars function was hard to read. I was hard to figure out what the defautls are and what consequences several variables had.
This commit should clean this up by making the defaults explicit and listing filters and contraints separately.
* Default storage is neither ceph nor swift.
* Honour both want_ceph and want_swift variables consistently.
* Reorder code that touches wantswift and wantceph to allow
sanity check.
* Adding headings for code blocks.

qa_crowbarsetup: cleanup and reorder set_proposalvars

---

scripts/qa_crowbarsetup.sh

This only works for Cloud 6+, or for Cloud 5 if we explicitly request
the vxlan networking mode. This way, it's compatible with Cloud 5 GM.
Depends on https://github.com/crowbar/barclamp-neutron/pull/206

[WIP] Allow use of vxlan in neutron

---

Makefile

tabs dont work well with copy-paste,
and can make the life of other tools harder

bash-tests: forbid tab characters

---

scripts/mkcloud

Previous logic made unreliable assumptions about the existing
contents of libvirtd.conf.

Fix libvirtd configuration and startup

---

scripts/mkcloud

Currently the hacloud option is very opinionated and requires at least 11 VMs
to work.  On a machine with only 16GB of RAM this is totally useless.  There
are plans to fix this:
https://trello.com/c/9viz41KH
However as a short-term workaround it is good enough to simply allow DRBD
disks to be set up even if the hacloud parameter is not set to 1; then we can
do:
mkcloud instonly
and then feed a pre-prepared YAML to crowbar batch to set up the cloud.

mkcloud: allow independent creation/use of DRBD disks

---

scripts/qa_crowbarsetup.sh

57b3348 of #264 accidentally removed the call to the 
`mount_localreposdir_target()` function, which broke use of local repositories.

qa_crowbarsetup.sh: unbreak local repo support

---

scripts/qa_crowbarsetup.sh

The ha support introduced a bug that tempest was deployed on all compute nodes. But it can only be deployed on just one node. This PR fixes that and deploys tempest on the first compute node.

qa_crowbarsetup: fix tempest node assignment in HA mode

---

scripts/qa_crowbarsetup.sh

Don't assume /etc/sysconfig/network/routes exists when checking its contents,
otherwise we get a needlessly alarmist error.

qa_crowbarsetup.sh: avoid spurious error when no routes files

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

By default mkcloud required 9 nodes for an HA setup as it only supported 3 clusters (data min. 2 nodes, services min. 3 nodes, network min. 3 nodes) plus one compute node as minimum.
This feature now supports the deployment of an HA setup on 1, 2 or 3 clusters.
To configure the scenario use the variable "clusterconfig". 
```
3 clusters: clusterconfig="data=2:network=3:services=3"
2 clusters: clusterconfig="services+data=2:network=3"
1 cluster:  clusterconfig="network+services+data=2"
```
The first one of each group (combined via +) defines the name of the cluster. The services from the grouped clusters are merged into the first one. A Group defines its node number via "=2" at the end. Groups can be separated via ":".

support 1, 2 and 3 clusters for HA deployment

---

scripts/qa_crowbarsetup.sh

Setup of SLES12 and HAE repos was previously broken when using local repos
instead of clouddata.cloud.suse.de.

qa_crowbarsetup.sh: fix SLES12 / HAE local repo access

---

scripts/qa_crowbarsetup.sh

This typo meant that clusterconfig values such as
"services+network+data=2"
(i.e. where the services cluster comes first but is also used to host network
and/or data) would break due to the clusternamedata and clusternamenetwork
variables not being set properly.

qa_crowbarsetup.sh: fix typo breaking shared services cluster

---

scripts/qa_crowbarsetup.sh

L2 population requires vxlan or gre, and with linuxbridge, we only
enable vlan.

qa_crowbarsetup: Disable use_l2pop when using linuxbridge

---

scripts/qa_crowbarsetup.sh

It's much more convenient to do "ssh node1" than the long name of each
node.
We do not use the crowbar alias mechanism as the nodes can have other
aliases (such as dashboard) through that mechanism, and we do not want
to override this.

qa_crowbarsetup: Add aliases to .ssh/config for each node

---

scripts/qa_crowbarsetup.sh

for testing, we always use self-signed certs
and even in production deployments, we have certs
that are only valid for the public-name of the controller node
but not the internal names for admin IPs

qa_crowbarsetup: never check SSL certs

---

scripts/qa_crowbarsetup.sh

moves the call of 
`crowbar machines list | sort | grep | something`
to a function and replaces all usages of `crowbar machines list`.
This does not save code, but it becomes more readable.

Crowbar machines list cleanup

---

scripts/repochecker

Currently the CI job openstack-repocheck can only be run remote on a
single host which has the solv files in a specific path.
This script can be run on any host (also local) to check installation
problems for the Cloud:OpenStack:* projects.

Add repochecker script

---

scripts/mkcloud

The alias_* steps are for internal use only, so remove them from the usage
text and instead use the _ prefix convention for private/internal symbols.
Fixes #292.

hide the alias_* internal steps (#292)

---

scripts/mkcloud

The `setupcompute` and `instcompute` steps are misnomers since
1. they don't just set up compute nodes but also controller, storage, and network nodes, and
2. they set up all the nodes (except the admin node), not a single node.
So rename them to `setupnodes` and `instnodes`, but maintain backwards-compatibility.
Fixes #269.

fix misnamed "compute" steps (#269)

---

scripts/mkcloud

If we can't clean up LVs from a previous run, then things will fail later on,
so it's best to bail immediately to save time.
Unfortunately we cannot use the safely() function here because shell sucks (no
proper exception handling).

mkcloud: bail in cleanup step if lvremove fails

---

scripts/repochecker

When using with Tumbleweed, the urls are different no updates are needed.

repochecker: Fix Tumbleweed case

---

scripts/qa_crowbarsetup.sh

The prepareinstcrowbar step could be called after the addupdaterepo step, so
it shouldn't nuke the PTF repo which addupdaterepo may have added.
Fixes #291.

mkcloud: don't delete PTF repo when deleting other repos

---

scripts/qa_crowbarsetup.sh

The variable nodescompute should also contain the correct names of nodes even in non-HA mode.
This PR fixes it. This is needed by the docker feature.

qa_crowbarsetup: fill nodescompute var with correct data also in non-HA mode

---

scripts/mkcloud

The problem is that we generate DNS queries from public IPs
routed over the public VLAN and dnsmasq did only listen
on the admin interface, so could not respond.
libvirt autodetects and uses the bind-dynamic dnsmasq feature
in src/network/bridge_driver.c and src/util/virdnsmasq.c
by looking for the bind-dynamic string in the dnsmasq help
and we can prevent it by replacing it there.
This addresses problems introduced with PR #290

mkcloud: allow cloud instances to get responses from dnsmasq

---

scripts/lib/libvirt/cleanup.py
scripts/lib/libvirt/net-start.py
scripts/lib/libvirt/vm-start.py
scripts/lib/mkcloud-libvirt.sh
scripts/mkcloud

This is part of the refactoring for mkcloud.
All the libvirt code that has been previously handled by Bash, should be extracted to a more suitable language for the task. We chose python over ruby here because it comes with libvirt bindings, which are available in SLES.
As I have very little experience with python, please give me some input on that.
Further I chose to write the tools as granular as possible, so that one script does only one job, which makes it more maintainable IMO. I thought about putting all libvirt stuff in one script but I didn't see an advantage in that. What do you suggest?
This PR introduces the
* `cleanup` of libvirt resources
* `network` definition and creation
* `vm` definition and creation
The actual creation of the XML files, as well as host specific libvirt …

Extract the Bash code for libvirt handling to python scripts

---

scripts/jenkins/update_automation

Instead jenkins jobs either need to call mkcloud from the real path
or have the checkout dir in $PATH

update_automation: drop symlinks

---

scripts/mkcloud

Only want_{ceph,swift} supports to set it to 0.
All other variables are tested for empty or defined.

mkcloud: fix integer comparison with empty string

---

scripts/mkcloud

On the mkcloud hosts we have tons of these empty directories which consume several MB of disk space.

mkcloud: cleanup cloudmnt dir

---

scripts/mkcloud

thank you [jenkins](https://ci.suse.de/job/openstack-mkcloud/3976/)
```
+ /root/github.com/SUSE-Cloud/automation/scripts/lib/libvirt/vm-start /tmp/.xml
File "/root/github.com/SUSE-Cloud/automation/scripts/lib/libvirt/vm-start", line 19, in <module>
main()
File "/root/github.com/SUSE-Cloud/automation/scripts/lib/libvirt/vm-start", line 15, in main
libvirt_setup.vm_start(args)
File "/root/github.com/SUSE-Cloud/automation/scripts/lib/libvirt/libvirt_setup.py", line 237, in vm_start
vmname = xml_get_value(args.vmpath, "name")
File "/root/github.com/SUSE-Cloud/automation/scripts/lib/libvirt/libvirt_setup.py", line 215, in xml_get_value
tree = ET.parse(path)
File "/usr/lib64/python2.6/xml/etree/ElementTree.py", line 862, in parse
tree.parse(source, parser) …
```

fix lonely_node variable name

---

scripts/repochecker

REPCHECK_BS_INSTANCE=ibs can be set to use SUSE's internal buildservice
instance. Default remains the public instance on build.opensuse.org .

repochecker: Allow checks for IBS projects

---

scripts/jenkins/update_automation

ignore local changes (they should use a copy of the repo)
and consistently checkout the latest remote master

update_automation: stick to remote master branch

---

scripts/mkcloud

mkcloud creates LVs for use as DRBD data disks, which are then used by the controller VMs as PVs to build drbd VGs on top of.  However we need to prevent the host from detecting the LVs inside the resulting drbd VGs, because they only concern the controller VM guests.  This requires tweaking `lvm.conf` which is not easy to automate, but we can at least check whether it was done right, and bail if not.
@jdsn This was based on your suggestion for editing `lvm.conf`, but I still don't understand it 100% because it will still detect the `/dev/dm-$i` devices corresponding to these LVs, so what does it really achieve by excluding the `/dev/$vg` and `/dev/mapper/$vg-*` devices?

mkcloud: watch out for incomplete LVM device filter

---

scripts/mkcloud

it already happened
that two mkcloud runs both find /dev/loop0 as free
but the 2nd of them finds it busy when it really wants to use it
collision happened in
https://ci.suse.de/view/Cloud/view/Worker/job/openstack-mkcloud/4168/console
https://ci.suse.de/view/Cloud/view/Worker/job/openstack-mkcloud/4169/consoleFull
02:13:19 losetup: /dev/mkcvg0/c4.admin: failed to set up loop device: Device or resource busy

mkcloud: avoid race on loop dev

---

scripts/qa_crowbarsetup.sh

it already happened twice that someone ran the script on the host instead of the admin VM

qa_crowbarsetup: only run on VMs by default

---

scripts/github-status/github-status.rb

Adding support for the error status, meaning that the test run itself could not be run (while failure means, the test could be run but it failed, so the PR is breaking it).
Also adding support for custom message to be shown in github. Primarily used to describe the error status.

github-status: support custom message and error status

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

This log can be used by the code in the steps or test frameworks called by mkcloud to figure out what has been done until now.

mkcloud, qa_crowbarsetup: write log of steps that are processed

---

scripts/mkcloud

In mkcloud script there is missing function `iscloudver`
```
scripts/mkcloud: line 1179: iscloudver: command not found
```

Fixing minimal number of nodes in mkcloud

---

scripts/mkcloud

we actually want to provide our config from the outside
and qa_crowbarsetup now sources mkcloud.config for us
which would override the values we wanted

mkcloud: dont source mkcloud.config

---

scripts/qa_crowbarsetup.sh

do not assign another compute role to node with docker. Should fix failing docker builds

do not assign another compute role to node with docker

---

scripts/mkcloud

Jenkins set some variables to identify the name of the test that
is running.  We name the tempest run using $JOB_NAME, but in this
Jenkins instance is always 'openstack-mkcloud'
Instead of testing with $BUILD_ID, we will use a hand-name name to
identify the tests.

Replace $JOB_NAME with a hand-made name

---

scripts/qa_crowbarsetup.sh

recently, we started to change mtu: 1500 to 1589
in the mkphyscloud case
which stopped ssh from working

qa_crowbarsetup: be more strict in sed

---

scripts/lib/libvirt/fixtures/cloud-node1.xml
scripts/lib/libvirt/templates/compute-node.xml
scripts/lib/libvirt/test_libvirt_setup.py
scripts/mkcloud

we want disk to be ordered after network in the default case
but ordered before in the lonely node case

fix boot order for lonely nodes

---

docs/mkcloud.md
scripts/qa_crowbarsetup.sh

This changes the path to match what's introduced by
https://github.com/crowbar/crowbar/pull/2108 and
https://github.com/crowbar/barclamp-provisioner/pull/441
Signed-off-by: Tim Serong <tserong@suse.com>

Rename Cloud-PTF repo to just PTF

---

scripts/qa_crowbarsetup.sh

It seems that with Kilo, Horizon redirects the page by default without
even returning anything, so we need to tell curl to follow the redirect.

qa_crowbarsetup.sh: Follow redirect in curl to Horizon

---

scripts/qa_crowbarsetup.sh

On Cloud 6, all nodes are SLES 12 by default, so we don't want to
restrict compute roles to only one node.

qa_crowbarsetup.sh: Only set intended roles for SLES12 nodes on Cloud 5

---

scripts/qa_crowbarsetup.sh

I can't think why anyone would ever place a package in the PTF repo and then *not* want it to be installed in preference to a different version from another repo.  So it makes sense for the PTF repo to have a higher priority than all other repos.

increase priority of PTF repo on all nodes

---

.gitignore

the output of the test suite is not really needed in our version control

add roundup folder to .gitignore

---

scripts/lib/libvirt/fixtures/cloud-node1.xml
scripts/lib/libvirt/test_libvirt_setup.py
scripts/mkcloud

There is no way to get the controller node into 4GB anymore with
the increased number of services and the much increased memory
usage of OpenStack Kilo. Raise it to get at least jenkins
somewhat green again.

mkcloud: Raise memory for controller node.

---

scripts/github-status/github-status.rb

In order to reuse github-status.rb for not only testing
automation repo pull requests, we need to be able to set the
name of the custom repo to check.

Add command line parameter for setting repository

---

scripts/mkcloud

Used like this:
mkcloud step1 step2 step3+paraA+paraB+paraC step4
This was added for cct tests but could be used for batch or others

mkcloud: support calling steps with parameters

---

scripts/jenkins/ci.suse.de/openstack-mkcloud.xml

This is a valid choice and is expected by cloud-mkcloud6-ha-trigger.

allow 'vxlan' as a choice for the 'networkingmode' parameter

---

scripts/qa_crowbarsetup.sh

When zypper returns 103, then it means that the zypp stack got updated
and zypper needs to be re-run.

qa_crowbarsetup: Fix runupdate to correctly re-run zypper if needed

---

scripts/qa_crowbarsetup.sh

The PTF channel was recently renamed in Cloud 6.x
to just "PTF".

Adjust naming of the PTF channel

---

scripts/qa_crowbarsetup.sh

you.suse.de is going away with the upcoming IBS switch to Build
Service Maintenance.

New testupdate urls for IBS maintenance

---

scripts/crowbar-testbuild.py
scripts/jenkins/ci.suse.de/openstack-mkcloud-pr-trigger.xml

Since cct is an integral part of the mkcloud gating run, we
also should run the selftest against cct PRs.

Implement PR testing for SUSE-Cloud/cct

---

scripts/qa_crowbarsetup.sh

The result of a knife search node is unstable, so slap in a sort to
have a predictable outcome.

Fix sle12_node detection

---

scripts/qa_crowbarsetup.sh

"crowbar machines list" returns FQDNs but "crowbar node_state status"
only hostnames. Get hostname from FQDN to compare the current node state.

Fix node power check after reboot

---

scripts/mkcloud

As @tboerger mentioned in #431 the split lines should get some indentation.
I initially didn't do this as I thought it would add extra spaces between the values.
As it turns out, this is not the case ... except you would use zsh for testing this ;)
Note: Two of the lines now are longer than the 72 characters @aspiers suggested in the other pull request. I decided to keep the line-break where it was to not screw up the diff. If you think it's worth breaking the line earlier, just say so.

Fix indentation at assignment of allcmds variable

---

scripts/qa_crowbarsetup.sh

The change to `slesdist` for Cloud 6 in #485 exposed a new code path for `hacloud=1` with SLE12.  Technically HA on SLE12 isn't supported yet since https://github.com/crowbar/barclamp-pacemaker/pull/207 is still being tested; however hopefully it will be supported very soon and even before then this will let us test it via Jenkins.

allow for SLE12-based HA in Cloud 6

---

scripts/jenkins/ci.suse.de/crowbar-trackupstream.xml

Now that we have a manila barclamp there.. :-)

Enable trackupstream for manila barclamp on Cloud 5

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

This addresses two problems with mkcloud failing when `hacloud=1`:
- a `curl` check of Horizon wasn't going through haproxy
- tempest wasn't being deployed on the same node the tempest test run was triggered on
Supersedes #475.

Fix mkcloud HA runs

---

scripts/qa_crowbarsetup.sh

This fixes the mkcloud upgrade test which was broken since the spilt / refactoring of this two methods.

Fix cloud upgrade repos

---

scripts/qa_crowbarsetup.sh

```
sed -i.netbak -e 's/"conduit": "bmc",$/& "router": "192.168.124.1",/'
```
otherwise it will produce
```
"conduit": "bmc", "router": "192.168.124.1", "router": "192.168.124.1", "router": "192.168.124.1", ....
```

Fix regexp in sed command for bc-template-network.json

---

scripts/crowbar-testbuild.py

This change is needed due to the crowbar repo merge.

Fix mkcloud testbuild script for gating

---

scripts/qa_crowbarsetup.sh

This change is temporary until we adapted the install scripts for the
new merged crowbar packages.

Raise timeout waiting for install-chef-suse.sh

---

scripts/jenkins/qa_openstack.sh

--is-public is no longer a valid option when creating a image
with "glance image-create".

Use --visibility=public while creating a glance image

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

We use IPs from the admin network to communicate with the outside
and since our switches drop jumbo frames,
we cannot use them there.
OTOH the SDN and nova_fixed networks
are purely internal and thus can safely use jumbo frames.
partial revert of f5811a2

qa_crowbarsetup: jumbo frames fixing

---

scripts/jenkins/qa_openstack.sh

When running qa_openstack on an instance on cloud.suse.de and the
instance has cloud-init installed, there might be conflicts while trying
to install the cloud_* patterns due to already installed
packages (i.e. python-paramiko) and a needed vendor change.
Removing cloud-init plus dependencies resolves this.

qa_openstack: Remove cloud-init plus dependencies

---

scripts/jenkins/qa_openstack.sh

The used host image where nova-compute is running has just 10 GB disk
space and since liberty nova-scheduler DiskFilter doesn't find any valid
hosts when using a flavor with 20 GB ephemeral disk.

qa_openstack: create flavor without ephemeral disk

---

scripts/lib/libvirt/libvirt_setup.py
scripts/lib/mkcloud-libvirt.sh
scripts/mkcloud

this hardcodes the max size to 9000
as that is also the fixed limit for real HW
and does not influence what VMs decide to use later

mkcloud: allow for large frames to be passed between VMs

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

This is a first step to integrate `crowbar_batch` and ultimately _scenario files_ into mkcloud.
The Pull Request is in an early stage but I would appreciate some feedback, so that I don't proceed in a wrong direction.
__Note:__
This PR could also be the very first step to integrate real scenario files to mkcloud. In the corresponding Trello cards it says that the crowbar_batch `proposals:` information should be part of a bigger scenario file that ultimately replaces a lot of ENV variables.
The latter is out of scope of this PR, but crowbar_batch can already handle YAML files that hold additional information. It just looks at the proposal section and ignores the rest.
So we can easily add more and more pieces to those _scenario.yaml_ files later.

mkcloud: basic integration of crowbar_batch

---

.travis.yml

While the test run we install packages with sudo. The default behaviour
will change to `sudo: false` in the near future. To prevent test
failures we should explicitly set it.
See http://blog.travis-ci.com/2015-03-31-docker-default-on-the-way/

Set explicit sudo for travis tests

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

@nkrinner mentioned he found it confusing that mkcloud appends `.yaml` to the `scenario` name.
He would like to be able to give it a full filename which makes sense as `.yml` is also a common extension for YAML files and my initial approach was a unnecessary limitation to the naming.
Furthermore there was no help text explaining the `scenario` setting yet.

mkcloud: usability improvements for scenario files (crowbar_batch)

---

scripts/qa_crowbarsetup.sh

It was only for the Cloud 6.x test update channel, which
doesn't exist yet.

Remove dependency on you.suse.de for now

---

scripts/lib/libvirt/compute-config
scripts/lib/libvirt/fixtures/cloud-node1-raid.xml
scripts/lib/libvirt/libvirt_setup.py
scripts/lib/libvirt/templates/compute-node.xml
scripts/lib/libvirt/test_libvirt_setup.py
scripts/mkcloud
scripts/qa_crowbarsetup.sh

Create extra volumes that should be used for RAID. 
Add first N disks to the RAID array for each node.
Tested with manual mkcloud runs: 
- worked for raid1 and one node or two nodes
- also for raid5 and one node
Requires https://github.com/crowbar/crowbar-core/pull/15

Enable creation of software RAID on nodes

---

scripts/qa_crowbarsetup.sh

Provide access to the packages from the test image.
The image contains the *-test packages which contain
functional tests.
Theses functional tests will be executed by cct.

qa_crowbarsetup: use image with testpackages

---

scripts/mkcloud

When calling compute-config, raidvolumenumber must be given since
2a2daadf676a0bc07b7f.

mkcloud: Add missing raidvolumenumber to compute-config

---

scripts/qa_crowbarsetup.sh

When calculating the urls for the testing iso on the controller node,
the TESTHEAD variable is needed to get the correct image.

qa_crowbarsetup: Fix test image download

---

scripts/mkcloudhost/mkcloude

Since port 80 also works with older releases, just link always
that one instead.

Crowbar is now behind port 80.

---

scripts/qa_crowbarsetup.sh

it prevent race condition between preparing cnftools image and ran of tempest suite , on slower connections to $clouddata

add wait_for active status of cnftools image

---

scripts/qa_crowbarsetup.sh

We keep the SES 1.0 repos for now as the product hasn't move to SES 2
yet; this patch will only enable people to work on SES 2 integration.

qa_crowbarsetup.sh: Add SES 2 repos on admin server for Cloud 6+

---

scripts/qa_crowbarsetup.sh

Underlying issue has been fixed in the packaging
marcos instead.
This reverts commit 76915919a613cdc4a70257a6394f06395df3bc2e.

Revert "Raise timeout waiting for install-chef-suse.sh"

---

scripts/mkcloud

`testsetup` is in charge of things which `cct` makes use of and currently those things are missing and cct is failing when functional tests gets triggered.

Let testsetup run before cct in mkcloud 

---

scripts/qa_crowbarsetup.sh

Manila barclamp isn't in GM5, GM5+up , nor in QAM queue
This fixes https://github.com/SUSE-Cloud/automation/issues/535
This reverts commit cc2aead6b94bbdeeac57f6a5f6af3a5e1cbb7852.

dont deploy manila on GM5*

---

scripts/lib/libvirt/libvirt_setup.py

when there was already a VM,
dom would still reference the old undefined one

mkcloud/python: fix VM start

---

scripts/crowbar-testbuild.py

crowbar-testbuild.py: remove extraneous space

---

scripts/qa_crowbarsetup.sh

The horizon proposal depends on the nova one, so deleting the nova one
first will fail.

qa_crowbarsetup: Delete horizon proposal before nova proposal

---

scripts/qa_crowbarsetup.sh

It might not be obvious to everyone why we do it that way...

qa_crowbarsetup: Add a comment explaining reboot_controller_clusters

---

scripts/qa_crowbarsetup.sh

It recommened to have the network cluster only host the "neutron-network" role
(that's the one that actually handles the network traffic of the cloud) the
"neutron-server" role is supposed to be deployed on the same node as all the
other service.

In HA setup deploy neutron-server on the services cluster

---

scripts/qa_crowbarsetup.sh

There seems to be some weird race with quickly adding a repository
and immediately using it.. libzypp throws this error:
Can't read bad stream: /var/cache/zypp/raw/cloud-testFVigWh/content

Disable GPG check on cloud-test media

---

scripts/qa_crowbarsetup.sh

They were renamed from SUSE-Cloud-6 to SUSE-OpenStack-Cloud-6. We
haven't noticed yet due to the fact that we don't have any official
milestone built from SUSE namespace.

qa_crowbarsetup: Fix paths to Cloud 6 repos

---

scripts/lib/libvirt/compute-config
scripts/lib/libvirt/libvirt_setup.py
scripts/lib/libvirt/templates/compute-node.xml

for SP1's qemu-2.3 we need to specify the 2.0 machine type to avoid both
http://bugzilla.suse.com/show_bug.cgi?id=946068 (no SVM flag in pc-2.3)
http://bugzilla.suse.com/show_bug.cgi?id=946020 (PXE broken in pc-0.14 to 1.4)

workaround bnc#946020+bnc#946068

---

scripts/mkcloud

20GB is huge and won't be needed for mkcloud; it also takes way too long
to replicate, causing issues in mkcloud (due to either load of
replicating or waiting for the sync when we have to reboot).

mkcloud: Use 5GB instead of 20GB for db/rabbitmq DRBD device

---

scripts/jenkins/qa_openstack.sh

In Liberty, Manila uses the tempest plugin interface to add tests to tempest.
So tempest now runs the Manila tests. The problem is that we need a image
(with nfs and samba installed and some other modifications) to be able
to run the tests.
Skip the tests for now until we have a image available.

qa_openstack: Skip Manila tempest tests

---

scripts/jenkins/qa_openstack.sh

Reverts SUSE-Cloud/automation#564
run_tempest.sh doesn't use the given parameters.

Revert "qa_openstack: Skip Manila tempest tests"

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

This is based on a new want_sles12sp1 option, that (hopefully) will be
dropped once the port to SP1 is fully completed and we won't use SLE12
GA.

mkcloud, qa_crowbarsetup: Add support for SLE12 SP1 for Cloud 6

---

scripts/crowbar-testbuild.py

Reportedly github-status.rb has been fixed to also run on SLE11
hosts, so remove the restriction so that we can spread out
load quicker.

Remove restriction to SLE12 hosts

---

scripts/qa_crowbarsetup.sh

This is https://github.com/SUSE-Cloud/automation/pull/567 with a minor fix, since Vanessa is not here today.

Remove "bc-" prefix of barclamp id's

---

scripts/qa_crowbarsetup.sh

Corresponding json files for cloud6 are already in place

Make qa clouds use network templates without bc- prefix in id

---

scripts/scenarios/cloud6/cloud6-2nodes-default.yml

to be used with cloud6 and 2 nodes setup.
Based on this one, we could create differen scenarios that can be used to cover different cases
EDIT: to be called as
``export want_node_aliases=controller=1,compute-kvm=1 nodenumber=2 scenario='cloud6-default.yml' mkcloud instonly setup_aliases batch``

Proposal for a default scenario file,

---

scripts/mkcloud

First of all this makes things slow as it trashes the memory
but also it causes block writeback issues which means it
could cause the Device or resource busy issues we currently.

mkcloud: Avoid qemu-img convert running with a cache

---

scripts/qa_crowbarsetup.sh

Fixes build of dc6 without TESTHEAD right now.

Only use the new unprefixed name if it exists

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

This replaces the use of TESTHEAD to decide whether we want to use test
updates or not.

Add want_test_updates variable

---

scripts/qa_crowbarsetup.sh

With SLE12 SP1 compute nodes, the acpiphp module is no longer
auto loaded anymore. Add a workaround to get jenkins to
pass again.

Load acpiphp module before doing volume attach tests

---

scripts/mkcloud

We need to be explicit about writing a raw outout and disable
sparse file detection to avoid not being able to write sparse
files on block devices (which only works on files)

mkcloud: specify output flags for convert

---

scripts/mkcloud

this allows to add new functions to qa_crowbarsetup
that can be called through mkcloud as
onadmin+funcname
or even
onadmin+func+param1+param2

mkcloud: allow to call onadmin function

---

scripts/mkcloud

it was not possible to use mkcloud on an lvm that also contains the base system, this PR allows to skip the sanity check if the lvm is used otherwise

mkcloud: allow to skip the lvm test, to allow mkcloud on shared lvm

---

scripts/mkcloud

Followup fix for 74940efcc4cba6f5ae08aadc8559c35db086d4e0

Fix MAC address of lonely node in crowbar_register

---

scripts/qa_crowbarsetup.sh

in order to properly gate the cct pull requests, we need to checkout the respective PR branch during a cct gating run.

Gating for cct pull requests

---

scripts/qa_crowbarsetup.sh

This is useful for debugging problems during the node deployment.

qa_crobarsetup: enable serial console for deployed nodes

---

scripts/crowbar-testbuild.py

We need 4 nodes now to enable Ceph testing with Cloud6+

Build ceph PRs with 4 nodes

---

scripts/qa_crowbarsetup.sh

This reverts commit ef654e216d330fa254f447e2197818af6518b24d.
Turns out that you can no longer follow the installation process
in YaST if the serial console is enabled.

Revert "qa_crobarsetup: enable serial console for deployed nodes"

---

scripts/jenkins/ci.suse.de/cloud-mkcloud6-trigger.xml

This is redundant, since we have the gating trigger already,
so this way it starts two jobs. Remove also the mode=basetest
as that is obsolete.

Remove automatic trigger for mkcloud6

---

scripts/mkcloud

Error was
+ kpartx -dsv /dev/mkcvg0/g1.admin
device-mapper: remove ioctl on mkcvg0-g1.admin2 failed: Device or resource busy

mkcloud: wait more for disk to become non-busy

---

scripts/qa_crowbarsetup.sh

It doesn't exist in other cases (like Mx or susecloudx)

Run features:functional when using develcloud6

---

scripts/github-status/github-status.rb

allow to list open PRs to be able to rebuild even succeeded PR tests in jenkins

github-status: function to list open pull requests

---

scripts/crowbar-testbuild.py

Rather than just printing the exception object, we want
to print the exception details, which are more helpful.

crowbar-testbuild.py: Print error when build fails

---

scripts/qa_crowbarsetup.sh

This shouldn't be needed anymore, provisioner json was fixed.

Remove symlinking of Cloud6 Pool/Updates to SLE12-SP0

---

scripts/qa_crowbarsetup.sh

Kernel was fixed, we can revert.
This reverts commit 1c9cb48c7e885b2c01051d1a5597286c5a14e0be.

Revert "Disable kernel logging to workaround spammy kernel update"

---

scripts/qa_crowbarsetup.sh

qa_crowbarsetup: Fix name of heat image we're using

---

scripts/qa_crowbarsetup.sh

Packages in Devel:Cloud:6 are now linked to Cloud:OpenStack:Liberty

qa_crowbarsetup: Remove libertycloud as source

---

scripts/mkcloud

this is only needed once per host and not for every mkcloud run

mkcloud: move PV+VG setup into setuphost

---

scripts/scenarios/cloud6/qa-scenario-1b-ipmi-kvm-xen.yaml

This is specific for QA setup, as it points to shared storage devices used by QA (10.162.26.129:/var/ha-database)
Installation is expecting 
3 controller nodes (named controller1, controller2, controller3)
4 compute nodes (named compute-kvm1, compute-kvm2, compute-xen1, compute-xen2) and
Such setup can be achieved by installing with
want_node_aliases=controller=3,computekvm=2,computexen=2
option.

Scenario for QA setup 1b: HA with IPMI; swift; kvm and xen compute

---

scripts/scenarios/cloud6/qa-scenario-2c-sbd-kvm.yaml

This is the scenario file for QA setup 2c: HA with SBD, ceph, and kvm compute nodes.
1. Install the nodes with these mkcloud options:
hacloud=1
clusterconfig="data=2"
nodenumber=7
want_node_roles=controller=2,compute=2,storage=3
want_node_os=suse-12.1=4,suse-12.0=3
want_node_aliases=controller=2,compute=2,ceph=3
2. Setup SBD using https://gist.github.com/jsuchome/4a658676db6ea29e924f
3. Run crowbar batch with updated scenario file:
crowbar_batch --timeout 1200 build qa-scenario-2c-sbd-kvm.yaml

Scenario for QA setup 2c: HA with SBD, ceph, and kvm compute

---

scripts/qa_crowbarsetup.sh

Don't touch the template in /opt/dell at all. This should be especially helpful
for the QA clouds as their customized configs would no longer need to contain
the whole template (including the "deployment" section)  but just the values
that are different from the template.

Only use /etc/crowbar/network.json for adjusting the network proposal

---

scripts/qa_crowbarsetup.sh

This is already done by install-suse-cloud.
(also required for https://github.com/crowbar/crowbar-core/pull/97)

qa_crowbarsetup: Stop checking that xinetd and dhcpd are running

---

scripts/qa_crowbarsetup.sh

Before doing the ssh and rdp checks make sure that the node actually is
transitioned to the "ready" state in crowbar. Otherwise (on really slow
systems) it might happen that mkcloud starts the post_allocate action before
the nodes are really ready for that.

Rework wait_node_ready condition

---

scripts/qa_crowbarsetup.sh

they are effectively dropped from install_chef_suse.sh once
https://github.com/crowbar/crowbar/pull/2172 is merged.
so this PR requires/depends on https://github.com/crowbar/crowbar/pull/2172

repo checks are now in crowbar

---

scripts/qa_crowbarsetup.sh

The URL contains the architecture now.

qa_crowbarsetup: Fix URL of crowbar_register for recent Cloud 6

---

scripts/qa_crowbarsetup.sh

No longer needed. Nova docker can now detect if docker image is missing

---

scripts/jenkins/ci.suse.de/cloud-mkcloud6-gating-trigger.xml

We're typically building roughly 4-5 a day, so this
keeps a history of two weeks (one sprint).

Raise number of kept builds to 64

---

scripts/qa_crowbarsetup.sh

The simple curl test for the dashboard failed with:
curl: (28) Operation timed out after 31406 milliseconds with 0 bytes
received
But the test passed when executed manually afterwards on the same
cloud. So retry the test 3x to be sure it's failing.

qa_crowbarsetup: Increase timeout for horizon simple test

---

scripts/mkcloudhost/allocpool
scripts/mkcloudhost/mkcloude

mkcloud workers needed some manual setup, to make this easier and consistent with all mkcloud hosts this PR drops the need to manually set symlinks

mkcloudhost: drop need for symlinks on mkcloud hosts

---

scripts/qa_crowbarsetup.sh

It seems that the docker backend doesn't allow disk overcommit.

qa_crowbarsetup: Use m1.tiny when booting testvm instance for docker

---

scripts/jenkins/jenkins-job-trigger

switch curl to silent mode, error would still be show but the progress is suppressed

jenkins-job-trigger: make triggering silent (curl --silent)

---

scripts/qa_crowbarsetup.sh

in the HA case, (when not using drbd) we need a shared NFS storage
and having it on the crowbar node makes it much easier
to share scenario.yaml files

qa_crowbarsetup: add NFS share for HA DB/AMQP

---

scripts/jenkins/jobs-obs/openstack-cleanvm.yml

The job is triggered by cleanvm and theoretically the build parameters
should be passed from the cleanvm job to the openstack-submit job.
But that doesn't happen.
So pass the paramter manually to the openstack-submit job.

Fix openstack-submit job

---

scripts/crowbar-testbuild.py

This has slightly more disk space available (~ 5GB more)
and is backed up, unlike the jenkins worker.

Switch to putting the PR testbuilds on clouddata

---

scripts/jenkins/ci.suse.de/cloud-mkcloud6-gating-trigger.xml

With the latest changes in crowbar-core, rebooting the openstack nodes should
work again. (https://bugzilla.suse.com/show_bug.cgi?id=950798)

Reenable reboot tests for Cloud6 gate (bsc#950798)

---

scripts/qa_crowbarsetup.sh
scripts/scenarios/cloud6/qa-scenario-1b-ipmi-kvm-xen.yaml
scripts/scenarios/cloud6/qa-scenario-2b-sbd-kvm-vmware.yaml
scripts/scenarios/cloud6/qa-scenario-2c-sbd-kvm.yaml
scripts/scenarios/cloud6/qa-scenario-6a-ipmi-kvm-docker.yaml

qa_crowbarsetup, scenarios: Do not use l2pop key anymore for Cloud 6

---

scripts/qa_crowbarsetup.sh

Should be completely unused meanwhile.

Remove sles12 GA repos for Cloud 6.x

---

scripts/qa_crowbarsetup.sh
scripts/scenarios/cloud6/cloud6-2nodes-default.yml
scripts/scenarios/cloud6/qa-scenario-1b-ipmi-kvm-xen.yaml
scripts/scenarios/cloud6/qa-scenario-2a-sbd-kvm.yaml
scripts/scenarios/cloud6/qa-scenario-2b-sbd-kvm-vmware.yaml
scripts/scenarios/cloud6/qa-scenario-2c-sbd-kvm.yaml
scripts/scenarios/cloud6/qa-scenario-6a-ipmi-kvm-docker.yaml

Services ceiloemter-cagent (ceilometer-agent-central) that runs on Control node to talk to openstack services is deprecated since Kilo. The agent is replaced by a new service ceilometer-polling. The change here updates use of ceilometer-polling service in controller HA deployment. Since the deprecation is applicable only from after Kilo release, the proposal is set only for Cloud6 or later.

qa_crowbarsetup, scenarios: ceilometer-polling service added

---

scripts/qa_crowbarsetup.sh

Technically this should be needed only for nova-docker compute nodes,
we're just going with simpler solution.

Set BTRFS as default filesystem for all nodes when docker is wanted

---

scripts/jenkins/jobs-obs/openstack-submit.yml

This makes it easier to figure out which :Staging
project got merged recently.

Set the build name again on the submit job

---

scripts/qa_crowbarsetup.sh

It is not used (Cloud 5 uses only SLE11 SP3, and Cloud 6 uses
SLE12-SP1)

Remove SLE12 HA references

---

scripts/jenkins/qa_openstack.sh
scripts/qa_crowbarsetup.sh

Newer versions of tempest have converted from tempest-cleanup
to tempest-cleanup, and immediately broke tempest-cleanup. So
we need to call tempest cleanup when it is available.

Use tempest cleanup if available

---

scripts/jenkins/ci1/freshvm

Instead of copying and converting from qcow2 to raw, just
use a backing file with qcow.
Also remove some dead code.

freshvm: Use qcow2 img to improve startup time

---

scripts/jenkins/qa_openstack.sh

When using a standardized cloud image, those do not contain
the SLES base repos. we need to configure them individually.

Add support for SLE12/SP1 pool/update repos

---

scripts/lib/mkcloud-libvirt.sh
scripts/mkcloud

split setupadmin from prepare function
by this the admin node can be redeployed without rerunning the libvirt_prepare part
This is needed for the upgrade from Cloud5 to Cloud6 (PR for that is WIP).

Split off setupadmin

---

scripts/mkcloud

drop a static wait and instead check what we are waiting for

mkcloud: refactor static wait

---

scripts/mkcloud

cleanup
do not expose each individual step of the upgrade process, rather group them in one step
for debugging it is still possible to call the individual steps via `onadmin+$functionname`
This is needed for the upgrade from Cloud5 to Cloud6 (PR for that is WIP).

Refactor upgrade process

---

scripts/jenkins/jobs-obs/openstack-trackupstream.yaml

Juno is now EOL (See http://docs.openstack.org/releases/)

Remove Juno from trackupstream

---

scripts/jenkins/jobs-obs/openstack-trackupstream.yaml

Liberty
Keeping this disabled for the next month or so will help us
on focusing on getting the Liberty release out.

Disable trackupstream for master for now since we are focusing on

---

scripts/qa_crowbarsetup.sh

This makes it easier to detect if a machine was installed with
a non-merged downstream patch.

qa_crowbarsetup.sh: Identify builds with extra updaterepos

---

scripts/jenkins/jobs-ibs/cloud-mkcloud6-suse-trigger.yaml

The URL to monitor was missing the host part.

Fix URL trigger for the SUSE gating job

---

scripts/jenkins/jobs-ibs/cloud-mkcloud6-suse-trigger.yaml

The settings between develcloud and susecloud gating should
be in sync.

Use nodenumber=4 for ceph testing like in gating check

---

scripts/lib/libvirt/libvirt_setup.py
scripts/mkcloud

The valid chars are defined in libvirt-1.2.18/src/qemu/qemu_command.c.
Tested on SLE-12 with GM4+up and GM5+up.
Sorry for the noise, I could not reopen the previous pull request

Generate valid serial strings for volumes

---

scripts/mkcloudhost/boot.mkcloud
scripts/mkcloudhost/cloudfunc

this makes it easier to route it within Nuremberg later
atm those addrs are just reserved for us in microfocus infoblox DB, but not routed, except over cloud openvpn like old 44.8.0.0/15 range.
already did on mkch[abcd] hosts
ln -sf ~/github.com/SUSE-Cloud/automation/scripts/mkcloudhost/boot.mkcloud /etc/init.d/boot.mkcloud
and already added new routes on gate (in addition to old ones)
but after this is merged, crowbar.v*.cloud.suse.de DNS entries will need to be updated in gate:~/configurer/conf.d/cloudvms.pm

mkcloudhost: use reserved IP addrs

---

scripts/mkcloud

Splitting off the prepareadmin step from the general prepare function
This allows to redeploy the admin node without destroying other parts of the cloud or network.
This is needed for the upgrade from Cloud5 to Cloud6 (PR #716 still WIP).

mkcloud: split off prepareadmin from prepare

---

scripts/mkcloud

This allows to run `mkcloud onhost+func` to modify an already deployed cloud (eg. deploy a new admin node).

Allow onhost function calls

---

scripts/qa_crowbarsetup.sh

The openstack command works with the v3 and v2 API.

Use "openstack" instead of "keystone" for LDAP test

---

scripts/lib/mkcloud-libvirt.sh

If $NOSETUPPORTFORWARDING is set, the whole boot.mkcloud script is not
needed and also not available. This fixes:
chmod: cannot access ‘/etc/init.d/boot.mkcloud’: No such file or directory

mkcloud: Only use /etc/init.d/boot.mkcloud when needed

---

scripts/qa_crowbarsetup.sh

This should help avoid conditions as in
https://ci.suse.de/job/openstack-mkcloud/13201/console
which did not update github status because jenkins stopped it
after no new line was produced for too long.
15:57:39   waiting 800 cycles of 5 seconds = 4000 seconds
15:57:40 ................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................... …

qa_crowbarsetup: add linebreaks to wait_for

---

scripts/jenkins/jobs-obs/macros.yaml
scripts/jenkins/jobs-obs/openstack-gerrit-rpm-packaging.yaml

There is now an internal zuul instance connected to review.openstack.org
and ci.opensuse.org . New changes (or "recheck" and "recheck-suse" comments)
trigger a new testbuild.
The testbuild currently does:
- branch Cloud:OpenStack:Upstream/rpm-packaging-openstack
- recreate a tarball with the changes provided by zuul
- checkin in OBS at home:suse-cloud-ci
- wait for the rebuild and report the result back to gerrit

Setup test job for upstream rpm-packaging initiative

---

scripts/qa_crowbarsetup.sh

in a crowbar-testbuild job with a package of the same version (but different build version), the one with the higher build version wins (which is mostly the package not from the ptf repo), even though the ptf repo as a higher priority
a vendor change may also come into play
We analyzed a failed mkcloud run with @mlandres today and found this fix:
Rrunning a zypper dup on the ptf repo ensures that the packages from there are used

Prefer ptf packages

---

scripts/qa_crowbarsetup.sh

safely makes the call of zypper dup fail
so if the ptf repo is not present this breaks the deployment
Solution, skip the zypper dup if the repo is not present.

qa_crowbarsetup: only run zypper dup from ptf repo if it is present

---

scripts/qa_crowbarsetup.sh

I've found several times that an HA deployment fails with **error 43** when running *testsetup*. This is right after tempest test have successfully run and we create an instance with qa_crowbarsetup.
This error seems to be caused by lack of disk space in the compute nodes to spawn the instance. The compute nodes have 13GB on the root partition and about 10GB free. Since the image requires 10GB, sometimes there's not enough space for it.
I have successfully tried manually to spawn the instance with 8GB disk and seems to be created properly. I'm suggesting reducing the m1.smaller flavor to 8GB disk in order to make this situation much less likely.

Reduce m1.smaller flavor to 8GB disk

---

scripts/qa_crowbarsetup.sh

there is a broken test update in the queue right now, let's
not bother with it.

Disable test updates for cloud6

---

scripts/qa_crowbarsetup.sh

This is some refactoring work needed for the support of controller HA in mkcloud.
The missing removal of used data nodes from the list of available nodes may have created some strange bugs/behaviour in the past.
Due to our setup of the mkcloud HA jobs (only one cluster named "data") we never hit this bug on the mkcloud workers. But once the cluster looks different it might be a problem as the data nodes might be used/assigned twice.
The rest is just cleanup.

Refactoring for controller ha

---

scripts/qa_crowbarsetup.sh

Meanwhile there is code that waits for all nodes to be discovered. So the 'sleep 50' should not be needed.

qa_crowbarsetup: dropping useless 'sleep 50'

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

If the admin server is freshly booted just before running the `setupnodes` step (e.g. if it was preceded by the `createadminsnapshot` step), then the tftp server might not yet be running.  So we need to wait for it before PXE-booting any nodes.

ensure tftp server is ready before PXE-booting nodes

---

scripts/qa_crowbarsetup-test.sh
scripts/qa_crowbarsetup.sh

This improves PR #740 by breaking exactly after 75 chars except for the last line.
And it adds roundup tests for this.

qa_crowbarsetup: improve linebreak in wait_for and add test

---

scripts/jenkins/ci.suse.de/cloud-mkcloud6-dvr-trigger.xml

It is already running in jenkins 
https://ci.suse.de/view/Cloud/view/Trigger/job/cloud-mkcloud6-dvr-trigger/
and it is testing DVR (Distributed Virtual Routes) in Neutron with openvswitch and vlans

jenkins: add mkcloud6-dvr-trigger

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

Manila is integrated into Cloud 6 and we want to test it. Upstream
uses the so called "generic driver" as backend and runs tempest tests.
To be able to run the tempest tests we need to prepare the setup.
The generic driver uses a cloud instance as a share server. The instance
mounts a cinder block device, adds a FS on top and uses the common
tools (nfs-server, samba) to export shares.
To manage the share-server, the manila-share service (which may run on
multiple compute nodes) need to acccess the share-server via ssh.
So we basically need:
- a new network which is available on the crowbar nodes
- a neutron provider network to access the nodes in the crowbar network
- a nova instance which has access to the new neutron network
In addition to that, the image used for the nova instance must …

qa_crowbarsetup: Prepare Manila generic driver for testing

---

scripts/jenkins/jobs-obs/openstack-gerrit-rpm-packaging.yaml

"unknown" is the initial state of a package, we also need
to consider that as pending.

Fix pending job detection

---

scripts/qa_crowbarsetup.sh

In 0ef0dc13c17, a new VM is created for Manila's generic driver. The VM
is in an extra project called "manila-service" and to parse the
uuid and the network details with the openstack client, the project
name must be given. Otherwise the details are empty.

qa_crowbarsetup: Fix manila service VM details detection

---

scripts/qa_crowbarsetup.sh

It's not full uppercase right now. Keeping the uppercase version in case
this is fixed upstream in the feature.

qa_crowbarsetup: Set manilaclient_INSECURE env var

---

scripts/lib/libvirt/admin-config
scripts/lib/libvirt/cleanup
scripts/lib/libvirt/compute-config
scripts/lib/libvirt/libvirt_setup.py
scripts/lib/libvirt/net-config
scripts/lib/libvirt/net-start
scripts/lib/libvirt/test_libvirt_setup.py
scripts/lib/libvirt/vm-start
scripts/mkcloud

In HA deployments, with more than one controller node, only the first controller VM was assigned an increased memory footprint. The other controller VM's got the normal amount of memory leading to some out-of-memory errors. This implementation assigns the same amount of (increased) memory to all controller VMs.
The former implementation already took care of several controller nodes in HA deployments. The number of controller nodes could be specified with the clusterconfig:services configuration variable. This implementation doesn't change the behavior of that variable.
This PR is a simplification of previous https://github.com/SUSE-Cloud/automation/pull/751. It also includes the fixes proposed by @aplanas in https://github.com/SUSE-Cloud/automation/pull/757, so it should supersede both …

Support for more than one controller VM creation

---

scripts/mkcloud

Some deployments I debugged ignored failures in the installation of the nodes and failed later in the process. To prevent this and follow the rule of fail early, the steps of the instnodes function should exit (via safely) if they detect an error.

mkcloud: fail on errors during node installation

---

scripts/lib/libvirt/cleanup_one_node
scripts/lib/libvirt/libvirt_setup.py
scripts/mkcloud

support to cleanup admin node inside of an mkcloud deployment - to allow testing the upgrade from cloud5 to cloud6

Cleanup admin node

---

scripts/qa_crowbarsetup.sh

Also stop everything if the boot failed.

qa_crowbarsetup: Wait for instance to be up when starting VM for manila

---

scripts/scenarios/cloud6/qa-scenario-1b-ipmi-kvm-xen.yaml
scripts/scenarios/cloud6/qa-scenario-2a-sbd-kvm.yaml
scripts/scenarios/cloud6/qa-scenario-2b-sbd-kvm-vmware.yaml
scripts/scenarios/cloud6/qa-scenario-2c-sbd-kvm.yaml

Currently all these scenarios are failing due to missing generic driver config, that was added here: https://github.com/SUSE-Cloud/automation/pull/771
Tested successfully here: https://ci.suse.de/view/Cloud/view/ByTopic/view/QA/job/cloud-mkphyscloud-qa-scenario-2a/104/console

Add manila generic driver attributes into qa scenario files

---

scripts/lib/libvirt/cleanup_one_node
scripts/lib/libvirt/libvirt_setup.py

cleanup function expects a dom object and not a string
this was changed (overlooked) as a last refactoring step in the PR #767 
A manual test with this fix was already successful.

libvirt_setup: fix cleanup_one_node function

---

scripts/qa_crowbarsetup.sh

If uuid and/or ip address are not available for the manila service
VM, abort. Otherwise the Crowbar proposal will fail later due to
the missing values.

qa_crowbarsetup: Fail early if manila details are not available

---

scripts/lib/libvirt/test_libvirt_setup.py

As nicely suggested by @aplanas the arg_parse call is not needed because the arguments are never actually parsed but directly assigned. Instead now the arguments are stored in an empty class.
Since this PR is based on https://github.com/SUSE-Cloud/automation/pull/764 it includes commits not yet merged.

Libvirt setup test simplification

---

scripts/qa_crowbarsetup.sh

otherwise it can be rather tricky to tell apart failed runs
that all just do exit 30

qa_crowbarsetup: print return code of failed function

---

scripts/scenarios/cloud6/qa/no-ssl/qa-scenario-1b-ipmi-kvm-xen.yaml
scripts/scenarios/cloud6/qa/no-ssl/qa-scenario-2a-sbd-kvm.yaml
scripts/scenarios/cloud6/qa/no-ssl/qa-scenario-2b-sbd-kvm-vmware.yaml
scripts/scenarios/cloud6/qa/no-ssl/qa-scenario-2c-sbd-kvm.yaml
scripts/scenarios/cloud6/qa/no-ssl/qa-scenario-6a-ipmi-kvm-docker.yaml

As already mentioned here https://github.com/SUSE-Cloud/automation/pull/783 , this is the the second batch of our qa scenarios with no ssl configuration. The goal is to have separate scenarios globally for no-ssl, ssl and ssl-insecure setup.

Add qa scenario files without any ssl options

---

scripts/qa_crowbarsetup.sh

to avoid failures like
https://ci.suse.de/view/Cloud/view/Builds/job/openstack-mkcloud/15357/console
where it ended with
Build timed out (after 60 minutes)
and did not collect supportconfigs = issue #728

qa_crowbarsetup: add explicit timeout to nova boot

---

scripts/qa_crowbarsetup.sh

run_tempest.sh returns 0 even if not a single test was executed.
So after a successful tempest run, also run "testr last" which returns
"3" in case no tests were executed.

qa_crowbarsetup: Detect useless tempest run

---

scripts/qa_crowbarsetup.sh

We create a share type called "default" and this type needs to be
set as default type for tempest and client-functional tests.

qa_crowbarsetup: Set default share type for Manila

---

scripts/jenkins/jobs-obs/openstack-trackupstream.yaml

Track the hyperv networking package for Liberty and Master.

trackupstream: Add openstack-networking-hyperv

---

scripts/qa_crowbarsetup.sh

The same image is used during the manila tempest scenario tests
to spawn VMs and theses VMs need CIFS/NFS client tools installed.

qa_crowbarsetup: Make manila service image public

---

scripts/scenarios/cloud6/qa/no-ssl/qa-scenario-2a-sbd-kvm.yaml
scripts/scenarios/cloud6/qa/ssl-insecure/qa-scenario-2a-sbd-kvm.yaml

On first commit, the neutron proposal didn't have the
nova authentication credentials yet, so we need to
commit neutron again after nova.

Recommit neutron proposal after nova proposal

---

scripts/scenarios/cloud6/qa/no-ssl/qa-scenario-1b-ipmi-kvm-xen.yaml
scripts/scenarios/cloud6/qa/no-ssl/qa-scenario-2a-sbd-kvm.yaml
scripts/scenarios/cloud6/qa/no-ssl/qa-scenario-2b-sbd-kvm-vmware.yaml
scripts/scenarios/cloud6/qa/no-ssl/qa-scenario-2c-sbd-kvm.yaml
scripts/scenarios/cloud6/qa/ssl-insecure/qa-scenario-1b-ipmi-kvm-xen.yaml
scripts/scenarios/cloud6/qa/ssl-insecure/qa-scenario-2a-sbd-kvm.yaml
scripts/scenarios/cloud6/qa/ssl-insecure/qa-scenario-2b-sbd-kvm-vmware.yaml
scripts/scenarios/cloud6/qa/ssl-insecure/qa-scenario-2c-sbd-kvm.yaml

Manila proposal can only be deployed after cinder, glance
and nova have been created.

Fix manila deployment order

---

scripts/qa_crowbarsetup.sh

The older clouds also fail but we don't care about that right now

Only check for failed port bindings on Cloud 6+

---

scripts/qa_crowbarsetup.sh

Second run of testsetup on the virtual cloud fails with "share-type already exists" error.

Create share-type only if it doesn't exist

---

scripts/qa_crowbarsetup.sh

The image we use for testing Manila has a hardcoded password.
So set it during deployment.

qa_crowbarsetup: Set image_password for manila tempest setup

---

scripts/qa_crowbarsetup.sh

When listing share types, the header has a "is_default" string.
So searching for "default" always matches and a share type is never
created.

qa_crowbarsetup: Fix manila share type creation

---

scripts/qa_crowbarsetup.sh

When testing with Xen or hyperv, a different image needs to be used
for booting the manila service instance.

qa_crowbarsetup: Use hypervisor specific manila image

---

scripts/jenkins/jobs-obs/openstack-gerrit-rpm-packaging.yaml

Otherwise it doesn't download the tarball ofthe new version
but of the old version, which doesn't make sense

Regenerate spec files before downloading tarballs

---

scripts/qa_crowbarsetup.sh

hyperv nodes cannot take the dns-server role, so the test would fail.

qa_crowbarsetup: dont always do multidns test

---

scripts/qa_crowbarsetup.sh

"want_manila" is a new env var (default '1') which can be set to 0
to disable manila deployment.

Add possibility to skip manila deployment

---

scripts/mkcloud

When using Xen, dom0 uses half of the memory and with our current xen job,
nova-compute can not be started due to missing memory.
This leads to a ComputerFilter error in the nova scheduler and no
manila-service VM or other VMs during testing can be started.
So add more memory to the nodes.

xen: Add more memory to Xen nodes

---

scripts/qa_crowbarsetup.sh

Commit edcc942069172138 uses the wrong logic. We want to *skip*
the manila proposal if we have docker deployed.

qa_crowbarsetup: Fix manila skip when using docker

---

scripts/qa_crowbarsetup.sh

also drops global variables that should have been declared local

qa_crowbarsetup: simplify code

---

scripts/jenkins/jobs-obs/openstack-gerrit-rpm-packaging.yaml

Without that, any merge will cause all running jobs to break.

Detach the test build branch from parent

---

scripts/scenarios/cloud6/qa/no-ssl/qa-scenario-1a-ha-kvm-swift.yaml

In qa scenario 1a, the role ceilometer-swift-proxy-middleware is trying
to use a cluster for it's configuration (it is an HA deployment), but
that option is not supported. Instead this patch replaces the cluster
for its individual members, as it is defined in scenario 1b.

Ceil-swift-proxy-middleware not to use cluster

---

scripts/jenkins/jobs-obs/openstack-trackupstream.yaml

- add python-networking-cisco
- rename openstack-networking-hyperv to python-networking-hyperv
naming schema for neutron networking plugins should be python-$pypiname

trackupstream: Fix python-networking-* packages

---

scripts/qa_crowbarsetup.sh

hyperv does not use libvirt, so libvirt does not know anything about it

qa_crowbarsetup: dont set libvirt_type for hyperv

---

scripts/qa_crowbarsetup.sh

Add functional tests only if the corresponding barclamp is available on admin node. 
Fix for https://ci.suse.de/job/openstack-mkcloud/16631/console

Run CCT functional tests iff barclamp is deployed

---

scripts/qa_crowbarsetup.sh

This matters because setcloudnetvars wasn't called.

qa_crowbarsetup: Add missing pre_hook call in onadmin_batch

---

scripts/jenkins/jobs-ibs/cloud-mkcloud6-job-ha-compute.yaml

Without this, the HA repos are not used.

jenkins: Add hacloud=1 to cloud-mkcloud6-job-ha-compute

---

scripts/qa_crowbarsetup.sh

"false && foobar" is still giving an exit code of 1. We have the same
here, and this makes qa_crowbarsetup fail.

qa_crowbarsetup: Do not fail when there's no manila proposal

---

scripts/qa_crowbarsetup.sh

When the manila service VM is not reachable via the floating network, some
manila tempest test will fail. Warn about that but don't abort to get at least
all other tempest tests.

qa_crowbarsetup: Warn early about failing manila tempest tests

---

scripts/qa_crowbarsetup.sh

Crowbar requires it for cloud5

Replace bc-template-network only in cloud version 6plus

---

scripts/mkcloud

so we free up the grabbed mappings
before trying to free the underlying drbd LV

mkcloud: workaround host grabbing guest devices

---

scripts/scenarios/cloud6/cloud6-2nodes-default.yml
scripts/scenarios/cloud6/cloud6-4nodes-compute-ha.yml
scripts/scenarios/cloud6/qa/no-ssl/qa-scenario-1b-ipmi-kvm-xen.yaml
scripts/scenarios/cloud6/qa/no-ssl/qa-scenario-2a-sbd-kvm.yaml
scripts/scenarios/cloud6/qa/no-ssl/qa-scenario-2b-sbd-kvm-vmware.yaml
scripts/scenarios/cloud6/qa/no-ssl/qa-scenario-2c-sbd-kvm.yaml
scripts/scenarios/cloud6/qa/ssl-insecure/qa-scenario-1b-ipmi-kvm-xen.yaml
scripts/scenarios/cloud6/qa/ssl-insecure/qa-scenario-2a-sbd-kvm.yaml
scripts/scenarios/cloud6/qa/ssl-insecure/qa-scenario-2b-sbd-kvm-vmware.yaml
scripts/scenarios/cloud6/qa/ssl-insecure/qa-scenario-2c-sbd-kvm.yaml

"path_to_private_key" is now mandatory when deploying manila.

scenarios: Add required "path_to_private_key" to manila

---

scripts/qa_crowbarsetup.sh

When we set the raid type for a node, we ssh in. However, it could be
that the DNS hasn't been udpated yet (there's a small race window
there). So wait for that.

qa_crowbarsetup: Wait for node name to be resolvable before ssh'ing in

---

scripts/qa_crowbarsetup.sh

The manila service VM needs to receive traffic on high ports
as they are used by NFS for mount negotiation (the rpc services
mountd, lockd and statd are listening on unpredictable high
ports)

Allow access to high-ports in manila-service-vm

---

scripts/qa_crowbarsetup.sh

It seems glance-scrubber doesn't always exit with non-0 on failures, so
also look at the logs for errors.
Note that we filter out glance_store errors because they're not
relevant, and always happen with the default config:
ERROR glance_store._drivers.filesystem [-] Specify at least 'filesystem_store_datadir' or 'filesystem_store_datadirs' option

qa_crowbarsetup: Look for errors in glance-scrubber log

---

scripts/qa_crowbarsetup.sh

this should help debug those cases where in sleshammer the NFS mount fails
and thus no login is possible

qa_crowbarsetup: set password on discovery images

---

scripts/mkcloud

This is the hard way, after all other attempts to do it "correctly" failed...
Yes, it takes time, but only for RAID based installations (that's just one jenkins job).

Do total wipeout of the disks used for RAID, to prevent bsc#966685

---

scripts/qa_crowbarsetup.sh

this makes other problems more obvious such as
++ ssh d52-54-77-77-77-01.vd3.cloud.suse.de lsblk -n -d
++ cut '-d ' -f 1
++ head -n 2
ssh: Could not resolve hostname d52-54-77-77-77-01.vd3.cloud.suse.de: Name or service not known
+ raid_disks=

qa_crowbarsetup: dont build RAID without disks (bsc#967878)

---

scripts/qa_crowbarsetup.sh

Cloud5 and older used a different way of invocing glance-scrubber
from cron, so it makes sense to use that one instead.

Fix glance-scrubber test for cloud 5 and older

---

scripts/jenkins/jobs-obs/openstack-gerrit-rpm-packaging.yaml

Otherwise in case the osc commands fails, the job exits with 0 and
the build looks good ut in fact it's maybe broken.
This happened i.e. when osc returned non-zero and reported:
SSL Error: (104, 'Connection reset by peer')

Check return value of osc in rpm-packaging job

---

scripts/qa_crowbarsetup.sh

Waiting for success to be true lets the wait_for loop run to its timeout in case crowbar installation errors. This PR lets the wait_for loop exit on error and then do the success check later.

let crowbar install fail early, no timeout on errors

---

scripts/qa_crowbarsetup.sh

apparently #880 introduced a new race,
where the /start request returned while the installing value was still false
- e.g. see https://ci.suse.de/view/Cloud/view/Builds/job/openstack-mkcloud/17925/console

qa_crowbarsetup: fix a race and show crowbar install.log in case of error

---

scripts/jenkins/qa_devstack.sh

Another special handling is needed for openSUSE Leap to
do the correct repo setup.

qa_devstack: Fix repository setup for Leap

---

scripts/jenkins/qa_devstack.sh

It's required to run devstack. The shell builtin doesn't work as expected.

qa_devstack: Be sure which is installed

---

scripts/jenkins/jobs-ibs/templates/cloud-mkcloud-gating-template.yaml

Now that the HA job is finally reliably green, lets add
it to the gating in order ot not break it again.

Add HA job to the Cloud 6 Gating

---

scripts/mkcloud

In order to allow to overwrite the URLs for distsuse, susedownload
and clouddata all these variables need to be passed to qa_crobarsetup.

mkcloud: pass custom URLs to qa_crowbarsetup

---

scripts/qa_crowbarsetup.sh

In some setups it is not enough to rely on the default IP ranges
for the SDN. This change allows to configure the SDN.

qa_crowbarsetup: make net_sdn configurable

---

scripts/jenkins/qa_devstack.sh

Our SUSE fixes are merged so there's no need to use a private
repo for devstack.

qa_devstack: Switch back to upstream repo

---

scripts/jenkins/qa_openstack.sh

I.e. SLE12SP1 JeOS doesn't have wget installed.

qa_openstack: install wget

---

scripts/qa_crowbarsetup.sh

the problem is when the image is already there, which happens to be
the case in an upgrade scenario, wget comes back with 1 and though
runs into the complain
```
18:52:29 + wget --progress=dot:mega -nc -O manila-service-image.qcow2 http://149.44.176.43/images/other/manila-service-image.qcow2
18:52:29 File `manila-service-image.qcow2' already there; not retrieving.
18:52:29 + complain 73 'manila image not found'
18:52:29 + local ex=73
18:52:29 + shift
18:52:29 + printf 'Error: %s\n' 'manila image not found'
```

better handling of manila image download

---

scripts/mkcloud

This change is needed because the puma server needs already 1GB while
the start. This amount raises while the first reqests due do caches and
requires.

Raise admin_node_memory to 4GB

---

scripts/mkcloud

otherwise, public net cannot be reached
because the cloud uses VLAN 300

mkcloud: pass vlan vars into qa_crowbarsetup

---

scripts/qa_crowbarsetup.sh

They frequently timeout / fail which causes a lot more trouble than
its worth. Fixing it is tracked in https://trello.com/c/jafB2kpq

Disable manila functional tests for now

---

scripts/jenkins/qa_openstack.sh

To simplify debugging and modifying openstack-quickstart, always use
files from /tmp if available.

qa_openstack: Always copy files from /tmp for if available

---

README.md
scripts/jenkins/jenkins_jobs.ini.sample

- update command to upload jobs. the template dir
must be given on the internal jenkins server
- mention that new jobs should always be defined in yaml

Update jenkins-job-builder doc

---

scripts/jenkins/qa_openstack.sh

This pull request restarts wickedd right after cloud-init has been removed. This is neccessary to fix build failures on OpenSUSE Leap:
https://ci.opensuse.org/view/OpenStack/job/openstack-cleanvm/2186/image=openSUSE-Leap-42.1,openstack_project=Mitaka,slave=cloud-cleanvm/
The problem is caused by the machine's host name changing and various services then using different host names (e.g. for agent registration) depending on when they were started. The `wickedd` at this early a point ensures the host name is finished changing before any of the problematic services are started.
Since the problem took a while to debug (thanks @rossella and @rhafer for the essential clues!), I'll provided a detailed analysis below. The host name changes that caused the problem can be seen in the following …

Restart wickedd after cloud-init removal

---

scripts/jenkins/qa_openstack.sh

commit 7861e41a0cb1d introduced the wrong variable. The correct
name is "openstackquickstartrc".

qa_openstack: Fix openstackquickstartrc debugging

---

scripts/qa_crowbarsetup.sh

curl on http://localhost:3000 (the root) routes to nodes#index, so
in relation to crowbar/crowbar-core#455 we have to replace all the
non json format http requests with a json formatted request
one more fix to advance in the gating of https://github.com/crowbar/crowbar-core/pull/455 (https://ci.suse.de/job/openstack-mkcloud/21101/console)

adapt the simple crowbar test

---

scripts/jenkins/jobs-ibs/macros.yaml

Add quotes to the given build name string. Otherwise the build name is empty.

jjb: Fix build name in IBS macros

---

scripts/jenkins/jobs-ibs/templates/cloud-mkcloud-gating-template.yaml

We need to use the version variable in the template otherwise the
version is in every gating the same.

Use version variable in template

---

scripts/qa_crowbarsetup.sh

before installation the installer before_filter blocks the nodes API
make sure to use installer status as a basic crowbar api available test
NOTE: this should fix all backup and restore CI (also upgrade partially)

use installers controller as the nodes controller is blocked

---

scripts/mkcloud

Depending on the kernel configuration, some of the mm/ksm entries in sysfs
might be missing. This patch changes mkcloud to not fail in case of missing
entries.

Make some kernel optimzations fail gracefully

---

scripts/qa_crowbarsetup.sh

Use generic function to check if the installer is available.
Drop temporary code that was needed by early Cloud6 milestones only.
This PR depends on: PR #964

Fix check for the crowbar installer

---

scripts/qa_crowbarsetup.sh

..and allow skipping functional tests
This change makes it possible to run cct with custom configuration required by jenkins job https://ci.suse.de/view/Cloud/view/QA/job/cloud-mkphyscloud-qa-test-cct.
Tested on qa2 server.

Enable using custom cct git repo, custom git branch

---

scripts/qa_crowbarsetup.sh

The `continue` statements in the `case` / `esac` block are vestigial from
refactoring a code block inside a loop [1]. This patch replaces `continue`
with `return`.
[1] 8064efb0e51415ef47ee4d670d67b21825e3c62d

Fix incorrect `continue` statement

---

scripts/qa_crowbarsetup.sh

This patch enables the generic ssl option for heat. It depends on
https://github.com/SUSE-Cloud/automation/pull/971
which introduces this feature into the heat barclamp.
(EDIT: it actually depends on https://github.com/crowbar/crowbar-openstack/pull/362)

Add ssl generic option to qa_crowbarsetup.sh

---

scripts/jenkins/jobs-ibs/cloud-automation-pr-trigger.yaml
scripts/jenkins/jobs-ibs/cloud-cct-pr-trigger.yaml

The conversion to JJB jobs broke these jobs, preventing us to retrigger a run of PRs (needed in case a job is removed from the Jenkins queue - accidentally or jenkins bug).
FYI: the updated jobs are already deployed on jenkins

Fix the trigger jobs of automation and cct PRs

---

scripts/jenkins/qa_openstack.sh

When running the jenkins job, enable Magnum. This currently installs
only the packages and the cofiguration is not complete but it's better
than nothing.

qa_openstack: Enable Magnum

---

Makefile
scripts/jenkins/jenkins-job-trigger
scripts/jenkins/jenkinsapi.conf.example

This is a python rewrite of jenkins-job-trigger.
It was easier that way to add support for the CSRF token.
This obsoletes PR #982 as it is a drop-in replacement for jenkins-job-trigger.
No changes to the jobs neeed.

Python rewrite jenkins job trigger

---

scripts/jenkins/qa/cloud-mkphyscloud-qa-scenario-0a.yaml

* wait untill all nodes are ready after they have been upgraded
* replace sleeps with wait_for
More details on why and how it's still failing are here: https://trello.com/c/mgoria08/777-5-s36p6-qa-infra-mkcloud-basic-upgrade-scenario-config-0

Minor improvements to the upgrade scenario 0a

---

scripts/jenkins/jobs-ibs/cloud-mkcloud7-suse.yaml

This generates a phased multijob that shows all relevant
Base and extra scenarios in one nice view. See here:
https://ci.suse.de/view/Cloud/view/ByTopic/view/Cloud6/job/cloud-mkcloud6-suse-trigger-new/

Add an overview multijob for the current state of Cloud6

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

The shebang references /bin/sh which is not required to link to /bin/bash.
Since the script uses bash features (the [[ ]] test for instance) it may break
if the user decides to use a shell other than bash as /bin/sh.
The legal valus of $hacloud are specified as '' or 1 by mkcloud. This patch
makes testing of $hacloud consistent throughout the script.

Switch to bash and make test for hacloud consistent

---

scripts/mkcloud

It can be desireble to preserve the state of the full cloud for debugging and
development purposes. This patch adds two new commands to mkcloud,
createcloudsnapshot, and restorefromcloudsnapshot, which snapshot all disks in
the cloud.

Add two new commands to mkcloud (cloudsnapshot)

---

scripts/qa_crowbarsetup.sh

the openstack client output in mitaka changed due to
https://review.openstack.org/#/c/277720
so choose a different method that seems to work between liberty and
mitaka

Use a mitaka compatible method for fetching floating ip of manila VM

---

scripts/jenkins/jobs-obs/openstack-trackupstream.yaml

Track openstack-barbican for Mitaka and above.
Co-Authored-By: johannes.grassler@suse.com

Enables trackupstream job for barbican

---

scripts/jenkins/jobs-obs/openstack-rpm-packaging-update.yaml

The job runs periodically and updates the packages in
Cloud:OpenStack:Upstream from the OpenStack rpm-packaging project.

Add JJB job to update Cloud:OpenStack:Upstream packages

---

scripts/jenkins/qa/cloud-mkphyscloud-qa-scenario-1a.yaml
scripts/jenkins/qa/cloud-mkphyscloud-qa-scenario-1b.yaml
scripts/jenkins/qa/cloud-mkphyscloud-qa-scenario-2a.yaml
scripts/jenkins/qa/cloud-mkphyscloud-qa-scenario-2b.yaml
scripts/jenkins/qa/cloud-mkphyscloud-qa-scenario-3a.yaml
scripts/jenkins/qa/cloud-mkphyscloud-qa-scenario-6a.yaml

The IP of interface `eth0` on the server used in https://github.com/SUSE-Cloud/automation/pull/996 proved to cause issues when used for nfs server (timeouts and fenced nodes) , bridge on `eth1` seems to be working properly for nfs.

Use correct IP address for nfs server in QA scenarios

---

scripts/qa_crowbarsetup.sh
scripts/scenarios/cloud6/cloud6-2nodes-default.yml
scripts/scenarios/cloud6/cloud6-4nodes-compute-ha.yml
scripts/scenarios/cloud7/cloud7-2nodes-default.yml
scripts/scenarios/cloud7/cloud7-4nodes-compute-ha.yml

Since those batch files deploy trove, and trove checks whether
trove integration is enabled, deployment fails otherwise

Enable trove integration in rabbitmq

---

scripts/jenkins/ci.suse.de/openstack-mkcloud.xml
scripts/jenkins/qa/cloud-mkphyscloud-qa-scenario-2a.yaml
scripts/qa_crowbarsetup.sh

* ~~add `export ZYPP_LOCK_TIMEOUT=120` to qa_crowbarsetup.sh`~~
* Unset rally server for openstack-mckloud job (the rally server will be moved to different location, temporarily it will be off)
*  Add new location for network.json files for QA scenarios
*  Source qa_crowbarsetup before setting up sbd in QA scenario 2a
Changes in `qa_crowbarsetup.sh` related to QA scenarios tested here: https://ci.suse.de/view/Cloud/view/QA/job/cloud-mkphyscloud-qa-scenario-1a/97

Changes to QA scenarios

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

This patch adds line number and function information to the debug output of
mkcloud and qa_crowbarsetup.sh (controlled by debug_mkcloud and
debug_qa_crowbarsetup).

Add better debugging output

---

scripts/mkcloud

When running cloudsnapshot functions on a system that is running several
mkcloud created clouds, the createcloudsnapshot/restorecloudfromsnapshot
functions are a bit too greedy removing logical volumes.

Fix bug in cloudsnapshot functions

---

scripts/qa_crowbarsetup.sh

The fix was mentioned by Tom in
https://github.com/SUSE-Cloud/automation/pull/1002
Co-Authored-By: Thomas Bechtold <tbechtold@suse.com>

qa_crowbarsetup: Make cct novaclient test pass on susecloud7

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

Instead of using `basename` to remove the path component from the current
script, use bash internal string modification. This is more robust in cases
where `BASH_SOURCE` is not set.

Fix small bug in debug prompt

---

scripts/qa_crowbarsetup.sh

If cloud is installed with SP2 support, we will still want to install SP1 nodes for some time.
Some packages needed for nodes installation
are located at Cloud add-on, so it needs to be available.
I know it is ugly, but other than that... what could possibly go wrong?

Prepare SP1 Cloud repositories also for SP2-enabled Cloud

---

scripts/qa_crowbarsetup.sh

The testiso containing i.e. python-novaclient-test is also
available from the SUSE namespace. So also download the iso
and install the test packages when running with cloudsource=susecloud .
This fixes the cct testing run which triggers some client tests and
needs the corresponding python-*client-test packages.

qa_crowbarsetup: Download testiso also with susecloud

---

scripts/mkcloud

Filters are not being applied if they're placed after "a/.*/".

Error Documentation Update

---

scripts/jenkins/jobs-obs/openstack-rpm-packaging-update.yaml

The upstream packages are all linked to a single rpm-packaging-openstack
which contains all needed files.
If there's a new spec, also create the link automatically.

Update openstack-rpm-packaging-update job

---

scripts/qa_crowbarsetup.sh

We're calling the neutron CLI via ssh, so our
NEUTRONCLIENT_INSECURE=true environment variable doesnt work.

qa_crowbarsetup: Fix reboot step with insecure ssl

---

scripts/qa_crowbarsetup.sh

Milestones are now tracking Cloud 7.
Note: it might conflict with https://github.com/SUSE-Cloud/automation/pull/1008, so better to get that other PR merged first.

qa_crowbarsetup: Drop code specific to milestones in Cloud 6

---

scripts/clouddata/syncSLErepos

This makes it much easier to fix the mkcloud/qa_crowbarsetup.sh
scripts. compatibility symlinks have been added manually on the server
until the other changes have been merged

Move repos and images into architecture specific subdirs

---

scripts/qa_crowbarsetup.sh

Fix missing extglob shopt for <= SLE-11
The extended pattern matching introduced in line 642 of `qa_crowbarsetup.sh` by 9e4595746ad17202b72da750b80294e569af632c requires the `extglob` shell option to be set, an issue on <= SLE-11 images for instance. This patch ensures that it is.
Thanks to @gosipyan for finding this problem.

Fix missing extglob shopt for <= SLE-11

---

scripts/mkcloud

for SLES12-SP2 we have openssh-7.2 which blocks ssh-dss keys by default
so we also upload rsa keys

mkcloud: use RSA instead of DSA and push other pubkeys into admin node

---

scripts/mkcloud

One should reasonably expect that a call to `restartcloud` results in a fully
running cloud, including a working sshd on the admin node.  Following this
logic, the call to `wait_for_crowbar_ssh` in `createcloudsnapshot` belongs
into the `restartcloud` function.

Cleanup of restartcloud

---

scripts/mkcloud

When the cloud is rebooted, the nodes run crowbar_join, which runs ntpdate to
update the nodes' date. Unfortunately the ntpd instance on the crowbar node
takes a while before it considers itself trustworthy enough to give out
temporal advice. This means that the nodes will hang on cowbar_join until
crowbar's ntpd finally pulls itself together. Sometimes ntpd takes longer than
the nodes are willing to wait, and the impatient nodes will not be considered
`ready` by crowbar, i.e. the cloud is not fully up. This patch adds an
additional wait after rebooting the crowbar node.

Fix for rebootcloud

---

scripts/lib/libvirt/fixtures/cloud-node1-raid.xml
scripts/lib/libvirt/libvirt_setup.py

Current code fails with:
```
File "/root/github.com/SUSE-Cloud/automation/scripts/lib/libvirt/vm-start", line 16, in <module>
main()
File "/root/github.com/SUSE-Cloud/automation/scripts/lib/libvirt/vm-start", line 12, in main
libvirt_setup.vm_start(args)
File "/root/github.com/SUSE-Cloud/automation/scripts/lib/libvirt/libvirt_setup.py", line 279, in vm_start
conn.defineXML(xml)
File "/usr/lib64/python2.7/site-packages/libvirt.py", line 3629, in defineXML
if ret is None:raise libvirtError('virDomainDefineXML() failed', conn=self)
libvirt.libvirtError: XML error: Invalid PCI address slot='0x30', must be <= 0x1F
```
So let's just not pick addresses above `0x1F`...

libvirt: Fix assignment of PCI addresses

---

scripts/lib/libvirt/templates/cpu-default.xml

The 'monitor' flag is not well supported as indicated in the QEMU wiki.
Furthermore, it's possible to use the following CPU on the hypervisor
even though it does not support the 'monitor' feature.
~$ grep -m 2 '\(model name\|monitor\)' /proc/cpuinfo | uniq
model name      : AMD Opteron 23xx (Gen 3 Class Opteron)
As a result of which, drop the mandatory requirement for the 'monitor'
feature on the host CPU.
Link: http://wiki.qemu.org/Features/CPUModels#Disabling_features_that_were_always_disabled_on_KVM

lib: cpu-default: Drop the mandatory 'monitor' feature

---

scripts/crowbar-testbuild.py

needed after c6264f478fb32a401f615b410b303bd65a95ea73
to prevent wget from traversing all test-updates

crowbar-testbuild: add a trailing slash to URL

---

scripts/lib/libvirt/libvirt_setup.py

The VIR_DOMAIN_UNDEFINE_NVRAM flag was introduced in libvirt-1.2.9. The
domain undefine command will fail on earlier libvirt installations.

Fix domain undefine for older libvirt installations

---

scripts/qa_crowbarsetup.sh

At this point we use the same vlan for the `storage` and the `os_sdn` network
in our deployments. By default (as defined by `template-network.json`) those
two networks are on different vlans though. This patch restores the default
behavior.

Revert to default vlan value for os_sdn network

---

scripts/jenkins/qa_openstack.sh

This pull request enables Barbican in `openstackquickstartrc` (off by default) and adds a small functionality test to cleanvm.

Enable Barbican in openstackquickstartrc

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

The default 1500 MTU for vNICs may not be the best choice if the host
is using a lower value for its external interface. This could lead to
networking issues when the VMs try to access the external network.
It's best to set the MTU value to match the lowest host's MTU value
in order to make sure the nodes can reach the network especially during
the mkcloud phases where fetching and installing from repositories is
fairly common.

scripts: mkcloud: Set MTU for vNICs based on host's NIC

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

Cloud 4 is not maintained anymore, and the only reason we keep support
for it in mkcloud is for upgrade to Cloud 5. Since the upgrade requires
maintenane updates anyway, just allow develcloud4 or GM4+up.

Remove remainings of Cloud 3 support, remove GM4 target

---

scripts/jenkins/jobs-obs/openstack-gerrit-rpm-packaging.yaml

This way pending builds in the underlying repositories are
not blocking the test in progress.

set branch test projects to block=local

---

scripts/crowbar-testbuild.py
scripts/jenkins/ci.suse.de/crowbar-trackupstream.xml
scripts/jenkins/jobs-ibs/cloud-crowbar-testbuild-pr-trigger.yaml
scripts/jenkins/jobs-ibs/cloud-mediacheck.yaml
scripts/jenkins/jobs-ibs/openstack-submit-project.yaml

Somebody already deleted all jenkins jobs for Cloud 4, so it
makes sense to remove the remaining cruft as well. mkcloud is
kept in tact as we need it for 4->5 upgrade testing.

Remove reminiscence of Cloud 4

---

scripts/qa_crowbarsetup.sh

10 minutes are not enough to install crowbar on smaller hosts so
triple the timeout interval. However, that shouldn't matter for bigger
and/or faster hosts since the script will detect when the crowbar has
actually been installed and move on.

scripts: qa_crowbarsetup.sh: Triple the crowbar installation timeout

---

scripts/lib/libvirt/fixtures/cloud-node1-xen.xml
scripts/lib/libvirt/libvirt_setup.py
scripts/lib/libvirt/templates/compute-node.xml
scripts/lib/libvirt/templates/extra-volume.xml
scripts/lib/libvirt/test_libvirt_setup.py

For Xen/HyperV the PCI address is not settable but only an IDE
bus id would be setable (but apparently we don't care about that)
https://bugzilla.suse.com/show_bug.cgi?id=987584

Only set disks address type in the virtio case (bsc#987584)

---

scripts/qa_crowbarsetup.sh

Rather than hardcoding a path that is x86_64 specific, we need
to choose one that allows different architectures

Use the magnum image for the proper architecture

---

scripts/qa_crowbarsetup.sh

This must be set according to the documentation:
http://docs.openstack.org/developer/magnum/userguide.html#overview

qa_crowbarsetup: Set os-distro property for Magnum image

---

scripts/qa_crowbarsetup.sh

This role is added later on starting with Cloud 7+. And the race during discovery
should be gone.
This is required for https://github.com/crowbar/crowbar-core/pull/516 -- note that the change should not be done without that PR.

qa_crowbarsetup: Stop looking for provisioner-base on discovered nodes

---

scripts/qa_crowbarsetup.sh

Crowbar got a new attribute to set a custom JSON blob which will be passed
to the instances. From the instances, the data can be accessed via
curl http://169.254.169.254/openstack/latest/vendor_data.json
Set this new attribute to make sure that a deployment still works.

qa_crowbarsetup: Set custom vendordata for metadata server

---

scripts/qa_crowbarsetup.sh
scripts/scenarios/cloud7/cloud7-2nodes-default.yml
scripts/scenarios/cloud7/cloud7-4nodes-compute-ha.yml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-1a.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-1b.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-2a.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-2b.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-3a.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-6a.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-1a.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-1b.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-2a.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-2b.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-2c.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-6a.yaml

We only set the vendordata json blob in Cloud7+ so also do
the check only in Cloud7+.

qa_crowbarsetup: Only check vendordata if key is set

---

scripts/mkcloud

This needs to be installed before libvirtd is being launched
for the first time, otherwise things don't work.

Install the UEFI osloader for libvirt support

---

Makefile
scripts/jenkins/jobs-obs/openstack-upstream-gerrit-rpm-packaging.yaml
scripts/jenkins/jobs-obs/openstack-upstream-rpm-packaging-update.yaml
scripts/jenkins/jobs-obs/templates/openstack-rpm-packaging-update.yaml
scripts/jenkins/jobs-obs/templates/openstack-upstream-gerrit-rpm-packaging.yaml
scripts/jenkins/zuul/layout.yaml

There is now a stable/mitaka branch for the rpm-packaging project.
For the CI, we need to update the available packages for all branches
(now stable/mitaka and master). We use the subprojects in OBS under
Cloud:OpenStack:Upstream for that.

rpm-packaging: Support multiple release updates

---

scripts/jenkins/jobs-ibs/templates/cloud-mkcloud-gating-template.yaml

Currently we need more then ~3 hours for a gating. Running HA in parallel
brings this down to ~1 1/2 hours.

Run gating HA job in parallel

---

scripts/jenkins/jobs-obs/templates/openstack-upstream-gerrit-rpm-packaging.yaml

Otherwise we're guessing the wrong name, which causes the spec file
to be excluded and that causes gating to skip over build failures.

Make sure we link the name of the generated spec files 

---

scripts/qa_crowbarsetup.sh

Instead of a half-backed hand-crafted and unmaintained
image with a terribly old cloud-init in it, use the media
we release to customers instead.

Use a sensible image for testsetup

---

scripts/qa_crowbarsetup.sh

`WARNING: Option "--pub_key" is deprecated; use "--pub-key"; this option will be removed in novaclient 3.3.0.`
`WARNING: Option "--key_name" is deprecated; use "--key-name"; this option will be removed in novaclient 3.3.0.`

Fix for depracated options

---

scripts/mkcloud

on s390x where we have only one or two cpus, we were spending almost
100% cpu in ksmd, which slows down almost everything

mkcloud: don't spin a complete core on ksmd on low-cpu count host

---

scripts/mkcloud

The setting on aarch64 workers is completely insane, it basically causes
the cpu to completely stall, triggering lock up detection:
[ 9563.821445] INFO: rcu_sched self-detected stall on CPU
[ 9563.821452]  40-...: (114019 ticks this GP)
idle=f45/140000000000001/0 softirq=382572/382585 fqs=112564
[ 9563.821457]   (t=114023 jiffies g=138434 c=138433 q=393704)
[ 9563.821459] Task dump for CPU 40:
[ 9563.821462] ksmd            R  running task        0   293      2
0x00000002

mkcloud: reduce ksm on aarch64 even further

---

scripts/mkcloudhost/mkcloud_reserve_pool

allows to specify notification delays longer than a day
and crossing midnight

mkcloud_reserve_pool: use arithmetic with seconds

---

scripts/qa_crowbarsetup.sh

node
This way we don't have to duplicate the logic of which test update
channels are needed when and where..

Only enable test update channels on the cloud nodes if also on the admin

---

scripts/qa_crowbarsetup.sh

even after a failure during the upgrade CI the job continues to run
(finally into a timeout)

check http response code because safely is not the correct check

---

scripts/qa_crowbarsetup.sh

The proposal creation has some magic to assign nodes to some roles, we
need to undo that in cases where we want to have docker deployment.
In this case the node was autoassigned to qemu because nested virt
wasn't available.

Also remove docker node from all other compute node types

---

Makefile

the new flake8 release 3.0.1 is not compatible with flake8-import-order anymore.

Workaround broken flake8 version

---

scripts/mkcloud

this is more convenient, especially on a shared cloudhost where you
don't want to change the systems mkcloud directory

Override scenariofile location

---

scripts/jenkins/jobs-ibs/templates/cloud-mkcloud-job-sle12sp2.yaml

Let's have first 2 nodes as SP2 so pacemaker cluster is created
from nodes with same OS version.
One SP2 node for compute and two SP1 one nodes for ceph.

Ensure that SP1 nodes are last

---

scripts/jenkins/jobs-ibs/cloud-mediacheck.yaml

I have no idea if this is correct, and if this is all that is missing, but https://ci.suse.de/view/Cloud/view/Milestones%20Cloud7/job/cloud-mediacheck/ does not have any Cloud7/SP2 check now.
For example, is it needed as a value in the `execution-strategy:` ?

Add Cloud7/SP2 target for mediacheck

---

scripts/jenkins/jobs-obs/templates/openstack-upstream-gerrit-rpm-packaging.yaml

There was a job hanging in "osc branch" for days so add a timeout.
To hanging job was:
https://ci.opensuse.org/view/OpenStack/job/openstack-upstream-gerrit-rpm-packaging-Master/143/console

Add timeout to osc commands for upstream rpm-packaging job

---

scripts/jenkins/ci.suse.de/openstack-mkcloud.xml

This is to enable manual set of the proper variable to test sahara in jenkins.
See:
https://github.com/crowbar/crowbar-openstack/pull/480
https://github.com/SUSE-Cloud/automation/pull/1126

Add want_sahara variable to jenkins mkcloud job

---

scripts/jenkins/jobs-obs/openstack-trackupstream.yaml

The packages are added for >= Liberty so track theses releases.

trackupstream: Add openstack-horizon-plugin-designate-ui

---

scripts/lib/libvirt/libvirt_setup.py
scripts/lib/libvirt/templates/cpu-amd.xml

The `<features>` was missing from the VM's libvirt config on AMD hosts, and this was causing a lack of ACPI support, which in turn meant that virsh shutdown etc. didn't work, and hence that mkcloud didn't work properly.
Some history:
A long time ago, 5696c1671 originally introduced some logic so that if the `npt` (AMD Nested Page Tables) flag was present in `/proc/cpuinfo` on the host, the <cpu> section would not be included.
Later, PR #343 switched libvirt VM creation code from bash to Python with templates, but at this point `<features>` was always included.
Much more recently, 7fe19ff9 from PR #1049 moved the `<features>` section into the CPU templates, resulting in it missing when the AMD `npt` flag was present.  668a415d then added support for other architectures, but still left AMD …

fix cpuflags (and hence ACPI / virsh shutdown) on AMD

---

scripts/jenkins/jobs-ibs/templates/cloud-mkcloud-job-upgrade-template.yaml

when https://github.com/SUSE-Cloud/automation/pull/1115 which enables
postgresql by default is merged, the upgrade CI will likely be broken
as there is no step yet to setup the database

disable postgresql to not break the upgrade CI

---

scripts/qa_crowbarsetup.sh

The zypper command might update the crowbar packages and trigger a restart
of the service. Wait for the crowbar service to answer queries before
continuing with the next mkcloud step.

In "runupdate" wait for crowbar service to restart

---

scripts/jenkins/qa_devstack.sh

We would like to disable this, because q_fwaas doesn't generate any config file and neutron-l3-agent is failing to start.

Disable service q-fwaas in for devstack

---

scripts/mkcloud

Supersedes #1119.
cee28264 from #1103 introduced faulty logic and misleading help text.
If `$scenariofile` is set by the user, then `$scenario` is totally ignored if set. This is because
: ${foo:=bar}
will not set `$foo` if it was already set.  And if `$scenario` isn't set then the code bails for no good reason.
If that was confusing, maybe this will help:
| scenariofile | scenario | behaviour
| ------------ | -------- | ----------------------
|    not set   |  not set | correct behaviour
|    not set   |    set   | correct behaviour
|      set     |  not set | incorrectly prohibited
|      set     |    set   | ignores $scenario
Additionally, the names `scenario` and `scenariofile` are vague and it's
not intuitive what is the difference between them.
So instead we replace the confusing …

fix scenariofile logic and help text

---

scripts/jenkins/jobs-ibs/templates/cloud-mkcloud-job-magnum-template.yaml

Magnum has no non-smoke tempest tests so use the ostestroptions
parameter to do an extra ostestr run with the Magnum tests.

Execute Magnum tempest tests for magnum CI job

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

Add an extra option called "ostestroptions". When this option is set,
in the testsetup step ostestr is called (after the usual tempest run)
with the given parameters.
This is useful when the tempest run only executes the smoke tests but
additional tests need to be executed.
For example, Magnum has no smoke tests but for a Magnum CI job we want
to execute the usual tempest smoke test run plus some (or all) tests
for Magnum. This is now possible with:
export ostestroptions=" --regex '^magnum.tests.functional.api'"

mkcloud: Add ostestroptions option

---

scripts/scenarios/cloud7/cloud7-4nodes-compute-ha.yml

This just causes a timeout right now since dispersion is just broken
with cloud 7, so remove this for nwo

Compute HA: disable swift dispersion

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

this was accidentally switched on in
https://github.com/SUSE-Cloud/automation/pull/1115
like that we can test it more isolated

disable want_postgresql for now

---

scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-2c.yaml

It's missing in QA scenario and causing builds to fail.

Add json metadata to nova barclamp for 2c scenario

---

scripts/mkcloud

Using plain ssh causes trouble with changing ssh-host-keys of admin node VMs, which we get since we are now building SP2 images in OBS/kiwi. The sshrun wrapper ignores those keys.

Fix user_keyfile upload

---

scripts/jenkins/jobs-ibs/templates/cloud-mkcloud-job-magnum-template.yaml

A single compute node is not enough to run magnum. So add another one.

Add more compute nodes for Magnum tempest job

---

scripts/jenkins/jobs-ibs/templates/cloud-mkcloud-job-magnum-template.yaml

With Ceph, some nodes would be using SLE12SP1 and we don't want that.

Disable ceph and use SLE12SP2 for magnum job nodes

---

scripts/qa_crowbarsetup.sh

With the current Magnum tempest job, smaller flavors are needed to not get
"No valid host found" errors.

qa_crowbarsetup: Create magnum flavors

---

scripts/jenkins/jobs-obs/openstack-cleanvm.yaml

OpenStack Juno is EOL and not used in our products.

Remove Juno from cleanvm

---

.gitignore
Makefile
README.md
mkcloudruns/README.md
mkcloudruns/install_suse_cloud
mkcloudruns/mkcloudconfig/README.md
mkcloudruns/mkcloudconfig/SUSECloud.mkcloud
mkcloudruns/mkcloudconfig/cloud6
mkcloudruns/mkcloudconfig/cloud7
mkcloudruns/mkcloudconfig/template
mkcloudruns/pids/README.md

Mkcloudruns repository is a good starting point for the team to
collaborate on unifying all the commonly used configuration options,
variables and more for development and testing environments. This should
address new comers and veterans equally by helping them save a lot of
time. Hopefully we agree on a common policy to update the wrapper
scripts here with new handy variables and options that are eventually
added to the automation repository.
The very need for something like this is a good indicator that
automation repository is having some inherent flaws in the way it is
designed and is being updated. The final aim should be to try and fix
automation repository in the right way so that we do not need to use
these wrapper scripts to eliminate the boilerplate for deploying various …

Merging mkcloudruns with automation repository.

---

scripts/mkcloud

we had a recent DNS failure resulting in mysterious calls of
wget --progress=dot:mega -N http:///images/x86_64/SP3-64up.qcow2
and this should give a clearer message to the user

mkcloud: explicitly catch broken DNS

---

scripts/qa_crowbarsetup.sh

Magnum uses a key called "default" for the tempest tests.
Create this key.

qa_crowbarsetup: Create keypair for magnum

---

scripts/jenkins/jobs-obs/openstack-trackupstream.yaml

We recently added the openstack-octavia packages to
Cloud:OpenStack:Master. Track the new package.

trackupstream: Also track openstack-octavia in C:O:Master

---

scripts/jenkins/jobs-obs/openstack-trackupstream.yaml

openstack-octavia packages are now also in Mitaka.

trackupstream: Also track octavia for Mitaka

---

scripts/qa_crowbarsetup.sh

In qa_crowbarsetup, ignoring when we set up NFS mounts, the script
correctly works when $clouddata is a URL fragment, but then it attempts
to ping it -- treating it like a distinct hostname. Split off from the
first / to deal with that scenario.

Cope with a URL fragment when checking ping

---

scripts/qa_crowbarsetup.sh

My previous attempt https://github.com/SUSE-Cloud/automation/pull/1177 failed with 
```
+(qa_crowbarsetup.sh:2978) custom_configuration(): '[' -n 1 -a iscloudver 7plus ']'
qa_crowbarsetup.sh: line 2978: [: too many arguments
```
This did not stop gating, so I thought it is working... :-(

Fix bash conditions

---

scripts/jenkins/jobs-ibs/templates/cloud-mkcloud-job-magnum-template.yaml

This fixes:
oncontroller_run_tempest(): ostestr '"' --regex '^magnum.tests.functional.api"'
usage: ostestr [-h]
ostestr: error: unrecognized arguments: "

Fix jenkins magnum job

---

scripts/jenkins/jobs-obs/heat-templates/openstack-cleanvm.yaml

In order to prevent users from using resources created by the
openstack-cleanvm heat template this commit labels them more
explicitely as being created by Heat.
Background: In an OpenStack project that contains both resources created manually and resources created by Heat stacks clashes occur occasionally. Namely, users that create stuff manually use Neutron networks/subnets or security groups created by a Heat stack. If the stack's owner later attempts to delete the stack, this will fail because its resources remain in use. This commit adjusts resource names and resource descriptions of the openstack-cleanvm heat template to warn users manually creating instances not to use them.

Added more warnings to Heat created resources

---

scripts/jenkins/jobs-ibs/templates/cloud-mkcloud-job-magnum-template.yaml

want_ceph shouldn't be used anymore in Jenkins (you can still use it when you
run mkcloud locally). But Jenkins has a variable called "storage_method" which
is implemented in the openstack-mkcloud trigger job. And depending on the value
this variable overrides want_ceph and want_swift when the openstack-mkcloud
trigger is used.

Fix storage method for magnum job

---

scripts/qa_crowbarsetup.sh

This pull request enables HA for the Magnum barclamp. Merge once https://github.com/crowbar/crowbar-openstack/pull/511 is merged.

Assign magnum-server role to HA cluster for hacloud=1.

---

scripts/jenkins/jobs-obs/templates/openstack-upstream-gerrit-rpm-packaging.yaml

Currently all runs are sequential which is extremely slow.
We can run them concurrently with no modification it seems
so lets do that.
Also set a logrotate for reducing performance impact of many runs
being stored in jenkins database.

Allow concurrent runs of upstream packaging tests

---

scripts/qa_crowbarsetup.sh

addresses part of #293 
and also properly does error-handling for the case where active state is never reached.

qa_crowbarsetup: use wait_for instead of sleep-loop

---

scripts/qa_crowbarsetup.sh

and update cct deps for running headless UI tests on admin node.
Depends on https://github.com/SUSE-Cloud/cct/pull/60
How this will be useful: if the variable `$cct_tests` contains `:ui:`, e.g. `feature:ui:upgrade`, the needed deps will be installed.

Install gems selectively for ui and non-ui tests

---

scripts/qa_crowbarsetup.sh

zlib-devel must be installed for ui tests

---

scripts/mkcloud

If aliases have been requested, then there's no reason to ignore that request when batch steps are not used.

always set up node aliases

---

scripts/qa_crowbarsetup.sh

as intended to be added in commit 8707ea26
but the quoting was not correct, so the service-list only got run once
This change also gets rid of some duplication in the wait_for lines

qa_crowbarsetup: fix waiting for nova services

---

scripts/mkcloud
scripts/mkcloudhost/mkcloude

Drop the warning that CVOL is obsolete.
The last usage of CVOL was an informative echo in mkcloude, also dropped with this PR.

Drop cvol obsoletion warning

---

scripts/jenkins/jobs-ibs/templates/cloud-mkcloud-job-ha-linuxbridge-template.yaml
scripts/jenkins/jobs-ibs/templates/cloud-mkcloud-job-ha-template.yaml
scripts/qa_crowbarsetup.sh

When deploying Cloud 7 with Ceph avoid to assign nova-compute, cinder-volume
and ceilometer-agent roles to eihter nodes in the controller-cluster or SP1
based ceph nodes.
This also means we need to increase the number of nodes for the HA jobs, that also
deploy ceph, to 5.

Fix compute node selection for HA/Ceph setups

---

scripts/lib/libvirt/compute-config
scripts/lib/libvirt/libvirt_setup.py
scripts/lib/libvirt/test_libvirt_setup.py

to workaround bnc#997358
https://bugzilla.suse.com/show_bug.cgi?id=997358

mkcloud/libvirt: use pc-i440fx-2.0 for admin node

---

scripts/jenkins/jobs-obs/openstack-trackupstream.yaml

Newer python-troveclient versions need a python-mistralclient package.

trackupstream: Track python-mistralclient for C:O:Master

---

scripts/qa_crowbarsetup.sh

in our small base images, a zypper up easily pulls in
100 recommended packages more than needed

qa_crowbarsetup: dont install extra recommended packages on update

---

scripts/mkcloud

This eliminates the risk of losing crucial debug output in a long mkcloud run because you forgot to redirect to a file and the terminal/screen/tmux scrollback buffer wasn't big enough.
Closes #1191.

always log output to a file

---

scripts/jenkins/jobs-obs/openstack-submit.yaml

When running the openstack-submit job (after a succesful cleanvm job),
look into the SLE_12_SP2 repository when copy packages from Staging
to Non-Staging.

openstack-submit: Use SLE_12_SP2 for Newton gating

---

scripts/qa_crowbarsetup.sh

While preparing the admin node, if $localrepodir_target is set, the
directory is mounted from the host, but the repositories are never
added to zypper. Refactor the function so that they are always added.

Also run zypper ar for local repos

---

scripts/qa_crowbarsetup.sh

Otherwise it could fail like https://ci.suse.de/job/openstack-mkcloud/33753/consoleText : 
```
+(qa_crowbarsetup.sh:4409) onadmin_prepare_cloudupgrade_repos_6_to_7(): safely createrepo /srv/tftpboot/suse-12.2/x86_64/repos/PTF
+(qa_crowbarsetup.sh:111) safely(): createrepo /srv/tftpboot/suse-12.2/x86_64/repos/PTF
Directory /srv/tftpboot/suse-12.2/x86_64/repos/PTF must exist
+(qa_crowbarsetup.sh:114) safely(): complain 30 'createrepo /srv/tftpboot/suse-12.2/x86_64/repos/PTF failed! (safelyret=1) Aborting.'
+(qa_crowbarsetup.sh:105) complain(): local ex=30
+(qa_crowbarsetup.sh:105) complain(): shift
+(qa_crowbarsetup.sh:106) complain(): printf 'Error: %s\n' 'createrepo /srv/tftpboot/suse-12.2/x86_64/repos/PTF failed! (safelyret=1) Aborting.'
Error: createrepo …
```

Make sure path for PTF repos is created

---

scripts/qa_crowbarsetup.sh

Although theoretically available in kubernetes 1.3.x, management
does not want to handle it, so don't try to deploy it

Skip manila on non-x86

---

scripts/qa_crowbarsetup.sh

Until this is properly fixed upstream, we can't test cinder with ssl.

bsc#988980 Remove ssl option for cinder

---

scripts/jenkins/jenkins_jobs.ini.sample

It seems our setup now needs "query_plugins_info=False" otherwise the update
command fails with an error when trying to query the plugins

Fix jenkins-job-build config sample

---

scripts/qa_crowbarsetup.sh

Fix the call to `crowbar_api_request` for Cloud 5, because in this case the `api_path` is empty and unqoted parameters would shift.

qa_crowbarsetup: fix crowbar_api_request for cloud 5

---

scripts/jenkins/ci.suse.de/openstack-mkcloud.xml

Otherwise a test such as [[ $want_ldap ]] is true, which is not what we want.

Unsetting want_ldap instead of setting it to 0

---

scripts/jenkins/jobs-ibs/cloud-mkcloud7-suse.yaml
scripts/jenkins/jobs-ibs/templates/cloud-mkcloud-job-devel-storage-template.yaml
scripts/jenkins/jobs-ibs/templates/cloud-mkcloud-job-ha-linuxbridge-template.yaml

This fixes jobs, that still used want_ceph instead of the new storage_method parameter.
want_swift and want_ceph are deprecated for the Jenkins job.
the storage preference is passed via the storage_method parameter.

jjb: switch to storage_method parameter

---

scripts/crowbar-testbuild.py

As ceph might be running a different OS than the rest of the Cloud (e.g.
SLE12-SP1 vs SLE12-SP2 for Cloud 7) we need at least 5 nodes for a ceph
enabled HA setup.

crowbar-testbuild: Use 5 nodes in the HA case

---

scripts/qa_crowbarsetup.sh

Commit 45a66ee90 broke HA deployments on releases other than Cloud 7
that had more than one possible node for cinder-volume, ceilometer-agent
or nova-compute. This is caused by not breaking $unclustered_nodes into
an array as expected by the rest of the code in custom_configuration().
Additionally, we add some quoting for the -z tests to avoid whitespace
issues that triggered "[: too many arguments" errors in the past.

Fix selection of nodes for cinder-volume, ceilometer-agent and nova-compute

---

scripts/jenkins/qa/cloud-mkphyscloud-qa-scenario-1a.yaml
scripts/jenkins/qa/cloud-mkphyscloud-qa-scenario-1b.yaml
scripts/jenkins/qa/cloud-mkphyscloud-qa-scenario-2a.yaml
scripts/jenkins/qa/cloud-mkphyscloud-qa-scenario-2b.yaml
scripts/jenkins/qa/cloud-mkphyscloud-qa-scenario-2c.yaml
scripts/jenkins/qa/cloud-mkphyscloud-qa-scenario-6a.yaml
scripts/jenkins/qa/cloud-mkphyscloud-qa-scenario-9.yaml
scripts/qa_crowbarsetup.sh

Recently we were facing issues with QA hw where bmc IPs were messed up. Making the waiting time streched to 1 min seems to resolve that issue.
Beside this scenario 2b was using wrong `nodenumber` param value that was probably the trigger to loosing nodes completely. 
Also the param `nodenumber` description was changed to better reflect its meaning in the JJB files.

Wait ~1min if using ipmitool on QA hw

---

scripts/lib/mkcloud-libvirt.sh
scripts/mkcloud

Several cleanups and enhancements to the DNAT port forwarding which allows access to cloud VMs on hosts like `blacher.arch.suse.de` which run the clouds on private networks which aren't routable from within the corporate network. The main highlights are:
- Supports separate non-conflicting DNAT ports for each cloud
- Each cloud's `iptables` setup is now written to `/etc/init.d/boot.mkcloud.d/$cloudname`
- `/etc/init.d/boot.mkcloud` is still supported for backwards-compatibility and for `mkch*.cloud.suse.de` hosts
- Guards against duplicate rule insertion
- Doesn't flush the PREROUTING chain every time
- Adds forwarding for Hawk and `mosh`
- Doesn't forward admin server ports on non-admin nodes, and vice-versa.
Supersedes #1193.

enhance setup of DNAT port-forwarding

---

scripts/jenkins/jobs-ibs/cloud-mkcloud6.yaml
scripts/jenkins/jobs-ibs/templates/cloud-mkcloud-gating-template.yaml
scripts/jenkins/jobs-ibs/templates/cloud-mkcloud-job-2nodes-template.yaml
scripts/jenkins/jobs-ibs/templates/cloud-mkcloud-job-4nodes-linuxbridge-template.yaml

Until now, gating jobs are based on three main tests: 2 nodes, 4 nodes
and HA. The HA job runs every night but not the other two. Separating
those tasks into their own jobs will make the run nightly.
The main purpose is that when there's a gating failure you are not
certain if the problem was already there or was triggered in the gate.
Now we will have that information.

Breakdown gating jobs into separate entities

---

scripts/jenkins/jobs-obs/openstack-trackupstream.yaml

Similar to te other projects, we don't want to track the clients
and some other packages.
This fixes the incomplete commit 883d4f26a .

trackupstream: Don't track clients for Newton:Staging

---

scripts/lib/mkcloud-common.sh

so that the new rule is always at the top
above the reject rules from libvirt
This is a partial revert of commit 10572913
This change fixed a real issue, reaching the crowbar node ssh on port 1122 after 2nd install

mkcloud-libvirt: remove and add iptables rules

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

We would like to be sure that proposal will be applied only when
assigned option want_ is equal to 1.
For current condtions it is enough that for example
export want_barbican=0
and condition
[[ $want_barbican ]] || return
will not work

Deploy proposals only when option want_ is equal to 1

---

scripts/qa_crowbarsetup.sh

In double braces there is no need for quotes (only in single braces there is) and no need for -z or -n.
Its just [[ $a ]] or [[ ! $a ]] .

qa_crowbarsetup: cleanup for a19d349ceb3c

---

scripts/jenkins/qa_openstack.sh

When getting the openstack client version, ignore the deprecation
warning printed to stderr.
This fixes:
qa_openstack.sh: line 375: [: openstackclient
3: integer expression expected

qa_openstack: Ignore deprecation warning

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

We tend to define functions as `function foo()`, but not always. This patch
makes all function defitions follow this scheme consistently.

Make function definition consistent

---

scripts/jenkins/jobs-obs/openstack-cleanvm.yaml

Newton has packages for Leap 42.2 so run cleanvm on that environment.

cleanvm: Run against openSUSE Leap 42.2

---

scripts/lib/mkcloud-common.sh

Old rule to forward port 6080 does not work properly with multi-cloud NAT setups. In addition it overlaps standard port forwarding for cloud 50 (80 -> 6080). This change changes VNC port forwarding to use standard calculated ports for each cloud.

Added port offset to VNC port forwarding rule

---

scripts/jenkins/jobs-obs/openstack-trackupstream.yaml

The package is not following any OpenStack release cycle and doesn't produce
any stable-$release tarballs.

trackupstream: No longer track python-swift3

---

scripts/jenkins/jobs-obs/openstack-trackupstream.yaml

All of them are maintained in a much better fashion upstream,
and we just don't serve any purpose in replicating them downstream.
I would like to replace them with links to the upstream project
in C:O:M so that we reduce workload.

Remove all the openstack clients from trackupstream

---

scripts/qa_crowbarsetup.sh

This was fixed with:
https://github.com/crowbar/barclamp-provisioner/commit/5d4f6411761386d8b76a9f5dfe5784bbed38d2f3

do not install susefirewall2 on lonelynodes

---

scripts/lib/mkcloud-dirmaint.sh
scripts/lib/mkcloud-libvirt.sh
scripts/mkcloud

This removes some hardcoded things from the dirmaint driver. And adds
code to "_cleanup" and "_prepare" to allow for multiple clouds being
deployed from a single host.
It will now setup automatically set a vswitch for the cloud, plug a nic
of the host into it and configure dnsmasq for the respective network.
However this code currently assumes that $cloud on z/VM will always
match ```mkcl<single-hex-digit>``` as it derives the mac addresses and vdev
names from that <single-hex-digit>.

mkcloud-dirmaint: Prepare for deploying muliple enviroments

---

scripts/qa_crowbarsetup.sh

want_magnum is set to 0 so the current check is wrong and always passes.
That means the magnum tests are always executed even if magnum is not deployed.

qa_crowbarsetup: Only run magnum tests if needed

---

scripts/lib/mkcloud-common.sh
scripts/mkcloud

when running tempest, controller nodes swap 1.5GB
thus severely lowing CI throughput

mkcloud: use 8GB for cloud7 controller nodes

---

docs/mkcloud.md
scripts/lib/mkcloud-libvirt.sh

When using the mkcloud on a new host, starting the libvirt daemon alone
will not start the virtlogd service which leads to the following problem:
libvirt: QEMU Driver error : Domain not found: no domain with matching name 'cloud-admin'
libvirt: XML-RPC error : Failed to connect socket to '/var/run/libvirt/virtlogd-sock': No such file or directory
File "/root/mchandras/automation/scripts/lib/libvirt/vm-start", line 16, in <module>
main()
File "/root/mchandras/automation/scripts/lib/libvirt/vm-start", line 12, in main
libvirt_setup.vm_start(args)
File "/root/mchandras/automation/scripts/lib/libvirt/libvirt_setup.py", line 377, in vm_start
dom.create()
File "/usr/lib64/python2.7/site-packages/libvirt.py", line 1035, in create
if ret == -1: raise …

docs: mkcloud: Start the virtlogd service on new installations

---

scripts/lib/mkcloud-libvirt.sh
scripts/mkcloud
scripts/qa_crowbarsetup.sh

extracted two simple commits from
https://github.com/SUSE-Cloud/automation/compare/master...alexdepalex:master
The variable is now named want_cached_images
so that it automatically gets passed into the admin node as well.

mkcloud: be more flexible in where/when we get images and repos

---

scripts/lib/mkcloud-libvirt.sh

This allows to use other base images for cloud nodes that have a different number of partitions.

mkcloud: resize autodetected partition instead of partition 2

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

to make it easier to compare timings of different runs

qa_crowbarsetup: track time needed for steps and onadmin actions

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

otherwise crowbar cannot be started due to the missing postgres
dependency
that likely fixes the backup restore job (in combination with https://github.com/crowbar/crowbar-openstack/pull/540)

add missing bootstrapcrowbar for resetting the admin node

---

scripts/qa_crowbarsetup.sh

As we are loosing nodes during cloud deployment, a bit waiting should fix the problem.

Wait after setting up pxe boot on the QA hardware nodes

---

scripts/qa_crowbarsetup.sh

When running the tempest tests for sahara, the 'fake' plugin
needs to be configured.

qa_crowbarsetup: Configure sahara plugins

---

scripts/lib/mkcloud-libvirt.sh
scripts/mkcloud

rename mkcloud_lib_dir to scripts_lib_dir
to be consistent with the new variable naming
mkcloud_dir -> SCRIPTS_DIR
(uppercase because it may be set from outside, or uses default)
mkcloud_lib_dir -> scripts_lib_dir
(internal only)

Scripts lib dir

---

jenkins/ci.opensuse.org/templates/openstack-rpm-packaging-sles12.yaml
scripts/jenkins/rpm-packaging/createproject.py

Creating a new project creates more often than not an error 500.
We're lazy and just try it 5 times in the hope we succeed our
chances of succeeding

Add hack for working around Build Service database deadlock

---

jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-compute-template.yaml

due to the number of nodes in the ha_compute job ceph gets used
as a storage_method.
this is problematic on cloud7 as it will set the compute nodes to
be sles12-sp1. but sles12-sp2 is needed for HA by Crowbar, as there
are no more HA repos in the cloud-repos.yml file under the sles12-sp1
platform
This should fix https://ci.suse.de/view/Cloud/view/Cloud7/job/cloud-mkcloud7-job-ha-compute-x86_64/ and https://bugzilla.suse.com/show_bug.cgi?id=1001193
it may still be needed to push that change to jenkins after merging, not sure

set storage_method to swift (bsc#1001193)

---

jenkins/ci.opensuse.org/openstack-cleanvm.yaml

Master only has SLE_12_SP2 and Leap42.2 repositories so only
try to run cleanvm with theses repos.

jenkins: Fix cleanvm targets for Master

---

jenkins/ci.suse.de/openstack-mkcloud.yaml

This was triggered by PR #1319 which moved it
and got green status without actual tests being run.

jjb/mkcloud: fail on missing allocpool script

---

jenkins/ci.suse.de/cloud-mkcloud7-job-simpletest-s390x.yaml
jenkins/ci.suse.de/cloud-mkcloud7.yaml

Since mkcloud support for handling s390x was put on hold, it
doesn't make sense to burn cpu cycles by constantly running jobs
that have no chance of succeeding. replace with a place holder
job until somebody can fix mkcloud.

Remove all s390x jobs and replace it with a placeholder

---

scripts/qa_crowbarsetup.sh

Fix for the `novanodes` and `ceilometernodes` which were converted to bash arrays but some of the following code still assumed that they are space-separated string lists.

Fixed conversion of bash arrays to json

---

scripts/qa_crowbarsetup.sh

The new openstackclient for Newton has a different syntax. This
fixes:
No recognized column names in [u'ip']
when running mkcloud with cloudsource=newtoncloud7

qa_crowbarsetup: Fix osc syntax for Newton

---

scripts/mkcloud

I saw openstack-mkcloud builds that failed due to errors in the mkcconf file. In order to better debug these kinds of issues we should collect the mkcconf file as part of the build artifacts.

also collect mkcconf in artifacts dir

---

jenkins/ci.suse.de/openstack-mkcloud.yaml

Similarly to mitaka, the hybrid backend is also missing for newton :(

Skip setting want_ldap=1 on newtoncloud7 as well

---

scripts/qa_crowbarsetup.sh

the `crowbar-core` and `crowbar-init` package are now responsible of the symbolic links

drop install_crowbar_init

---

scripts/qa_crowbarsetup.sh

The storage team uses the "storage3" branch for SES3 and SES4 testing.

qa_crowbarsetup: Use different branch for SES testing

---

scripts/qa_crowbarsetup.sh

The python-*client-test packages are only needed in the cct step and only
when $skip_func_tests is 0.
The SOC7 Newton clients don't have -test packages (yet) so this makes
the testing easier for now.

qa_crowbarsetup: Move -test pkg installation

---

scripts/qa_crowbarsetup.sh

for debugging the random NFS mount timout

qa_crowbarsetup: run tcpdump during nfs mount

---

scripts/qa_crowbarsetup.sh

Before DVR was enabled when you set the variable 'want_dvr' to any
value, even false. Now we check that the value has to be 1 (true).

Only enable want_dvr when set to 1

---

scripts/lib/mkcloud-common.sh

When we successfully determined that a rule is already present,
just silently ignore it

Avoid excessive warnings

---

scripts/qa_crowbarsetup.sh

As a workwarrond from bsc#1005884 and bsc#1005885 we can't query
the version from the ceph package.

qa_crowbarsetup: query ceph version from the binary.

---

scripts/jenkins/qa_openstack.sh

* `openstack --version` can produce deprecation warnings. In this case the output will go via stderr.

qa_openstack: fixes for cleanvm

---

scripts/jenkins/qa_openstack.sh

Meanwhile a new ISO arrives, this workaround can help to move to green cleanvm for SLE12SP2

qa_openstack: start virtlogd service if available.

---

scripts/lib/mkcloud-common.sh
scripts/qa_crowbarsetup.sh

We saw mkcloud builds that were stopped by safely without collecting supportconfigs.
Safely only does an exit via complain, whereas the function error_exit collects the supportconfigs in case of a SIGTERM in mkcloud.
When exiting via safely from mkcloud we should also collect the supportconfigs.

Safely with supportconfig

---

hostscripts/clouddata/syncSLErepos

While SES is still in development we want to have the latest state
from the SUSE namespace. This should help with our current CI problem
where the package version of ceph is different to the version
"ceph --version" prints out. That problem is fixed on IBS in the
SUSE namespace but not yet in the currently used source for SES sync.

syncSLErepos: Sync latest SUSE namespace version of SES

---

scripts/qa_crowbarsetup.sh

support to skip any proposal (creation and applying of it) by setting 
`want_${barclamp}_proposal=0`
Setting it to 1 or empty as no effect currently.
This only adds a way to skip proposals. It does not remove the old variables.
We may do this at a later point.

generic method to skip any proposal

---

scripts/qa_crowbarsetup.sh

With the upgrade to SLES12 SP2, the hang for some reason does
not trigger anymore, so we don't need an outdated sleshammer
fork anymore

Remove obsolete Sleshammer/aarch64 workaround

---

jenkins/ci.suse.de/cloud-automation-pr-trigger.yaml
jenkins/ci.suse.de/cloud-cct-pr-trigger.yaml
jenkins/ci.suse.de/cloud-crowbar-testbuild-pr-trigger.yaml
jenkins/ci.suse.de/openstack-mkcloud.yaml
jenkins/ci.suse.de_xml/cloud-crowbar-testbuild-pr.xml
scripts/crowbar-testbuild.py
scripts/github-status/github-status.rb

The status message of the github status in our PRs was always
truncated. In order to make more room for the message we shorten
the context string:
* ci.suse.de/openstack-mkcloud/gating => suse/mkcloud
Additionally the messages are made consistent for all similar jobs.
Furthermore the testbuild jobs (preliminary job for a PR gating) now
have their own status to better reflect that two steps are needed and
to show both states and have links to both CI jobs.
A testbuild job now needs these status results:
* suse/mkcloud/testbuild  _(building the PR RPM package)_
* suse/mkcloud _(the PR gating job)_
**Note**
This PR is only here to document the change. It will be merged without +1s as it only can be done when all our jenkins jobs can be stopped. This timeslot is now (almost everybody …

jjb: shorter github status context, separate testbuild status

---

scripts/mkcloud

Currently, if you run mkcloud with no arguments or the multitude of
scenarios to trigger the usage message, it is printed out and then
shows: onadmin_help: command not found.
onadmin_help is in qa_crowbarsetup, so source the file before running
the function.

Fix help message

---

scripts/lib/libvirt/admin-config
scripts/lib/libvirt/compute-config
scripts/lib/libvirt/fixtures/cloud-admin-uefi.xml
scripts/lib/libvirt/fixtures/cloud-node1-uefi.xml
scripts/lib/libvirt/libvirt_setup.py
scripts/lib/libvirt/test_libvirt_setup.py
scripts/lib/mkcloud-common.sh
scripts/lib/mkcloud-libvirt.sh
scripts/mkcloud

Allow support for firmware_type as a parameter to admin_config and add an option to mkcloud "want_efi" to use UEFI image to boot mkcloud.

Uefi boot support  on mkcloud

---

scripts/qa_crowbarsetup.sh

Some packages, like libopenssl-devel fail to install, because the SDK
repo only contains only libopenssl-devel, but not libopenssl. By
lowering the priority of the SDK repositories, devsetup will find
libopenssl-devel on the install media, which is complete.

Fix devsetup: Lower SDK repository's priority

---

scripts/lib/mkcloud-libvirt.sh

To avoid issues with HA jobs, clean drbd signatures from the media
properly. This mess wouldn't be necessary if we'd just use thin
volumes, but we don't.

Clean drbd signatures properly

---

scripts/mkcloud

The `clouddescription` value can be set by the Jenkins `mkcloud` job to things like
Jenkins Build: 39680 / cloud-mkcloud7-job-docker-x86_64
which contains spaces.  So we need to quote it when writing `mkcloud.config`, otherwise we only get the first word in `/etc/motd` on the admin server.
Finally fixes #759!

quote clouddescription when passing to admin server

---

scripts/qa_crowbarsetup.sh

The deployment fails sometimes when calamari is deployed on the controller
because calamari deploys (and needs) a postgres DB on localhost but
on the controller is already a postgres DB running.

qa_crowbarsetup: Do not deploy calamari on SOC7

---

scripts/lib/mkcloud-libvirt.sh

this fixes "compute-config: error: too few arguments"
this has been overseen in https://github.com/SUSE-Cloud/automation/pull/1141
for reference: https://ci.suse.de/job/openstack-mkcloud/39982

add missing parameter to compute-config script

---

scripts/mkcloud

The waiting for ssh on admin node is done by a dedicated
function that is called above. So drop duplication.

mkcloud: drop duplicate wait for loop

---

scripts/lib/mkcloud-common.sh

A pointed out in https://github.com/SUSE-Cloud/automation/pull/1384#issuecomment-255878398 the is_onhost detection was wrong.
The entire BASH_SOURCE stack needs to be checked instead of matching
all the common files.
This commit is extracted from PR #1415 as it needs to be fixed for other cases as well.

mkcloud: fix is_onhost detection

---

scripts/lib/qa_crowbarsetup-help.sh
scripts/mkcloud
scripts/mkcloud-test.sh
scripts/qa_crowbarsetup.sh

Move qa_crowbarsetup help to common file.
Renaming `onadmin_help` to `qacrowbarsetup_help` which is a correct name (because the `onadmin_` prefix means that a function runs **on** the admin node).
The goal is to untie mkcloud and qa_crowbarsetup.
So we removed the sourcing of qa_crowbarsetup a few weeks ago (this is a feature).
The idea behind this is, that mkcloud can change more radical than qa_crowbarsetup. The latter will most likely remain a collection of shell functions. But mkcloud will need to change sooner or later into a OOP style (this will not be bash). Changes like this contradict this plan. Breakages should not be fixed by sourcing qa_crowbarsetup.sh again.
This PR contains the revert of commit dae0ddd21698e274175fee60c31d8ae8a24d5600

unsource qa_crowbarsetup

---

scripts/qa_crowbarsetup.sh

It may happen that 'crowbarctl upgrade repocheck crowbar' fails but we
don't catch that error. Added an explicit check for the return value so
later on we can check the command output.

Check crowbarctl upgrade repocheck return code

---

jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-nondisruptive-ha-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-nondisruptive-template.yaml

Executing cloudupgrade step should only upgrade controller nodes so far.
No reason to run testsetup when we are not upgrading all nodes yet.

For non-disruptive upgrade, run only steps that could pass

---

jenkins/ci.suse.de/templates/cloud-mkcloud-job-btrfs-template.yaml

We do not need them for Ceph any more.
This should fix btrfs job failures, I think

Do not install SLES12SP1 nodes with Cloud7

---

scripts/lib/mkcloud-common.sh
scripts/mkcloud
scripts/qa_crowbarsetup.sh

This way people can do:
export architectures="x86_64"
in their mkcloud, and controller will not try to establish a repository
for other architectures.

Forward architectures environment

---

hostscripts/clouddata/syncSLErepos

Use if block only to set the differing paths.
Drop `sync_from_ibs` variable that would survive loops.

syncSLErepos: fixes and better readablility for cornercase

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

As pointed out by @aspiers  in https://github.com/SUSE-Cloud/automation/issues/759
the /etc/motd file on the admin node is written too late. Failed deployments before motd is written are missing details about the cloud setup.
So we now write the most of motd when the admin node is setup.
The remaining info is appended (if missing) later in the function `onadmin_add_cloud_repo` (same place as before).

qa_crowbarsetup: write motd early, append info later

---

scripts/jenkins/update_automation

more secure checks for git repo and SLE11 support
The old git version we ship on SLES11 does not automatically setup the branches upon first checkout. So we need to use checkout -b in this case.
If the target directory was there but empty it was still falsly recognized as git repo.
So we now remove the target directory before cloning to it, it might already be there.

Update automation sle11

---

scripts/mkcloud

Git versions older than 1.8 do not support the '-C' argument. Change the
directory manually instead so it can be run with all versions.

Workaround for old git versions

---

jenkins/ci.suse.de/cloud-crowbar-testbuild-pr-trigger.yaml

Evaluating the wrong status lists this PR again on the next trigger run, as the PR job has not finished meanwhile.
Due to this we will collect too many status report for a sha1 (commit) and the status setting breaks.

jjb: use testbuild context when listing open crowbar PRs

---

jenkins/ci.suse.de/openstack-mkcloud.yaml

A full tempest run on our rotten hardware takes 4h 41h, so there
is no way to finish successfully in 4h.

Raise mkcloud timeout to 6h

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

This is needed by the CloudFoundry team to be able to test on a Mitaka cloud.

Readd "mitakacloud7" source

---

scripts/qa_crowbarsetup.sh

We have a stable link to the latest iso. Use that because otherwise
the iso is downloaded 2x.

qa_crowbarsetup: Do not download the C7 iso twice

---

jenkins/ci.suse.de/cloud-mkcloud7.yaml

Since all existing arm jobs are also broken on x86_64, better
add something that has a chance of succeeding..

Add two arm related test job that has a chance of succeeding

---

scripts/qa_crowbarsetup.sh

When Ceph id deployed, also deploy cephfs with Manila
for testing.

qa_crowbarsetup: Deploy cephfs with Manila

---

scripts/qa_crowbarsetup.sh

This is basically a revert of ed7448973e851fcf364d8659f7d9bdde624166ed
It does not seem to make sense to reset the cloudsource after the
upgrade, it breaks all post-upgrade checks for 'current' version.

Do not reset the cloudsource to the pre-upgrade state.

---

jenkins/ci.opensuse.org/openstack-diskimage-builder.yaml

Add option to build Leap 42.2 images

jenkins: openstack-diskimage-builder: Build Leap 42.2 images

---

jenkins/ci.opensuse.org/openstack-trackupstream.yaml

zaqar exists in Newton already, move it to the right exception
list

Fix trackupstream for openstack-zaqar

---

scripts/qa_crowbarsetup.sh

When the build fails on prechecks code, it would be nice to see
the reason.

Log the output of upgrade prechecks

---

jenkins/ci.suse.de/cloud-mkcloud7-suse.yaml

Those are not gating jobs but merely check jobs, indicate
properly that those are running against the media in the SUSE namespace

Fix job_names for suse jobs

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

https://ci.suse.de/view/Cloud/view/Worker/job/openstack-mkcloud/42030/console
timed out after 60 minutes of inactivity
11:04:56   waiting 300 cycles of 1 seconds = 300 seconds
12:04:56 ............................
Build timed out (after 60 minutes). Marking the build as aborted.
28 netcats in an hour makes an average of 2 minutes per netcat

mkcloud: limit netcat waiting

---

scripts/qa_crowbarsetup.sh

In some setups, the cloud nodes might not have access to
the R&D network. Which is fine, because that is available
on the crowbar node already.

Point test update repos to crowbar node (bsc#1011612)

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

The idea is for qa_crowbarsetup.sh not to deal with upgrade_cloudsource
at all. It will just deal with cloudsource. Updating cloudsource from
upgrade_cloudsource will happen in mkcloud only.

Removed all references to upgrade_cloudsource

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

As alternative to 2nd commit, we could just ignore pending interactive patches in the upgrade prechecks call, as already suggested by @bmwiedemann 
But I do not know why this can be correct, what if there's an interactive patch that is required for the upgrade to run correctly?

Install interactive patches only for the upgrade case

---

scripts/mkcloud

when using mkcloud to just call cleanup
it blocks at the end when trying to fetch motd
from the now killed admin node

mkcloud: dont block on missing admin node

---

scripts/qa_crowbarsetup.sh

- drop sleeps in favor of wait_for loops
- determine the ipmi password first and then run the cycle once, instead of twice (one with wrong password and one with the correct one)
- use `nodes` function to determine the node number (it might change over time, so always let `nodes` compute the current number
@vmoravec  Please do a test run on the qa hardware

use wait_for loops instead of sleeps

---

scripts/jenkins/qa_openstack.sh

This reverts commit 3102ca8d226da349fd02962b0dcddfaeb99b52f5, reversing
changes made to 898e5447f600f04b5642e332fdf58d7ce6c6c1d1.
We can merge this PR once the virtlog problem is fixed in the cleanvm images for SP2, so we do not hide the problem in future images.

Revert "Merge pull request #1389 from aplanas/cleanvm"

---

scripts/qa_crowbarsetup.sh

I'm not sure when exactly to call those...
cloud6 parts are called from `onadmin_prepare_cloud_repos`, but only for GM values of `cloudsource`. Does it mean we are not supposed to do it for develcloud values?
@dirkmueller @bmwiedemann ?

Mount SUSE-OpenStack-Cloud-7 repositories, fix location for SUSE-OpenStack-Cloud-6

---

scripts/qa_crowbarsetup.sh

The crowbar-client/init changes are not in Milestone 6, so
the old method needs to be used. Fixes regression introduced
in https://github.com/SUSE-Cloud/automation/pull/1436

Make Milestone6 deployable again

---

hostscripts/soc-ci/soc-ci

This mkcloud host is active now.

add mkchp.cloud.suse.de

---

scripts/iscsictl.py

We need to provide the system variable 'ZYPP_LOCK_TIMEOUT' to iscsictl.py script to avoid situations like 'System management is locked by the application with pid 3730 (zypper)' in jenkins.

Add ZYPP_LOCK_TIMEOUT variable

---

scripts/lib/mkcloud-common.sh

As part of the hardware relocation the vlan ranges need to be adjusted.
QA now has a range of 3x 16 vlans starting from vlan 800. We'll start
by moving qa4 to the new range of VLAN 832-847.

Move QA4 to the new vlan range

---

hostscripts/soc-ci/README.soc-ci.md
hostscripts/soc-ci/soc-ci

We are usually interessted in the supportconfigs when a
openstack-mkcloud job fails. So add the possibility to
download the Jenkins artifacts (which include the supportconfigs).

soc-ci: add artifacts download and workers pool overview

---

scripts/jenkins/qa_openstack.sh

When running qa_openstack, also deploy Sahara, Designate and
Gnocchi.
Note: All theses services are not yet fully configured and started
in openstack-quickstart. But this commit still helps with manual testing
because the database and endpoints are created and with that it is easier
to continue with enablement in cleanvm.

qa_openstack: Deploy more services

---

jenkins/ci.opensuse.org/openstack-diskimage-builder.yaml

openSUSE Leap 42.2 does not provide pre-built cloud images so disable
this combination. Moreover, add 13.2 to the list of distributions but
do not use the 'opensuse' element because openSUSE 13.2 does not provide
a pre-built cloud image either.

jenkins: openstack-diskimage-builder: Disable cloud images for Leap 42.2

---

jenkins/ci.opensuse.org/openstack-diskimage-builder.yaml

Commit 4b31a6280b7a("jenkins: openstack-diskimage-builder: Add openSUSE
13.2 distribution") added support for openSUSE 13.2 but it also
introduced a broken combination filter because of the inline comment.
The inline comment became part of the combination filter which led to
a non-working filter in the end so we move it elsewhere.

jenkins: openstack-diskimage-builder: Fix combination-filter

---

jenkins/ci.opensuse.org/openstack-diskimage-builder.yaml

The wrong syntax was introduced with 4fd4254e89c775 .
This fixes:
yaml.scanner.ScannerError: while scanning a tag
in "suse-cloud/automation/jenkins/ci.opensuse.org/\
openstack-diskimage-builder.yaml", line 43, column 27
expected ' ', but found '"'
in "suse-cloud/automation/jenkins/ci.opensuse.org/\
openstack-diskimage-builder.yaml", line 43, column 43

jenkins: Fix openstack-diskimage-builder job syntax

---

hostscripts/rpm-packaging/createproject.py
jenkins/ci.opensuse.org/templates/openstack-rpm-packaging-sles12.yaml

This allows us to use a different base distribution for
each code stream and consequently allows switching Ocata
to SP2

Switch to "standard" repository name

---

scripts/jenkins/qa_openstack.sh

When setting $QUICKSTART_DEBUG and the new env var
$cloudsource_extra to a zypper repo, packages from this
repo will be used.
This is useful when testing locally with some packages which
are not yet merged.

qa_crowbarsetup: Allow extra repo for testing

---

scripts/qa_crowbarsetup.sh

otherwise the upgrade subcommand won't be available until release
of cloud7

upgrade: on cloud 6 crowbarctl needs to run in experimental mode

---

jenkins/ci.opensuse.org/openstack-trackupstream.yaml

This is done by track-upstream-and-package.pl already.

trackupstream: Remove tar_scm configuration

---

scripts/mkcloud

These variables need to be exported to be in env (and to be fetched by grep).
The new location of this code makes this more obvious.

mkcloud: move export to better place

---

scripts/qa_crowbarsetup.sh

Its dependecies break the installation if OpenStack.
The lonely nodes will be registered via crowbar register and then they become part of the cloud, so cloud-init prevents this.

qa_crowbarsetup: remove cloud-init from lonely nodes

---

scripts/mkcloud

Here is the log from the build when the action timed out, although the upgrade itself actually ended correctly:
http://pastebin.nue.suse.com/17660/src

Increase the timeout for admin server upgrade

---

scripts/qa_crowbarsetup.sh

The problem is that cloudver is bumped to 7 at some point during
the upgrade process, while it is still operating with Cloud6 based
admin server (and crowbarctl)

CROWBAR_EXPERIMENTAL needs to be set for the whole 6-7 upgrade

---

scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-2a.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-2a.yaml

The convention is the neutron API sits in `cluster:services`, not in `cluster:network`.

Update QA scenario with 3 clusters: put network API on cluster:services

---

scripts/mkcloud

the api is restricted and noderepocheck is taking care about that

upgrade: don't try to activate the repos during the upgrade

---

hostscripts/clouddata/syncSLErepos

We don't use it in Cloud, so stop wasting disk space

syncSLE: Stop mirroring Storage 3

---

jenkins/ci.opensuse.org/openstack-diskimage-builder.yaml

Add some popular elements to the generated image to make sure that
openSUSE plays well with them. These elements are also used by the
OPNFV openSUSE Jenkins jobs.

jenkins: openstack-diskimage-builder: Add some popular dib elements

---

jenkins/ci.suse.de/templates/cloud-mkcloud-gating-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-2nodes-tempestfull-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-2nodes-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-4nodes-linuxbridge-tempestfull-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-4nodes-linuxbridge-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-backup-restore-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-btrfs-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-crowbar-devsetup-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-crowbar_register-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-devel-storage-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-devel-virt-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-docker-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-dvr-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-compute-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-linuxbridge-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-hyperv-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-magnum-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-many_compute-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-raid-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-ssl-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-uefi-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-disruptive-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-nondisruptive-ha-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-nondisruptive-ha-without-nodes-upgrade-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-xen-template.yaml

Since we currently trigger those jobs once per media, and we have a lot
more than one media per day (more like 6+ medias per day), the backlog
wasn't really enough anymore. keep one week of backlog.

Jenkins: keep 7 days of backlog

---

jenkins/ci.opensuse.org/openstack-diskimage-builder.yaml

openSUSE 13.1 has reached EOL so there is not much point in testing
it anymore.

jenkins: openstack-diskimage-builder: Drop openSUSE 13.1

---

scripts/lib/mkcloud-common.sh
scripts/qa_crowbarsetup-test.sh

to only match on explicit M6 milestone targets
but not on develcloud,susecloud,Beta,RC,GM

fix iscloudver 7M6minus

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

Note that i'm executing it before I change the cloudsource. We wouldn't be able to check it later

Allow vendor change on nodes when upgrading packages from develcloud6

---

scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-2c.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-2c.yaml

This PR is changing manila backend from default one to cephfs for non-ssl and ssl-insecure scenarios.
Tested here: https://ci.suse.de/view/Cloud/view/QA/job/cloud-mkphyscloud-qa-scenario-2c/277/

Change manila backend to cephfs

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-2a.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-2b.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-2c.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-9.yaml

We need to add 1 minute delay for SBD (2a, 2b, 2c, 9) scenarios to avoid the situation where nodes are not ready yet for SBD setup.

Add 1 minute delay for synchronization

---

scripts/qa_crowbarsetup.sh

Due to probably existing security group rules in place
lets use a proper security group different from default
to run the testvm tests
*May not fix anything, but seems to affect some CI jobs failures: https://ci.suse.de/job/openstack-mkcloud/46856/console

automation: chage the security group used for tests

---

jenkins/ci.suse.de/templates/cloud-mkcloud-job-2nodes-tempestfull-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-4nodes-linuxbridge-tempestfull-template.yaml

This saves roughly 20% execution time of the testsetup
step and puts more stress on the system, which is good.

Switch to parallel full tempest runs

---

jenkins/ci.suse.de/cloud-mkcloud6.yaml
jenkins/ci.suse.de/cloud-mkcloud7.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-2nodes-tempestfull-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-4nodes-linuxbridge-tempestfull-template.yaml

Unfortunately mkcloud substitutes smoke parameters when tempestoptions
is empty. so set some explicit other value to prevent that from
happening

keep tempestoptions non-empty

---

scripts/mkcloud

We want to run `prepareinstcrowbar` before `runupdate` so we call
`onadmin_setup_local_zypper_repositories` to change all repos to the
correct `clouddata` URI.

Change order of run step expansion

---

scripts/qa_crowbarsetup.sh

Right now, ec2-api ends up on the first compute node, but that's not
what is expected: we'd want it to be on one of the controllers.

qa_crowbarsetup: Fix deployment of ec2-api on HA clouds

---

scripts/qa_crowbarsetup.sh

Swift in Liberty or newer started refusing devicecount < $((zones*replicas)),
which is totally sensible, but wasn't ensured by the test environment

Lower replicas setting for low-nodecount deployments

---

jenkins/ci.suse.de/cloud-mkcloud6.yaml
jenkins/ci.suse.de/cloud-mkcloud7.yaml
jenkins/ci.suse.de/openstack-mkcloud.yaml
scripts/mkcloud
scripts/qa_crowbarsetup.sh

This is more readable and hopefully allows us to remove some ugly
backpatching once cloud6 is out of maintenance.

Change tempestoptions default to the long options variant

---

scripts/lib/mkcloud-common.sh

For debugging mkcloud failures it might be helpful to have the error
code number (which is hopefully unique) in the error message.

Add error code to error message

---

jenkins/ci.suse.de/cloud-automation-pr-trigger.yaml
jenkins/ci.suse.de/cloud-crowbar-testbuild-pr-trigger.yaml

As we meanwhile have a filter to skip PRs that do not affect
an mkcloud run it is safe to reduce the polling interval for
open PRs. We reduce to 5 minutes for now and monitor.
Btw. this is already deployed (to test this) on jenkins for these jobs.

ci: reduce PR polling interval to 5min

---

scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-1a.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-1b.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-2a.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-2b.yaml

Replicas should be equal to the number of nodes in swift-storage
This fixed the swift failures in qa scenarios.
Also it is in line with the dev scenario changes: https://github.com/SUSE-Cloud/automation/commit/1c2231e511fa65a8e9c2a52b8c9689b51fdbf2b7

Change number of replicas to equal to 2

---

scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-1a.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-1b.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-2a.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-2b.yaml

Change number of replicas to equal to 2 for ssl-insecure scenarios too
Replicas should be equal to the number of nodes in swift-storage
This fixed the swift failures in qa scenarios.
Also it is in line with the dev scenario changes: 1c2231e

Change number of replicas to equal to 2 for ssl

---

scripts/qa_crowbarsetup.sh

Also, increase the timeout to 2 hours... (does not hurt when we have exit on error, and the last step could really take along time...)

Better check for nodes upgrade: exit when error is detected

---

scripts/qa_crowbarsetup.sh

The adjustments on the server already happened, and this
allows testing also on non-x86.

Move manila-service-image into an arch specific subdir

---

scripts/jtsync/jtsync.rb

~~**Currently untested, mainly because I haven't yet tried to figure out how to test it**~~
It's much more helpful if the new status is immediately visible via a notification (which can appear in many forms, e.g. via an email from Trello, or as an notification from the Android app), rather than having to load the Trello app or website in order to see the new status.

jtsync: include new status in notification

---

scripts/qa_crowbarsetup.sh

This is changing due to the ability to add CNAME records.
This is needed for https://github.com/crowbar/crowbar-core/pull/992.

qa_crowbarsetup: Update how we set attributes of the DNS barclamp

---

jenkins/ci.suse.de/openstack-mkcloud.yaml
scripts/mkcloud
scripts/qa_crowbarsetup.sh

Aodh has now its own barclamp. Its time to enable its deployment in the CI and by mkcloud by default

aodh: enable aodh deployment by default

---

scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-1a.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-1b.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-2a.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-2b.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-2c.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-3.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-9.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-1a.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-1b.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-2a.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-2b.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-2c.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-3.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-6a.yaml

There are now 100 vlans that can be used after move to the new vlan range: https://gitlab.suse.de/qa/cloud-doc/blob/master/infra/nuremberg.md
so ranges:
qa2 1200-1299
qa3 1300-1399
qa4 1400-1499

Change vlan number to 99

---

jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-nondisruptive-ha-template.yaml
scripts/mkcloud

1. ceilometer works again, after removing aodh to separate barclamp
2. want_postgresql=1 is default value for some time already

upgrade: reenable ceilometer; drob obsolete parameter

---

jenkins/ci.suse.de/cloud-trackupstream.yaml

Crowbar got removed by accident during the conversion to jjb.

jenkins: Readd crowbar to cloud-trackupstream

---

scripts/mkcloud

revert 2029b683
https://bugzilla.novell.com/show_bug.cgi?id=884706
as it is probably fixed by now

revert mkcloud: workaround vlan/virtio checksum offloading bug

---

scripts/qa_crowbarsetup.sh

Updated to be in Sync with the ceph changes and needed to pass the ceph tests.
Updates the required yaml file for the ceph tests with the full hostnames used by the ceph cookbook.

 automation: use ceph-mon full hostnames instead of simple hosts for tests

---

hostscripts/clouddata/syncSLErepos

for better separating R&D net https://trello.com/c/SBO0VngV
because dist.nue.suse.com nfs works fine,
but euklid's does not

syncSLErepos: dont use euklid anymore

---

scripts/qa_crowbarsetup.sh

Fix the hostname resolution to be in sync with the testing framework.
We were returning the wrong hostnames for the ceph tests after merging https://github.com/SUSE-Cloud/automation/pull/1610
This patch fixes it by using the simple hostname + network name if needed as to be in sync with https://github.com/crowbar/crowbar-ceph/pull/84
Also fix: Using `-eq` for string comparision always returns 0:
```
$ test='a'          
$ echo $test        
a
$ [[ $test -eq "a" ]]
$ echo $?            
0
$ [[ $test -eq "b" ]]
$ echo $?            
0
$ [[ $test == "b" ]] 
$ echo $?           
1
```

automation: Fix ceph hostname resolution for tests

---

scripts/qa_crowbarsetup.sh

Lets see if crowbar/crowbar-ceph#83 and crowbar/crowbar-openstack#743
finally resolve this failure
This reverts commit 77eb877a9f466296e6e12a7c27d679efdca16a53.

Revert "Skip radosgw tests since its broken (bsc#1017837)"

---

scripts/qa_crowbarsetup.sh

This shall fix the EC2 related HA build failures, as till now, the deployment was only happening for the first node in the cluster.

mkcloud: enable HA deployment for ec2-api

---

jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-nondisruptive-ha-without-nodes-upgrade-template.yaml

Wit this job, just admin server is installed, and nodes
do not even have Cloud7 repositories set up.

Remove testsetup from job that does not upgrade nodes

---

scripts/lib/mkcloud-common.sh

update on commit 5b108152
because it has been causing trouble with timeouts
in the CloudFoundry team's environment.

mkcloud: increase ServerAliveInterval

---

scripts/qa_crowbarsetup.sh

At least 2 latest builds failed with the timeout in the last step:
https://ci.suse.de/job/openstack-mkcloud/51186/
https://ci.suse.de/job/openstack-mkcloud/51141/

Raise timeout for upgrade of nodes

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-test-tempest-full.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-test-tempest-smoke.yaml

This change separates `testsetup` from triggering  tempest tests to avoid test run duplication.

Modify QA tempest tests jobs

---

scripts/qa_crowbarsetup.sh

I thought we have problems with timeout, but actually the check for end of 'nodes' step is wrong.
The new behavior was introduced by
https://github.com/crowbar/crowbar-core/pull/1037
https://github.com/crowbar/crowbar-core/pull/1043

Correct check for finish of the upgrade

---

scripts/qa_crowbarsetup.sh

the crowbarctl interface has changed and requires an argument now
which nodes to upgrade
* https://github.com/crowbar/crowbar-core/issues/1056
* https://github.com/crowbar/crowbar-client/pull/145 (plus rubygems release after merge)

upgrade: adapt crowbarctl upgrade nodes

---

hostscripts/gatehost/gatevm.xml
scripts/lib/mkcloud-common.sh

ip ranges and VLANs
drop obsolete p.cloud (was Cloud 1.0 deployment)

add p3 cloud

---

scripts/qa_crowbarsetup.sh

That is needed when we deploy with Ceph as backend. Otherwise some
tempest tests fail with:
Failed to schedule create_share: No valid host was found.

qa_crowbarsetup: Set storage_protocol for manila in tempest

---

scripts/qa_crowbarsetup.sh

Production clouds start with `p` and have a larger subnet at their
disposal. The current test for production cloud is overly broad and
captures clouds such as `vp5` which have smaller networks.

Fix netmask in nova_fixed for non-production

---

scripts/qa_crowbarsetup.sh

The custom-key value is only set during initial deployment of Cloud7,
so it is not present when the cloud is upgraded from Cloud6.
An alternative to https://github.com/SUSE-Cloud/automation/pull/1647

Skip the check for custom vendor data if they are not present

---

scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-2a.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-2b.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-2c.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-9.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-2a.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-2b.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-2c.yaml

fix 2b
We recently renamed UUID to uuid

switch scenario 2a/2c to default keystone token provider (fernet) and

---

scripts/qa_crowbarsetup.sh

There is an crowbar option to create trusted flavors. It is disabled
by default but we should test the creation so enable it in our CI.

qa_crowbarsetup: Create and test trusted_flavors

---

scripts/qa_crowbarsetup.sh

crowbar command is only available at admin server, but this method is
run on controller node
The wrong check was introduced by https://github.com/SUSE-Cloud/automation/pull/1658

Fix checking for custom metadata on controller node

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-test-tempest-full.yaml

Substitute -t (serial) option with --parallel to speed up tempest full
Even though parallel is the default i left it to be more explicit.

Change tempest full to parallel run

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-test-tempest-defcore.yaml
scripts/qa_crowbarsetup.sh

The job should be run after the tempest full and upload the results with the refstack client.
But for now just a job, without a trigger in tempest full.

Defcore job rework

---

scripts/qa_crowbarsetup.sh

This expression was also matching on my hostname which broke my mkcloud runs.

qa_rowbarsetup.sh: Make p cloud hostname matching more specific

---

scripts/qa_crowbarsetup.sh

We'd like to test our code, so better use it instead of
directly rebooting nodes.

Test coverage the easy way: use crowbarctl for rebooting nodes

---

scripts/jtsync/jtsync.rb
scripts/jtsync/test_jtsync.sh

Add new logic for matrix jobs:
Instead of setting the card on each status change the card is only set
if a new build started or the build changes from successful to
failed.

jtsync: Handle matrix jobs correctly

---

scripts/mkcloudhost/routed.cloud

when running inside R&D
because it has more direct routing

routed.cloud: use internal clouddata name

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-2a.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-2a.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-2a.yaml

The deployment was tested [here](https://ci.suse.de/view/Cloud/view/QA/job/cloud-mkphyscloud-qa-scenario-2a/316/console). For now, we will run all manila-related tempest tests manually.

Add NetApp Storage server as the backend for Manila (no-ssl and ssl-insecure scenarios)

---

scripts/qa_crowbarsetup.sh

Current tempest runner does not skip the required tests unlike run_tempest.sh did

Defcore use list of tests to run

---

scripts/lib/mkcloud-common.sh
scripts/lib/qa_crowbarsetup-help.sh

to allow increasing all wait_for sleeps
because some (virtualized) mkcloud hosts are a lot slower
and this can make them pass

mkcloud-common: add want_timescaling

---

scripts/scenarios/cloud6/qa/no-ssl/qa-scenario-1a.yaml
scripts/scenarios/cloud6/qa/no-ssl/qa-scenario-1b.yaml
scripts/scenarios/cloud6/qa/no-ssl/qa-scenario-2a.yaml
scripts/scenarios/cloud6/qa/no-ssl/qa-scenario-2b.yaml
scripts/scenarios/cloud6/qa/ssl-insecure/qa-scenario-1a.yaml
scripts/scenarios/cloud6/qa/ssl-insecure/qa-scenario-1b.yaml
scripts/scenarios/cloud6/qa/ssl-insecure/qa-scenario-2a.yaml
scripts/scenarios/cloud6/qa/ssl-insecure/qa-scenario-2b.yaml

Needed due compatibility with cloud 7 in upgrade process

Change number of replicas to 2 in swift config 

---

scripts/scenarios/cloud6/qa/no-ssl/qa-scenario-1a.yaml
scripts/scenarios/cloud6/qa/no-ssl/qa-scenario-1b.yaml

The replicas attributes were put into incorrect barclamp sections by mistake in [previous PR](https://github.com/SUSE-Cloud/automation/pull/1715).

Use correct replicas configuration in swift for QA scenarios

---

scripts/qa_crowbarsetup.sh

qa_crowbarsetup: allow smaller MTU values
than the default 1500
instead of silently ignoring those
change is needed for
https://etherpad.nue.suse.com/p/multi-vmhost-crowbar
with Linux multicast-VXLAN

qa_crowbarsetup: allow smaller MTU values

---

scripts/qa_crowbarsetup.sh

this avoids issues such as
https://github.com/SUSE-Cloud/automation/pull/1729
breaking deployment of GM7 that does not include
the required crowbar-openstack code

qa_crowbarsetup: only enable ssl if available

---

jenkins/ci.suse.de/cloud-trackupstream.yaml
scripts/mkcloud
scripts/qa_crowbarsetup.sh

The term HCP should no longer be used. Instead we rename it to SAP who is working on this fork.
This PR depends on PR #1740 but could be merged any time.

rename HCP to SAP

---

scripts/qa_crowbarsetup.sh

This was removed by https://github.com/SUSE-Cloud/automation/pull/1736

Cloud 7 updates repo is needed when doing Cloud6->7 upgrade

---

jenkins/ci.suse.de/cloud-mediacheck.yaml
jenkins/ci.suse.de/cloud-trackupstream.yaml

This enables jtsync for cloud-mediacheck and cloud-trackupstream.
Note: This will only set the status if the build was not triggered manually.
__This pr depends on features of https://github.com/SUSE-Cloud/automation/pull/1616 do not merge before__

Enable jtsync for cloud-mediacheck and cloud-trackupstream

---

scripts/lib/libvirt/compute-config
scripts/lib/mkcloud-libvirt.sh
scripts/mkcloud

When using the script manually to setup a compute/controller node,
make most of the needed parameters optional. This simplifies the call
and also makes it more exclicit which parameter is for what.
Having all parameters as positionals is ugly.

Make node setup params optional

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-test-pacemaker-cts.yaml

Pacemaker-CTS thoroughly exercises a pacemaker cluster by running a randomized series of predefined tests on the cluster. We need to add this scenario to make sure that our cloud doesn't have problems with clusterization.

Add pacemaker-cts test scenario

---

jenkins/ci.suse.de/openstack-mkcloud.yaml
scripts/qa_crowbarsetup.sh

Domain-specific identity backends can be configured to enable the same
functionality as the hybrid backend, so let's start testing it.
LDAP users are now in their own domain so we have to specify that domain
when looking up users. Moreover, keystone builds its own ID mapping for
LDAP users so their suseid is no longer a visible attribute from
openstack.
This depends on https://github.com/crowbar/crowbar-openstack/pull/860 and will not work until that is merged.

keystone: Test LDAP configuration on cloud 7

---

scripts/qa_crowbarsetup.sh

I need #1417 for cloud 6 also, we hit https://bugzilla.suse.com/show_bug.cgi?id=1008331 a lot in maintenance

qa_crowbarsetup: Do not deploy calamari on SOC6

---

scripts/lib/libvirt/compute-config
scripts/lib/libvirt/fixtures/cloud-admin-uefi.xml
scripts/lib/libvirt/fixtures/cloud-admin.xml
scripts/lib/libvirt/fixtures/cloud-node1-raid.xml
scripts/lib/libvirt/fixtures/cloud-node1-uefi.xml
scripts/lib/libvirt/fixtures/cloud-node1-xen.xml
scripts/lib/libvirt/fixtures/cloud-node1.xml
scripts/lib/libvirt/libvirt_setup.py
scripts/lib/libvirt/templates/compute-node.xml
scripts/lib/libvirt/templates/net-interface.xml
scripts/lib/libvirt/test_libvirt_setup.py
scripts/lib/mkcloud-common.sh
scripts/lib/mkcloud-dirmaint.sh
scripts/lib/mkcloud-libvirt.sh
scripts/mkcloud

This is useful to test real world setups where nodes do have multiple
nics.
Setting the new variable $nics (defaults to 1) generates $nics network
interfaces per node.

Allow multiple nics for controller and compute nodes

---

scripts/mkcloud

Otherwise it fails only after the admin node has been prepared.

Fail when cloudbr-derived names exceed IFNAMSIZ

---

scripts/qa_crowbarsetup.sh

When using LDAP as a keystone identity backend it is useful to allow
keystone to look up groups in LDAP so that LDAP groups can be given
automatic project assignments, negating any need for an administrator to
give assignments to individual LDAP users. This patch adds the necessary
settings to the keystone proposal to allow keystone to be aware of
groups in LDAP. It changes the user_id_attribute to 'uid' because that
is the attribute LDAP itself uses to determine group membership, but
this change means that the old 'hybrid' method will use 'uid' rather
than 'suseid' as the keystone user ID. We also add a smoke check to make
sure that keystone can find groups and understands group membership as
defined in LDAP.

Enable keystone groups searching in LDAP

---

jenkins/ci.suse.de/openstack-mkcloud.yaml
scripts/jenkins/log-parser/openstack-mkcloud-rules.txt

Take advantage of the Jenkins Log Parser plugin:
- https://wiki.jenkins-ci.org/display/JENKINS/Log+Parser+Plugin
This requires a patch to jenkins-job-builder in order for the per-project rules to be correctly activated during upload of the job to Jenkins:
- https://review.openstack.org/#/c/445509/
(However, it should not break anything if the patch is not applied.)
Once correctly configured, when viewing a job in the web UI, you can click on "Parsed Console Output" to see a nice analysis of the errors and warnings, broken down by mkcloud section.  Note that #1755 has already been merged to help clean up this UI.
Also remove the email publisher which breaks with the latest `jjb`.

Make use of Jenkins Log Parser plugin

---

jenkins/ci.suse.de/openstack-mkcloud.yaml

Allow to set the clusterconfig variable that gets passed to the mkcloud script.
While any parameters can be set when a job gets triggered, the unsupported ones are hidden when a job is rebuilt.
This also solves to build the jobs with the SAP configuration.

mkcloud: support clusterconfig

---

scripts/mkcloud

This is to allow to run cleanup without having to set cloudsource and other required parameters.
The handling of this is unified with the help, usage and step functions.

mkcloud: skip sanity checks for cleanup, help and steps

---

jenkins/ci.suse.de/cloud-mkcloud6.yaml
jenkins/ci.suse.de/cloud-mkcloud7.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-2nodes-tempestfull-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-2nodes-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-4nodes-linuxbridge-tempestfull-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-4nodes-linuxbridge-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-backup-restore-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-btrfs-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-crowbar-devsetup-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-crowbar_register-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-devel-storage-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-devel-virt-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-docker-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-dvr-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-compute-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-linuxbridge-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-hyperv-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-magnum-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-many_compute-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-raid-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-ssl-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-uefi-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-disruptive-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-nondisruptive-ha-dvr-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-nondisruptive-ha-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-nondisruptive-ha-without-nodes-upgrade-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-xen-template.yaml

allow to disable projects with a quick switch in jjb
Templates set the variable disabled=true to disable an entire project. The jobs are still there and deployed.
This helps when resouces are low or the workers of an additional arch are not available - they can be disabled now with a small change to the project configuration in jjb.

Job enablement refactoring

---

jenkins/ci.opensuse.org/openstack-diskimage-builder.yaml
jenkins/ci.opensuse.org/openstack-repocheck.yaml

openSUSE 13.2 is no longer maintained, see
https://en.opensuse.org/Lifetime#Discontinued_distributions

Drop openSUSE 13.2

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-2c.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-2c.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-2c.yaml

Extend all 2c scenario to use both linuxbridge and ovs with vlan + vxlan neutron drivers.

Extend 2c scenario

---

scripts/heat/ping_template.sh

The cinder test script was ending abruptly for no reason. A trap capture has been put in place to prevent that behavior, the same way the other scripts do.
Additionally a mechanism to allow for recovery when the cinder volume is not attached on time has been added.
The use of `sudo` to write the output file has been added mainly to support debugging on cloud7, since on cloud6 that wasn't necessary.

fixes for cinder tests

---

scripts/jenkins/qa_openstack.sh

This is needed by some Java packages such as Apache Storm (needed by Monasca).
Without this `/etc/hosts` entry they will fail to start because they cannot resolve the
machine's own host name.

Add machine's host name to /etc/hosts

---

scripts/qa_crowbarsetup.sh

which does not change when expiry value changes
follow-up on #1767

qa_crowbarsetup: rely on repo key fingerprint

---

scripts/mkcloud

This reverts commit 2e75e274af462518277ac32f7e31d2d413806649.

Revert "mkcloud: fix cloudbrlimit due to merge of PR #1750"

---

hostscripts/soc-ci/soc-ci

There is no mkchj host available so do not try to connect to it.

soc-ci: Remove j host

---

jenkins/ci.suse.de/macros.yaml

We're planning to use a new wrapper for build names, so ` #478 develcloud6` will become `#478 develcloud6 - qa3 linuxbridge:vlan`

Add a new wrapper for build names
