SUSE-Cloud/automation

scripts/qa_crowbarsetup.sh

ldappool significantly speeds up LDAP requests[1] so it's a good idea to use
it. We weren't using it before because there was a bug making it incompatible
with the use_ssl parameter[2]. The bug has been fixed but not released, but we
can use LDAPS rather than StartTLS and avoid the problem entirely.
[1] https://www.mattfischer.com/blog/?p=624
[2] https://review.openstack.org/#/c/443264/

Use ldappool with keystone LDAP backend

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-1b.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-1b.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-1b.yaml

Extend 1b scenario to use both linuxbridge and ovs with vlan + vxlan neutron drivers.

Extend 1b scenario

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-1a.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-1a.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-1a.yaml

Extend 1a scenario to use both linuxbridge and ovs with vlan + vxlan neutron drivers.

Extend 1a scenario

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

When testing the upgrade from 6 to 7 we need to use a cinder backend that doesn't use storage that is located on any of the cloud nodes (or the admin node) to have it available during the whole upgrade process. This PR adds the ability to have mkcloud setup a "lonelynode" with an NFS server running that is exporting /srv/nfs/cinder.

Allow to setup an independent nfsserver for cinder

---

scripts/qa_crowbarsetup.sh

to circumvent https://bugs.launchpad.net/python-openstackclient/+bug/1501362

use imageid instead of image name for lookup

---

scripts/qa_crowbarsetup.sh

Add ceilometer to the list of barclamps with SSL testing options.
Depends on: [Ceilometer: add ssl support](https://github.com/crowbar/crowbar-openstack/pull/871)

ceilometer: enable SSL testing

---

jenkins/ci.suse.de/cloud-automation-pr-trigger.yaml
jenkins/ci.suse.de/cloud-cct-pr-trigger.yaml
jenkins/ci.suse.de/cloud-crowbar-sap-testbuild-pr-trigger.yaml
jenkins/ci.suse.de/cloud-crowbar-testbuild-pr-trigger.yaml
jenkins/ci.suse.de/cloud-update-ci.yaml

to allow having more than one, allowing for easy maintenance
When this is merged and deployed, we can enable again
https://ci.suse.de/computer/cloud-swarm-p1cloudtrigger/

jenkins: allow trigger jobs to run on other cloud trigger nodes

---

jenkins/ci.suse.de/openstack-mkcloud.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-nondisruptive-ha-dvr-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-nondisruptive-ha-template.yaml

With https://github.com/SUSE-Cloud/automation/pull/1766 we're able to deploy cinder using the nfs backend. This adapts the mkcloud job to utilize that in the jenkins jobs.

Make "nfs" a valid cinder_backend choice for the mkcloud job

---

scripts/jenkins/log-parser/openstack-mkcloud-rules.txt

We exclude some warnings which we know are fine in an mkcloud context.

make Jenkins Log Parser plugin check for warnings

---

scripts/lib/mkcloud-libvirt.sh

so that virsh net-start succeeds
problem is that the systemd-managed dnsmasq binds port 53 on the any address
0.0.0.0:53
:::53
but we need it available for libvirt's dnsmasq

mkcloud: disable dnsmasq in setuphost

---

scripts/qa_crowbarsetup.sh

The cinder-ha backend wasn't tested, and as yet another proof
of the common saying of "if it's not tested then it's broken",
it actually was broken.

qa_crowbarsetup.sh: Use cinder-HA when ceph backend is chosen

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-9.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-9.yaml

Extend 9 scenario to use both linuxbridge and ovs with vlan + vxlan neutron drivers.

Extend 9 scenario

---

jenkins/ci.suse.de/openstack-mkcloud.yaml

When the Log Parser Plugin sees warnings, it marks the build as unstable which causes yellow icons instead of green.  That doesn't really help us, especially considering that `openstack-mkcloud` will never stabilise (because it's covering an enormous range of scenarios of vastly different degrees of stability) so disable it.

stop Log Parser Plugin marking builds unstable on warning

---

scripts/mkcloud

This builds on #1785, since it is not just the upgrade runs that are
having issues but the general hacloud scenario as well.

ha: Clean up expected vip failed actions

---

scripts/jtsync/jtsync.rb

to allow easier debugging of problems that are otherwise just reported as
`undefined method '[]' for nil:NilClass`

jtsync: do not hide backtrace

---

scripts/lib/mkcloud-common.sh
scripts/mkcloud
scripts/qa_crowbarsetup.sh

Use all SLE12 repos (pool + updates) from one configurable smturl. 
This makes use of mkcloud much easier for users having smt repos inhouse.

added new variable $smturl and use it for all SLE >= 12 Product/Update repos

---

jenkins/ci.suse.de/openstack-mkcloud.yaml

Try to bring some order back into this insane mess:
- group parameters more logically
- fix indentation
- tidy up some description strings and reduce line lengths
The new job can be previewed at https://ci.suse.de/job/openstack-mkcloud-reordered/build
In the future, hopefully we can use
https://wiki.jenkins-ci.org/display/JENKINS/Parameter+Separator+Plugin
so clearly delimit each section.  I have also submitted
https://issues.jenkins-ci.org/browse/JENKINS-43070
with the goal of being able to name each section delimited by a separator.

tidy up openstack-mkcloud YAML

---

scripts/mkcloudhost/cloudfunc
scripts/mkcloudhost/routed.cloud
scripts/mkcloudhost/runtestn

by dropping /root/cloud.d/
in favour of using cloudfunc from the same dir (usually a git checkout)
and /etc/mkcloud/cloudrc.host
with fallbacks for existing systems

mkcloud/host: allow to run as non-root

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

We only want to clean up two specific resources that we expect to have
failed, this is not a general "make all the problems go away" method, so
let's rename it to make it more clear.

Rename the crm cleanup method

---

jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-nondisruptive-ha-without-nodes-upgrade-template.yaml

The default valye of want_nodesupgrade has changed to 1 recently,
so we need to unset it here.
Here was the change: https://github.com/SUSE-Cloud/automation/pull/1799

Job that is upgading just admin server should unset nodes variable

---

scripts/qa_crowbarsetup.sh

Enable auto-refresh for the zypper PTF repositories
to avoid using stale repository contents when executing
the update barclamp.

qa_crowbarsetup: auto-refresh for PTF repos (bsc#1030462)

---

scripts/scenarios/cloud6/cloud7-upgrade-non-disruptive-ceph.yml

See https://ci.suse.de/job/openstack-mkcloud/57549/consoleText

cinder's secret_uuid is required for ceph backend

---

jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-disruptive-template.yaml

The job fails because of number of swift replicas is bigger than number of disks
See https://ci.suse.de/job/openstack-mkcloud/57546/consoleText
(which is wrong for Cloud7, but current mkcloud code does not set replica number for Cloud6)

Raise the number of nodes so that default swift replica count is correct

---

scripts/mkcloud

If the mkcloud environment runs into a failure, stop the periodic chef-client
run on all nodes.
This is useful to not alter the environment where the failure happens. Sometimes
there is a failure and the periodic chef-client run fixes the failure afterwards
which makes it more difficult to debug problems in the failed environment.

mkcloud: Stop chef-client on nodes after a failure

---

jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-disruptive-template.yaml

It seems that due to a very old version of swift in cloud6
we cannot change the default number of replicas so it will
always default to 3. Using a nodenumber count of 3 makes the
default number of nodes assigned to the swift-storage role to be
2 which doesnt sync with the required number of replicas, causing
the upgrade prechecks to fail.
Setting the nodenumber to 4 makes the default number of swift-storage
nodes to be 3, making the upgrade prechecks pass.

Raise the nodenumber so the default swift replica count is correct

---

scripts/jenkins/log-parser/openstack-mkcloud-rules.txt
scripts/mkcloud
scripts/qa_crowbarsetup.sh

Fix 4 sources of false positives in the `Errors` section of the log parser plugin when parsing output of the `openstack-mkcloud` job.

Fix false positives in log parser plugin

---

scripts/qa_crowbarsetup.sh

It seems we are consistently failing them on all old products. lets
aim low by first getting it right for C7 and ignore the existing
problems for C5/C6.

Disable cluster resource failcount tests for C6 and older

---

jenkins/ci.opensuse.org/heat-templates/deploy-cleanvm.sh
jenkins/ci.opensuse.org/heat-templates/openstack-cleanvm.yaml

The commits in this pull request
* Add the `package_repo` parameter that allows you to inject a package repository URL with customized packages you want to test (e.g. a branch of `Cloud:OpenStack:Newton:Staging` in your home project).
* Update the Heat template to run a Newton based cleanvm job by default.

Cleanvm Heat template: custom package repository and update for Newton

---

scripts/qa_crowbarsetup.sh

Missing the get_novacontroller function before running
scripts on the controller. Also adds safely to the calls.
PR affected was merged without testing as I didnt set the proper label so this was not working. 
This one is tested and works, sorry for the inconvenience.

Fix suspend/resume instances during upgrade

---

scripts/qa_crowbarsetup.sh

Cloud upgrade does a ceph health check at the start but ceph
could report some minor health problems initially after it is upgraded.
See this job https://ci.suse.de/job/openstack-mkcloud/58107/consoleText . It fails with ceph not being health but when I ssh and repeat the test, it is already fine.

Wait a bit after ceph upgrade so the health check succeeds

---

scripts/qa_crowbarsetup.sh

The group_members_are_ids LDAP parameter wasn't added until f9e5076d in
SOC 7, so trying to use it in SOC 6 results in a crowbar proposal
error. This patch moves the parameter so that it is only used with SOC
7.

Fix LDAP parameters for SOC 6

---

scripts/qa_crowbarsetup.sh

The local variable 'l' is set differently for SOC 7, so it needs to be
set before we try to use it. This should correct the LDAP group
membership test issues[1].
[1] https://ci.suse.de/job/openstack-mkcloud/58297/console

Fix ordering of LDAP proposal value setting

---

scripts/lib/mkcloud-libvirt.sh

This was missed from the recent changes to support non-root usage.

add missing sudo to lvmdiskscan invocation

---

jenkins/ci.suse.de/cloud-mkcloud7.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-nondisruptive-ha-lbaasv2-template.yaml
scripts/scenarios/cloud6/cloud7-upgrade-non-disruptive-lbaasv2.yml

In order to be able to test the LBaaSv2 related parts of the upgrade we
need to deploy cloud 6 with LBaaSv2 enabled (it's still defaulting to v1).
This jobs is using the NFS backend for cinder and switches the neutron
mechansim driver to "linuxbridge".

New upgrade job with LBaaSv2 enabled

---

scripts/crowbar-testbuild.rb
scripts/crowbar-testbuild.yaml

The redeployment of our CI on the SAP side requires our tools to be more flexible and configurable to allow them to be run in different environments.
Making crowbar-testbuild configurable needed to touch almost every line of the code.
Thus it was a good opportunity for a clean rewrite in ruby.
The new script will be merged first, then a temporary test job will do more test runs, then the old job will be switched to the new script.

crowbar-testbuild: rewrite in ruby, fully configurable

---

scripts/mkcloud

this should allow to run mkcloud with default settings for a non-root run while keeping the defaults for the root user

mkcloud: set log_dir to ./log by default if running as non-root

---

scripts/qa_crowbarsetup.sh

when we want to use test updates, we also need to enable the SDK
test updates channel otherwise we run into inconsistencies that
cause cct runs to fail.

add SP2 test updates in case SLES test updates are enabled

---

scripts/qa_crowbarsetup.sh

crowbarctl has a five minutes timeout when committing proposals, and
this change basically kills a good part of our CI because of timeouts.
This reverts commit b333958684cb9e7b4dfc3fc01cc1d77b6e4594a8.

Revert "qa_crowbarsetup: use crowbarctl to commit proposals"

---

scripts/qa_crowbarsetup.sh

Due to onadmin_cleanup_db_mq_vips seemingly restarting the db/rpc
services on the resource cleanup, the heat-api may be unavailable
for some time after the cleanup.
This introduces a little wait before creating the heat stack to
see if the heat api is up and running correctly

Check for heat api availability before creating the heat stack

---

scripts/lib/libvirt/libvirt_setup.py

We are comparing against the name method instead of
calling it, thus get_domain_by_name is always returning nothing.
This may be why the cloud-mkcloudX-job-backup-restore-x86_64 jobs are failing.
```
mkche:~ # python
Python 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import libvirt
>>> l = libvirt.open("qemu:///system")
>>> [d.name for d in l.listAllDomains()]
[<bound method virDomain.name of <libvirt.virDomain object at 0x7f07da604090>>, <bound method virDomain.name of <libvirt.virDomain object at 0x7f07da6040d0>>, <bound method virDomain.name of <libvirt.virDomain object at 0x7f07da604110>>, <bound method virDomain.name of <libvirt.virDomain object at 0x7f07da604150>>, <bound method virDomain.name of …
```

Fix wrong call to name method

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-test-upgrade-ui.yaml
scripts/qa_crowbarsetup.sh

* using the heat template file from mkcloud
* heat template parameters added to use fixed network on QA clouds
* ping the VMs from the gate when the upgrade is running

Add workload to cloud for QA upgrade job using UI

---

jenkins/ci.suse.de/openstack-mkcloud-log-parser-test.yaml
jenkins/ci.suse.de/openstack-mkcloud.yaml
scripts/jenkins/log-parser/openstack-mkcloud-rules.txt

When openstack-mkcloud is testing PRs, it does a
git --no-pager show
to show the changes in the PR being tested.  However if the changes, or even the context around the changes, mentions something like `error` or `fail` or `fatal` then the Log Parser plugin will incorrectly flag this as a false positive.  So we indent the `git show` output by a unique prefix and then configure the plugin to ignore anything with that prefix.

ignore output of "git show" when testing PRs

---

jenkins/ci.suse.de/openstack-mkcloud.yaml

so that the git merge will not fail from their absence
change is partially tested (the lines work in bash on another git repo)

jenkins/mkcloud: configure user+email

---

scripts/lib/mkcloud-libvirt.sh

this code was added in commit 6cfe0bee3
and is probably obsolete now with the more general cleanup code
in recursive_remove_holders

leave the drbd cleanup to recursive_remove_holders

---

scripts/qa_crowbarsetup.sh

automatically when using a proxy
so that the corporate proxy will not send stupid HTML
instead of the JSON we expect

qa_crowbarsetup: add localhost to no_proxy variable

---

scripts/lib/mkcloud-libvirt.sh

because the rpm -q shortcut will not find a 'kvm' package
and then try to install kpartx and fail, because of the lock
for https://bugzilla.suse.com/show_bug.cgi?id=1033541
example failure without this:
https://ci.suse.de/job/openstack-mkcloud/59906/console

mkcloud: look for qemu-kvm on SLE12

---

jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-nondisruptive-ha-ceph-compute_ha-template.yaml
scripts/scenarios/cloud6/cloud7-upgrade-non-disruptive-ceph-compute_ha.yml

It's almost same as the upgrade-ceph job, only change is that the compute nodes have remote role

Add a job for non-disruptive upgrade with compute HA nodes

---

jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-nondisruptive-ha-ceph-compute_ha-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-nondisruptive-ha-ceph-template.yaml

The mkcloud deployment starts the first $#services nodes of clusterconfig
(which is two here) with higher memory settings (the controller mem
settings). So we should assign the controller aliases to the first two
nodes.

put controller nodes first

---

jenkins/ci.suse.de/cloud-crowbar-sap-testbuild-pr-trigger.yaml

This enables the trigger job, to run all PRs of the sap-oc organization.

cloud-crowbar-sap-testbuild-pr-trigger: enable job

---

jenkins/ci.suse.de/cloud-crowbar-testbuild-pr.yaml

This will allow to finally enable all SAP PR builds with the existing trigger job (next PR)

crowbar-testbuild: switch to new implementation of crowbar testbuild

---

scripts/jenkins/qa_openstack.sh

This change makes the default cinder and manila volumes configurable
through exported environment variables which makes it easier to change
those defaults.

Make cinder and manila devices more configurable

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

Monasca needs 10+GB of memory to start up, so we need
to allocate a second controller VM for it to succeed.

Allocate a bigger ("controller") VM for monasca

---

jenkins/ci.suse.de/openstack-mkcloud.yaml

because by default sudo clears all env vars that are not whitelisted
in /etc/sudoers

jenkins/mkcloud: pass ZYPP_LOCK_TIMEOUT through sudo

---

scripts/jenkins/qa_openstack.sh

Added verbose output for debugging to `qa_openstack.sh`. The output is
disabled by default and is enabled when the `debug_openstack` variable
is set to `1`.

Verbose output

---

scripts/lib/mkcloud-common.sh
scripts/mkcloud
scripts/qa_crowbarsetup.sh

if want_mtu_size is default and not set in env, it gets not passed from mkcloud to qa_crowbarsetup.sh, so we need to check if the variable is set

default want_mtu_size not passed to qa_crowbarsetup

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

Currently, we check the crm failure report during the testsetup phase to
make sure that nothing in the deployment caused any resources to hiccup.
This is great for telling us that something went wrong, but because our
logs from supportconfig are truncated, we often can't get enough
information to see what happened on the system at the time the failure
occurred. This patch adds the check during the proposal phase after each
proposal starting with the nova proposal is applied. This way, if an
error occurred during the application of a proposal (whether the error
was caused by the proposal or not) the automation run will terminate and
the supportconfig generated should have relatively recent logs to
examine.  The reason this is only applied for proposals that come after
the nova proposal is …

Fail fast(er) on crm failures

---

jenkins/ci.opensuse.org/openstack-trackupstream.yaml

Enable tracking for those monasca packages that contain a _service file.

trackupstream-openstack: Track monasca packages

---

jenkins/ci.opensuse.org/openstack-trackupstream.yaml

It is python-monasca-common and python-monasca-statsd because both
packages do not contain any services.

trackupstream-openstack: Fix some monasca names

---

scripts/crowbar-testbuild.rb
scripts/crowbar-testbuild.yaml

The parameters may differ if the build service projects are setup differently (e.g. at sap).
@tpatzig This adds the support to change the parameters for any osc subcommand that might be used in the testbuild script (yes you can create a new section for a subcommand and it will be used). Please have a look and maybe a testrun on your system (hint: see the changed config yaml).

crowbar-testbuild: support custom osc parameters

---

scripts/qa_crowbarsetup.sh

For maintenance / update testing we'd like to avoid downgrading
to versions that are embedded in the Cloud media. However we still
want to allow upgrading in case we build a media with something newer
for trying out.

qa_crowbarsetup.sh: avoid downgrades when preparing the admin node

---

jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-nondisruptive-ha-lbaasv2-template.yaml

The job uses scenario which does not deploy swift.
But the storage_method variable sets deployswift to 1 (although no
swift is actually deployed) and this in turn leads testsetup step
to do some swift testing, which obviously fails.
See e.g. swift test failures in this job https://ci.suse.de/job/openstack-mkcloud/60929/consoleText

Do not pass swift storage method to lbaas job

---

scripts/qa_crowbarsetup.sh

allowing ldap users to log into horizon using domain `ldap_users`

qa_crowbarsetup: enable horizon multidomain

---

scripts/qa_crowbarsetup.sh

to be used as a separate mkcloud step

qa_crowbarsetup: split off onadmin_zypper_update function

---

scripts/lib/mkcloud-common.sh
scripts/qa_crowbarsetup.sh

this reverts the previous attempt from commit 20681e75a
which did not work, because at the time we source mkcloud-common,
the config from the mkcloud host is not yet sourced
thus we do not yet have the want_ceilometer_proposal value

qa_crowbarsetup: handle service deps later

---

scripts/qa_crowbarsetup.sh

otherwise the 2nd apply will fail
because duplicate nodes are not allowed

qa_crowbarsetup: make pacemaker proposal idempotent

---

scripts/qa_crowbarsetup.sh

When SSL is turned on, the RadosGW server uses port 8081[1][2] and does
not listen on port 8080. Hard-coding 8080 as the connection port was
causing the RadosGW tests to fail when SSL was turned on[3]. This patch
makes the port number conditional on whether SSL is being used so that
the test bucket can successfully be created even in an SSL environment.
[1] https://github.com/crowbar/crowbar-ceph/blob/d290aaca5cddd4539e512355b26efe9ddbe99397/chef/cookbooks/ceph/recipes/conf.rb#L48
[2] https://github.com/crowbar/crowbar-ceph/blob/2bce1372a2e6aba8570d0f30f3cab88839d09d5c/chef/cookbooks/ceph/attributes/radosgw.rb#L22
[3] https://ci.suse.de/job/openstack-mkcloud/61042/

ceph: Fix radosgw port for SSL

---

scripts/qa_crowbarsetup.sh

Some of our installed images, SLES12 SP2, for instance, do not ship with
patch installed, but the current code seemed to assume it will always be
available. Check if patch is available, and install it if it isn't.

Install patch if patching network.json

---

scripts/mkcloud

fix calling for functions
that can get optional params,
otherwise it would be called with the function name as only param
instead of no param

mkcloud: fix calling for functions

---

scripts/mkcloud

When there is an error on package installation (because
of some repo being outdated or a libzypp update not yet installed)
mkcloud goes into a long-windling death due to trying to collect
supportconfig from everything below the horizon. Skip that.

Fix setuphost on a pristine but broken host

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

For various use cases we were asked to support to add updaterepos after the deployment.
This PR adds support for this via the existing addupdaterepos function.
When called without parameter (like in regular deployments) all repos from the variable $UPDATEREPOS are added to the PTF repo.
When called later (or at any time, repeatedly) with a parameter (n, integer > 0) the first n repos from the variable $UPDATEREPOS_EXTRA are added to the PTF repo. The variable is not changed. So the parameter has to increase to successively add content to the PTF repo.
If the parameter is 0 or 'all' then all repos from the variable $UPDATEREPOS_EXTRA are added.
Intended usage e.g.: `mkcloud all addupdaterepo+2 onadmin+zypper_update onadmin+cloudupgrade_clients testsetup`

support to add additional updaterepos after deployment

---

scripts/mkcloud

When clouddata.nue.suse.com is unreachable, mkcloud complained in a
confusing way about the fact that the clouddata variable was not set.
Provide a more meaningful error message when this happens.

Provide meaningful message when clouddata unreachable

---

jenkins/ci.suse.de/cloud-mkcloud7-job-simpletest-s390x.yaml

SLE12 images needs to be upgraded and recaptured, but meanwhile we need
to upgrade them via the updater barclamp to fix some bugs in the named
service.

simpletest-s390x: upgrade nodes via updater barclamp

---

scripts/lib/libvirt/fixtures/cloud-node1-raid.xml
scripts/lib/libvirt/fixtures/cloud-node1-uefi.xml
scripts/lib/libvirt/fixtures/cloud-node1.xml
scripts/lib/libvirt/libvirt_setup.py

because we use vda+vdb for the RAID
and disk sizes usually do not match up
and get rid of the unreliable string manipulation logic

libvirt_setup: make sure RAID disks are before others

---

scripts/qa_crowbarsetup.sh

we need to wait for the api to be available before interacting with it for the client upgrade, because crowbar might still be in restarting mode from a previous update/upgrade

Wait for crowbar api in clientupgrade

---

scripts/qa_crowbarsetup.sh

When configuring the manila-service project, export in addition to
OS_TENANT_NAME also OS_PROJECT_NAME. OS_TENANT_NAME is deprecated and
should be removed in the future.

qa_crowbarsetup: export also OS_PROJECT_NAME

---

scripts/qa_crowbarsetup.sh

Currently, when an error occurs during a remote command, the exit code
from the ssh call is captured and returned without affecting the
deployment. We really do want the deployment to stop when errors are
detected, so this patch wraps the crm checks with 'safely' so that
errors cause the run to abort and supportconfigs collected.

ha: Really abort when crm failures are detected

---

scripts/qa_crowbarsetup.sh

due to https://bugs.launchpad.net/python-openstackclient/+bug/1501362
Added option `--os-image-api-version 1` as fallback `openstack image show`

image cannot be found by name with openstackclient and glance v2 api

---

jenkins/ci.suse.de/openstack-mkcloud.yaml

When a build fails, usually the first thing we want to know is why it failed.  The parsed console is the quickest way of finding this out, so jump directly to it instead of requiring an extra click.

linked to parsed console for failed builds

---

docs/basic-mkcloud-config.sh
mkcloudruns/mkcloudconfig/SUSECloud.mkcloud

PARALLEL is no longer needed and supported

doc: drop obsolete variables from documentation

---

hostscripts/clouddata/syncSLErepos

to always have a consistent repo synced
and delete-delay instead of delete-after
in order to use the more efficient recursion algorithm

syncSLErepos: use delay-updates

---

scripts/qa_crowbarsetup.sh

We want to set the MTU of all those networks to the $want_mtu_size var
as we want to allow setting up the custom MTU for all netwroks trougth
the network cookbook.
Not setting it would make the controller tests fail to ping the admin
as the mtu size set for the br-fixed iface would be too low.
Fixes https://github.com/crowbar/crowbar-core/pull/1087 mkcloud runs

Set mtu of public/nova_fixed/nova_floating networks

---

scripts/mkcloud

Add $UPDATEREPOS_EXTRA to the environment details printed in
show_environment. This helps with debugging when an mkcloud run fails.

Print $UPDATEREPOS_EXTRA in show_environment

---

hostscripts/clouddata/syncSLErepos

might be needed for SOC8
and is already used on mkchm now

clouddata: also sync SP3 repos

---

scripts/qa_crowbarsetup.sh

Lets just add an explicit hook for monasca. currently
there is nothing to do.

Avoid the "no hooks defined" message for monasca

---

scripts/lib/mkcloud-common.sh
scripts/lib/mkcloud-dirmaint.sh
scripts/lib/mkcloud-libvirt.sh
scripts/mkcloud
scripts/mkcloudhost/routed.cloud
scripts/qa_crowbarsetup.sh

The variable clouddata and its derivatives originate from the fact that all services we need for a cloud deployment are offered on one single host - for us at SUSE.
There are however other users of mkcloud who use services on existing servers. So we need to be able to configure the hostnames by service and not by assumptions which services are combined.
This PR will drop the variable `$clouddata` (still being backwards compatible and using its values, if it was set) and introduce one variable per service (nfs, repo(http), rsync, smt).
The new variables can be set to IPs or hostnames. mkcloud-common will compute the missing part on its own.
The idea is:
$reposerver, $nfsserver, $rsyncserver and $smtserver are only set from outside.
They can be set to an IP or a hostname. But these …

kill clouddata variable

---

scripts/qa_crowbarsetup.sh

for GM6(+up) targets we don't have a valid TEST ISO

Avoid false warning when TESTISO isn't set

---

scripts/qa_crowbarsetup.sh

This code block was disabled with commit:
ea43af427add52bebc077f3cf73dacf849b8f5a9
when we switched to stonith mode "libvirt".

qa_crowbarsetup: drop dead code for pacemaker setup

---

jenkins/ci.opensuse.org/openstack-trackupstream.yaml

The monasca packages are in upstream packaging, so running
trackupstream on it doesn't work. Also they're not in mitaka, so
those are skipped as well.

Stopping trackupstream for mitaka and master for monasca

---

scripts/qa_crowbarsetup.sh

for version 6plus
Without this change the 5plus would grab everything
and then try to add 'SLE11-HAE-SP3-{Pool,Updates}' repos
which dont exist on 6plus

qa_crowbarsetup: fix HA repo handling

---

scripts/qa_crowbarsetup.sh

Commit b4a2cb3e accidently removed a backslash when changing the
add_mount call, add it back.

Add missing backslash in add_ha_mount

---

jenkins/ci.opensuse.org/openstack-repocheck.yaml
jenkins/ci.opensuse.org/openstack-trackupstream.yaml

Juno* is no longer maintained, and Leap 42.1 is end of life. Add
Leap 42.3 instead for checks.

Update repocheck to only track currently maintained distributions

---

jenkins/ci.suse.de/openstack-mkcloud.yaml
scripts/mkcloud
scripts/qa_crowbarsetup.sh

Introduce a new 'crowbar_networkingmode' variable which defaults to 'single'.
When set to 'team' ('nics' variable must be > 1 then), mkcloud deploys the cloud
with a bonding network setup. This is useful for testing more complex (and more
realistic) scenarios.
Note: The crowbar node itself has no bonding enabled. Our current mkcloud setup
gives the crowbar node only a single nic (even if 'nics' > 1). That's why this
commit adds an extra entry to the conduit_map for the crowbar node.
It can be used to set the Crowbar networking mode which can be 'team' which
does bond multiple interfaces.
This is useful for testing more realistic scenarios where multiple interfaces
are used together.

mkcloud: Allow custom crowbar networking mode

---

scripts/qa_crowbarsetup.sh

This is a hotfix solution for issue #1947
It fixes the overwrite problems described in the issue by moving the
problematic code blocks from step 'prepareinstallcrowbar' to
'bootstrapcrowbar', thereby delaying the change to the crowbar template
after it was updated in the 'runupdate' step.

Do not change crowbar templates during prepareinstallcrowbar

---

jenkins/ci.suse.de/templates/cloud-mkcloud-job-4nodes-linuxbridge-template.yaml

The last Ceph update for SLE12SP1 broke the ceph packages

Temporally disable test repo for 4nodes-linuxbrige jobs

---

scripts/qa_crowbarsetup.sh

because it will redirect to closest mirror.
This way, $distsuse is only used for NFS

qa_crowbarsetup: use download.nue.suse.com for HTTP

---

scripts/lib/mkcloud-common.sh

The `nfs_base_path` needs a leading `/`, otherwise the mount command
will fail.

mkcloud: Add leading '/' in nfs_base_path

---

jenkins/ci.suse.de/cloud-mkcloud7-suse.yaml

Currently it was only triggering on a Cloud7 GM media rebuild, which
doesn't make sense because it doesn't happen very often anymore.

Trigger the cloud7-suse job daily

---

jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-ironic-template.yaml
scripts/qa_crowbarsetup.sh
scripts/scenarios/cloud7/cloud7-ironic-basic-ha.yml

Ironic will not work with default proposals as compute service config needs to be different from the one for VMs. Ironic also requires special networking setup (network proposal).
Additionally the job setup was modified to better suit Ironic:
- 1 compute node is enough as nova-compute-ironic is just a proxy
- 2 node HA cluster for controllers
- 2 'baremetal' nodes for ironic instances
- split mkcloud steps as plain_with_ironic was removed
NOTE: this PR requires #1923 for proper ironic node creation

updated ironic job to use batch

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

This PR allows to add packages to the PTF repo during the upgrade process.
Until now it was only possible to do it before installation of the initial cloud (UPDATEREPOS variable). The variable UPDATEREPOS_EXTRA offers something similar for
manually triggered runs.
Background:
Some patches for cloud X break the upgrade process from cloud X-1. In order to test these properly the patched package(s) for cloud X need to be added during the upgrade workflow instead of being added before installation of cloud X-1.
This PR allows to define the variable UPDATEREPOS_UPGRADE (its a plus separated list of urls, just like UPDATEREPOS). The content of these repos will be added to the PTF repo during the upgrade process. If it is empty nothing will be added.

mkcloud: support update repos during upgrade process

---

scripts/mkcloud

The ironicnemask variable was not exported to the onadmin envs which
caused the batch templates to not fill properly.

Add missing ironicnetmask env variable

---

scripts/scenarios/cloud7/cloud7-ironic-basic-ha.yml

For some reason gre got removed from original batch scenario for
ironic job. It failed with default deployment so the missing option
was added.

Added missing gre ml2 driver in ironic scenario

---

jenkins/ci.suse.de/templates/cloud-mkcloud-job-sap-ha-template.yaml
scripts/crowbar-testbuild.py
scripts/crowbar-testbuild.yaml
scripts/mkcloud
scripts/qa_crowbarsetup.sh

This change should reflect that the continuous delivery is not SAP specific but just another type of channel.

rename want_sap to want_cd

---

scripts/scenarios/cloud7/cloud7-ironic-basic-ha.yml

Some deployment parameters still contained references to local setup (i.e. virtual.cloud.suse.de). These were removed to make the template portable.

ironic: removed references to local deployment

---

scripts/scenarios/cloud7/cloud7-ironic-basic-ha.yml

The nfs_client is not really needed for basic ironic deployment and a stripped version which was included in the scenario fails validation when deploying.

ironic: removed nfs_client from scenario

---

jenkins/ci.suse.de/templates/cloud-mkcloud-job-raid-template.yaml

Since we also use raid for the second node there is no space left for a
swift disk.

jenkins: Use storage_method=none for raid testing

---

jenkins/ci.suse.de/openstack-mkcloud.yaml

mkcloud properly adds second NIC as default if ironic is enabled but
openstack-mkcloud jenkins template overrides the default with another
default (1 NIC). For proper ironic setup the number of NICs needs to be
enforced to 2.

ironic: Enforce 2 NICs per node

---

scripts/mkcloud

from iptables manpage:
-w, --wait
Wait for the xtables lock. To prevent multiple instances of the
program from running concurrently, an attempt will be made to obtain an
exclusive lock at launch.  By default, the program will exit if the lock
cannot be obtained.  This option will make the program wait until
the exclusive lock can be obtained.

iptables: wait for other process to finish and retry

---

jenkins/ci.suse.de/openstack-mkcloud.yaml

Previously the default and minimum nodenumber for an hacloud was 4.
The default cluster only used two nodes though. Having one compute node by default should be sufficient.
In order to free or save resources on our workers we now lower the number of nodes for an hacloud to 3 (2 for the cluster, one compute).
All current hacloud jobs define their required nodenumber explicitly:
`grep -lr hacloud=1 | xargs grep -E "nodenumber=|hacloud="`
So the existing jobs should not be affected by this change.
Thanks @skazi0 for the hint to this.

openstack-mkcloud: reduce default nodenumber for ha cloud to 3

---

scripts/lib/mkcloud-common.sh
scripts/mkcloud
scripts/qa_crowbarsetup.sh

During testsetup, testvm sends a curl request to `$reposerver_fqdn/test`.
This is not ideal for all environments. To fix this, this patch
introduces the variable `$test_internet_url` to make this value
configurable.

Make URL to use for internet test configurable

---

scripts/mkcloud

Timing information at each mkcloud step helps with debugging, especially when trying to find certain information in logs.

Add timestamp to start/end of each step

---

scripts/jenkins/qa_devstack.sh

The plain 42.2 distribution should be enough, so don't intermix
new dependencies. Also upgrade list of enabled services to match
the upstream tested list.

devstack: don't add additional repositories

---

hostscripts/rpm-packaging/createproject.py

Now that we're freezing the parent project link, we can actually
do a sensible rebuild mode to ensure that all direct rebuilds are
also triggering indirect rebuilds for consistency check.

Use direct rebuild mode

---

scripts/lib/mkcloud-common.sh
scripts/qa_crowbarsetup.sh

With this switch we use `$zypper` instead of `zypper` by default.
This unifies the default parameters that were inconsistently used in various places.
For specific calls the default parameters for zypper can still be overridden like this:
```
zypper_override_params="--non-interactive" $zypper ref
zypper_override_params="--non-interactive" ensure_packages_installed wget
```
This PR (or something very similar) is needed to make https://github.com/SUSE-Cloud/automation/pull/1967  work

unify zypper parameters by using $zypper instead of zypper

---

scripts/qa_crowbarsetup.sh

This is a temp workaround until crowbar has been fully ported
to SP3 and helps us getting TDD going. To be reverted.

temporarily mount SP2 repos to make crowbar install happy

---

scripts/mkcloud

In case the mtu is different than exptected the for loop manipulated the IFS (to match full lines). After the loop the IFS was tried to set to its original value.
But an unset IFS behaves differently than an empty IFS.
So lots of commands that were run after this manipulation failed (most prominent "ssh $sshopts ..." which resulted in errors like: "command-line line 0: garbage at end of line").
This PR fixes it by dropping the need for the IFS manipulation.

drop IFS manipulation, keep IFS unset

---

jenkins/ci.suse.de/cloud-mkcloud8.yaml

The list of Cloud8 jenkins jobs is not the same as the Cloud7 jenkins
jobs. This commit adds some more jobs to reduce the gap.

Add more Cloud8 jenkins jobs

---

scripts/mkcloudhost/cloudfunc
scripts/mkcloudhost/hacloud.common
scripts/mkcloudhost/routed.cloud
scripts/mkcloudhost/runtestmulticloud
scripts/mkcloudhost/runtestn

Without this change all clouds with want_ironic=1 would get the same
subnet assigned for ironic use which causes failures during libvirt
network creation.

ironic: set net_ironic depending on used cloud

---

scripts/qa_crowbarsetup.sh

This is needed to import new GPG keys coming from freshly created PTF repo.
~Needs a rebase after https://github.com/SUSE-Cloud/automation/pull/1971~

Refresh zypper repositories after adding the update repo.

---

jenkins/ci.suse.de/openstack-mkcloud.yaml
scripts/mkcloud
scripts/qa_crowbarsetup.sh

Postgresql is since a long time the only option crowbar supports and
uses.

Remove obsolete want_postgresql

---

scripts/qa_crowbarsetup.sh

In SOC6 there is not `flatten_volume_from_snapshot` attribute in
cinder, so we need to check that we are in SOC7 or bigger.

qa_crowbarsetup: avoid setting attribute in SOC6

---

jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-ironic-template.yaml

For basic ironic tests no storage node is needed. It can cause problems
with Cloud8 as storage node would get SP2 which would make it unusable
for other services which require SP3.

ironic: disable storage role

---

scripts/qa_crowbarsetup.sh

ceph-osd requires at least 2 nodes (these can also have ceph-mon role).
One extra is needed for ceph-mds, which is needed by manila.

At least 3 ceph nodes are needed. With Cloud8 this means SP2 nodes.

---

scripts/qa_crowbarsetup.sh

As ceph nodes require SP2 and they have to be at least 3,
we don't want to have ceph with 4 nodes cluster, as there would
be only one SP3 node left for all other roles.

For SOC8, require more cloud nodes to allow ceph deployment.

---

jenkins/ci.suse.de/cloud-mkcloud6.yaml
jenkins/ci.suse.de/cloud-mkcloud7.yaml
jenkins/ci.suse.de/cloud-mkcloud8.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-ceph-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-template.yaml

Cloud8 ceph needs some fine tuning regarding nodes and roles allocations
so let's not use it by default.
An alternative to https://github.com/SUSE-Cloud/automation/pull/2026

Do not use ceph for default Cloud8 HA jobs + add specific HA+ceph job

---

jenkins/ci.opensuse.org/openstack-submit.yaml

This broke openstack-submit for Cloud:OpenStack:Newton for the past few
weeks, and the error was not trivial to understand just based on the
output of the job.

openstack-submit: Output error message when a package is not a link

---

scripts/qa_crowbarsetup.sh

Not deleting the testvm can lead to problems when the testsetup step is
repeated multiple times. Also, it is better for a test to clean up after
itself than to leave resources around that are no longer needed after
the test has finished.
In our environment the second test setup run failed because the deletion of the nova vm before it's re-creation takes too long.
The following excerpt from the mkcloud log shows the issue: The deletion of testvm gets started, but when the security group for testvm should be deleted it is still in use because the deletion of testvm has not yet finished. Since there are now two security groups with the name 'testvm', they can not be assigned to the VM and the boot fails. Deleting the testvm at the end of the first test setup should fix this issue.
``` …
```

Delete testvm in testsetup after shutting it down

---

scripts/qa_crowbarsetup.sh

The cloud-ptf repo may not contain all recommended packages required
for installation. Use --no-recommends in zypper dup to prevent errors
when a recommended package is missing in the cloud-ptf repo.

Install packages from cloud-ptf with --no-recommends

---

scripts/qa_crowbarsetup.sh

This reverts commit 623e4180f32041b58e1b22b8af8a5ad335e0c880.
It was only a workaround until the fix was ported to all current versions of crowbar. So do not merge this revert earlier.

mark PTF key as workaround for =< cloud7

---

scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-1a.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-1b.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-2a.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-2b.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-1a.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-1b.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-2a.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-2b.yaml
scripts/scenarios/cloud8/qa/no-ssl/qa-scenario-1a.yaml
scripts/scenarios/cloud8/qa/no-ssl/qa-scenario-1b.yaml
scripts/scenarios/cloud8/qa/no-ssl/qa-scenario-2a.yaml
scripts/scenarios/cloud8/qa/no-ssl/qa-scenario-2b.yaml
scripts/scenarios/cloud8/qa/ssl-insecure/qa-scenario-1a.yaml
scripts/scenarios/cloud8/qa/ssl-insecure/qa-scenario-1b.yaml
scripts/scenarios/cloud8/qa/ssl-insecure/qa-scenario-2a.yaml
scripts/scenarios/cloud8/qa/ssl-insecure/qa-scenario-2b.yaml

Because of this change: https://github.com/crowbar/crowbar-openstack/pull/972 cinder nfs option is obsolete

Obsolete nfs_mount_options

---

scripts/qa_crowbarsetup.sh

This is a fix for f87bca5fe912c2c5ce1eb7180d585674bb6bad81
The $instanceid variable is not set when it was used so the wait_for loop did not wait for anything (it is first defined 10 lines later).
This PR fixes it as it queries the instanceid of a potentially running instance called testvm first and only calls delete on it if an instance exists.
@gonzolino FYI

qa_crowbarsetup: fix deletion of testvm

---

scripts/qa_crowbarsetup.sh

As there's a need to have multiple SP2 nodes for ceph in SOC8,
do not choose it automatically and only allow ceph to be set explicitely.

Do not deploy ceph by default (only based on number of nodes) for SOC8.

---

scripts/lib/qa_crowbarsetup-help.sh
scripts/mkcloud
scripts/qa_crowbarsetup.sh

as it is not used in mkcloud
to fix mkphyscloud jobs that failed from mode=''

mkcloud: move crowbar_networkingmode into qa_crowbarsetup

---

scripts/qa_crowbarsetup.sh

Instead of waiting for all controller nodes to reboot and then check if
there was a problem, do it after each controller node reboot.

Check controller reboot problems earlier

---

jenkins/ci.suse.de/cloud-trackupstream.yaml

because the huge tarballs cause timeouts in service runs
and we do not update it much anymore.
Last hyper-v related changes were 2016-02-08
timeouts:
https://ci.suse.de/view/Cloud/view/Worker/job/cloud-trackupstream/component=crowbar-hyperv,label=openstack-trackupstream,project=Devel%3ACloud%3A6%3AStaging/

trackupstream: stop autoupdating crowbar-hyperv

---

scripts/qa_crowbarsetup.sh

The wait_for_neutron function does not cope well if the neutron
barclamp is not deployed. Check if $NEUTRON_SERVER is not set and return
in that case.

Don't wait for neutron if it isn't deployed

---

scripts/mkcloud

For those who fatfingered the sudo password, there is a
weird error message printed. avoid the error message.

Avoid unary operator expected error when mistyping password

---

scripts/qa_crowbarsetup.sh

If Manila VM was not found, it's (empty) name was still used in subsequent commands causing false positives in logs.

testpostupgrade: Handle missing manila properly

---

scripts/qa_crowbarsetup.sh

In non-CI mkcloud deployments, it might be acceptable to continue with
the proposal stage even if pacemaker has detected service failures. This
patch adds a check_crm_failcounts variable which can be set to 0 to turn
off the default fail-fast behavior in HA clouds.

Make crm failure checks optional

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

While transitioning to Ocata, we want a cloudsource=ocatacloud8 to be able
to test the Ocata setup.
This can later be used by the CloudFoundry team ,too.

Add ocatacloud8 cloudsource

---

scripts/qa_crowbarsetup.sh

SES docs suggest to wait for ceph cluster status after upgrading each
node. We saw some errors in CI which might be caused by not waiting before
executing following actions.
**EDIT:** 
The `wait_for` is supposed to print current status instead of dots for better understanding of the upgrade flow. Also `-q` is omitted from `grep` to not lose the final status (e.g. HEALTH_WARN line can contain more information).

upgrade: Wait for CEPH status after each node

---

jenkins/ci.suse.de/templates/cloud-mkcloud-job-4nodes-linuxbridge-tempestfull-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-4nodes-linuxbridge-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-template.yaml

Our gating jobs are not using bonding for nics which is not an
realistic scenario in a real world deployment.
Change that and use bonding for the 4node linuxbridge jobs and for the
gating HA job.

jenkins: Use crowbar teaming (bonding) mode for some jobs

---

scripts/jenkins/track-upstream-and-package.pl

This fixes:
Error: Could not find an xml element with the statement
when only "renderspec" is used as source service.

Fix renderspec source service handling

---

scripts/qa_crowbarsetup.sh

We have to disable want_cinder_rbd_flatten_snaps for Cloud 7
as this feature was not in GM7 and will break GM7 deployments.

qa_crowbarsetup.sh: Set want_cinder_rbd_flatten_snaps to 0

---

scripts/qa_crowbarsetup.sh

because the Pool repo is supposed to be for gold-master based deployments only

qa_crowbarsetup: fix develcloud7/8 repo setup

---

scripts/qa_crowbarsetup.sh

We need to check the actual content to determine if we want it or not.
The current check only check if it exists.

qa_crowbarsetup: Fix flatten_volume_from_snapshot check

---

scripts/qa_crowbarsetup.sh

We meanwhile mirror the -testupdates to clouddata, so at least
they're consistent and stable and don't change at random point
in times during deployment, breaking everything. Also it avoids
a NFS mount to dist, which is unavailable for anyone outside
the NUE office network, which makes remote work signficantly harder.

Stop using direct dist.suse.de mounts for test updates

---

docs/mkcloud.md
hostscripts/clouddata/syncSLErepos
jenkins/ci.suse.de/openstack-mkcloud.yaml
scripts/mkcloud
scripts/qa_crowbarsetup.sh

Cloud 5 is EOL, so we can rip out some pieces that are no longer
relevant. With this change cloud5 related deployments are no longer
possible, which allows to simplify other things further.

Drop cloud5 related parts

---

scripts/qa_crowbarsetup.sh

Seeing:
```
9pnet: Could not find request transport: virtio
```
Errors in the logs when admin machine is starting. This means 9p shares
are not mounted, and thus boot process is halted, presenting a recovery
mode. Adding a module to be loaded earlier seems to fix this issue.
The sloution was taken from here:
https://superuser.com/a/879012

Fix 9p installation

---

scripts/qa_crowbarsetup.sh

xargs will not be able to access functions defined in the bash file,
thus leaving us with these errors:
```
... onadmin_setup_local_zypper_repositories(): xargs -r run_zypper rr
xargs: run_zypper: No such file or directory
```

Fix zypper rm calls

---

scripts/qa_crowbarsetup.sh

Currently errors like this:
+ '[' -gt 3 ']'
qa_crowbarsetup.sh: line 1765: [: -gt: unary operator expected
because in commit e52046a5b we moved $i into another place

qa_crowbarsetup/IPMI: fix powering off extra nodes

---

scripts/lib/qa_crowbarsetup-help.sh
scripts/qa_crowbarsetup.sh

that were already created in an earlier run
to speed up things
and to not mess up proposals like pacemaker
that get updated when nodes were added since the last run

qa_crowbarsetup: allow to not reapply proposals

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

With this change people can mirror clouddata to a local directory, and point to that with `localreposdir_src`, and set a non-empty value for `localreposdir_is_clouddata` and do an mkcloud run without being connected to the VPN

Use a clouddata mirror locally

---

scripts/qa_crowbarsetup.sh

because it is not always root (e.g. in ENG-Cloud Provo)

qa_crowbarsetup: allow to override IPMI username

---

jenkins/ci.opensuse.org/openstack-cleanvm.yaml

We want to test with the latest openSUSE and SLES releases, so:
- for Cloud:OpenStack:Master, use Leap-42.3 and SLE_12_SP3
- for Cloud:OpenStack:Ocata, use in addition to the current images SLE_12_SP3

cleanvm: Update images used for cleanvm runs

---

scripts/lib/mkcloud-common.sh
scripts/lib/mkcloud-libvirt.sh
scripts/lib/mkcloud-onhost.sh
scripts/mkcloud
scripts/qa_crowbarsetup.sh

This is a quick way to enable consistent caching of the clouddata
data on the host system and enforce local-only usage of those
when installing a virtual cloud. This is very useful for unstable
and slow VPN connections (e.g. road warriors) as it doesn't require
downloading gigabytes of data every time or causing machines to
hang due to remote NFS mounts that are timing out.
just do export cache_clouddata=1 and be happy.

mkcloud: make it usable in local caching mode

---

hostscripts/zuul/layout.yaml
jenkins/ci.opensuse.org/openstack-rpm-packaging-build.yaml
jenkins/ci.opensuse.org/openstack-rpm-packaging-update.yaml

rpm-packaging branched stable/pike so create the CI jobs for backports.

Add rpm-packaging jobs for Pike

---

scripts/mkcloud

Recently things started to fail with out of disk space issues,
likely because the cloud 7 media grew significantly in size due to
monasca being added.

Size admin node disk slightly bigger when upgrade is being used

---

scripts/lib/mkcloud-common.sh
scripts/lib/mkcloud-onhost.sh
scripts/qa_crowbarsetup.sh

We were accidentally checking hacloud rather than want_test_updates,
so it was always using the Updates-test channel.

Fix typo in add_ha_repo function

---

scripts/qa_crowbarsetup.sh

In order to query the raid config it does a direct ssh, which
might not be available with real hardware at the time the dns resolves
because the server is still booting.

Wait longer for servers to be booted

---

scripts/lib/libvirt/fixtures/cloud-admin-uefi.xml
scripts/lib/libvirt/fixtures/cloud-admin.xml
scripts/lib/libvirt/fixtures/cloud-node1-raid.xml
scripts/lib/libvirt/fixtures/cloud-node1-uefi.xml
scripts/lib/libvirt/fixtures/cloud-node1-xen.xml
scripts/lib/libvirt/fixtures/cloud-node1.xml
scripts/lib/libvirt/libvirt_setup.py

We have to support a variable number of disks and NICs in order to
accommodate our deployment scenarios and these two device classes
compete over the available PCI slots.
Currently the PCI slot of the memballoon device collides with the
network cards for more than 2 NICs.
We can extend the number of supported PCI devices by using more than one
PCI bus (each PCI bus supports up to 32 devices). This change places all
disks onto `bus=0x00`, all NICs onto `bus=0x01`, and the memballoon
device onto `bus=0x02`.For more than 2 NICs the PCI slot of the memoballoon device collides
with the network cards. This patch moves the slot used up by 16 to
create some buffer between the last NIC and the memoballoon device.

Extend the number of supported disks and NICs

---

docs/mkcloud.md
scripts/mkcloud

There was a separate setting for that, so set it instead of manually
documenting the workaround.

make cache_clouddata=1 fetch the images from the cache

---

scripts/lib/mkcloud-libvirt.sh
scripts/mkcloud

Caching should also work with non-libvirt drivers.

mkcloud: Allow caching with all mkcloud drivers

---

scripts/lib/mkcloud-onhost.sh

They might be used, and it is not easy to determine whether
or not we want to use them. As it is small, lets not worry
about over optimizing and just mirror it always.

Mirror the SES repos as well for cache_clouddata=1

---

scripts/mkcloud

Otherwise you can not set and use the variables.

mkcloud: pass ipmi vars to qa_crowbarsetup

---

scripts/scenarios/cloud7/cloud7-ironic-basic-ha.yml
scripts/scenarios/cloud7/cloud7-ironic-swift-ha.yml
scripts/scenarios/cloud8/cloud8-ironic-basic-ha.yml
scripts/scenarios/cloud8/cloud8-ironic-swift-ha.yml

Having ironic=nic2 assignment is better default than any conditional
one as the conduit is not used for anything else and can safely default
to nic2. This is also safer since ironic is untagged and can conflict
with admin if put on the same nic.

Make ironic nic assignment global in jenkins jobs

---

scripts/jenkins/jenkins-job-trigger

On some machines passing an unicode string as host name triggers an
exception:
python -c 'import socket; socket.create_connection((u"<some-host>", 8080));'
File "<string>", line 1, in <module>
File "/usr/lib64/python2.7/socket.py", line 554, in create_connection
for res in getaddrinfo(host, port, 0, SOCK_STREAM):
LookupError: unknown encoding: idna
Whereas using an str does not trigger the problem:
python -c 'import socket; socket.create_connection(("<some-host>", 8080));'
This fix will convert the host name to a str making the error go away.

FIX idna encoding issues

---

scripts/qa_crowbarsetup.sh

Getting TESTING ISO is currently broken, this should make it working again. Tested successfully manually on qa2 cloud.

Fix detection of Testing ISO name which  has changed from DVD1 to Media1

---

scripts/jenkins/qa_openstack.sh

"nova floating-ip-delete" was removed in Pike so use the command from
python-openstackclient instead.

qa_openstack: Fix "nova floating-ip-delete" for Pike

---

scripts/jenkins/qa_openstack.sh

run_tempest.sh is no longer available in newer tempest versions (>= 16).

qa_crowbarsetup: Use "tempest run"

---

scripts/jenkins/qa_openstack.sh

Commit 57703158b62 forgot to add "-s -t" when using the tempest
CLI. Both are needed to run only smoke tests in serial.

qa_openstack.sh: Run smoke tests in serial

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

The magnum barclamp currently fails to deploy
in develcloud8 because some packages are missing
from Devel:Cloud:8 (python-kubernetes and
python-marathon).
This commit temporarily disables magnum in develcloud8
in order to get Jenkins jobs to pass over the point
where they try to deploy magnum and fail.
This is required to unblock [the mkcloud8 gating job](https://ci.suse.de/view/Cloud/view/Cloud8/job/cloud-mkcloud8-gating/).

Disable magnum in develcloud8

---

scripts/mkcloud

This reverts commit 55263846e19032986464ffd4948c9d1088ba424b.
For some reason this change was merged twice, the first one being
9901dca6. We don't need to set the hdd size twice, and we especially
don't need to check the max value of it before it is initially set.
Doing so causes mkcloud to emit an error:
/root/automation/scripts/lib/mkcloud-common.sh: line 50: 20 >  ? 20 :  : syntax error: operand expected (error token is "? 20 :  ")
which is currently causing the setup_aliases step to fail and therefor
making the batch proposal step impossible[1].
[1] https://ci.suse.de/job/cloud-mkcloud-qam-scenario-1a/26/consoleFull

Revert "Size admin node disk slightly bigger when upgrade is being used"

---

scripts/lib/mkcloud-common.sh

The MTU of the lo device is irrelevant for determining the host's
maximum MTU.

Exclude `lo` when determining MTU of host

---

jenkins/ci.opensuse.org/openstack-trackupstream.yaml

We use a hardcoded version. There is nothing to track.

trackupstream: Do not track openstack-monasca-log-agent

---

scripts/qa_crowbarsetup.sh

This PR updates the qa_crowbarsetup script to be compatible with Pike:
- replaces nova security group CLI commands removed in Pike: the nova security group CLI subcommands were removed in Pike. The script is updated to replace remaining occurrences of these subcommands with corresponding openstack CLI subcommands.
- fix --f ambiguous parameter usage: replaces the --f parameter usage in openstack CLI commands with --format, to fix the following error in Pike:   
> openstack image list: error: ambiguous option: --f could match --fit-width, --format
These changes are required to fix mkcloud for pikecloud8 cloudsource.

qa_crowbarsetup: update for Pike

---

scripts/lib/libvirt/compute-config
scripts/lib/libvirt/fixtures/cloud-node1-9pnet-mount.xml
scripts/lib/libvirt/fixtures/cloud-node1-raid.xml
scripts/lib/libvirt/fixtures/cloud-node1-uefi.xml
scripts/lib/libvirt/fixtures/cloud-node1-xen.xml
scripts/lib/libvirt/libvirt_setup.py
scripts/lib/libvirt/templates/compute-node.xml
scripts/lib/libvirt/test_libvirt_setup.py
scripts/lib/mkcloud-libvirt.sh
scripts/lib/mkcloud-onhost.sh
scripts/mkcloud
scripts/qa_crowbarsetup.sh

This patch utilizes the existing pattern to mount the local repositories from
the host using 9pnet_virtio whenever possible so we can make use of the cached
images on the controller nodes when performaing openstack operations such
as image upload/download for testing purposes.

cache images

---

scripts/qa_crowbarsetup.sh

Commit 7835272aa7 added the ability to use locally cached images but
changed the magnum-service-image name wrongly. Fixed with this commit.

qa_crowbarsetup: Fix magnum service image name

---

jenkins/ci.suse.de/ardana-trackupstream.yaml

**source:** https://github.com/SUSE-Cloud/automation/blob/master/jenkins/ci.suse.de/ardana-trackupstream.yaml
**package missing:**
ardana-ansible
ardana-build-config
ardana-ci
ardana-configuration-processor
ardana-extensions-dcn
ardana-extensions-example
ardana-input-model
ardana-input-model-ref
ardana-installer-ui
ardana-opsconsole-ui
ardana-opsconsole-server
ardana-qa-ansible
ardana-re-osrb
ardana-re-tools
ardana-service
ardana-service-ansible
ardana-storevirtual-installer
ardana-swiftlm
ardana-ui-common
ardana-vsa

ardana: update packages for trackupstream job

---

jenkins/ci.suse.de/cloud-mkcloud8.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-4nodes-linuxbridge-ocata-template.yaml

We want to keep Devel:Cloud:8:Ocata running for CloudFoundry CI usage.
So add a job for periodic testing.

jenkins: Add 4nodes-linuxbridge job for Ocata

---

scripts/jenkins/log-parser/openstack-mkcloud-rules.txt

The mariadb-errormessages package being installed is not an indication
of an error, make sure the log parser doesn't report it in the Parsed
Console output.

log-parser: Whitelist mariadb-errormessages RPM

---

scripts/qa_crowbarsetup.sh

The repo aliases have been changed recently, so the removal did not work.
Original names were changed by
https://github.com/SUSE-Cloud/automation/commit/7310b5cc2e7e87144a124b639603701af0e81386

Correctly remove SP1 repos before upgrading to SP2

---

scripts/qa_crowbarsetup.sh

add_ha12sp2_repo was removed with https://github.com/SUSE-Cloud/automation/commit/3a9b76fb21dcafd16448c6aebddea9e7b49394dd

Use correct method to add HA repository

---

jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-mariadb-template.yaml

It does not have enough nodes. If we want to test it together with ceph,
we should create separate job for that.

Do not deploy ceph with mariadb-ha job

---

scripts/qa_crowbarsetup.sh

When the nova client fails something, it produces an ugly ERROR message
that the jenkins log parser treats as a potential error. We don't need
to treat 'show' commands that are checking the existence of something
for idempotency purposes as failures. This also restructures some delete
commands to first check for existence before attempting the delete,
because if the delete fails for some reason other than nonexistence we
want to know about it.
When the openstack client command fails something, the stderr doesn't
contain ERROR and isn't treated as such by the log parser, so we might
as well let it keep being verbose.

qa_crowbarsetup: Hide stderr from nova commands

---

jenkins/ci.suse.de/cloud-automation-pr-trigger.yaml

cloud-automation-pr-trigger: pr gating for devel and stable release
Due to changes meant for the development release sometimes builds for the stable releases break.
To prevent such changes from being merged we will also build mkcloud for the stable release.

Add cloud7 to pr gating

---

scripts/crowbar-testbuild.yaml

Since we switched to MariaDB as default we need more nodes to fullfill
the requirements of Galera.

testbuild: MariaDB needs at least 3 nodes to deploy Galera

---

scripts/lib/qa_crowbarsetup-help.sh
scripts/mkcloud

We need to set the db backend explicitely so that qa_crowbarsetup code does not try to create DRBD-based cluster...

Use mysql (MariaDB actually) backend for all Cloud8 deployments

---

README.md

This patch adds a short note in the jenkins section of the README about
the log parser rules file. Having this here would have helped me when I
was grepping for 'Parsed Console Output' which is what the jenkins view
is titled. This does not link back to the
"openstack-mkcloud-log-parser-test" page of our "keep jenkins green"
document since that is in a private repository and this repository is
open source.

CI: Document the log parser rules

---

scripts/mkcloud

If people are deploying cloud8+ we want mysql to be the engine. We
already added a rule for that but we did not export the variable. This
meant that the `want_database_sql_engine` variable was not displayed by
env and not forwarded to onadmin calls, so for qa_crowbarsetup.sh the
variable was still undefined - leaving us with an mkcloud that wants to
deploy drdb on a three-node cluster in some cases.
```
> env | grep variable
> variable=3
> env | grep variable
> export variable=3
> env | grep variable
variable=3
```

fix database engine selection

---

jenkins/ci.suse.de/cloud-mediacheck.yaml

Otherwise the disk of the worker is filling up with ISO images.

mediacheck: cleanup in error case as well

---

jenkins/ci.opensuse.org/openstack-submit.yaml

The Pike gating was not working. No packages were copied to the non-staging
area. The error[1] was:
Please add support for the project: Pike
[1] https://ci.opensuse.org/view/OpenStack/job/openstack-submit/3692/

openstack-submit: Fix Pike submissions

---

hostscripts/clouddata/syncSLErepos

and devel:tools:building (for jenkins-swarm-client)
to be independent from download.o.o
e.g. for github-status, jt_sync and cct

syncSLErepos: sync dlre

---

hostscripts/scale-cloud/batches/00_ipmi.batch

Placeholders will be filled by script deploying the batch.

scale-cloud: removed ipmi credentials

---

hostscripts/soc-ci/soc-ci

"j" was missing in the list of available hosts.

soc-ci: Also allow host vj1.cloud.suse.de

---

hostscripts/scale-cloud/batches/00_ipmi.batch

Having deployment list in the batch prevents applying this batch before
nodes are added. The ipmi roles are added automatically so they don't need
to be listed explicitly here.

scale-cloud: removed ipmi deployment data

---

scripts/scenarios/cloud8/cloud8-ironic-basic-ha.yml

The pxe_ssh driver was deprecated in Ocata and removed in Pike[1]. This
patch removes it from the cloud8 job.
We aren't currently testing baremetal deployments with the pxe_ssh
driver so removing it is not a loss. In order to fully test ironic it
would be better to get virtualized deployments to work with the
pxe_ipmitool driver.
[1] https://docs.openstack.org/releasenotes/ironic/pike.html#id10

ironic: Stop using pxe_ssh driver (SCRD-768)

---

jenkins/ci.suse.de/cloud-mediacheck.yaml

This is a temporary fix for the cloud-mediacheck job.
Currently we have a `resource-agents` package in the `_product` in `Devel:Cloud:8:*` that is more recent than the one in SLE12 SP3 because we are waiting for that package to be updated in a maintenance update of SLE12 SP3 (the old version causes problems with Galera). Since we've got the package in the product, mediacheck attempts to install it from _only_ our product media, which do not contain all of its dependencies.
As a temporary remedy, this commit disables the media check for the problematic package. This commit needs to be reverted once `resource-agents` is updated in SLE 12 SP3.

Disable mediacheck installability checking for resource-agents package

---

scripts/qa_crowbarsetup.sh

Reducing the number of apache processes per keystone vhost to 2 should
save us quite a chunk of memory on the jenkins workers.

qa_crowbarsetup: Reduce number of apache keystone processes

---

scripts/qa_crowbarsetup.sh

because GM7+up does not have an api processes value
This is a fixup on commit f5fcccabdc

qa_crowbarsetup: fix keystone

---

scripts/lib/qa_crowbarsetup-help.sh
scripts/qa_crowbarsetup.sh

by placing \$PROPOSAL-batch.yaml files in a certain directory.
This allows to keep the flexibility of the default 'proposal' mechanism
while allowing for the power and complexity of the batch file
for certain parts of the configuration

Allow to use crowbar batch for single proposals

---

jenkins/ci.suse.de/cloud-mkcloud6.yaml
jenkins/ci.suse.de/cloud-mkcloud7.yaml
jenkins/ci.suse.de/cloud-mkcloud8.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-compute-template.yaml

SOC6 and SOC7 jobs were broken because of template update to use 5 nodes setup instead 4 nodes because of which was not able fetch correct secnario file.
Template for SOC6 and SOC7 updated to have 4 node setup for compute ha setup. cloud-mkcloud6.yaml cloud-mkcloud7.yaml
Template for Cloud8 updated to use 5 nodes cloud-mkcloud8.yaml
cloud-mkcloud-job-ha-compute-template.yaml updated to use parameters for compute and controller nodenumber

Fix compute ha job templates

---

jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-ironic-agent-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-ironic-template.yaml

After increasing number of controllers to fixed 3, in cloud7 runs 
default total number of nodes was 3 and there was no room for compute. 
Using template variables for setting number of nodes should make these
jobs work properly in both cloud7 and 8.
See: https://github.com/SUSE-Cloud/automation/pull/2184

Template number of nodes for ironic jobs

---

scripts/lib/find_fastest_server.pl
scripts/lib/mkcloud-common.sh

so that we don't have to manually adapt scripts to different locations
In case no server is reachable, we fall back to the old default,
so that we do not break in travis and other outside places.

mkcloud: find fastest repo server

---

jenkins/ci.opensuse.org/openstack-trackupstream.yaml

trackupstream: Track horizon-neutron plugins for fwaas and vpnaas

---

scripts/qa_crowbarsetup.sh

It is useful to see a list of slowest tests during a jenkins run. That
way we can easily grep and compare results.

qa_crowbarsetup: Output slowest tempest tests if possible

---

scripts/qa_crowbarsetup.sh

These packages are not installable for GM7+up anymore as the
testiso remains on GM level. furthermore the actual usage of
those packages is commented out so there is little value in
trying to make them installable in the first place. To be
revisited when the magic Cloud 8 testing plan is in place.

Skip setting of CLOUDTESTISO for GM7/GM7+up

---

scripts/qa_crowbarsetup.sh

The latest defcore guidelines are 2017.09
The new set of test is now retrieved and not filtered as before.

Switch to 2017.09 defcore guidelines

---

jenkins/ci.opensuse.org/openstack-trackupstream.yaml

The openstack-trackupstream job was undeployable for a couple of
days due to a syntax error. when you embed a comment in the filter,
it applies to all the rest of the string, not only to the current
line of yaml in the JJB.

Fix syntax error in JJB for trackupstream

---

hostscripts/zuul/zuul.conf

This adds a compatability option to deal with a Gerrit behavior
change between 2.11 and 2.13.

Set strip_branch_ref compat option

---

jenkins/ci.opensuse.org/openstack-cleanvm.yaml
jenkins/ci.opensuse.org/openstack-devstack.yaml
jenkins/ci.opensuse.org/openstack-repocheck.yaml
jenkins/ci.opensuse.org/templates/openstack-rpm-packaging-sles12.yaml

The build-discarder doesn't seem to be cleaning up "enough" for
ci.opensuse.org to not crawl down. as we use logrotate on ci.s.de
successfully lets switch to that.

Properly logrotate artefacts on ci.opensuse.org

---

scripts/qa_crowbarsetup.sh

~This is was only used to convert from subunit versions, but not needed anymore since all the things support version 2 now.~
~Besides the package python-subunit in Pike does not install/provide subunit-1to2 subunit-2to1 filters/binaries becasue of the single spec switch~
Ostestr is generating subunit ver 2 So we can drop on of the filters

Replace testr with ostestr

---

scripts/qa_crowbarsetup.sh

This does not work on cloudsource=ocatacloud8

stop setting password_hash_round on older cloud8

---

scripts/qa_crowbarsetup.sh

This patch adds the necessary network.json changes for an ironic
deployment and an 'ironic' case in the proposal deployment step.
Deployment of the ironic barclamp is guarded by the $want_ironic
setting which is already in use elsewhere.
For now this leaves the existing ironic jenkins jobs alone (which uses
the batch command to customize the network and ironic barclamps) but we
can consider switching to this model, which is more in line with how
other barclamps are deployed, in the future.

ironic: Add deployment support

---

scripts/jenkins/qa_openstack.sh

Depending on the provenance of the VM image used by cleanvm, it may have
packages beyond the JeOS set of packages installed already. If one of these
packages exists in Devel:Cloud:* in a newer change, a vendor change may be
needed. In this case zypper will prompt for that vendor change, even in
non-interactive mode, thus stalling deployment. This commit generally allows
vendor changes for cleanvm to prevent this from happening.
Related: https://github.com/SUSE-Cloud/automation/pull/2135 (during testing this broke due to this sort of situation. I put a workaround specific to the packages I encountered this with on there, but I'd vastly prefer the general solution I implemented here).

Allow vendor change for cleanvm

---

jenkins/ci.opensuse.org/heat-templates/deploy-cleanvm.sh
jenkins/ci.opensuse.org/heat-templates/openstack-cleanvm.yaml

This pull request polishes up the scripts/heat template for deploying `openstack-cleanvm` locally.
* Added default repository URLs/branches (default is to build Ocata cloud
on SLES 12 SP3)
* Adjusted defaults in the Heat template to build an Ocata based cloud
Caveat: I haven't tested this yet, so it may still be subtly broken. I'll be off for two weeks starting next week so won't be able to fix it for a while if it does turn out to be broken. Feel free to play with this/fix it/merge it meanwhile. Failing that I'll test/fix it in two weeks :-)

Update local openstack-cleanvm

---

hostscripts/gatehost/crowbarp2.xml

During scale testing, Crowbar VM got additional CPU cores.
This change is there to keep the repo in sync with reality.

Update crowbarp2 CM config

---

hostscripts/gatehost/freshadminvm

The domain contained dot at the end which failed to resolve.
In addition, the master version doesn't have the domain and it's easy
to define the address in /etc/hosts on adminhost.

freshadminvm: removed domain from vm addr

---

hostscripts/gatehost/freshadminvm

When using local copy of automation scripts, freshadminvm still uses
global /usr/src/automation in some parts. Having this changeable from
outside makes it a bit more flexible.

freshadminvm: make SCRIPTS_DIR changeable

---

hostscripts/gatehost/freshadminvm

Files in lib were renamed recently to handle 'physical' driver.

freshadminvm: Update driver lib path

---

hostscripts/scale-cloud/setup-baremetal.sh
hostscripts/scale-cloud/setup.sh

Sometimes the redirect from download.nue.suse.com to provo ibs mirror
doesn't work and causes download of lots of data from NUE.

scale-cloud: make sure we use provo ibs mirror

---

scripts/mkcloud

In order to collect performance data from a successful run we need the possibility to collect supportconfig data.
Doing this for all builds is not ideal (too much data). So we want to trigger a weekly (or manual) run that captures supportconfig data. This PR adds this support via the onhost+stepname mechanism.

mkcloud: allow to run supportconfig as onhost step

---

scripts/qa_crowbarsetup.sh

so that iscloudver will work when mkcloud-common.sh is sourced
required after #2218 broke SOC8 HA runs

qa_crowbarsetup: source mkcloud.config first

---

scripts/crowbar-testbuild.rb

let osc do the copying of rpms when the build succeeded

crowbar-testbuild: let osc do the copying

---

scripts/lib/ipmi/ipmi_sim.emu
scripts/lib/ipmi/ipmi_sim_lancontrol
scripts/lib/libvirt/compute-config
scripts/lib/libvirt/fixtures/cloud-node1-9pnet-mount.xml
scripts/lib/libvirt/fixtures/cloud-node1-raid.xml
scripts/lib/libvirt/fixtures/cloud-node1-uefi.xml
scripts/lib/libvirt/fixtures/cloud-node1-xen.xml
scripts/lib/libvirt/fixtures/cloud-node1.xml
scripts/lib/libvirt/libvirt_setup.py
scripts/lib/libvirt/templates/compute-node.xml
scripts/lib/libvirt/templates/ipmi-device.xml
scripts/lib/libvirt/test_libvirt_setup.py
scripts/lib/mkcloud-common.sh
scripts/lib/mkcloud-ipmi.sh
scripts/mkcloud
scripts/qa_crowbarsetup.sh

This adds a BMC interface to the libvirt node definition through QEMU, which allows IPMI kernel drivers to be loaded, thereby letting crowbar discover information about the BMC interface while the node is being joined. The BMC properties (such as its IP address and credentials) are then managed by binding an ipmi_sim instance to a veth pair that connects the BMC interface to the admin network bridge. This will allow us to properly test the IPMI barclamp in CI, and will also be useful for testing the ironic barclamp with production-grade drivers such as pxe_ipmitool.

mkcloud: support IPMI with libvirt nodes

---

scripts/qa_crowbarsetup.sh

in HA jobs, the password change somehow doesnot propagate to other
barclamps, causing chef-client to fail.
This patch disables the test until it is fixed

disbale update_keystone_password test

---

scripts/qa_crowbarsetup.sh

On HA scenarios, a typical proposal can take several minutes to run, but
the default crowbar batch build command times out and fails before it is
finished[1]. This patch adds a timeout flag to the
update_keystone_password test, using 2400 which is the value that other
crowbar batch build commands use in this repository.
[1] https://ci.suse.de/job/openstack-mkcloud/87363/console

keystone: Add timeout to crowbar batch build

---

scripts/qa_crowbarsetup.sh

The onadmin_wait_tftpd function waits for the tftpd server to be ready
on the admin node. The wait_for call does not include a process name
which leads to the following output on failure:
Ran into error: Waiting for 'unknown process' timed out.
Since the above message is not very informative by itself, this change
adds some more information to the wait call.

Add more information to wait_tftpd

---

scripts/build_ses.sh
scripts/lib/mkcloud-common.sh
scripts/lib/mkcloud-driver-libvirt.sh
scripts/mkcloud
scripts/qa_crowbarsetup.sh

Adding initial version of the deployexternalceph step
This step calls:
- lonelynodes to generate nodes for an external ceph cluster
- calls crowbar_register to add them the crowbar
- Adds the storage network to the nodes
- Optionally, adds the ceph network to the nodes
- Sets their aliases to be ceph0 - cephN
- Deploys SES on the cluster nodes using deepsea
You run this step, you need to have first run lonelynodes and crowbar_register. You also need enable want_external_ceph:
export want_external_ceph=1
If you want to specify a specific version SES version use want_ses_version. E.g to use SES5:
export want_ses_version=5

Add deployexternalceph step

---

jenkins/ci.suse.de/templates/cloud-mkcloud-job-uefi-template.yaml
scripts/lib/mkcloud-common.sh

The EFI runs had a special -efi image for the admin node,
which we don't need anymore as I merged it's changes into
the main image, so that one should boot for both efi and non-efi.
In efi builds there is currently an issue with reboot (also with
the old image), which I'm separately investigating, but we can
switch it to non-reboot for now to have something working

remove special admin node image for efi runs

---

scripts/jenkins/qa_devstack.sh

Without metadata service instances do not get their details and also no
copying of ssh keys which fails many tempest jobs.

devstack: enable nova-metadata service

---

hostscripts/clouddata/syncSLErepos
scripts/lib/mkcloud-onhost.sh
scripts/qa_crowbarsetup.sh

Some cloud relevant fixes are only available in the LTSS update
channel as they got released after the general maintenance period
ending, e.g. apache2 in the Cloud 6 case.

Enable LTSS Updates for SLE12 SP1

---

scripts/qa_crowbarsetup.sh

During testsetup with SOC6: `ostestr: error: unrecognized arguments: last`
I checked it on the system and it seems that SOC6 has no ostester --last.
Previous change from Sep 27 in commit 622577f25a2d362d94cf5aa2b2a00d8accb8b70b changed it  from tester to ostestr(but not counts with SOC6).

for SOC6 use testr not ostester

---

scripts/build_ses.sh

For baremetal nodes, 60s is sometimes too little for a full reboot.

build_ses: increase reboot allowance

---

jenkins/ci.suse.de/cloud-mkcloud7.yaml
jenkins/ci.suse.de/cloud-mkcloud8.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-disruptive-template.yaml

If no database migration is needed (mariadb already in SOC7),
normal upgrade path should work without significant changes...

New job for Cloud7-8 disruptive upgrade

---

jenkins/ci.suse.de/ardana-trackupstream.yaml

We use the tarball from pypi for now and the package name changed. So
do not track it for now.

trackupstream: Do not track ardana-configurationprocessor

---

jenkins/ci.opensuse.org/openstack-trackupstream.yaml

It's been failing for ages as the package as been removed from OBS.
we don't see to need it anymore for Pike.

trackupstream: Stop tracking gnocchi in Pike and Master

---

jenkins/ci.suse.de/ardana-trackupstream.yaml

A new Ardana extension is available for Cloud 8 to integrate
with VMware NSX-v. We want to pull regular updates from it.

Track ardana-extensions-nsx updates

---

ardana/ansible/init.yml

Otherwise the legacy layout is used during installation.

ardana: Pass needed env vars when calling ardana-init.bash

---

ardana/ansible/init.yml

Commit fc4f04fb835e89d missed one part where still the old ardana-ci
branch was used.

ardana: Download files from master branch (part 2)

---

ardana/heat-template.yaml
jenkins/ci.suse.de/ardana-job.yaml

We need the IP addresses for the different nodes from different
networks to setup the model later on. So create more outputs to be
able to query the IPs.
Also adjust the name for the floatingip output name to be consistent.

ardana: Add IPs from different networks to heat stack output

---

ardana/ardana-init.bash

~/openstack-input needs to contain the ansible files from
/usr/share/ardana/ansible .

ardana: Copy ansible files in ardana-init.bash

---

scripts/jenkins/ardana/ansible/repositories.yml

Everything apart from the old ansible release should be in D:C:8:S by now.

ardana: Remove unneeded repos

---

scripts/jenkins/ardana/ansible/init.yml

This script is now embedded in ardana-ansible package
(temporarily still fetching from SUSE-Cloud/automation,
to be coming directly from git once the review merges)

Remove fetching of ardana-init.bash from git

---

scripts/jenkins/ardana/heat-template.yaml

To be able to install software on the compute nodes (we do not have
the repos setup on the deployer currently), the nodes need access to
the outside network. This is for now done via the private mgmt network
and a router.

ardana: Allow compute nodes to access public network

---

scripts/jenkins/ardana/ansible/init.yml

This is not nice, but a simple step to get the needed repositories on
the compute nodes.

ardana: Copy repository setup from deployer to compute nodes

---

scripts/jenkins/ardana/ansible/init.yml

Commit 5bf00fbaeb9 did the repository setup on the compute nodes but a
refresh of the newly added repos is also needed. Add this.

ardana: Refresh repos on compute nodes

---

scripts/jenkins/ardana/heat-template.yaml

We need this to figure out the dns port IP addresses from the mgmt
network.

ardana: Add mgmt network id to heat template output

---

jenkins/ci.suse.de/ardana-job.yaml

We need to set the dns servers in the ardana input model correctly so
we need to get the nameservers from the network.

ardana: Make the dns server IP addresses from the mgmt net available

---

scripts/jenkins/ardana/ansible/init.yml

Create ssh key for root on deployer and use that for authenticating to
the compute nodes in the further steps
Co-Authored-By: tbechtold@suse.com

ardana: Use password less ssh for root

---

jenkins/ci.suse.de/ardana-job.yaml
scripts/jenkins/ardana/ansible/init.yml

pool.ntp.org does not work so we need to adjust the ntp server we
use.

ardana: Use ntp.suse.de in model

---

jenkins/ci.suse.de/ardana-job.yaml

For testing, it is useful to trigger a build with a different
automation repo/branch .

ardana: Allow a custom automation repo and branch

---

scripts/jenkins/ardana/ansible/files/input-model-nic-mappings.yml
scripts/jenkins/ardana/ansible/templates/input-model-servers.yml
scripts/jenkins/ardana/heat-template.yaml

As the ardana management network is already connecting to the external
router we don't need to connect the deployer instance to the "fixed"
network just for assigning a floating IP. This allows us to use the same
nic mappings on all nodes.

ardana: Simplify network config of heat stack a bit

---

jenkins/ci.suse.de/ardana-job.yaml
scripts/jenkins/ardana/ansible/files/input-model-net-global.yml
scripts/jenkins/ardana/ansible/init.yml
scripts/jenkins/ardana/ansible/templates/input-model-servers.yml
scripts/jenkins/ardana/heat-template.yaml

To be more aligned with vagrant based setups, restructure the
networking config of the heat template and the used input model.

ardana: Restructure network config

---

scripts/jenkins/ardana/ansible/templates/input-model-servers.yml

As the IP of the baremetal network needs to stay the same during
deployment we need to switch to the "mgmt" network, which is using the
pre-allocated IP from neutron.

ardana: Use "mgmt" for baremetal network

---

scripts/jenkins/ardana/ansible/files/input-model-net-global.yml
scripts/jenkins/ardana/heat-template.yaml

To avoid ardana allocating IPs that are already used by neutron.

ardana: Skip neutron router/dns addresses in ardana nets

---

scripts/jenkins/ardana/ansible/repositories.yml

We recently switched the provo-clouddata mirror to sync more
often, so hopefully it is good enough.

ardana-ci: remove references to DC8S repo and switch to provo mirror

---

scripts/jenkins/ardana/ansible/files/input-model-network-groups.yml
scripts/jenkins/ardana/ansible/init.yml

With commit c5858c0390c we switched the packager to serve repos in the
Management network. This change is reflected that also in the
network-groups attribute to have ardana create the IP Tables rules for
the packager/lifecycle-manager port (79 by default) for the correct IP
Address.
That also me that until we find a way to declare static IP allocations
in the input mode for all networks we're hosting everything in the
Management network.
Co-Authored-By: Thomas Bechtold <tbechtold@suse.com>

aradana: Move lifecycle-manager endpoint the Management network

---

scripts/jenkins/ardana/ansible/files/input-model-disks-controller.yml
scripts/jenkins/ardana/ansible/init.yml

We currently don't have VGs setup in the image (see also commit
38907cc96c94) so we need to remove the glance-cache VG. Otherwise the
deployment fails later when checking for a mountpoint for
/var/lib/glance/cache .
Also use a ansible file/ instead of replacing lines in the
disks_controller.yml file. This simplifies changes to the model.

ardana: Remove glance-cache from volume groups

---

scripts/qa_crowbarsetup.sh

New parameter for enabling setting the attribute use_dhcp at the ipmi proposal.
to avoid crowbar changing to static BMC IP addresses.

Add new param for setting use_dhcp on ipmi proposal

---

scripts/jenkins/ardana/ansible/init.yml

We don't have cloud-init in the image, so we need to manually grow
the filesystem

Grow initial partition on deployer node

---

scripts/jenkins/ardana/ansible/repositories.yml
scripts/jenkins/ardana/ardana-init.bash

We're embedding the right ansible version in the media
directly now for full offline install.

Stop downloading ansible from Leap 42.1

---

hostscripts/clouddata/syncSLErepos

rsyncing from /mnt/dist doesn't work for the provo mirror because
it doesn't have access to NFS. we need to use rsync. as the ibs-mirror
provo is constantly broken, we sync Cloud 8 from NUE directly

syncSLErepos: Fix sync for the Cloud pool repos

---

scripts/lib/libvirt/libvirt_setup.py

http://bugzilla.suse.com/show_bug.cgi?id=1064517
using virsh shutdown to cleanly stop VMs was broken for a while
and this simple workaround helps
Note: might not work on SLE-12 GA, but that is EOL for a long time anyway

mkcloud: Fix VM shutdown

---

jenkins/ci.suse.de/ardana-job.yaml
scripts/jenkins/ardana/ansible/init.yml

When working in an environment it is not obvious which reachable IP
address the deployer has. Write that info to /etc/motd . Then it is
easily accessable when working in an env.

ardana: Write deployer floating ip to /etc/motd

---

jenkins/ci.suse.de/ardana-trackupstream.yaml

Packages renamed away from ardana-* prefix should not be handled
by trackupstream. e.g. python-glance-check now comes from pypi.

Remove renamed packages from ardana-trackupstream

---

scripts/jenkins/ardana/ansible/init.yml

ansible is already logging to ~/.ansible/ansible.log. And the "| tee"
screws up the exit code of the "shell" command leading to false
positives.

ardana: No need to use tee for logging

---

scripts/jenkins/ardana/ansible/init.yml

glance-cloud-configure is not enought. We need also the configuration
tasks for neutron and others
Additional the rootfs on the compute nodes needs to be expanded.

ardana: More fixes for tempest

---

jenkins/ci.suse.de/cloud-mkcloud7.yaml

Temporarily change the way tempest runs test cases
in SOC7 from parallel (default) to serial, to clear
the CI job failures while bsc#1074009 is being worked
on.
Several temporary solutions have been explored so far,
this is the one with the least impact.
More info here: http://bugzilla.suse.com/show_bug.cgi?id=1074009

jenkins: force --serial tempest in SOC7

---

jenkins/ci.suse.de/ardana-trackupstream.yaml

ardana-opsconsole-server has been renamed to
python-ardana-opsconsole-server and is now living on pypi.

trackupstream: Remove opsconsole-server from trackupstream

---

scripts/qa_crowbarsetup.sh

for some reason zypper dup would complain:
Problem: problem with installed package kernel-default-3.12.74-60.64.40.1.x86_64
Solution 1: deinstallation of kernel-default-3.12.74-60.64.40.1.x86_64
Solution 2: keep obsolete kernel-default-3.12.74-60.64.40.1.x86_64
and not consider installing both old and new kernels in parallel.
Newer zypper versions have a --force-resolution switch that might help
but on SOC6/SLE-12-SP1 it is unavailable

qa_crowbarsetup: allow kernels in PTF repo

---

jenkins/ci.opensuse.org/openstack-cleanvm.yaml
jenkins/ci.opensuse.org/openstack-repocheck.yaml

It is  EOL:
https://news.opensuse.org/2018/01/22/opensuse-42-2-to-reach-end-of-life-this-week/

Remove Leap 42.2

---

scripts/jenkins/ardana/ansible/files/input-model-net-global.yml
scripts/jenkins/ardana/ansible/files/input-model-nic-mappings.yml
scripts/jenkins/ardana/heat-ardana-deployerincloud-lite.yaml

This network is needed for the "ext_net" (external network for neutron)
in the deployerincloud input models. This commit also adjusts the
nic_mapping accordingly.
This is should get us past the remaining tempest failure.

ardana: Create additional network in heat template

---

jenkins/ci.suse.de/ardana-job.yaml
scripts/jenkins/ardana/ansible/init.yml

The new parameter allows to specify the name of a filter file to be
passed to the tempest-run playbook. Then name must match on of the
existing filter file in tempest-ansible/roles/tempest/files/run_filters/
minus the .txt.j2 extension.

ardana: Add tempest_run_filter parameter

---

README.md
docs/ardana/testing.md

Developers need to be able to setup a SUSEfied Ardana based
deployment. Currently the easiest way is the jenkins job we have.
Document that approach so more people can setup custom environments.

ardana: Add some basic documentation how to setup a ardana env

---

docs/ardana/testing.md

The link was wrong (pointing to github instead of ci.suse.de).

doc: Fix ardana-job build link

---

scripts/jenkins/ardana/ansible/files/input-model-firewall-rules.yml
scripts/jenkins/ardana/ansible/init.yml

By default, ICMP is blocked, which is silly for a development
environment. Configure the firewall rules to allow ICMP.
This input model definition is copied from the deployerincloud-lite
example model with the ICMP rules uncommented.

Allow ICMP in input model

---

jenkins/ci.suse.de/ardana-job.yaml

That way, it is easier to find out the owner of a stack (assuming
people set the job_name variable to their own username).

ardana: Add job_name to heat stack name

---

scripts/lib/mkcloud-driver-libvirt.sh

This is to prevent fsck from incorrectly getting a different file system
type from fstab. This would happen when a file system in fstab is
mounted by label, with the same label in use by the fs to fsck but a
different type.
A different way around this would be to set the env FSTAB_FILE to the
empty string for fsck invocation. This more generic solution is not
necessary as resize2fs is used on the same fs, which like e2fsck only
works on the ext fs types.
Example log of the problem this fixes:
mkcloud# ./mkcloud.sh plain
...
resize2fs /dev/mapper/cloud-cloud.admin1 failed! (safelyret=1) Aborting.
...
mkcloud# grep xfs /etc/fstab
/dev/disk/by-label/ROOT / xfs defaults 1 1
mkcloud# fsck -V -y -f /dev/mapper/cloud-cloud.admin1
fsck from util-linux 2.29.2
[/sbin/fsck.xfs (1) -- /] fsck.xfs -y …

mkcloud: use e2fsck instead fsck

---

scripts/qa_crowbarsetup.sh

The no_proxy environment variable did not work for a curl connection to
the dashboard.
Fix a variable name typo.
Add the domain for nodes as only the URL is inspected before resolving
the host part.

qa_crowbarsetup.sh: fix proxy exclusion for internal network

---

scripts/jenkins/update_automation

For the switch to github_pr update_automation needs to checkout one more repo. This PR holds the refactoring and the addition of the new repo.

refactor update automation for switch to github_pr

---

scripts/qa_crowbarsetup.sh

The Cloud 8 testing ISO is not fully resolvable anymore and the only
part this is used is for the CCT nova and manila functional test. Based
on the feedback from QE we don't really care about this tests.

Drop Cloud 8 testing ISO

---

jenkins/ci.suse.de/cloud-mediacheck.yaml

In Cloud 8 we have now 3 ISO flavors due to the media split.

jjb: mediacheck add axis for ISO flavors

---

jenkins/ci.suse.de/cloud-mediacheck.yaml

In case we provide a media flavor then the pattern matching would cut
the OBS_TARGET.

jjb: Mediacheck fix pattern matching in case if 3rd optional param

---

jenkins/ci.opensuse.org/openstack-trackupstream.yaml

Similar to other OpenStack packages, follow Master and the stable/pike
branch for python-ironic-python-agent.

trackupstream: Track python-ironic-python-agent in Master and Pike

---

scripts/github_pr/github_pr_cloud.yaml
scripts/github_pr/github_pr_crowbar.yaml

With this logging output to stdout we can now see which jobs were triggered within a run of github_pr.
This is useful when running it regularly within a CI.

github_pr: add console logging for automation, cct, crowbar PRs

---

scripts/github_pr/interactions/ia_cloud.rb

The call of jenkins-job-trigger was missing the jenkins
job name. Without that the PR build could not be started.

github_pr: fix jenkins-job-trigger call

---

jenkins/ci.suse.de/ardana-job.yaml

The std-min model exposes more issues in testing and is also
what Gozer CI currently is testing, so we should default
to that one.

Switch to std-min model by default

---

hostscripts/soc-ci/soc-ci

Instead of returning a dict with strings, return the config object
itself. That way, functions can get also a boolean value (via
conf.getboolean()) if needed.

soc-ci: Return ConfigParser object for config usage

---

jenkins/ci.suse.de/ardana-trackupstream.yaml

Add tracking for ardana-opsconsole-server (recently changed to obscpio generated rather than static tarball: https://build.suse.de/request/show/154848)

Track upstream opscon server

---

jenkins/ci.suse.de/ardana-job.yaml
scripts/jenkins/ardana/ansible/init.yml
scripts/jenkins/ardana/ansible/repositories.yml

Capture the build version of the IBS Cloud media ISO used for each `ardana-job`, and make it clearly visible at the top of the job's console output and also in `/etc/motd` and `/etc/ardana/media-build-version`.  This should help development and testing, especially since it helps QE find a recent media build ISO which had a successful ardana-job run.
https://ci.suse.de/job/ardana-job-aspiers/12/consoleText is an example of what the job log looks like with this change.

ardana-job: capture cloud media build version

---

scripts/lib/mkcloud-common.sh
scripts/lib/mkcloud-onhost.sh
scripts/qa_crowbarsetup.sh

The naming of SOC8 changed, the Crowbar product now has a Crowbar-
prefix in the version number. adjust.

mkcloud: use -Crowbar-8- as infix for the Cloud 8 repositories

---

hostscripts/soc-ci/soc-ci

Refactor a few callsites to use a common function for finding the root
Jenkins job.

soc-ci: Refactor fetching job details from Jenkins

---

scripts/jenkins/ardana/ansible/init.yml
scripts/jenkins/ardana/ansible/repositories.yml

In preparation for being able to serve them to managed nodes, NFS mount
the SLES and Cloud repositories from the mirror instead of configuring
them with HTTP. Since Ardana already serves repositories from
/opt/ardana_packager, symlink the mounts there after ardana-init sets it
up. We also need to ensure the nodes trust the Devel:Cloud:8 so that we
don't have to use disable_gpg_check in the ansible playbooks.
With mkcloud/crowbar, we mounted these repositories in /srv/tftpboot.
With Ardana, we must choose a different directory since the
deployerincloud* models install the dnsmasq package (for neutron) on the
deployer node, which forces /srv/tftpboot to be globally unreadable and
unsearchable.
For now, we still need to keep the HTTP-based repositories installed.
Once changes in …

NFS mount Cloud and SLES repos

---

jenkins/ci.suse.de/ardana-job.yaml

This changes the behavior - if job_name is empty, the resulting
heat stack is wiped. if it is set non-empty, it is remaining
active.
This also add a periodic rebuild on every new media being
published.

Regularly run ardana-job and clean up results

---

scripts/scenarios/cloud8/qa/no-ssl/qa-scenario-2c.yaml
scripts/scenarios/cloud8/qa/ssl-insecure/qa-scenario-2c.yaml

Ceph deployment through crowbar is not supported in SOC8. This
change removes the Ceph barclamp and update the scenario to support
consuming an external SES deployment.

Fix QA scenario 2c

---

scripts/github_pr/github_pr_crowbar.yaml

Meanwhile there are more teams than just one.
The original one was renamed as well.
The pull requests of members with write access should be built by our CI. So we need to allow all these teams in the github_pr config for crowbar.
Without this fix there are several people whose pull requests will never be built.

github_pr: update crowbar teams

---

jenkins/ci.suse.de/cloud-crowbar-testbuild-pr.yaml
jenkins/ci.suse.de/openstack-mkcloud.yaml

Switch openstack-mkcloud and crowbar-testbuild jobs to use github_pr instead of github-status.
The latter is obsolete and will be replaced by github_pr.
Several jobs already switched to it, this PR will switch the remaining jobs.

Set status with ghpr

---

jenkins/ci.suse.de/ardana-job.yaml

We still need some of the files from the workspace then to
manually debug stuff

skip workspace cleanup when the build failed

---

scripts/jtsync/jtsync.rb
scripts/jtsync/test_jtsync.sh

The mapping for the jenkins job cloud-mediacheck differs from the rest.
The mapping for all ci.opensuse jobs was broken because the variable project of
the class Mapping is only readable.
Signed-off-by: Jürgen Löhel <jloehel@suse.com>

Fixes the mapping of jtsync and adds tests for it.

---

jenkins/ci.suse.de/ardana-job.yaml

Previously it was starting the build when there was something new
in NUE. Turns out there is a significant delay between NUE
and provo, so this was racy..

Start a build when the provo mirror finished syncing

---

jenkins/ci.suse.de/ardana-job.yaml
scripts/jenkins/ardana/ansible/repositories.yml

This makes it easy to look at the build job log for a host which you're already connected to.

ardana-job: put the Jenkins build job URL in /etc/motd

---

hostscripts/soc-ci/README.soc-ci.md
hostscripts/soc-ci/soc-ci

SSL verification should be configurable to deal with the cases where the
certificate is invalid (because out of date), or to deal with the
possibility that the host system does not trust the signing CA.

soc-ci: make SSL verification configurable

---

hostscripts/clouddata/syncSLErepos

There seems to be a race with the OBS repopublisher, which first
syncs the rpms and then repodata, which causes the 2nd rsync
to freak out. Go back to syncing the iso and then loopback
sncing it. for that to be of reasonable speed, the bwlimit
needs to be removed.

syncSLErepos: go back to syncing isos and local unpacking

---

scripts/crowbar-testbuild.rb

From time to time triggered jenkins jobs are not processed.
This might be due to various reasons.
In order to easier rebuild a missing job the testbuild
script will now log a rebuild link. The link will open
a confirmation page in jenkins and prefill all parameters.
The job is not starting automatically, one additional
button klick is needed (and wanted as protection).
The one who starts the rebuild should make sure that not
two identical jobs are running in parallel. If there are two
identical jobs the status of the job reporting last will be
the status of that commit on github.

testbuild: log rebuild links to easier rerun a job

---

scripts/github_pr/github_pr_cloud.yaml
scripts/github_pr/github_pr_crowbar.yaml
scripts/github_pr/interactions/ia_cloud.rb

This is similar to https://github.com/SUSE-Cloud/automation/pull/2412
but just adds the logging also to the pull request trigger jobs.
----
From time to time triggered jenkins jobs are not processed.
This might be due to various reasons.
In order to easier rebuild a missing job the PR trigger
jobs will now log a rebuild link. The link will open
a confirmation page in jenkins and prefill all parameters.
The job is not starting automatically, one additional
button klick is needed (and wanted as protection).
The one who starts the rebuild should make sure that not
two identical jobs are running in parallel. If there are two
identical jobs the status of the job reporting last will be
the status of that commit on github.

PR job trigger: log rebuild links to easier rerun a job

---

scripts/qa_crowbarsetup.sh

This commit removes ostestr command usage from qa_crowbarsetup.sh.
Because ostestr doesn't have 'last' subcommand[0] but ostestr just
ignore the 'last' subcommand, actually. However, it just runs same tests
again. It just wastes the resource. So I think it's better to switch to use testr.
In the upstream OpenStack development, we're switching to use stestr[1]
instead of testr. So, it's better to switch to use it in the future.
[0] https://docs.openstack.org/os-testr/latest/user/ostestr.html
[1] http://stestr.readthedocs.io/en/latest/

qa_crowbarsetup: Remove ostestr usage

---

Makefile
scripts/jenkins/update_automation
scripts/jenkins/update_automation-test.sh

For several QA jenkins jobs the feature was used to override
the location of the automation repo. This was used to stage
code changes before they became a pull request.
This feature was accidentally dropped with the latest
refactoring of update_automation.
This commit adds back this feature but with a slightly different
usage.
The definition must follow this pattern:
`<domain>/<owner>/<repo>#<branch>`
e.g. github.com/SUSE-Cloud/automation#master
The definition of the branch can be omitted (incl. the "#").
Then the branch name will use "master" as default.
@gosipyan @kbaikov You will need to adapt the QA jobs to use the new definition.

update_automation: allow to override automation repo

---

jenkins/ci.suse.de/ardana-job.yaml

When init.yml is running site.yml there is not log activity for a very
long time, which cause the jenkins job to timeout for the larger models.
In the mid term we need to find a better solution here. This should be
considererd a temporary fix to address the immediate issue of all jobs
timeing out.

ardana: Increase inactivity timeout even further

---

jenkins/ci.suse.de/cloud-mkcloud7.yaml

The crowbar devsetup is only usefull for the next upcomming version so
in the current case C8.

jjb: Remove crowbar devsetup job from C7

---

jenkins/ci.suse.de/templates/cloud-mkcloud-gating-template.yaml

Instead of only copying a subset from Staging to non-Staging we should copy everything which has a valid link and exists in both repos otherwise we can forget packages.

jjb: Remove packagefilter from gating

---

scripts/jenkins/qa_openstack.sh

Latest Tempest uses stestr now. So when listing tests, use stestr.

qa_openstack: Also check tests when using stestr

---

jenkins/ci.suse.de/openstack-mkcloud.yaml
scripts/mkcloud

We may want mkcloud to act differently on CI runs than on manual
executions. A good example for this would be the timing reports at the
end of the mkcloud run which make more sense only in a CI environment.
We introduce the variable CI_RUN: when enabled, mkcloud should consider
this a CI run. The first use of this variable will be for only enabling
timing reports on manual runs. Note that timing is still profiled, but
not reported.

mkcloud: enable mkcloud options specific for CI

---

hostscripts/clouddata/syncSLErepos

because the standard maintenance expired
and SP3 even though it is empty+unused atm, it will be used later

also sync SP2-LTSS

---

scripts/jenkins/qa_openstack.sh

The need to copy a block of code for each upstream OpenStack release is removed by computing the names automatically.
Deviations could still be added (like "master").
With computing the name also the maintenance effort for this tool is lowered.

qa_openstack: reduce code duplication and maintenance

---

scripts/lib/mkcloud-driver-libvirt.sh
scripts/mkcloud

It can happen that libvirt_vm_start fails (i.e. libvirt: DBus Utils
error : Connection timed out). Right after vm_start there's a wait for
the VM to actually start. This change uses 'safely' to call
libvirt_vm_start and abort it faster in case of an error.

mkcloud: safely for libvirt_vm_start

---

scripts/qa_crowbarsetup.sh

ATM there is only a LTSS-Updates repo for SLES12SP1/cloud6.
But the LTSS-Updates repo is added to the function create_repos_yml
for all cloud versions. This repos will be added to the nodes
allocated in the cloud. That means this repos must be available on
the admin node http://admin:8091/.
Therefore it is required to add the LTSS repo in the prepare function.
Cloud6 has its own onadmin_prepare_sles12sp1_other_repos and for the
newer version there is onadmin_prepare_sles_other_repos.
This requires as well that, if there is not yet a real LTSS repo
available, one has to create an empty folder, export this via NFS and
createrepo in it.

Added LTSS repo to prepare_repo function for cloud7+

---

scripts/jenkins/ardana/ansible/init.yml

Set ARDANA_INIT_AUTO only for the ardana-init task instead of globally
on the playbook. It's the only place where it is needed.

ardana: cleanup environment usage

---

scripts/qa_crowbarsetup.sh

The test simply compares the number of nodes required with the number of
nodes that salt can ping
The `nodes number all` did not
produce the correct result for the physical
setups. So the temprorary solution is to use
`crowbar machines list` until the nodes
function can handle all the cases

Use a test that works for physical nodes too

---

Makefile
README.md

To allow for running it locally, add shellcheck command to
Makefile. searches for all files that contains /bin/bash
(to find the shell scripts) and excludes the yml/yaml files
as they also contains /bin/bash but they are not scripts.
REF: https://github.com/SUSE-Cloud/automation/pull/936

Automation: add shellcheck to makefile

---

jenkins/ci.suse.de/ardana-job.yaml

The jenkins launcher is now running as user "jenkins" to follow
the principle of least privileges, which however caused the job
to fail as we only allow login from root on the deployer.

Explicitly ssh deployer as root

---

hostscripts/rpm-packaging/createproject.py

Sometimes backtraces are longer than 750.

createproject.py: increase cut off for errors to 9000

---

jenkins/ci.suse.de/cloud-mkcloud6-cd-gating.yaml
jenkins/ci.suse.de/openstack-submit-project.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-gating-template.yaml

Support blacklist and whitelist filter for package names to allow for easier configuration of the jobs (no need to list all whitelisted packages, instead list the unwanted ones).
Revert (partially) the wrong commit cdca70f
Adapt package filter in cloud6 cd-gating job.

jjb: fix package filter of submit-project

---

scripts/lib/mkcloud-onhost.sh

With the rename of the product to Crowbar-8 the caching got broken,
as it cached the ardana repositories. Adjust to use the proper
variable name which takes care of that oddity.

mkcloud: fix caching of repositories for Crowbar8+ again

---

jenkins/ci.opensuse.org/openstack-trackupstream.yaml

Add tracking for openstack-neutron-vsphere for everything that is not
Master or Ocata.

openstack-trackupstream: Add openstack-neutron-vsphere

---

scripts/qa_crowbarsetup.sh

Checking if the security group manila-service exists (to create it if it
doesn't) currently prints an expected error:
Error while executing command: No SecurityGroup found for manila-service

qa_crowbarsetup: silence expected error output

---

scripts/qa_crowbarsetup.sh

This patch removes the integration tests we added for the SLES based magnum
image. As for testing magnum, there are funtional tests specific for API and
each COE which should cover creating a cluster template and cluster if
configured properly.

magnum: Remove tests for SLES Image (bsc#1082278)

---

scripts/mkcloud
scripts/qa_crowbarsetup.sh

Re-enables the magnum barclamp previously
disabled in #2140 due to missing packages in the
Ocata-aligned Devel:Cloud:8.
NOTE: do not merge this PR until after the develcloud8
cloudsource has been migrated to Pike and the missing
magnum packages have been corrected.

Re-enable magnum in develcloud8

---

scripts/jenkins/ardana/ansible/init.yml

We no longer plan to ask users to set up repos themselves under /opt.
Instead, we'll ask them to follow a procedure similar to the old
crowbar procedure[1] to set up repositories under /srv. We can also
automate this as a later optimization. In any case, ardana-ansible will
create the needed links from /srv to wherever.
[1] https://www.suse.com/documentation/suse-openstack-cloud-7/book_cloud_deploy/data/sec_depl_adm_conf_repos_product.html

SCRD-2502 Cleanup link from NFS mount to /opt

---

scripts/jenkins/ardana/ansible/init.yml

This avoids having to login as root, which is commonly not
a good practice to follow :-)

ardana-job: add ssh keys also to ~ardana

---

scripts/jenkins/ardana/heat-ardana-std-controller.yaml

The controller nodes in Heat are currently named like
"controller%index%" which is wrong.

ardana: Fix controller resource name in standard heat template

---

scripts/mkcloud

This fixes the case that when even one of the vm's was already shut down,
shutdowncloud would throw an error and mkcloud would hang on the
support config collection, because it waits for the ssh timeout of an
already offline vm.

mkcloud: no config collection on shutdowncloud

---

docs/ardana/rpm-file-checks.md
docs/ardana/testing.md
scripts/jenkins/ardana/ansible/files/rpm-added-files-whitelist.txt
scripts/jenkins/ardana/ansible/files/rpm-verify-modification-whitelist.txt
scripts/jenkins/ardana/ansible/init.yml
scripts/jenkins/ardana/ansible/post-deploy-checks.yml
scripts/jenkins/ardana/ansible/pre-deploy-checks.yml
scripts/jenkins/ardana/ansible/test-post-deployment-checks.yml

See [SCRD-2756 (Add CI checks to ensure SLES updates can be installed any time)](https://suse-jira.dyndns.org/browse/SCRD-2756)
**NOTE:** hasn't been successfully tested the whole way through in a single run yet, due to unrelated issues preventing everything else working.
Check that Ardana doesn't mess with the filesystem inappropriately by removing or modifying rpm-owned files, or adding files into `/usr`.  This is done by running `rpm -Va` and `rpm -qf` before and after Ardana deployment, and comparing the results.
If any tampering is discovered, `init.yml` will fail with a helpful error.
The checks will run even if `site.yml` or tempest failed.  A list of all failures (including `site.yml` and tempest) is displayed at the end, to avoid hiding multiple failures behind one failure.

SCRD-2756 post-deployment sanity checks

---

scripts/mkcloud

So that the user knows which cloud gets turned off, when
there are multiple.

mkcloud: shutdowncloud now prints the cloud name

---

jenkins/ci.suse.de/ardana-trackupstream.yaml

ceph/cephlm is being replaced by extensions-ses, and ardana-ci
seems unused (and is not on the media)

ardana-trackupstream: remove tracking of not-required projects

---

scripts/lib/mkcloud-common.sh
scripts/lib/mkcloud-driver-libvirt.sh
scripts/mkcloud

The function setuphost was called with SKIPSUPPORTCONFIG, but since
setuphost is part of the regex in line 1532 (in ## MAIN ##) error_exit
is not called on setuphost errors, thus the config wasn't collected in
the first place.
The exceptions to this are the two calls to pvcreate and vgcreate
inside the function libvirt_do_setuphost(), which were decorated with
safely, which calls error_exit. But since SKIPSUPPORTCONFIG was set, it
wouldn't collect the configs either.
I removed the SKIPSUPPORTCONFIG on the setuphost call and added a
safely_skip_support decorator function, which provides the same functionality,
but without the config collection, which should make the code more
readable.

mkcloud: Wrapped SKIPSUPPORTCONFIG in function

---

scripts/lib/mkcloud-common.sh

So that in the case that a vm can't be reached, e.g. because it was shutdown or
an error occured before the vm was started, mkcloud doesn't hang on an
ssh request.

mkcloud: Added timout to sshopts

---

scripts/github_pr/interactions/ia_crowbar.rb

Without this parameter the triggered jenkins jobs will default to "crowbar" as organization.
This is an error in case github_pr handles other organizations.

add organisation parameter to job_parameters

---

scripts/jenkins/ardana/ansible/files/std-min/input-model-net-global.yml
scripts/jenkins/ardana/heat-ardana-standard.yaml

The ardana-ci model expects to create a bond0 for -mgmt out of eth1
and eth3, and eth4 is supposed to be the external network. Due to
a typo external-mgmt were swapped, which caused awkward networking
faults. rename _unused to _mgmt2 to make that bond clearer, and
disable vlan for external network as the neutron router needs to
be able to route it.

Fix routing to external network for std-min case

---

jenkins/ci.suse.de/ardana-job.yaml
scripts/jenkins/ardana/ansible/init.yml
scripts/jenkins/ardana/ansible/post-deploy-checks.yml
scripts/jenkins/ardana/ansible/pre-deploy-checks.yml
scripts/jenkins/ardana/ansible/vars/main.yml

This avoids 3 hours of no output and lets us follow the
stream of the deployment instead. convert post-deploy checks into
a playbook that can be invoked on its own.

Run site.yml from the Jenkins Job directly

---

jenkins/ci.suse.de/cloud-trackupstream.yaml

The branding packages are not being sync automatically, causing them to fall behind the "upstream" github counterparts if there isnt a manual sync done. Adding those packages to the upstream sync job should mitigate that issue.

Add branding packages to upstream sync job

---

scripts/jenkins/ardana/ansible/files/rpm-verify-modification-whitelist.txt

**DON'T MERGE until [gerrit#I51c2bf0c](https://gerrit.suse.provo.cloud/#/c/3800/) is merged**
Ardana was incorrectly modifying `/etc/logrotate.conf`, so we had to temporarily add an exception to the rpm verification whitelist for modified files in order to avoid `ardana-job` permanently failing.  However once [gerrit#I51c2bf0c (SCRD-2080 don't replace standard /etc/logrotate.conf)](https://gerrit.suse.provo.cloud/#/c/3800/) is merged, this exception is no longer necessary.

SCRD-2080 Revert to expecting logrotate.conf not to be modified

---

scripts/jenkins/ardana/ansible/repositories.yml

This is more resilient to transient media replacement during
runs.

Mount cloud repo as repo-md

---

scripts/lib/mkcloud-common.sh

Apparently users of the provo VPN endpoint are stumbling over
not setting to be x86_64 only (even if they only want to use x86_64).
So add some magic to detect the case and stop mounting non-x86_64
mointpoints in that case.

mkcloud: default to x86_64 only when using the provo mirror

---

scripts/scenarios/cloud8/cloud8-ironic-swift-ha.yml

See bug https://bugzilla.suse.com/show_bug.cgi?id=1087472

The drivers pxe_ssh, agent_ssh and fake_ssh are no longer available

---

scripts/jenkins/ardana/heat-ardana-deployerincloud-lite.yaml
scripts/jenkins/ardana/heat-ardana-standard.yaml
scripts/jenkins/ardana/heat-ardana-std-controller.yaml

The cassandra and spark stuff crashes with OOM all the time, even already during deploy. we need to switch to larger flavors. use custom flavor names to that we're more flexible going forward.

Increase memory for ardana jobs

---

scripts/qa_crowbarsetup.sh

We were missing this bit when creating new PTF repos for next version
of the product.
See https://github.com/SUSE-Cloud/automation/commit/0b7e5f2af609951ead16bf6390e0fd6f97c79d97

upgrade: Create and sign PTF repos the same way as normal install

---

scripts/qa_crowbarsetup.sh

We generate the certificates, so the insecure flag is necessary; without
this, crowbarctl command will fail trying to validate the certificates.

qa_crowbarsetup.sh: Set insecure flag for crowbar when using ssl

---

jenkins/ci.suse.de/openstack-ardana.yaml

Allows the selection of the image_id_compute parameter in the
openstack-ardana job.
Indirectly fix the issue when this parameter is not passed from
cloud-ardana-job-std-min-centos-template.yml template file.

Allows selection of image_id_compute

---

jenkins/ci.suse.de/cloud-mkcloud6.yaml

With Cloud6 going into LTSS mode, we can reduce those tests that
never passed during the lifecycle of cloud6

Remove cloud6 jobs that were never green

---

hostscripts/clouddata/syncSLErepos

Sync the Cloud repos first. This is usually the thing I care about
when calling the script manually.
Also do 8, 7 and then Cloud 6. Then development version is usually the
one that changes often.

syncSLErepos: Change sync order

---

hostscripts/clouddata/syncSLErepos

We have to rename the "HPE Helion OpenStack Cloud" product to "HPE
Helion OpenStack" (see bsc#1090093).

syncSLErepos: Sync the Helion Openstack iso

---

jenkins/ci.suse.de/openstack-ardana.yaml
scripts/jenkins/ardana/ansible/files/dac-3cp/input-model/disks_controller.yml
scripts/jenkins/ardana/ansible/files/dac-3cp/input-model/firewall_rules.yml
scripts/jenkins/ardana/ansible/files/dac-3cp/input-model/interfaces_set_1.yml
scripts/jenkins/ardana/ansible/files/dac-3cp/input-model/net_global.yml
scripts/jenkins/ardana/ansible/files/dac-3cp/input-model/network_groups.yml
scripts/jenkins/ardana/ansible/files/dac-3cp/input-model/nic_mappings.yml
scripts/jenkins/ardana/ansible/templates/dac-3cp/input-model-servers.yml
scripts/jenkins/ardana/heat-ardana-dac-3cp.yaml
scripts/jenkins/ardana/heat-ardana-dac.yaml
scripts/jenkins/ardana/heat-ardana-std-controller.yaml

Add support for the dac-3cp input model, which combines
a 3 controller cluster with a deployer-as-controller
scenario. This can be used to test controller reboot
scenarios (3 controllers are needed to ensure galera
cluster quorum).

openstack-ardana: enable dac-3cp input model

---

jenkins/ci.suse.de/cloud-suse-cloud-specs.yaml

the mode "normal" (from jenkins job) is called "unseen" as parameter

jjb: cloud-specs test - set correct mode for github_pr

---

jenkins/ci.suse.de/cloud-suse-cloud-specs.yaml
scripts/github_pr/suse.cloud-specs.helper.sh

Make sure a new job starts with an empty workspace.
Even save space during a specs-test run, by removing the artifacts after each PR, to not let the workspace accumulate to much disk usage.

Cleanup cloud specs tests

---

scripts/jenkins/ardana/heat-ses-cluster.yaml
scripts/jenkins/ardana/heat-ses-mon-node.yaml
scripts/jenkins/ardana/heat-ses-osd-node.yaml

This might be useful when testing the external SES integration for
Ardana in the engcloud (but can be used in any cloud running Heat).
Use the stack with:
openstack stack create --parameter "ses_key_name=tbechtold" \
-t heat-ses-cluster.yaml  --wait ses-stack-name
When calling heat-ses-cluster.yaml, the "ses_key_name" is
mandatory and the used ses_image_id (defaults to jeos-SLE12SP3) needs
to contain cloud-init.
After the stack creation, you can login via the floating ip (see
"openstack stack show ses-stack-name") and watch the deployment
process of the ceph cluster via:
tail -f /var/log/cloud-init-output.log
TODO: Connect the deployed cluster with a ardana deployment.

ardana: Add heat templates to deploy SES in an OpenStack cloud

---

Makefile

There seems to be some existing packages in travis which may be outdated
or missing requirements. In this case requests seems to be installed
but not urllib3.
A simple pip install wont update those existing packages leaving the
environment kind of broken for our tests. So instead mark the pip
install with -U so it upgrades the existing  packages, which in turn
installs the dependencies correctly.

force upgrade existing python packages

---

scripts/qa_crowbarsetup.sh

If test repositories were used for the original deployment,
they should be generated also for the upgraded setup.

upgrade: Generate /etc/crowbar/repos.yml for upgraded setup (SCRD-3125)

---

scripts/lib/mkcloud-common.sh

To avoid confusion regarding the meaning of various version modifiers
such as `6plus` or `6minus` this change expands on the description of
the function arguments.

Update documentation of `getcloudver`

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-2b.yaml
scripts/scenarios/cloud8/qa/no-ssl/qa-scenario-2b.yaml

Scenario 2b update to use the vmware_dvs ml2 plugin.
See the documentation in: https://gitlab.suse.de/qa/cloud-doc/blob/master/vmware-dvs.md
The original scenario was not using the DVS ml2 plugin, so could connect to the existing vmware cluster installation.
vmware_dvs plugin has a limitation: the openstack and vmware should be connected to the same Layer 2 segment (same switch). So before running the scenario the user has to install vmware manually on the spare node (documented in https://gitlab.suse.de/qa/cloud-doc/blob/master/vmware.md).
Several barclamps now use vmware (glance, cinder, neutron and nova)

Update vmware scenario 2b to use vmware_fvs ml2 plugin

---

scripts/qa_crowbarsetup.sh

The latest guidelines are 2018.02
Use the subunit-2to1 filter
Use the local refstackserver to upload the resuls since
the official server now requires keys

Update defcore function to use the latest guidelines

---

scripts/jenkins/ardana/ansible/files/std-split/input-model/disks_controller.yml
scripts/jenkins/ardana/ansible/files/std-split/input-model/firewall_rules.yml
scripts/jenkins/ardana/ansible/files/std-split/input-model/interfaces_set_1.yml
scripts/jenkins/ardana/ansible/files/std-split/input-model/net_global.yml
scripts/jenkins/ardana/ansible/files/std-split/input-model/network_groups.yml
scripts/jenkins/ardana/ansible/files/std-split/input-model/nic_mappings.yml
scripts/jenkins/ardana/ansible/init.yml
scripts/jenkins/ardana/ansible/templates/std-split/input-model-servers.yml
scripts/jenkins/ardana/heat-ardana-std-split.yaml

The std-split model is testing a 3 control plane cluster
separation and is hence useful for testing a more scaled out
mid-sized cloud

Add support for std-split model testing

---

scripts/qa_crowbarsetup.sh

Interestingly, testpostupgrade used openstack stack delete to drop the
stack, and then used the heat command to check the status. Switch to the
openstack CLI.

testpostupgrade: Use openstack stack show

---

scripts/github_pr/github_cloud-specs.yaml

Usually developers fork a repository and create PRs from their
forks to the upstream repository.
For SUSE/cloud-specs this is a bit different.
To allow PR checking for all PRs even if they came from the a
branch of the repository itself (instead of a fork) we hereby
allow PRs from the user SUSE (which is the organization user).

github_pr: allow pr checks from non-fork branches

---

jenkins/ci.suse.de/cloud-ardana8.yaml
jenkins/ci.suse.de/templates/cloud-ardana-job-std-3cp-update-template.yaml

Create a job that installs a 3 controller node cloud based
on D:C:8 and then runs the maintenance update workflow [1] to
update packages to the D:C:8:Staging baseline.
The purpose of this job is to test that staging changes do
not break the documented maintenance update workflow.
[1] http://docserv.suse.de/documents/SUSE_OpenStack_Cloud_8/suse-openstack-cloud-operations/html/system_maintenance.html#maintenance_update

jjb: add cloud-ardana8-update-x86_64 job (SCRD-3018)

---

jenkins/ci.suse.de/cloud-mkcloud7.yaml
jenkins/ci.suse.de/cloud-mkcloud8.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-disruptive-ha-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-nondisruptive-ha-mariadb-template.yaml

For now we're testing the setups that do not need DB migration.

upgrade: Use MariaDB as initial database option for SOC7-SOC8 upgrades

---

jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-nondisruptive-ha-mariadb-template.yaml

We want to test changing the setup as well, but let's save it for another
jobs.

upgrade: Start the upgrade with rabbitmq already using clustered setup

---

scripts/jenkins/ardana/ansible/reboot-node.yml
scripts/jenkins/ardana/ansible/update-node.yml

Introduces a couple of fixes for the Jenkins Ardana package update job:
1. fixes a bug which ran ardana-init several times instead of just one time when a CLM package update was installed
2. adds a workaround for [bsc#1091479](https://bugzilla.suse.com/show_bug.cgi?id=1091479) which is to restart spark services on all nodes after a node reboot
With the workaround at 2. in place, we should have a successful update run.

openstack-ardana: fixes for the cloud-ardana8-update job

---

jenkins/ci.suse.de/cloud-ardana8.yaml
jenkins/ci.suse.de/openstack-ardana.yaml
jenkins/ci.suse.de/templates/cloud-ardana-job-std-3cp-test-mu-template.yaml
scripts/jenkins/ardana/ansible/pre-update-checks.yml
scripts/jenkins/ardana/ansible/repositories.yml

Creates a job which tests that it is possible to install
pending SLES and Cloud8 test updates as maintenance updates
using the Ardana update workflow. The test automation job
does the following:
- uses SOC8 GM cloudsource + already released maintenance updates
- does a full deployment (min 3 controller nodes are required)
- validate that the deployment works (runs tempest tests)
- add the SLES12-SP3-Updates-test and SUSE-OpenStack-Cloud-8-Updates-test 
repositories
- run the maintenance update workflow to update all nodes in the cloud
- validate that the deployment works (tempest tests again)
Also updates the openstack-ardana job to allow for individual repositories to be
configured and to run tempest before applying the update.

jjb: add cloud-ardana8-test-mu-x86_64 job (SCRD-3207)

---

jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-nondisruptive-ha-mariadb-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-nondisruptive-ha-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-nondisruptive-ha-without-nodes-upgrade-template.yaml

This is due to speed up the deployment process, so that regular
testing is more efficient.

upgrade: Do not deploy barclamps that are tech previews

---

jenkins/ci.suse.de/openstack-ardana.yaml

We delete the logs in less then a day but they are important so we
should keep them longer.

jjb: openstack-ardana keep logs the same time as for mkcloud

---

scripts/jenkins/ardana/ansible/repositories.yml

Using rsync to bring the cloudsource media contents
on the deployer instead of NFS-mounting it to avoid
'msg: Media source does not contain the desired medium'
errors occurring when the provo-clouddata contents
are resynced while a job is running.

openstack-ardana: rsync cloudsource repository

---

jenkins/ci.suse.de/cloud-mkcloud6.yaml

Cloud 6 is only maintained for SAP and they don't use this so we can
remove the jobs.

Remove XEN and RAID Jobs from Cloud 6

---

scripts/mkcloud

The database step of the upgrade workflow was dropped.

When upgrading to SOC8, we do not need to boostrap crowbar

---

jenkins/ci.suse.de/cloud-ardana8.yaml
jenkins/ci.suse.de/openstack-ardana.yaml
jenkins/ci.suse.de/templates/cloud-ardana-job-dac-3cp-template.yaml
jenkins/ci.suse.de/templates/cloud-ardana-job-std-3cp-devel-staging-updates-template.yaml
jenkins/ci.suse.de/templates/cloud-ardana-job-std-3cp-template.yaml
jenkins/ci.suse.de/templates/cloud-ardana-job-std-3cp-test-maintenance-updates-template.yaml
jenkins/ci.suse.de/templates/cloud-ardana-job-std-min-centos-template.yaml
jenkins/ci.suse.de/templates/cloud-ardana-job-std-min-template.yaml

This changeset implements a simple virtual resource pool
mechanism trying to mimick mkcloud's hardware allocation
logic but applied to the heat stack resources provisioned
by the openstack-ardana Jenkins job.
This is needed in order to have the heat stack setup available
e.g. for debugging after the job completes and at the same
time employ some form of cleanup.
A named resource pool concept is created, where each pool
consists of a number slots and each slot can be allocated to
a single heat stack. The openstack-ardana job will preserve
created heat stacks in a suspended state, up to a maximum
number of slots configured for each resource pool. Older
heat stacks are removed at the beginning of every job run.
Heat tags are used to associate heat stacks with their
individual resource pools. …

openstack-ardana: virtual resource pools for heat stacks

---

scripts/jenkins/ardana/ansible/files/rpm-added-files-whitelist.txt
scripts/jenkins/ardana/ansible/files/rpm-verify-modification-whitelist.txt

Adds more exceptions to the post-validation whitelist for
rogue files and modified RPM owned files, to work around issues
revealed when running on the dac-3cp input model, which installs
an integrated deployer (e.g. https://ci.suse.de/job/openstack-ardana/1515).
Bugzilla entries have been created to track exceptions that need
to be fixed:
* octavia installs in /usr/lib/systemd/system/ and /usr/share/octavia system paths (bsc#1094847)
* permissions changed for RPM owned path /var/log/spark (bsc#1094851)
* permissions changed for RPM owned paths /var/log/monasca and /etc/monasca/agent (bsc#1094873)
* permissions changed for RPM owned path /var/log/cassandra (bsc#1094850)
* permissions/owner changed for RPM owned file /etc/storm/storm.yaml (bsc#1094971)
* /usr/lib64/libreiserfscore.so.0 is …

openstack-ardana: add post-validation exceptions

---

jenkins/ci.suse.de/openstack-ardana.yaml
scripts/jenkins/ardana/ansible/post-deploy-checks.yml
scripts/jenkins/ardana/ansible/pre-update-checks.yml

Use the image files available at provo-clouddata instead
of downloading them from the external source. This will
reduce the overall flakiness of Ardana Jenkins jobs
(see https://bugzilla.suse.com/show_bug.cgi?id=1094862)

openstack-ardana: use provo-clouddata image mirror

---

jenkins/ci.suse.de/openstack-ardana.yaml

Fixes the cleanup logic used to determine the list
of old stacks in a stack pool which need to be
deleted when a job begins.
The current logic fails to cover cases where the number
of old jobs is lower than the maximum number set for the
job pool. The effect is that a new job deletes all old
stacks that it finds.
Replacing tail with awk helps better encode the logic of
selecting "all but the first X-1, chronologically sorted
stacks" used to determine which stacks need to be deleted.

openstack-ardana: fix build pool cleanup

---

scripts/mkcloud

I think this job https://ci.suse.de/job/openstack-mkcloud/119839/console has failed because crowbar was not yet available when the `crowbarctl upgrade repocheck nodes` command was executed.

Wait for crowbar to be running end responding after the reboot

---

jenkins/ci.opensuse.org/openstack-devstack.yaml

This should prevent from blocking the build worker for too long.
Sometimes it happens that the devstack job gets stuck and produces no more output. In these cases we want to abort the job and free the worker for the next job.

jjb: add timeout of 60 min. for devstack job

---

scripts/lib/mkcloud-common.sh

in case this function is used in places where the password is not public

ssh_password: dont have the password world readable

---

scripts/lib/libvirt/libvirt_setup.py

making it more python2 and python3 compatible
python2
```
In [2]: next(itertools.chain('abc','def'))
Out[2]: 'a'
```
python3
```
In [25]: itertools.chain('abc','def').next()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-25-c7429c06af55> in <module>()
----> 1 itertools.chain('abc','def').next()
AttributeError: 'itertools.chain' object has no attribute 'next'
In [26]: next(itertools.chain('abc','def'))
Out[26]: 'a'
```

fix usage of next function

---

scripts/mkcloud

e342651 switched mkvlan from using `ifconfig(8)` to `ip(8)`, because `ifconfig` was deprecated.  Unfortunately this broke idempotence, because if the IP address already exists, `ip addr add` will fail, causing steps which call `setuppublicnet` to break if called more than once after a reboot.
So check whether the IP exists, and if it does, don't try to re-add.

 make mkvlan idempotent

---

scripts/qa_crowbarsetup.sh

Based on an experience yesterday, this can happen if the iso is momentarily unavailable (presumably while being updated?!)

don't assume the ISO download succeeded

---

scripts/jenkins/qa_devstack.sh

swift-container-sharder was missing from the list stalling from ssh to
finish

devstack: updated list of killall swift jobs on exit

---

scripts/jenkins/ardana/heat-ardana-dac.yaml
scripts/jenkins/ardana/heat-ardana-deployerincloud-lite.yaml
scripts/jenkins/ardana/heat-ardana-standard.yaml
scripts/jenkins/ardana/heat-ses-cluster.yaml

When a ResourceGroup is used to group multiple servers
together, the implicit dependency between those servers
and the list of networks they are attached to no longer
works [1].
The result of this is we get intermittent errors when
deleting heat stacks, because subnets are deleted before
the servers that are using them.
The workaround (and recommendation [2]) is to use a subnet
list or a port list instead of a network list when defining
OS::Nova::Server resources.
[1] https://bugs.launchpad.net/heat/+bug/1547435
[2] https://bugs.launchpad.net/heat/+bug/1243992

openstack-ardana: fix subnet heat resource deps

---

jenkins/ci.suse.de/cloud-mkcloud8.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-disruptive-ha-mariadb-template.yaml

We need to place rabbitmq shared storage away from admin server.
NFS setup on admin server gets wiped out during the upgrade.
**Requires** https://github.com/SUSE-Cloud/automation/pull/2567

Use lonelynode with NFS server for disruptive job as well.

---

scripts/qa_crowbarsetup.sh

In HA setups apply nfs_client barclamp only when neither swift nor
ceph are deployed.
In non HA setups stay with the local file backend for glance, even when
swift is deployed.

qa_crowbarsetup: Use swift backend for glance when swift is deployed

---

scripts/github_pr/interactions/ia_cloud.rb

github_pr supports a dryrun option. In order to support this the call to 'system' needs to be change to a wrapper method that will check if dryrun is set.
Without this dryrun is not possible with the cloud config for github_pr.
The change in github_pr is in this commit:
https://github.com/openSUSE/github-pr/commit/fcb1b30ba15869571e766e1d07c2ee9878920094

github_pr: allow dryrun for cloud config

---

jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-disruptive-ha-mariadb-template.yaml

There's no need to include the lonely node in the nodenumber sum.
Use the number provided by cloud-mkcloud8.yaml

Fixes for the disruptive HA job

---

scripts/qa_crowbarsetup.sh

This allows to replicate a setup with rabbit on a separate cluster.

qa_crowbarsetup: allow rabbit on an extra cluster

---

hostscripts/rpm-packaging/createproject.py

with the move to per-project requirements, we can no longer use
the rpm-packaging maintained global requirements.txt because it
doesn't contain useful dependencies anymore.

rpm-packaging: Remove dependency on global-requirements.txt

---

jenkins/ci.opensuse.org/openstack-repocheck.yaml

Ocata wasn't build for Leap15 and we have no interest in adding
it - Pike+ would be a better target

Filter Leap 15 for Ocata

---

hostscripts/clouddata/syncSLErepos

runs are already failing because they are missing:
https://ci.suse.de/view/Cloud/view/Builds/job/openstack-mkcloud/123209/console

syncSLErepos: sync crowbar test-updates

---

jenkins/ci.suse.de/cloud-mkcloud8.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-nondisruptive-ha-mariadb-debug-template.yaml

Other than the debug option, it's just a copy of cloud-mkcloud-job-upgrade-nondisruptive-ha-mariadb-template.yaml

Add an extra upgrade job that has OpenStack debug logging on

---

jenkins/ci.suse.de/cloud-mkcloud7.yaml
jenkins/ci.suse.de/cloud-mkcloud8.yaml

The Cloudfoundry Ci has upgraded to Pike+, they're no longer
interested in ocata, so we can retire the testing.

Remove ocata mkcloud job

---

jenkins/ci.suse.de/cloud-trackupstream.yaml

This is needed so that the package pulls updates daily from
SUSE/caasp-openstack-heat-templates.

Adding caasp-openstack-heat-templates to trackupstream

---

scripts/mkcloud

Several jobs fail to gather supportconfig data from the nodes
because of the timeout. 
See e.g. https://ci.suse.de/job/openstack-mkcloud/124937/console

Give supportconfig more time to gather data

---

scripts/qa_crowbarsetup.sh

That means also for the successful case, so we know the values
of all those checks.
Especially so we know why the upgrade mode was selected as non-disruptive or normal.

Always show the upgrade prechecks result in the build log

---

scripts/qa_crowbarsetup.sh

In some cases it was mistakingly executed for the normal mode causing
confusing errors (see SCRD-4051)

Make sure testpostupgrade step is only executed for non-disruptive upgrade

---

scripts/jenkins/ardana/ansible/repositories.yml

Using the repository from the SUSE internal IT team
to install sshpass instead of the old one, which is
not well maintained.
NOTE: this is requires to unblock the Ardana gating job, which is now failing due to an expired or incorrect key being used with the old repository.

Replace zypper repo for sshpass

---

jenkins/ci.suse.de/openstack-mkcloud.yaml
scripts/mkcloudhost/allocpool

In case allocpool finds a process with the pid of the pid file,
also the cmdline needs to be matched to verify, if this process
was an mkcloud run.
Otherwise it might happen (and it did) that the pid counter runs
over and restarts and a pidfile now holds a pid of a different
process (in our case a deamon). This would block a slot from
allocpool even though there no longer is an mkcloud process.
This change does the comparision of the cmdline.

allocpool: match cmd name when pid found

---

scripts/qa_crowbarsetup.sh

Such change is introduced with https://github.com/crowbar/crowbar-openstack/pull/1713
Currently only with a check for SOC7. May be extended for SOC8 once we decide on schema changes there.

Adapt search for database attributes to the changes in schema

---

scripts/jenkins/ardana/ansible/files/input-model-net-global.yml

The subnet ranges configured in the input model for
the ARDANA-NET and MANAGEMENT-NET networks didn't match
those used in the heat template. This caused the newer
version of configuration processor to complain with the
following type of message:
```
ERR: Server ardana-ccp-c0-m1 (192.168.245.4) using
interface model ARDANA-INTERFACES does not have a
connection to a network which contains its address.
```
, which basically means that the addresses assigned
to servers in servers.yml (i.e. allocated by heat/openstack)
don't match the address ranges configured in the net_global.yml
file.

openstack-ardana: fix network subnet ranges

---

jenkins/ci.suse.de/openstack-ardana.yaml

Ignore errors encountered while cleaning up old stacks,
to avoid aborting an important job, such as the gating
job because of cleanup related issues.
This is hopefully just a temporary measure, until there
is a better strategy for planning engineering cloud
maintenance windows, which are currently impacting the
gating jobs too often.

openstack-ardana: ignore stack cleanup errors

---

scripts/jenkins/ardana/ansible/files/rpm-verify-modification-whitelist.txt

The owner changes made by Ardana playbooks to the
/etc/storm/storm.yaml configuration file have been
fixed [1][2].
[1] https://bugzilla.suse.com/show_bug.cgi?id=1094971
[2] https://gerrit.suse.provo.cloud/4209
NOTE: this is only required by the dac-3cp openstack-ardana Job, which is currently failing because this post-validation check is obsolete.

openstack-ardana: update post-validation for storm.yml

---

jenkins/ci.opensuse.org/templates/openstack-rpm-packaging-sles12.yaml

it is desirable to follow the project build log so printing
the link earlier

rpm-packaging: echo the home project link earlier

---

jenkins/ci.suse.de/openstack-ardana.yaml
scripts/jenkins/ardana/ansible/ansible.cfg
scripts/jenkins/ardana/ansible/post-deploy-checks.yml

This is part of [SCRD-4003-Merge the automation scripts/tools used by QA and CI](https://jira.prv.suse.net/browse/SCRD-4003).
As QA is using using ansible 2.6.2 from within a virtual environment, this change applies the same approach to the CI.
It also adds a customized `ansible.cfg` with some optimizations, the same used for QA.
Tested in: https://ci.suse.de/job/openstack-ardana-flavio/5/

Use ansible 2.6.2 from virtual environment for ardana CI

---

jenkins/ci.opensuse.org/openstack-cleanvm.yaml

For testing Rocky on SP4 we need to enable SP4. This is first done on Master and later on Rocky, once that repository exists.
Jira: https://jira.prv.suse.net/browse/SCRD-4291

Add SP4 to Master repository

---

jenkins/ci.suse.de/openstack-ardana.yaml

The ansible virtualenv must be entered before any ansible
commands are called.

openstack-ardana: fix ansible virtualenv call

---

jenkins/ci.suse.de/openstack-ardana.yaml

The information provided by the additional output is not really required
and just complicates the output.

openstack-ardana: Remove set -x/+x in the publishers

---

jenkins/ci.suse.de/openstack-ardana.yaml
scripts/jenkins/ardana/ansible/_update-clm.yml
scripts/jenkins/ardana/ansible/init.yml
scripts/jenkins/ardana/ansible/reboot-node.yml
scripts/jenkins/ardana/ansible/reboot.yml
scripts/jenkins/ardana/ansible/roles/heat-generator/tasks/main.yml
scripts/jenkins/ardana/ansible/update-node.yml
scripts/jenkins/ardana/ansible/update.yml

Using -vvv is flooding the logs with ansible connection
information which has never proven useful in the past.
Reducing verbosity to make the output easier to decipher
(-v should be sufficient for most purposes).
Result: the size of the raw log file for a std-min job has been reduced from 30M to 20M

openstack-ardana: reduce ansible verbosity

---

scripts/lib/qa_crowbarsetup-help.sh
scripts/qa_crowbarsetup.sh

The fetching of ISOs was hardcoded to always sync from
download.suse.de/install. However the SUSE IT team is frequently
cleaning up that directories, which means ISO's that we rely on
are disappearing and breaking our CI. Any attempt at getting them
restored is time consuming. So instead we'll now host those isos
that we rely on on clouddata. Some refactoring and renaming of
parameters makes what is happening a bit more obvious.

Make GM6/GM7 cloudsource more reliable

---

jenkins/ci.suse.de/openstack-ardana-heat.yaml
jenkins/ci.suse.de/openstack-ardana.yaml

Moves the heat stack management logic (creating and cleaning
up heat stacks) to its own Jenkins job and makes it more robust:
* concurrency is disabled for the new job, to avoid overloading
the engcloud with simultaneous heat requests and to allow the
build pool management logic to run in a form of critical section.
* having a separate job dealing with the engcloud will make it
more obvious when there's a problem with it
* the cleanup job is triggered after the main openstack-ardana
job has completed. It will not block the main job and its failure
status will not change the status of the main job
* if a heat stack cannot be deleted, an alternative implementation
which directly deletes servers and volumes is now available
* the new openstack-ardana-heat job can be triggered manually
to …

SCRD-4417 openstack-ardana: move heat stack management to separate job

---

scripts/jenkins/ardana/ansible/files/rpm-added-files-whitelist.txt

A recent Ardana installer UI change caused the
/usr/share/ardana/ardana-installer-ui/web/config.json
file to be created and detected as a rogue RPM file.
This PR adds an exception to unblock the CI, while
the issue is being tracked by https://bugzilla.suse.com/show_bug.cgi?id=1104047.

openstack-ardana: add ardana-installer-ui rogue file exception

---

jenkins/ci.suse.de/openstack-ardana.yaml

Fixes the deployer IP message being displayed at the end
of a job run to reflect the floating IP value instead of
the management IP value.

openstack-ardana: fix deployer IP message

---

scripts/github_pr/github_pr_cloud.yaml

Github_pr meanwhile allows to skip certain filters from
the config. This is useful when manually triggering
actions from a PR that would usually be filtered out.
Therefore filters can be marked as skippable.
Details in these commits of the github-pr repo:
https://github.com/openSUSE/github-pr/commit/12965f424a6f18d71f4bc75ef88194d9772f75e2
https://github.com/openSUSE/github-pr/commit/1f34fc2217c6eb8dac7f80e2669b21b378e999f7
Hint:
This will allow to trigger PR gating runs from external contributors using github_pr.

github_pr: allow to skip TrustedSource filter

---

jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-disruptive-ha-template.yaml

We attempt to build and use a lonely node during the disruptive HA job,
but we don't set a number of lonely nodes we require.

Add a lonely node to upgrade-disruptive-ha

---

jenkins/ci.suse.de/cloud-mediacheck.yaml

Cloud6 == EOL
Mitaka/Ocata == only for CF CI, no longer in use
Add Cloud9/SUSE missing media check

Remove unmaintained medias from mediacheck

---

scripts/jenkins/ardana/ansible/files/sshpass.sh
scripts/jenkins/ardana/ansible/init.yml
scripts/jenkins/ardana/ansible/repositories.yml

The functionality provided by the sshpass package is
replaced by a simple script which essentially provides
the same functionality (some bits take from mkcloud-common.sh).
This way, we remove the need to install a special repository
for the sshpass package and all intermittent failures associated
with this repository.

openstack-ardana: remove the need for the sshpass package

---

jenkins/ci.suse.de/cloud-ardana8-suse.yaml
jenkins/ci.suse.de/cloud-ardana9.yaml
jenkins/ci.suse.de/openstack-ardana.yaml
jenkins/ci.suse.de/templates/cloud-ardana-job-dac-3cp-template.yaml
jenkins/ci.suse.de/templates/cloud-ardana-job-std-3cp-devel-staging-updates-template.yaml
jenkins/ci.suse.de/templates/cloud-ardana-job-std-3cp-template.yaml
jenkins/ci.suse.de/templates/cloud-ardana-job-std-3cp-test-maintenance-updates-template.yaml
jenkins/ci.suse.de/templates/cloud-ardana-job-std-min-centos-template.yaml
jenkins/ci.suse.de/templates/cloud-ardana-job-std-min-template.yaml
jenkins/ci.suse.de/templates/cloud-ardana-job-std-split-template.yaml
scripts/jenkins/ardana/ansible/generate-heat.yml
scripts/jenkins/ardana/ansible/init.yml
scripts/jenkins/ardana/ansible/repositories.yml
scripts/jenkins/ardana/ansible/roles/cloud-common/defaults/main.yml
scripts/jenkins/ardana/ansible/roles/heat-generator/defaults/main.yml
scripts/jenkins/ardana/ansible/roles/heat-generator/vars/standard.yml
scripts/jenkins/ardana/ansible/update-node.yml

Updates the previous `cloudsource` ansible variable
in the Ardana deployment automation playbooks to
closer resemble the `cloudsoure` parameter used by
mkcloud jobs. The `cloudsource` variable values will now
encode both the cloud version and media:
- a stagingcloud\<X\> value corresponds to Devel:Cloud:X:Staging
media
- a develcloud\<X\> value corresponds to Devel:Cloud:X media
- a GM\<X\> value corresponds to the official GM media (not
yet available for Cloud9)
All the Ardana deployment playbooks have been updated to
differentiate between cloud releases and new jobs have been 
created for cloud 9.

openstack-ardana: created jobs for Ardana 9

---

jenkins/ci.suse.de/openstack-ardana.yaml

The openstack-ardana-heat cleanup job is triggered, even after a
successful job, to suspend the heat stack used by the main
openstack-ardana job. The cleanup job needs access to the
workspace used by the main job, to pass parameters via
a properties file, so the workspace used by the main job
mustn't be deleted in case of success.

openstack-ardana: fix workspace cleanup

---

jenkins/ci.suse.de/openstack-ardana-heat.yaml

The error return codes collected by the various operations
(delete stack, cleanup stack, etc.) are not correctly
collected and this causes false success status indications
(e.g. when creating a stack fails).
Example of a false positive: https://ci.suse.de/job/openstack-ardana-heat/243

openstack-ardana-heat: fix return codes

---

jenkins/ci.suse.de/cloud-ardana-testbuild-gerrit.yaml
scripts/jenkins/ardana/gerrit/build_test_package.py

Sometimes `osc results` returns 'broken' even when the build will eventually succeed. It isn't great to work around this, but for now add a sleep and recheck a few times before actually failing on transient errors.

Add retry around broken build results

---

scripts/qa_crowbarsetup.sh

The value is not an error, it's part of MySQL server mode.
It is only seen in glance/scrubber.log if DEBUG mode is enabled.
See end of https://ci.suse.de/job/openstack-mkcloud/128449/console - the build fails because the check finds ERROR_FOR_DIVISION_BY_ZERO

Ignore ERROR_FOR_DIVISION_BY_ZERO value in glance/scrubber.log

---

jenkins/ci.suse.de/cloud-automation-pr-trigger.yaml
jenkins/ci.suse.de/cloud-crowbar-testbuild-pr-trigger.yaml
jenkins/ci.suse.de/cloud-suse-cloud-specs.yaml

When a PR failed to receive a response from the pr trigger it was not
possible to see what was going on. Enabling debug fixes that.
Example run with it enabled:
https://ci.suse.de/view/Cloud/view/Trigger/job/cloud-automation-pr-trigger/111345/console

pr trigger: enable debug

---

scripts/github_pr/github_cloud-specs.yaml
scripts/github_pr/github_pr_cloud.yaml
scripts/github_pr/github_pr_crowbar.yaml

Otherwise this shows no indication on Github that the PR was processed.

github pr: Set status when pr owner has no permission

---

jenkins/ci.suse.de/openstack-ardana.yaml
scripts/jenkins/ardana/ansible/generate-heat.yml
scripts/jenkins/ardana/ansible/group_vars/all/all.yml
scripts/jenkins/ardana/ansible/group_vars/virt_all.yml
scripts/jenkins/ardana/ansible/init.yml
scripts/jenkins/ardana/ansible/inventory
scripts/jenkins/ardana/ansible/post-deploy-checks.yml
scripts/jenkins/ardana/ansible/pre-deploy-checks.yml
scripts/jenkins/ardana/ansible/pre-update-checks.yml
scripts/jenkins/ardana/ansible/reboot.yml
scripts/jenkins/ardana/ansible/repositories.yml
scripts/jenkins/ardana/ansible/ssh-keys.yml
scripts/jenkins/ardana/ansible/test-post-deployment-checks.yml
scripts/jenkins/ardana/ansible/update.yml

Switch to using the ansible inventory and group_vars instead of generating
a dedicated host file and ardana_net_vars variable file and keeping common
variables in a cloud-common role.

openstack-ardana: make proper use of ansible inventory and group_vars

---

scripts/qa_crowbarsetup.sh

So that the setups with self-signed certificates can pass the tests.

Pass --insecure option to nova boot commands

---

docs/repositories.dot

This allows us to use the https://www.gravizo.com service to embed an [automatically rendered version of this graph into Markdown documentation within GitHub](https://github.com/SUSE/cloud/compare/master...aspiers:repo-graph?expand=1&short_path=9676f3d#diff-9676f3de81de209bd11d15b454788da7), without having to worry about rendering it ourselves.
This needs to be in a public GitHub repository in order for http://www.gravizo.com/ to be able to read it.
This is just a first pass; we can easily improve the graph later (and maybe even in 10 years from now we'll have some code to autogenerate it using the OBS API ...)

add graphviz graph of OBS repository relationships

---

scripts/scenarios/cloud9/qa/no-ssl/qa-scenario-1a.yaml
scripts/scenarios/cloud9/qa/no-ssl/qa-scenario-1b.yaml
scripts/scenarios/cloud9/qa/no-ssl/qa-scenario-8a.yaml
scripts/scenarios/cloud9/qa/ssl-insecure/qa-scenario-1a.yaml
scripts/scenarios/cloud9/qa/ssl-insecure/qa-scenario-1b.yaml
scripts/scenarios/cloud9/qa/ssl-insecure/qa-scenario-8a.yaml
scripts/scenarios/cloud9/qa/ssl/qa-scenario-1a.yaml

This role is optional and requires swift to be installed otherwise gives and error.
See bug #1105616

Don't assign nodes to ceilometer-swift-proxy-middleware in qa scenarios

---

jenkins/ci.suse.de/openstack-ardana.yaml
scripts/jenkins/ardana/ansible/roles/heat-generator/tasks/main.yml

Fixes two recently introduced errors:
- leftover reference to the old ardana_net_vars.yml file
that causes the SSH keys to no longer be installed properly
on the controller nodes and the deployment to fail with an
'SSH Error: data could not be sent to the remote host' failure,
introduced by #2652
- use of an empty virtual configuration file value when caasp
is not enabled, which was not handled properly by the heat generator,
introduced by #2605

openstack-ardana: fix recent errors

---

scripts/jenkins/ardana/ansible/roles/ardana_deploy/files/enable-centos-rpms-on-rhel/roles/deployer-rhel-repo/vars/main.yml

This change adds `supportutils-plugin-suse-openstack-cloud` as it is missing on the RHEL repository.

Add supportutils-plugin-suse-openstack-cloud to list of rhel packages

---

scripts/iscsictl.py

This commit changes octal numbers from "0600" to "0o600" to fix
an error when running `make test` on Python 3.

Fix make test error on py3

---

scripts/jenkins/log-parser/openstack-mkcloud-rules.txt

Ignore github_pr.rb false positive, and weird libvirtd errors.
The automatic CI tests will not test this properly, so will have to test via https://github.com/SUSE/cloud/blob/master/docs/CI/keep-jenkins-green/jobs/openstack-mkcloud-log-parser-test.md

make log parser plugin ignore more things

---

.gitignore

This commit adds an entry scripts/jenkins/jenkins-job-triggerc to
.gitignore. This file is created during `make test` execution. So, we
don't need to manage this file by a git repo.

Add jenkins-job-triggerc to .gitignore

---

jenkins/ci.opensuse.org/openstack-devstack.yaml
scripts/jenkins/qa_devstack.sh

Upstream devstack still defaults to Python 3.5, but we need either
python 3.4 or 3.6, so set the variable appropriately.

Fix qa_devstack for leap 15.0

---

scripts/scenarios/cloud7/cloud7-2nodes-default.yml
scripts/scenarios/cloud7/cloud7-4nodes-compute-ha.yml
scripts/scenarios/cloud7/cloud7-ironic-basic-ha.yml
scripts/scenarios/cloud7/cloud7-ironic-swift-ha.yml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-1a.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-1b.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-2a.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-2b.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-2c.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-3.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-6a.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-8a.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-8b.yaml
scripts/scenarios/cloud7/qa/no-ssl/qa-scenario-9.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-1a.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-1b.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-2a.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-2b.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-2c.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-3.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-6a.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-8a.yaml
scripts/scenarios/cloud7/qa/ssl-insecure/qa-scenario-8b.yaml

The default database backend for Cloud 7 will soon change from
"postgresql" to "mariadb". In order to keep the scenarios deployable
with GA as well as with GA+Updates after the changed default, we're
forcing the backend to "postgresql" in the crowbar batch files for now.
Many of the batch files are still taylored for postgresql anyway (e.g.
using two-node cluster with and without drbd)

Adjust scenarios for change of default database backend

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-1a.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-1b.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-2a.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-2b.yaml
jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-8a.yaml

The commit https://github.com/SUSE-Cloud/automation/commit/ffce9054527be9d3750305049e80203b0c96c2c0 made it necessary to explicitly enable swift in mkcloud, even though crowbar batch already contains swift.
This broke qa scenarios where swift was used for storage.

Enable swift explicitly for qa scenarios

---

scripts/qa_crowbarsetup.sh

On machines with low RAM (32GB in total) the initial chef
run takes slightly longer, so we didn't wait enough half the time.
Increasing the timeout fixes the issue.

qa_crowbarsetup: wait longer for initial chef run

---

scripts/scenarios/cloud7/cloud7-4nodes-compute-ha.yml
scripts/scenarios/cloud7/cloud7-ironic-basic-ha.yml
scripts/scenarios/cloud7/cloud7-ironic-swift-ha.yml

Recently `ha` subtree was moved below `postgresql` as part of migration
from postgresql to mariadb. Some batches were not updated to match the
new schema.

Update batch scenarios to match schema

---

jenkins/ci.suse.de/cloud-mkcloud6.yaml
jenkins/ci.suse.de/cloud-mkcloud7.yaml
jenkins/ci.suse.de/cloud-mkcloud8.yaml
jenkins/ci.suse.de/cloud-mkcloud9.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-template.yaml

The HA+SSL combination isn't very well tested in our CI, but it
is the more common scenario that customers / PoCs are using. For
example the SAP Cloud Project is requiring this combination, but
also other users are choosing this combination. Hence we should
be testing it.
For now only switch Cloud9. Switching more once we have more
testing passes.

Switch Cloud9 HA jobs to use ssl

---

scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/templates/tests/horizon.sh.j2
scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/vars/horizon.yml

These are the wrapper files helps to run Horizon Selenium integration tests located at http://git.suse.provo.cloud/cgit/ardana/ardana-qa-tests/tree/ardana-qa-tests/horizon

Added support for Horizon on ardana_qe_tests role

---

hostscripts/clouddata/syncSLErepos

In case the install/suse-12.X directory wasn't created, rsync
skipped the syncing because the parent of the destination didn't
exist. Make sure that is always the case by creating the destdir
beforehand explicitly.

syncSLErepos: Create destination directory before rsyncing

---

jenkins/ci.suse.de/openstack-mkcloud.yaml
scripts/jenkins/ardana/ansible/jenkins/ardana-deploy-and-test.yml
scripts/jenkins/ardana/ansible/jenkins/ardana-deploy-test-update-test.yml
scripts/jenkins/ardana/ansible/jenkins/ardana-deploy.yml
scripts/jenkins/ardana/ansible/jenkins/ardana-iverify.yml
scripts/jenkins/ardana/ansible/jenkins/ardana-ses-integration.yml
scripts/jenkins/ardana/ansible/jenkins/ardana-tempest.yml
scripts/jenkins/ardana/ansible/jenkins/ardana-update.yml

The setup we're using depends on a job being run on one out of n
nodes, not all in parallel.

openstack-mkcloud: don't run on all matching label nodes in parallel

---

scripts/qa_crowbarsetup.sh

This was removed in commit 6e230ec9fb2f555fce0fb9f1a74e0a8c2e882df5,
but removal would break GM installations, since the migration is
delivered via maintenance update.
Fix after merging https://github.com/SUSE-Cloud/automation/pull/2721

Check for presence of specific migration.

---

jenkins/ci.suse.de/templates/cloud-ardana-job-gerrit-template.yaml

This is needed for gerrit-build-successful-verified-value:1 to have any
effect. By default the Jenkins Gerrit trigger plugin doesn't vote in
Gerrit, we want it to do that for this job.

cloud-ardana-job-gerrit: override default votes

---

jenkins/ci.suse.de/openstack-ardana.yaml
jenkins/ci.suse.de/pipelines/openstack-ardana.Jenkinsfile
scripts/github_pr/github_pr_cloud.yaml
scripts/github_pr/interactions/ia_cloud.rb
scripts/jenkins/ardana/pr-failure.sh
scripts/jenkins/ardana/pr-success.sh
scripts/jenkins/ardana/pr-update.sh
scripts/jenkins/github-pr/parse.rc
scripts/jenkins/mkcloud/openstack-mkcloud.builder.sh

Add a filter to the github_pr cloud config to run the openstack-ardana job when pull requests are proposed to the automation project.
Also, move the bulk of both openstack-ardana and openstack-mkcloud to scripts within the automation project so that changes to the jobs can be self-gating.

Run openstack-ardana on automation PRs

---

scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/templates/tests/neutron.sh.j2
scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/vars/neutron.yml

- Update neutron script to run esx tests. (https://gerrit.suse.provo.cloud//#/c/4696/)
- Skip esx tests for KVM based deployment.
- Capture skip tests count.

Update neutron wrapper script to run esx tests.

---

scripts/github_pr/github_pr_cloud.yaml

It misses the necessary parameters and the lockable resource. It
prevents triggering crowbar for a commit that would match both
FileMatches.
This partially reverts
4a23690202b2989c5590305ec78d158387ea094e
from https://github.com/SUSE-Cloud/automation/pull/2687

Remove broken ardana trigger for PRs in this repo

---

jenkins/ci.suse.de/cloud-automation-pr-trigger.yaml

When something fails and a repo has many open PRs triggering all of them
won't work as jenkins rejects creation of too many jobs.

Take a PR URL to trigger only from it

---

jenkins/ci.suse.de/cloud-automation-pr-trigger.yaml

None is not a magic key word for the empty string, use nothing instead.

Fix automation-pr-trigger job default parameter

---

jenkins/ci.suse.de/openstack-ardana-bootstrap.yaml
jenkins/ci.suse.de/openstack-ardana-tempest.yaml
jenkins/ci.suse.de/openstack-ardana-testbuild-gerrit.yaml
jenkins/ci.suse.de/openstack-ardana-vcloud.yaml
jenkins/ci.suse.de/openstack-ardana.yaml

Reuse the workspace on the master Jenkins node when checking
out the Jenkinsfile contents from the automation repo, to avoid
flooding GitHub with too many API requests.

SCRD-4983 openstack-ardana: reuse the workspace for pipeline jobs

---

scripts/jenkins/ardana/ansible/ardana-update.yml
scripts/jenkins/ardana/ansible/bootstrap-deployer-vm.yml
scripts/jenkins/ardana/ansible/group_vars/all/all.yml
scripts/jenkins/ardana/ansible/group_vars/virt_all.yml
scripts/jenkins/ardana/ansible/init.yml
scripts/jenkins/ardana/ansible/repositories.yml
scripts/jenkins/ardana/ansible/roles/ardana_deploy/tasks/run_ardana_plays.yml
scripts/jenkins/ardana/ansible/roles/ardana_update/defaults/main.yml
scripts/jenkins/ardana/ansible/roles/bootstrap_deployer/defaults/main.yml
scripts/jenkins/ardana/ansible/roles/rocketchat_notify/tasks/main.yml
scripts/jenkins/ardana/ansible/roles/send_to_os_health/tasks/main.yml
scripts/jenkins/ardana/ansible/run-ardana-deploy-plays.yml
scripts/jenkins/ardana/ansible/run-ardana-qe-tests.yml
scripts/jenkins/ardana/ansible/run-ardana-tempest.yml

Adds support for differentiated cloud8/cloud9 root
repository path. Previously, the root path was hardcoded
to `/srv/www/suse-12.3`, which didn't match the SLES12_SP4
based path used for cloud9.

openstack-ardana: support cloud9 repository paths

---

scripts/qa_crowbarsetup.sh

With 3 nodes needed for galera, there's not many left for ceph roles.
See e.g. this failure: https://ci.suse.de/job/openstack-mkcloud/133850/parsed_console/

For HA deployments of SOC7, do not consider ceph as default storage

---

jenkins/ci.suse.de/cloud-ardana9.yaml
jenkins/ci.suse.de/pipelines/openstack-ardana-gerrit.Jenkinsfile
jenkins/ci.suse.de/templates/cloud-ardana-job-gerrit-template.yaml

Implements a top-level pipeline job for Gerrit for Ardana:
- calls the openstack-ardana pipeline job as a downstream job
- is a placeholder for all upcoming validation stages to be performed
on a single Gerrit change:
- commit validator
- unit-testing targeting specific repositories
- other tests

SCRD-4999 openstack-ardana: gerrit top-level pipeline job

---

jenkins/ci.suse.de/openstack-mkcloud.yaml
scripts/github_pr/github_pr_cloud.yaml
scripts/jenkins/mkcloud/openstack-mkcloud.builder.sh
scripts/jenkins/mkcloud/openstack-mkcloud.prep.sh

In #2709 we moved the bulk of the openstack-mkcloud job to a script
within the automation repo, but that new script was not added to
the file filter for the openstack-mkcloud job. Add the new script
directory to the file filter so that the openstack-mkcloud job runs
on changes to its builder script.
Depends on work from #2713 and #2687

Run openstack-mkcloud job on changes to its script

---

jenkins/ci.suse.de/cloud-mkcloud9.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-2nodes-rocky-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-4nodes-linuxbridge-rocky-template.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-rocky-template.yaml

These CI jobs let us test the Devel:Cloud:9:Rocky packages for defects
introduced by the switch to upstream's stable/rocky branch without needlessly
breaking the regular Devel:Cloud:9 CI (i.e. Crowbar changes will still be able
to pass CI without additional CI breakage due to Rocky related changes). Once
we've gotten these jobs green, we can introduce the stable/rocky packages to
Devel:Cloud:9 and revert this commit.

Add CI jobs for Devel:Cloud:9:Rocky

---

scripts/jenkins/jenkins-job-cancel

Adds a new `jenkins-job-cancel` Python script which can be
used to abort all but the most recent build belonging to a job
and matching a list of parameter values.
This script can be used by jobs triggered for SCM events,
such as GitHub and Gerrit, to abort builds running for obsolete
change versions (e.g. GitHub branch contents or Gerrit patches
that are no longer current etc).

Add Jenkins API python script: jenkins-job-cancel

---

scripts/jenkins/gitlint.ini

Fixes the bugzilla ID regex enforced by the commit message
validator.

openstack-ardana: fix commit message validator

---

jenkins/ci.suse.de/cloud-mkcloud7.yaml

Since Cloud 7 needs 3 node HA cluster now (the default database switched
to galera), we don't have enough nodes left for deploying ceph (needs at
least 3 osd nodes). Switch the job to deploy swift.

Don't use ceph for cloud7 ha jobs

---

scripts/jenkins/ardana/ansible/deploy-caasp.yml

By default it uses the jenkins user which we should avoid.

Add remote_user for running CaaSP

---

scripts/jenkins/ardana/ansible/files/rpm-verify-modification-whitelist.txt

Update the whitelist maintained for the post-deploy RPM
file modification check to account for monasca-ansible patch
https://gerrit.suse.provo.cloud/4210/, which changed the
/usr/lib/monasca/agent/custom_checks.d file permissions from
root:root to monasca-agent:monasca.

openstack-ardana: update monasca RPM file permissions check

---

scripts/jenkins/ardana/ansible/group_vars/all/versioned.yml
scripts/jenkins/ardana/ansible/init.yml
scripts/jenkins/ardana/ansible/roles/input_model_generator/templates/input_model/data/control_plane.yml

Following @stefannica idea in [1] this change adds a filter for
disabling/enabling/tracking features depending of the cloudsource value.
For now it is enabling manila only for staging builds.
1. https://github.com/SUSE-Cloud/automation/pull/2772

openstack-ardana: Add filter to enable features according to cloudsource

---

scripts/jenkins/ardana/gerrit/gerrit2obs-name.py

without this the script cant be called and track-upstream-internal.sh
fails

shebang for python script gerrit2obs-name.py

---

jenkins/ci.suse.de/ardana-trigger-trackupstream.yaml

Also make concurrent=false explicit.
I tested triggering on both ref update and change merge. While a change
merge always results in a ref update, a run triggered by the ref update
won't comment on the change that got merged. Not triggering on a ref
update will miss a direct push to the branch without a review.
Triggering on both will run the job twice, which is a bit of waste as we
require review.
This job can always be manually triggered.

trackupstream: Do not trigger on ref update

---

scripts/jenkins/mkcloud/openstack-mkcloud.builder.sh

The job executing the script already sets this.
This was omitted from 10eb9b5559100cdb65b3c59e1671026113f8276f to not
trigger the broken job that it fixed.

Remove duplication of automationrepo environment

---

scripts/qa_crowbarsetup.sh

EC2 support is deprecated in Cloud 8 and we will remove it in Cloud 9.

Stop deploying EC2 in Cloud 8 & 9

---

jenkins/ci.opensuse.org/openstack-devstack.yaml
scripts/jenkins/qa_devstack.sh

IPv6 is required for the next cloud versions and we are still not
testing it.
This patch creates two jobs, one to deploy devstack with ipv4 and
other with an ipv6 control planes, and run tempest on them.
Devstack doesn't support dual stack in the control plane.
It also enables ipv4 and ipv6 for the dataplane in neutron
Ref:
https://github.com/SUSE/cloud-specs/pull/249
https://github.com/SUSE/cloud-specs/pull/129

Test devstack with IPv4 and IPv6

---

ccp/ses-ansible/README.md
ccp/ses-ansible/inventory
ccp/ses-ansible/roles/ses/defaults/main.yml
ccp/ses-ansible/roles/ses/files/policy.cfg
ccp/ses-ansible/roles/ses/handlers/main.yml
ccp/ses-ansible/roles/ses/tasks/deepsea_setup.yml
ccp/ses-ansible/roles/ses/tasks/main.yml
ccp/ses-ansible/roles/ses/tasks/openstack_config.yml
ccp/ses-ansible/roles/ses/tasks/pre_setup.yml
ccp/ses-ansible/roles/ses/tasks/salt_setup.yml
ccp/ses-ansible/roles/ses/tasks/zap_disks.yml
ccp/ses-ansible/roles/ses/templates/deepsea_minions.sls.j2
ccp/ses-ansible/roles/ses/templates/global.conf.j2
ccp/ses-ansible/roles/ses/templates/master.conf.j2
ccp/ses-ansible/roles/ses/templates/master_minion.sls.j2
ccp/ses-ansible/roles/setup_ses_configs/defaults/main.yml
ccp/ses-ansible/roles/setup_ses_configs/tasks/main.yml
ccp/ses-ansible/roles/setup_ses_configs/templates/ses-config.yml.j2
ccp/ses-ansible/ses-install.yml

This repository initial code based is copied from Flavio Ramalho QA setup
playbooks.
Adding new sub directory, ccp, to house CCP related automation logic.
CCP will require some changes that's why added new SES ansible tree under ccp
codebase.
Changes added to setup DEV_ENV variable, ipv6 local entry in /etc/hosts,
workaround to bypass max pg per OSD error and calculate number of replicas
based on disk devices.
Incorporated recent changes made in Flavio's ses-ansible.

Adding SES ansible plays for configuring single node SES for ccp

---

scripts/qa_crowbarsetup.sh

In an HA deployment a chef-client run can take around 10 minutes on a
single node. As the crowbar needs to wait for existing chef-client runs
to finish before the new chef-client run for applying the keystone
barclamp can be triggered we need to increase the timeout of the crowbar
batch call to have enough time for 2 chef-client runs + some safety
margin. This commit increases the timeout from 15 to 25 minutes.

keystone_password: Increase crowbar batch timeout

---

scripts/mkcloudhost/allocpool

If not chomped the following grep will fail if the PID
ends with a new line character and a job will fail to start.

allocpool: chomp the pid value

---

scripts/mkcloudhost/allocpool

Before it failed with
```
Argument "Binary file /proc/6780/cmdline matches\n" isn't numeric in numeric eq (==)
at /root/github.com/SUSE-Cloud/automation/scripts/mkcloudhost/allocpool line 32, <$fh> line 1.
```

allocpool: match pattern properly

---

Makefile
scripts/jenkins/ardana/gerrit/build_test_package.py
scripts/jenkins/ardana/gerrit/gerrit2obs-name.py
scripts/jenkins/ardana/gerrit/gerrit_project_map.py
scripts/jenkins/ardana/gerrit/project-map2project-regexp.py

Move the function gerrit_project_map into its own module, so it can
avoid the imports from the rest of its old location.

Avoid the need for python-sh on trigger slaves

---

jenkins/ci.suse.de/openstack-ardana-heat.yaml
jenkins/ci.suse.de/pipelines/openstack-ardana-heat.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana-vcloud.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana.Jenkinsfile
scripts/jenkins/ardana/ansible/roles/heat_stack/tasks/delete.yml
scripts/jenkins/ardana/ansible/roles/heat_stack/tasks/main.yml
scripts/jenkins/ardana/ansible/roles/heat_stack/tasks/monitor.yml

Moves the logic dealing with long operations involving creating/deleting
heat stacks in the ECP cloud back to a separate Jenkins job, `openstack-ardana-heat`.
The advantages of having this handled in a separate job:
- ECP infrastructure related failures can be monitored separately
- the job can be run manually to cleanup stacks left over from previous
openstack-ardana pipeline runs
- cleaning up a heat stack during the post-build actions of other jobs
(e.g. openstack-ardana) can be triggered and run without blocking the
upstream job, which means that upstream jobs can finish earlier and
report the result faster
- last but not least, the job can be reused by other pipelines which
need to manage heat stacks, for example a job that automates creating a
SES cluster
The heat stack management …

openstack-ardana: re-add heat stack create/delete job

---

scripts/lib/mkcloud-onhost.sh

cache the Systems-Management repos

---

scripts/jenkins/ardana/ansible/roles/input_model_generator/templates/input_model/data/network_groups.yml
scripts/jenkins/ardana/ansible/roles/input_model_generator/vars/templates/network/compact.yml

- Currently ilo route is hard coded into qcow2 image for each qe environment and it being removed during network restart through site.yml.
- This change will add and persist the ilo route through input model.

Add and persist ilo route for qe env.

---

scripts/jenkins/ardana/ansible/ansible.cfg

Ansible is storing host keys on ssh known_hosts files wich cause issues when the same IP is used for different hosts (virtual envs [1]).
This change adds `UserKnownHostsFile=/dev/null` to ansible ssh_args
so those host keys won't be stored.
1. https://ci.suse.de/job/openstack-ardana-vcloud/733/console

openstack-ardana: do not store host keys on known_hosts

---

jenkins/ci.suse.de/pipelines/openstack-ardana-vcloud.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana.Jenkinsfile

The `openstack-ardana-heat` Jenkins job builds triggered as post
build actions to clean up heat stacks must not reuse the workspace
from their parent jobs because they are running asynchronously
and the parent workspace may no longer be available.
This error has affected at least one job run so far: https://ci.suse.de/job/openstack-ardana-heat/61/

openstack-ardana: don't reuse workspace to cleanup heat stacks

---

scripts/qa_crowbarsetup.sh

In order to add a check to the ceilometer proposal that notifications
are enabled, we need to enable it in the CI env. With the change
https://github.com/crowbar/crowbar-openstack/pull/1792 we need
to prep the proposal accordingly to enable notifications in the
rabbitmq proposal if ceilometer is being deployed

mkcloud: rabbitmq notifications needed with ceilometer

---

scripts/jenkins/ardana/ansible/ansible.cfg

Comment out ansible mitogen plugin on ansible config to make sure it
is/isn't affecting some CI failure cases.

openstack-ardana: disable ansible mitogen plugin

---

jenkins/ci.suse.de/openstack-ardana-bootstrap-clm.yaml
jenkins/ci.suse.de/openstack-ardana.yaml
scripts/jenkins/ardana/ansible/roles/setup_zypper_repos/README.md
scripts/jenkins/ardana/ansible/roles/setup_zypper_repos/defaults/main.yml
scripts/jenkins/ardana/ansible/roles/setup_zypper_repos/tasks/setup_repo_from_iso.yml
scripts/jenkins/ardana/ansible/roles/setup_zypper_repos/templates/motd.j2
scripts/jenkins/ardana/ansible/roles/setup_zypper_repos/vars/milestone.yml

This change add support for deploying ardana based on a milestone release.
A new value for `cloudsource` was added (`cloud9M3`) for deploying
SUSE-OpenStack-Cloud-9 milestone 3.
For each new milestone a change to the JJB's is necessary to add its
equivalent `cloudsource` value.

openstack-ardana: add support for milestone cloudsource

---

jenkins/ci.suse.de/openstack-ardana-bootstrap-clm.yaml
jenkins/ci.suse.de/openstack-ardana-heat.yaml
jenkins/ci.suse.de/openstack-ardana-pcloud.yaml
jenkins/ci.suse.de/openstack-ardana-tempest.yaml
jenkins/ci.suse.de/openstack-ardana-testbuild-gerrit.yaml
jenkins/ci.suse.de/openstack-ardana-vcloud.yaml
jenkins/ci.suse.de/pipelines/openstack-ardana-bootstrap-clm.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana-heat.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana-pcloud.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana-tempest.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana-testbuild-gerrit.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana-vcloud.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana.Jenkinsfile
scripts/jenkins/ardana/jenkins-helper.sh

The openstack-ardana pipeline job uses the idea of a shared
workspace: a common folder shared by the openstack-ardana job with
all downstream jobs targeting the same `ardana_env` virtual or physical
cloud setup. This mechanism was previously implemented by manipulating
the Jenkins `WORKSPACE` locations, replacing them in downstream jobs with
symbolic links pointing to the main job's Jenkins workspace - a hack which
was causing some issues with the Jenkins server's job management.
This commit reimplements the shared workspace mechanism: a `SHARED_WORKSPACE`
location uniquely associated with every `ardana_env` cloud setup is managed
and shared by jobs independently of their Jenkins workspaces. This approach also
simplifies the implementation:
- the shared workspace location is now only …

openstack-ardana: reimplement shared workspaces

---

jenkins/ci.suse.de/pipelines/openstack-ardana-tempest.Jenkinsfile

`junit`, similar to `archiveArtifacts`, doesn't support absolute paths,
which means it cannot be pointed to a shared workspace.

openstack-ardana: use workspace path for junit

---

jenkins/ci.suse.de/pipelines/openstack-ardana-bootstrap-clm.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana-pcloud.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana-tempest.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana-vcloud.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana.Jenkinsfile

Use a consistent name for the root folder where Jenkins artifacts are
stored: `.artifacts` instead of `$BUILD_NUMER.artifacts`.

openstack-ardana: fix Jenkins artifacts name

---

scripts/jenkins/ardana/ansible/group_vars/all/vcloud.yml
scripts/jenkins/ardana/ansible/group_vars/all/versioned.yml
scripts/jenkins/ardana/ansible/roles/ardana_deploy/defaults/main.yml
scripts/jenkins/ardana/ansible/roles/ardana_deploy/tasks/main.yml
scripts/jenkins/ardana/ansible/roles/ardana_deploy/tasks/reimage_nodes.yml
scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/defaults/main.yml
scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/tasks/main.yml
scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/tasks/prepare_test_env.yml
scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/tasks/qe_test_requires.yml
scripts/jenkins/ardana/ansible/roles/bootstrap_ardana/defaults/main.yml
scripts/jenkins/ardana/ansible/roles/rocketchat_notify/defaults/main.yml
scripts/jenkins/ardana/ansible/roles/send_to_os_health/defaults/main.yml
scripts/jenkins/ardana/ansible/roles/send_to_os_health/tasks/main.yml
scripts/jenkins/ardana/ansible/roles/send_to_os_health/tasks/os_health_requires.yml

This PR addresses the following issues on the ardana automation playbooks.
- When running openstack-ardana job the default is to use the input model
from ardana repository (model parameter is set and scenario_name is
empty).
For the heat template file name the same logic is used, whici is use
the model variable and only use scenario_name when its defined and not
empty.
- The SLE-SDK repos and packges installed by send_to_os_health and
ardana-qe-tests roles were affecting maintenance updates.
This change address this issue by making sure those repos/packages
are removed after its use.
- Add workaround for bug bsc#1110414 present on `cloud9M3`.
Applying this workaround is controlled by the versioned_features variable.
- Cloud 9 sets `host_key_checking = True` on ansible.cfg which requires …

openstack-ardana: several small fixes

---

jenkins/ci.suse.de/pipelines/openstack-ardana-bootstrap-clm.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana-pcloud.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana-tempest.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana-vcloud.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana.Jenkinsfile

The `junit` and `archiveArtifacts` pipeline plugins don't support
absolute paths, which means they can only take in files that are
in the Jenkins `WORKSPACE` folder. Using a dedicated workspace for
every job run, which is cleaned up at the end, and creating symlinks
there from the shared workspace solves this problem.

openstack-ardana: use workspace symlink for artifacts

---

scripts/jenkins/qa_devstack.sh

The[ job running devstack with ipv6 in build.opensuse.org](https://ci.opensuse.org/view/OpenStack/job/openstack-devstack-ipv6/1/consoleText) fails with the following error:
`The label ::1 is not a valid A-label`
However, I'm able to deploy devstack locally using python3.
Since[ OpenStack is targeting T cycle for  python3 support](https://governance.openstack.org/tc/resolutions/20180529-python2-deprecation-timeline.html) and python2 is EOL 1/1/2020 I think that makes sense to start to test with python3 only

Use python3 for Leap 15 devstack jobs

---

scripts/jenkins/ardana/gerrit/build_test_package.py

Currently no job deletes the Ardana Testbuild Projects but we should do
some cleanups.

Delete the Ardana Testbuild Project after 30days

---

jenkins/ci.suse.de/cloud-ardana8.yaml
jenkins/ci.suse.de/templates/cloud-ardana-job-gerrit-template.yaml

The cloud8 Ardana Gerrit job is currently only checking the
commit message. It shouldn't vote V+1 on Gerrit changes without
running integration tests, because this may cause breaking changes
to be merged before Zuul has a chance to invalidate them.

openstack-ardana-gerrit: make cloud8 job non-voting

---

jenkins/ci.opensuse.org/openstack-trackupstream.yaml
scripts/scenarios/cloud9/cloud9-2nodes-default.yml
scripts/scenarios/cloud9/cloud9-5nodes-compute-ha.yml

It is being retired for Cloud9 after being deprecated for some time.

mkcloud: Remove trove from cloud9 testing

---

jenkins/ci.suse.de/pipelines/openstack-ardana-bootstrap-clm.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana-gerrit.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana-heat.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana-pcloud.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana-tempest.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana-testbuild-gerrit.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana-vcloud.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana.Jenkinsfile

Enables logging timestamps for all Ardana pipeline jobs.
The result can be seen here, for example: https://ci.suse.de/job/openstack-ardana-vcloud/925/console
The timestamps plugin also allows settings to be configured directly in the URL (e.g. https://ci.suse.de/job/openstack-ardana-vcloud/925/timestamps/?time=yy-mm-dd%20HH:mm:ss&appendLog&locale=en_US )
NOTE: there's a known Jenkins issue that prevents the timestamps plugin from displaying timestamps in the Blue Ocean UI: https://issues.jenkins-ci.org/browse/JENKINS-44195

openstack-ardana: enable timestamps in Ardana pipeline logs

---

scripts/qa_crowbarsetup.sh

This disables the CCT tests for Cloud 6 and Cloud 7 as they fail
randomly. Once this is fixed we could re-add the tests.

Remove Test ISO for Cloud 6 and 7

---

scripts/jenkins/github-pr/parse.rc

These were not found as they were not fatal without set -eu .
Avoid trying to find an executable named as the content of
$github_pr when its not empty, only error when its empty.
Avoid an unset variable error, the context may be set to the empty
string.

Avoid expected errors in sourced shell file

---

scripts/qa_crowbarsetup.sh

Next try for "Make sure testpostupgrade step is only executed for non-disruptive upgrade": 
https://github.com/SUSE-Cloud/automation/pull/2591
In some cases it was mistakingly executed for the normal mode causing confusing errors (see SCRD-4051)
The original PR had the check on the wrong place.

Check for upgrade progress file must be done on admin node

---

scripts/jenkins/qa_devstack.sh

Once the Leap 15 support is merged in devstack upstream
https://review.openstack.org/#/c/576798/
we need this patch to make it work with IPv6
https://review.openstack.org/#/c/605983/
The job testing Leap 15 and IPv6 requires python3 and meanwhile is not added upstream is being tested in our CI
https://ci.opensuse.org/view/OpenStack/job/openstack-devstack-ipv6/

Make devstack work with IPv6

---

jenkins/ci.suse.de/pipelines/openstack-ardana-bootstrap-clm.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana-gerrit.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana-heat.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana-pcloud.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana-tempest.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana-testbuild-gerrit.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana-vcloud.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana.Jenkinsfile

The Triggered Builds Section in Blue Ocean is no longer displayed
when pipelines have parallel stages [1]. To reduce the impact of this
bug until it's solved upstream, URLs pointing to the downstream builds
are generated in the stage logs.
NOTE: for these URLs to appear in the upstream job logs, the downstream job first has to complete execution, which doesn't make this a good solution to JENKINS-53735 for monitoring live builds.
[1] https://issues.jenkins-ci.org/browse/JENKINS-53735

openstack-ardana: add Blue Ocean URLs to downstream jobs

---

jenkins/ci.suse.de/ardana-trackupstream.yaml
scripts/jenkins/ardana/gerrit/project-map.json

The package isn't used anymore and we removed it from the product.

Remove ardana-extensions-example from trackupstream

---

jenkins/ci.suse.de/pipelines/openstack-ardana-qa-tests.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana.Jenkinsfile
scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/defaults/main.yml

- Extended-choice parameters are not defined when the job is automatically
triggerd. So, we need to check if the variable is defined before using
it.
- Using `ansible_user_dir` variable from ansible facts to reference the
ardana home directory is not realiable as if there are facts cached from
a previous playbook ran as root `ansible_user_dir` is set to root.
- If the openstack-ardana-qa-tests job is running as a standalone job
use dedicated workspace to allow users to run several tests in parallel
targeting the same environment.

openstack-ardana: fixes for ardana-qa-tests

---

scripts/jenkins/qa_devstack.sh

It was a missing a pipe and the order of the commands were wrong, it was sorting the output by hash instead of the review number

Fix pending review function

---

jenkins/ci.suse.de/cloud-ardana8.yaml
jenkins/ci.suse.de/cloud-ardana9.yaml
jenkins/ci.suse.de/templates/cloud-ardana-gating-template.yaml

Monasca is going to be broken for a while in Cloud 9, until all
the needed monasca packages are ported to Rocky. In the meantime,
we still need to maintain a working CI, so disabling monasca for
all Cloud 9 Ardana CI jobs (switching to `demo` as an input model,
which has monasca disabled) is a fair compromise.
This commit also disables all Ardana Cloud9 CI jobs that are using
input models including monasca, for the same reasons.
Reverting this change is tracked by https://jira.suse.de/browse/SCRD-5371

openstack-ardana: switch Gerrit CI to demo input model for Cloud 9

---

jenkins/ci.suse.de/pipelines/openstack-ardana-gerrit.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana-vcloud.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana.Jenkinsfile

Using try-catch blocks to display the URLs of downstream jobs
in the Blue Ocean only works if the downstream job is passing.
When failing, the try-catch block will not set the needed variables
and the resulting "undefined variable" failure just eclipses the
real cause of the failure.
The correct approach is to use `propagate: false` when launching
downstream builds, which will complete successfully regardless of
the downstream build result, then check the result in the upstream
job.

openstack-ardana: fix URLs for failing downstream jobs

---

jenkins/ci.opensuse.org/openstack-devstack.yaml
scripts/jenkins/qa_devstack.sh

It's much better for debugging to store the tempest results in html. 
Also, it stores the tests in junit format, leveraging the Junit plugin in tempest to show the test results, this way you can see the exact number of tests failing from the job itself.

Store tempest results on devstack jobs

---

jenkins/ci.suse.de/openstack-ardana-qa-tests.yaml
jenkins/ci.suse.de/openstack-ardana-vcloud.yaml
jenkins/ci.suse.de/templates/cloud-ardana-pipeline-template.yaml
scripts/jenkins/ardana/ansible/group_vars/all/all.yml
scripts/jenkins/ardana/ansible/group_vars/all/vcloud.yml
scripts/jenkins/ardana/ansible/load-job-params.yml
scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/defaults/main.yml
scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/tasks/prepare_test_env.yml
scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/templates/tests/barbican-cli-func.sh.j2
scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/vars/barbican-cli-func.yml
scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/vars/barbican-functional.yml
scripts/jenkins/ardana/ansible/roles/input_model_clone/defaults/main.yml

Currently the ardana branch used for cloning input model and ardana-qa-tests is manually set on the jenkins job.
This change allows the ardana branch to be automatically set based on the cloud release (cloud8: stablb/pike, cloud9: master) when the branch parameter on the jenkins job is empty.
This change also change the behavior when loading parameters from jenkins jobs to the playbooks, currently all parameters are loaded, with this change only the non-empty parameters will be loaded.

openstack-ardana: set ardana branch based on cloud release

---

jenkins/ci.suse.de/pipelines/openstack-ardana.Jenkinsfile

Enable the periodic openstack-ardana jobs to report their status on the
[SUSE Cloud Jenkins Green Trello board](https://trello.com/b/ywSwlQpZ/suse-cloud-jenkins-green), same as the openstack-mkcloud jobs.

openstack-ardana: Trello job status reporting

---

scripts/jenkins/ardana/ansible/roles/input_model_generator/vars/templates/interface/standard.yml

With standard scenario, standalone deployer cannot reach to the public endpoints (external-api network) and that is require for some of the qa tests. Adding an interface to external-api network solves this issue.
Tested - https://ci.suse.de/job/openstack-ardana/966/console

Add interface for deployer to reach to public endpoints

---

scripts/jenkins/ardana/ansible/roles/ardana_tempest/tasks/main.yml

Added a task to fail if any tempest test fails, so the job calling the
tempest playbook will report a failure when there at least one tempest
test that failed.

openstack-ardana: playbook must fail if any tempest test failed

---

jenkins/ci.suse.de/pipelines/openstack-ardana-bootstrap-clm.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana-pcloud.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana-qa-tests.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana-tempest.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana-vcloud.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana.Jenkinsfile

Updates the pipeline jobs to display the IP address
where the deployer can be reached immediately after
the preparation of the virtual/physical environment,
as well as at the end of the pipeline, also showing
instructions on how to cleanup the virtual cloud.
This change will also change the build name itself
to show the IP, as soon as it becomes available.

openstack-ardana: display deployer IP more often

---

hostscripts/clouddata/syncSLErepos

rsync.opensuse.org is down since a month without a ETA for a replacement
so let's use a working rsync server.
See https://status.opensuse.org/incidents/166

Replace rsync.opensuse.org

---

scripts/jenkins/qa_devstack.sh

Previous commit allowed the devstack jobs to use some jenkins
plugins to store and report the test results.
However, there were several mistakes, mainly for rushing things :(.
The junitxml dependency has to be added to the VM were devstack is
running. Also, the if block to check for the file `subunit `can be avoided
since we want to fail the build if it doesn't exist.
Signed-off-by: aojeagarcia <aojeagarcia@suse.com>

Fix devstack job in ci.opensuse.org

---

scripts/jenkins/ardana/ansible/roles/ardana_deploy/templates/maint_updates.yml.j2

Current deployment job is failing when we only define cloud or sles MU as empty parameter is not being added into input.yml file.
e.g https://ci.suse.de/view/Cloud/view/Builds/job/openstack-ardana/1003/console
This PR solves the issue by checking if cloud and sles mu parameter is defined when setting up MU repos.
Tested in baremetal and virtual environments:
https://ci.suse.de/view/Cloud/view/Builds/job/openstack-ardana/1012/
https://ci.suse.de/job/openstack-ardana/1016/console

Fix install job when only cloud or sles MU defined

---

scripts/jenkins/ardana/ansible/bootstrap-vcloud-nodes.yml
scripts/jenkins/ardana/ansible/setup-ssh-access.yml

Before attempting to provision any of the target Ardana cloud nodes,
the ansible playbooks must first wait for those nodes to complete
the startup procedure (i.e. wait for the SSH service to start),
otherwise connectivity errors may occur.
This problem is easily reproducible with simpler input models, like
'minimal', which complete the virtual cloud creation quickly and
thus don't allow the deployer node enough time to complete the
startup process.

openstack-ardana: wait for cloud nodes to start

---

scripts/jenkins/ardana/ansible/deploy-cloud.yml
scripts/jenkins/ardana/ansible/group_vars/all/versioned.yml

Jira: SCRD-5330
Freezer is not available for the Rocky release that Cloud9 is based
upon, so only enable the freezer service in generated input models
for Cloud8.

Disable freezer for Cloud9 generated models

---

scripts/jenkins/ardana/ansible/roles/heat-generator/tasks/main.yml
scripts/jenkins/ardana/ansible/roles/input_model_generator/README.md
scripts/jenkins/ardana/ansible/roles/input_model_generator/defaults/main.yml
scripts/jenkins/ardana/ansible/roles/input_model_generator/templates/input_model/data/disk_models.yml
scripts/jenkins/ardana/ansible/roles/input_model_generator/templates/input_model/data/network_groups.yml
scripts/jenkins/ardana/ansible/roles/input_model_generator/templates/input_model/data/networks.yml
scripts/jenkins/ardana/ansible/roles/input_model_generator/templates/input_model/data/neutron/neutron_config.yml
scripts/jenkins/ardana/ansible/roles/input_model_generator/templates/input_model/data/servers.yml
scripts/jenkins/ardana/ansible/roles/input_model_generator/vars/templates/network/compact.yml

Input model generator fixes required to make the `entry-scale-kvm`
scenario to also work with ECP virtual cloud deployments in addition
to physical ones:
- added the missing `cinder-volume` device group to all generated
input models, without which the `cinder-volume` service wasn't
provisioned
- extended the range covered by the `/dev/sd*` to `/dev/vd*`
replacement to allow more devices to be used
- added a `designate_backend` parameter to the input model
generator, with `bind` and `powerdns` as possible values,
to control which designate backend is deployed in generated
input models
- added the `bind-ext` component endpoint to the EXTERNAL-API
network group, to enable designate to be tested the same as with
bare-metal deployments
- switched the EXTERNAL-VM network in the `compact` …

openstack-ardana: make entry-scale-kvm work with virtual clouds

---

scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/vars/service-ansible-playbooks.yml

In order to let service-ansible-playbooks testing to run completely, I increase timeout to 5 hours

Increased timeout for service-ansible-playbook on ardana_qe_tests role

---

scripts/jenkins/qa_devstack.sh

It turns out that junitxml needs root privileges to be installed.
In addition, we remove the pending patch from the variable since it was merged upstream
Signed-off-by: aojeagarcia <aojeagarcia@suse.com>

Fix pip junitxml installation and remove review

---

jenkins/ci.suse.de/cloud-ardana8.yaml
jenkins/ci.suse.de/cloud-ardana9.yaml

Update the openstack-ardana jobs automating the cloud update
workflow for the staging media and maintenance updates to use
the recently implemented update automation support.

openstack-ardana: update staging/maintenance update jobs

---

jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-1a.yaml

This is the default choice in product so it would be
good to test it in qa. Scenario 1a is the simplest one
and run most often.
Also changing the parameters to choice to avoid
typos

Change neutron defaults to openvswitch vxlan

---

jenkins/ci.suse.de/openstack-mkcloud.yaml
mkcloudruns/mkcloudconfig/SUSECloud.mkcloud
scripts/qa_crowbarsetup.sh

The CI jobs for Cloud7+ are defaulting to vxlan, so we should
transition the jenkins defaults to reflect that. The corresponding
switch of product defaults is done in https://github.com/crowbar/crowbar-openstack/pull/1842

qa_crowbarsetup: openvswitch vxlan becoming the default choice

---

jenkins/ci.suse.de/cloud-ardana8.yaml
jenkins/ci.suse.de/cloud-ardana9.yaml
jenkins/ci.suse.de/pipelines/openstack-ardana-gerrit.Jenkinsfile
jenkins/ci.suse.de/templates/cloud-ardana-job-gerrit-template.yaml

This commit updates cloud-ardana8-job-gerrit-x86_64 and
cloud-ardana9-job-gerrit-x86_64 to be periodic jobs instead
of jobs triggered by Gerrit change requests. These jobs
will run periodically against a set of test Gerrit reviews [1][2]
to ensure the Gerrit pipelines remain in working order. This
testing is required to monitor the state of the Gerrit pipelines
independently from Gerrit changes.
Two regular Gerrit CI jobs are created to replace the ones
mentioned above: openstack-ardana-gerrit-cloud8 and
openstack-ardana-gerrit-cloud9.
[1] https://gerrit.suse.provo.cloud/4940
[2] https://gerrit.suse.provo.cloud/4941

openstack-ardana-gerrit: create periodic gerrit jobs

---

scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/vars/neutron.yml

Default timeout (2 hours) for the qa job is not enough to run neutron tests as tests run with concurrency=1 due to test design. Setting the timeout to 8 hours till it can be run concurrently.

Increase timeout for neutron tests

---

jenkins/ci.suse.de/pipelines/openstack-ardana-bootstrap-clm.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana-heat.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana-pcloud.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana-qa-tests.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana-tempest.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana-update-and-test.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana-update.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana-vcloud.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana.Jenkinsfile

The post block supports a 'cleanup' stage that runs after all other
stages. Move calls to the cleanWs function from the 'always' stage
to the 'cleanup' stage so that the workspace will continue to be
available during the 'success' and 'failure' stages.

openstack-ardana: move cleanWs calls to cleanup stage

---

hostscripts/clouddata/syncSLErepos

This adds the next storage version to
clouddata and switches version 5 to
the released one.

Add ses6 dev version to clouddata

---

jenkins/ci.suse.de/cloud-ardana8.yaml
jenkins/ci.suse.de/cloud-ardana9.yaml

When the commit message is edited via the Gerrit UI, a NO_CODE_CHANGE
event is generated by Gerrit. We need to set `exclude-no-code-change`
to false in our gerrit trigger jobs to catch these events.
This PR also fixes the Gerrit Cloud9 job to use the correct Lockable Resources
label (recently broken in #2893).
Tested successfully against https://gerrit.suse.provo.cloud/#/c/4950/

SCRD-5293 openstack-ardana-gerrit: enable no-code-change events and fix resource label

---

scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/defaults/main.yml

For creating openstack resources (projects, users, etc) we use ansible
modules which requires the shade library. For that, shade is installed on
the test virtual environment and the ansible python interpreter is set to
use python from the virtual environment.
Using `~` on the virtual enviroment path causes ansible to fail with
`OSError: [Errno 2] No such file or directory`. So this patch replaces
`~` with the full path.

openstack-ardana: fix create os resources tasks on ardana_qe_tests role

---

scripts/jenkins/ardana/gerrit/build_test_package.py

Depends-On in Zuul and changes in Gerrit can use different ways to refer
to the same commit. Check and remember both canonical and non-canonical
ids to avoid a loop.

SCRD-5512 avoid loop with non-canonical change id

---

scripts/jenkins/ardana/ansible/deploy-cloud.yml
scripts/jenkins/ardana/ansible/group_vars/all/versioned.yml

Disable the `heat-cloudwatch-api` service when deploying
cloud 8. This service was removed in Queens [1].
[1] https://docs.openstack.org/releasenotes/heat/queens.html

openstack-ardana: disable heat-cloudwatch-api

---

scripts/jenkins/ardana/ansible/roles/rocketchat_notify/tasks/get_cloud_build_version.yml
scripts/jenkins/ardana/ansible/roles/rocketchat_notify/tasks/main.yml
scripts/jenkins/ardana/ansible/roles/rocketchat_notify/vars/deploy.yml
scripts/jenkins/ardana/ansible/roles/send_to_os_health/defaults/main.yml
scripts/jenkins/ardana/ansible/roles/send_to_os_health/tasks/get_cloud_build_version.yml
scripts/jenkins/ardana/ansible/roles/send_to_os_health/tasks/main.yml
scripts/jenkins/ardana/ansible/roles/send_to_os_health/vars/ardana-qe-tests.yml
scripts/jenkins/ardana/ansible/roles/send_to_os_health/vars/tempest.yml

The cloud media build number is added to the motd by the
`setup_zypper_repos` role. Other roles relies on different methods to
get the cloud media build number, this is very error prone as depending
of the cloudsource there are different methods to get the cloud media
build number and other roles may not have access to cloudsource.
With this change, instead of applying the same logic from `setup_zypper_repos`
to get the media build number, other roles simply read that info from the motd
as it was previously added.

openstack-ardana: get cloud media build number from motd

---

scripts/qa_crowbarsetup.sh

If there's a need to have PTF repo for both original and upgraded cloud,
we have to make sure that the old one is removed when changing the repository
setup.

Remove old PTF repo during the upgrade so the new one can be added to zypp

---

scripts/lib/mkcloud-driver-libvirt.sh

If virsh net-start fails to start the network, the libvirt_net_start
function in the mkcloud driver continues merrily on, even though the
interface doesn't exist. Exit if it fails.

ipv6: Catch virsh net-start errors

---

scripts/scenarios/cloud7/cloud7-2nodes-default.yml
scripts/scenarios/cloud7/cloud7-4nodes-compute-ha.yml
scripts/scenarios/cloud8/cloud8-2nodes-default.yml
scripts/scenarios/cloud8/cloud8-5nodes-compute-ha.yml
scripts/scenarios/cloud9/cloud9-2nodes-default.yml
scripts/scenarios/cloud9/cloud9-5nodes-compute-ha.yml

In f55c442 the enable_notifications settings was turned on for mkcloud
proposals, but the proposal step is skipped in some CI jobs and the
batch step is used instead. This patch makes the correction to every
batch file that is used for jobs with mkcloudtarget=all_batch on Cloud
7, 8, and 9, which are currently all broken[1].
[1] https://ci.suse.de/job/cloud-mkcloud9-job-2nodes-x86_64/339/

Enable rabbit notifications in all_batch scenarios

---

scripts/jenkins/ardana/ansible/roles/rocketchat_notify/tasks/main.yml
scripts/jenkins/ardana/ansible/roles/send_to_os_health/tasks/main.yml

Fixing a syntax error from my previous commit, conditionals starting with quotes should end with quotes.

openstack-ardana: add missing quotes on cloud build number

---

scripts/jenkins/qa_devstack.sh

We were only running tempest smoke tests, we should run the same tests that upstream gates are running.
In addition, we should store the tempest results, it was storing only devstack results.

Run same test as upstream gates

---

scripts/jenkins/qa_devstack.sh

ci.opensuse.org devstack jobs are failing to store the results with the following error
> 08:53:24 No repository found in /opt/stack/tempest. Create one by running "testr init".
This patch leverage new tempest cli features to store directly the outout

Fix testr subunit failure

---

scripts/jenkins/qa_devstack.sh

subunit2junitxml fails if there are errors causing the job to fail.
Ignore the errors and store the results

Fix subunit2junitxml report

---

scripts/jenkins/qa_devstack.sh

I started to be embarrassed because of the long list of small fixes that I should have tested previously.
At least the html report is working :) https://ci.opensuse.org/view/OpenStack/job/openstack-devstack-ipv4/36/artifact/results.html
I apologize, but seems that the subunit2junitxml --output-to options needs and `=`

Fix subunit2junitxml output

---

scripts/jenkins/ardana/ansible/roles/input_model_generator/defaults/main.yml
scripts/jenkins/ardana/ansible/roles/input_model_generator/templates/input_model/data/disk_models.yml

The virtual Ardana cloud deployments currently disable
all provisioning of LVM volumes by means of the `skip_disk_config`
mechanism. One consequence of this is that services use the
root partition for all their files while the additional
`volume-group` entries in the generated disk model are ignored.
This commit removes this additional `volume-group` entries and
relies only on the root partition the size of which is controlled
only by the ECP openstack flavor associated with the virtual server
instances. The immediate effect is a huge (~50%) reduction in the
storage resources required to instantiate virtual cloud environments
associated with generated input models.

input-model-generator: disable additional LVM volumes

---

jenkins/ci.suse.de/pipelines/openstack-ardana-update-and-test.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana-update.Jenkinsfile

The Blue Ocean URL variable is not passed up to the
main pipeline job from the recently added update downstream
jobs. This commit fixes that.

openstack-ardana: fix update build URL message

---

scripts/jenkins/qa_devstack.sh

The block to store the tempest tests results was out of the if condition to check if we should run tempest.
This patch set run tempest and store the results in the same block, also fixes a problem with the subunit2junitxml converter that was having errors with the `--output-to` option

Reorganise and clean tempest run

---

scripts/scenarios/cloud7/cloud7-2nodes-default.yml
scripts/scenarios/cloud8/cloud8-2nodes-default.yml
scripts/scenarios/cloud9/cloud9-2nodes-default.yml

Temporarily enable debug logging for cinder while we track down a
heisenbug in cinder-volume.

Turn on debug logging for cinder in CI (SCRD-5775)

---

scripts/jenkins/ardana/ansible/roles/ses_configure/defaults/main.yml
scripts/jenkins/ardana/ansible/roles/ses_configure/tasks/configure_rgw.yml
scripts/jenkins/ardana/ansible/roles/ses_configure/tasks/create_users.yml
scripts/jenkins/ardana/ansible/roles/ses_configure/tasks/main.yml

For each QE environment a new instance of rados gateway listening on a
specific port (defined on the deployer hostvars) should be configured on the
SES cluster, instead of using the same port for all environments.
This change also includes improvements on the output of some SES related
tasks.

openstack-ardana: fix rados gateway port

---

scripts/jenkins/ardana/ansible/roles/ssh_keys/tasks/main.yml
scripts/jenkins/ardana/ansible/setup-ssh-access.yml

Instead of looping through the list of ssh keys and adding one by
one, build a list containing the ssh keys and add them all together in a block.

openstack-ardana: add ssh public keys all together

---

jenkins/ci.opensuse.org/openstack-trackupstream.yaml

Freezer didn't have a Rocky release and we're not including it in Cloud
9 so stop worrying about it in trackupstream.

Stop tracking freezer-ui for Rocky

---

scripts/jenkins/mkcloud/openstack-mkcloud.builder.sh

prepapreinstcrowbar and bootstrapcrowbar steps were missing.
using aliases to avoid missing any more steps

fix MKCLOUDTARGET when UPDATEBEFOREINSTALL

---

scripts/jenkins/ardana/gerrit/project-map.json

Add ardana-configuration-processor to the list of repositories
which are source-tracked by IBS packages and are processed by
Gerrit related Jenkins jobs (Gerrit CI, trackupstream-trigger).
Depends on #2944

openstack-ardana-gerrit: enable ardana-configuration-processor

---

scripts/scenarios/cloud7/cloud7-2nodes-default.yml
scripts/scenarios/cloud8/cloud8-2nodes-default.yml
scripts/scenarios/cloud9/cloud9-2nodes-default.yml

Reverts SUSE-Cloud/automation#2940
The issue was fixed with a change in the systemd unit file:
https://build.opensuse.org/package/rdiff/Cloud:OpenStack:Rocky:Staging/openstack-cinder?linkrev=base&rev=40

Revert "Turn on debug logging for cinder in CI (SCRD-5775)"

---

jenkins/ci.opensuse.org/openstack-trackupstream.yaml

In b242d67 we tried to add the Rocky project to the list of exclusions
for the freezer-ui package but neglected to remove freezer-ui from its
original exclusion list. This fixes that.

Fix freezer-ui exclusion in trackupstream

---

scripts/lib/libvirt/fixtures/cloud-admin.netv6.xml
scripts/lib/libvirt/libvirt_setup.py
scripts/lib/libvirt/net-config
scripts/lib/libvirt/templates/admin-net-v6.xml
scripts/lib/libvirt/templates/ironic-net-v6.xml
scripts/lib/libvirt/test_libvirt_setup.py

libvirt XML networking templates need to specify different options if we
are going to specify IPv6 networks. Add a new -v6 template, along with a
new option to net-config to support it.

ipv6: Teach net-config about IPv6

---

jenkins/ci.suse.de/ardana-trackupstream.yaml

Doing releases from pypi doesn't work because in general people
forget about doing that, or are unable to push the release due
to restrictions.

Start tracking python-ardana-configurationprocesor from git.

---

jenkins/ci.opensuse.org/openstack-trackupstream.yaml

openstack-utils is a RedHat utility that hasn't been updated in two
years. We don't use it directly nor do we reference it in our
documentation. Let's stop being concerned about it.

Stop tracking openstack-utils for Queens and Rocky

---

jenkins/ci.suse.de/cloud-ardana8.yaml
jenkins/ci.suse.de/openstack-ardana-bootstrap-clm.yaml
jenkins/ci.suse.de/openstack-ardana-update-and-test.yaml
jenkins/ci.suse.de/openstack-ardana-update.yaml
jenkins/ci.suse.de/pipelines/openstack-ardana-update-and-test.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana.Jenkinsfile
jenkins/ci.suse.de/templates/cloud-ardana-pipeline-template.yaml
scripts/jenkins/ardana/ansible/roles/setup_zypper_repos/defaults/main.yml

Add an option to the jenkins jobs to enable/disable SUSE/Cloud test
updates repositories following the logic in [1].
1. https://github.com/SUSE-Cloud/automation/tree/master/scripts/jenkins/ardana/ansible/roles/setup_zypper_repos#usage

openstack-ardana: add option to enable test updates repos

---

jenkins/ci.suse.de/cloud-ardana8.yaml
jenkins/ci.suse.de/cloud-ardana9.yaml
jenkins/ci.suse.de/openstack-ardana-pcloud.yaml
jenkins/ci.suse.de/openstack-ardana-vcloud.yaml
jenkins/ci.suse.de/pipelines/openstack-ardana-gerrit.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana.Jenkinsfile
jenkins/ci.suse.de/templates/cloud-ardana-job-gerrit-template.yaml
jenkins/ci.suse.de/templates/cloud-ardana-pipeline-template.yaml

This commit improves the description of the 'model' and 'scenario_name'
Ardana Jenkins job parameters, as well as removes some parameters
that haven't been used in a long time.
Starting with this commit, the user must select either a 'model'
or a 'scenario_name' when triggering a job manually.

openstack-ardana: cleanup and better job parameter tips

---

jenkins/ci.suse.de/pipelines/openstack-ardana-gerrit.Jenkinsfile

The openstack-ardana-gerrit job is currently reusing the
Jenkins workspace for all its builds, which causes conflicts
when multiple jobs are running in parallel.

openstack-ardana-gerrit: use dedicated workspace

---

jenkins/ci.suse.de/cloud-ardana9.yaml
jenkins/ci.suse.de/templates/cloud-ardana-pipeline-template.yaml

Adds two periodic jobs targeting the `entry-scale-kvm`
input model generator scenario in Cloud9 Ardana and also
running a set of QA test cases in addition to the `ci`
tempest test filter:
- `cloud-ardana9-job-entry-scale-kvm-x86_64`: uses a virtual
cloud deployment, same as all the other jobs
- cloud-ardana9-job-entry-scale-kvm-qe102-x86_64: uses the
`qe102` bare-metal setup to deploy a physical cloud

openstack-ansible: entry-scale-kvm periodic jobs

---

jenkins/ci.suse.de/cloud-ardana8.yaml

Adds missing `std-min` model parameter value.

openstack-ardana: fix std-min cloud8 jobs

---

jenkins/ci.suse.de/pipelines/openstack-ardana-bootstrap-clm.Jenkinsfile
scripts/jenkins/ardana/ansible/bootstrap-clm.yml
scripts/jenkins/ardana/ansible/bootstrap-vcloud-nodes.yml
scripts/jenkins/ardana/ansible/group_vars/all/vcloud.yml
scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/defaults/main.yml
scripts/jenkins/ardana/ansible/roles/heat-generator/defaults/main.yml
scripts/jenkins/ardana/ansible/roles/heat-generator/vars/caasp.yml
scripts/jenkins/ardana/ansible/roles/heat-generator/vars/standard.yml
scripts/jenkins/ardana/ansible/roles/input_model_generator/defaults/main.yml
scripts/jenkins/ardana/ansible/roles/input_model_generator/vars/templates/service/full-spread.yml
scripts/jenkins/ardana/ansible/roles/input_model_generator/vars/templates/service/split.yml
scripts/jenkins/ardana/ansible/roles/input_model_generator/vars/templates/service/standard.yml
scripts/jenkins/ardana/ansible/roles/send_to_os_health/defaults/main.yml
scripts/jenkins/ardana/ansible/roles/setup_root_partition/defaults/main.yml
scripts/jenkins/ardana/ansible/roles/setup_root_partition/tasks/main.yml

This PR enables LVM disk configuration in Ardana deployment:
- use a different SLES image set (cleanvm-jeos-lvm-SLE12SP3/SP4),
which use an LVM root partition
- reduce the size of the volume groups in the generated heat stacks
from 30 GB to 20 GB, to be aligned with those used by `ardana-dev-tools`
- remove the ansible tasks that were previously disabling the Ardana
disk configuration in `osconfig-ansible`
It also adds a `setup_root_partition` ansible role inspired largely from
`ardana-dev-tools` [1], which automates expanding the root partition,
LVM volume and file system of the cloud nodes.
The PR also adds the `SLES12SP3-SDK-Updates` repository to the
list of repositories required to install `python-devel`, to correct the problem of
strict version dependency between `python-base`, …

openstack-ardana: switch to LVM root partition images

---

jenkins/ci.suse.de/templates/cloud-mkcloud-gating-template.yaml

The Crowbar IBS gating job has been mistakingly submitting
Ardana venv packages to the non-staging IBS project, which
overlaps with the Ardana IBS gating job.

mkcloud-gating: exclude Ardana venv packages

---

jenkins/ci.suse.de/cloud-ardana8.yaml
jenkins/ci.suse.de/cloud-ardana9.yaml
jenkins/ci.suse.de/templates/cloud-mkcloud-gating-template.yaml
scripts/jenkins/ardana/gerrit/README.md
scripts/jenkins/ardana/gerrit/gerrit-settings.json

Use the develcloudX cloudsource for Gerrit jobs instead of
stagingcloudX. This will effectively isolate the Gerrit CI
from OpenStack package updates landing in IBS in the staging
project (*), while at the same time continuing to include the latest
Ardana ansible sources.
This PR comes as a continuation of #2903 . The final result of these two
PRs modifies Ardana Jenkins Gerrit jobs to use the following classes of packages, layered on top of eachother:
- cloud baseline: Devel:Cloud:X packages, which are already validated by the Ardana IBS gating jobs
- Ardana baseline: Ardana ansible packages rebuilt to correspond to the latest merged Gerrit repository sources, which are already validated individually by the Gerrit CI against the Devel:Cloud:X contents before they are merged
- Gerrit …

openstack-ardana-gerrit: use develcloud cloudsource

---

scripts/jenkins/ardana/ansible/roles/input_model_generator/README.md
scripts/jenkins/ardana/ansible/roles/input_model_generator/templates/input_model/data/network_groups.yml
scripts/jenkins/ardana/ansible/roles/input_model_generator/templates/input_model/data/neutron/neutron_config.yml
scripts/jenkins/ardana/ansible/roles/input_model_generator/vars/entry-scale-kvm.yml
scripts/jenkins/ardana/ansible/roles/input_model_generator/vars/templates/interface/compact-bond.yml
scripts/jenkins/ardana/ansible/roles/input_model_generator/vars/templates/interface/compact.yml
scripts/jenkins/ardana/ansible/roles/input_model_generator/vars/templates/interface/full-spread-bond.yml
scripts/jenkins/ardana/ansible/roles/input_model_generator/vars/templates/network/compact.yml
scripts/jenkins/ardana/ansible/roles/input_model_generator/vars/templates/network/full-spread.yml

Using the `neutron.l3_agent.external_network_bridge` tag to
indicate the provider network used as a backend by the neutron
external network has been broken since cloud8 [1]. Using this
tag will effectively supply no provider network attributes to
the external neutron network, which in turn causes neutron
to automatically select one of the tenant networks to act as
a backend for the external network.
This commit fixes the generated external neutron network
configuration to provide explicit provider attribute values
and to model the external network as a flat provider network.
The commit also changes the generated names used for the external neutron
networks to match the name used by the `ardana-input-model` input models
(e.g. `ext-net`, `ext-net1` and so on), because the implementation of …

input-model-generator: fix external network support

---

jenkins/ci.suse.de/cloud-ardana.yaml
jenkins/ci.suse.de/openstack-ardana-bootstrap-clm.yaml
jenkins/ci.suse.de/openstack-ardana-heat.yaml
jenkins/ci.suse.de/openstack-ardana-qa-tests.yaml
jenkins/ci.suse.de/openstack-ardana-tempest.yaml
jenkins/ci.suse.de/openstack-ardana-update-and-test.yaml
jenkins/ci.suse.de/openstack-ardana-update.yaml
jenkins/ci.suse.de/openstack-ardana-vcloud.yaml
jenkins/ci.suse.de/pipelines/openstack-ardana-gerrit.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana-update-and-test.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana-vcloud.Jenkinsfile
jenkins/ci.suse.de/pipelines/openstack-ardana.Jenkinsfile
jenkins/ci.suse.de/templates/cloud-ardana-job-gerrit-template.yaml
jenkins/ci.suse.de/templates/cloud-ardana-pipeline-template.yaml
scripts/jenkins/ardana/ansible/roles/heat-generator/templates/heat-template.yaml
scripts/jenkins/ardana/ansible/roles/heat_stack/defaults/main.yml

Changes all periodic and Gerrit Ardana Jenkins jobs to use a
dedicated `cloud-ci` ECP account, while the shared `cloud`
project is still preserved as a default, to be used for manual 
builds.
This is required to prevent the CI from running into quota limitation
errors that would otherwise occur with an ECP account shared by non-CI
elements (developers, QA, etc.). It also allows us to better monitor
the total CI resource usage by simply looking at the OpenStack project
it's using.
The new `engcloud-cloud-ci-private` OpenStack configuration label
value has the same credentials as the old `engcloud-cloud-ci` value,
with the exception of the project name, which points to the dedicated
`cloud-ci` project instead.

openstack-ardana: use dedicated ECP project for CI (SCRD-5739)

---

scripts/jenkins/ardana/gerrit/build_test_package.py

This gets the name of the .obsinfo file from the _service file instead
of relying on it being the same as the package name.

Expect ardana packages with different source files

---

scripts/jenkins/ardana/ansible/group_vars/all/vcloud.yml
scripts/jenkins/ardana/ansible/group_vars/all/versioned.yml
scripts/jenkins/ardana/ansible/roles/setup_root_partition/defaults/main.yml
scripts/jenkins/ardana/ansible/roles/setup_root_partition/tasks/main.yml

Disable LVM on virtual deployments with GM8* cloudsources until https://gerrit.suse.provo.cloud/#/c/5143 gets released.
This PR also includes a fix for `setup_root_partition` role and a cleanup on the versioned conditional variables.

openstack-ardana: disable LVM for GM8 cloudsources 

---

scripts/jenkins/ardana/ansible/roles/setup_root_partition/defaults/main.yml
scripts/jenkins/ardana/ansible/roles/setup_root_partition/tasks/main.yml

Following @rtamalin suggestion, this change moves `root_mount` variable to
`defaults.yml` as it makes more sense when this variable is used to define
`resize_tools` which is also in `defaults.yml`

openstack-ardana: move root_mount to role defaults

---

scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/defaults/main.yml
scripts/jenkins/ardana/ansible/roles/send_to_os_health/defaults/main.yml

As a temporary solution to the problem of python-devel/python-base
package version mismatch between the SLES12-SP4 base image and the
released SLES12-SP4-SDK GM, the SP3 SDK-Updates repo was also included
before installing python-devel.
The root cause of the problem was identified as an incorrectly
built SLES12-SP4 image and was corrected by including the
`snapshot-SP4` repositories from SLE-12 update projects instead
of the `standard` ones [1], hence this hack is no longer required.
[1] https://build.suse.de/project/meta/home:fmccarthy:ardana-images

openstack-ardana: remove SDK SP3 repo hack

---

scripts/qa_crowbarsetup.sh

For about a month there is a broken test update in the SOC8 Updates
Test repository that breaks everything, and its not getting removed.
Allow to blacklist the -test update channel as well.

qa_crowbarsetup.sh: check for broken marker also on Crowbar test updates

---

scripts/jenkins/ardana/ansible/roles/setup_zypper_repos/tasks/setup_maint_update_repos.yml
scripts/jenkins/ardana/ansible/roles/setup_zypper_repos/tasks/setup_sles_cloud_repos.yml

This change adds retries to rsync tasks on setup_zypper_repos role to prevent error: `rsync warning: some files vanished before they could be transferred (code 24) at main.c(1652) [generator=3.1.0]` which is recurring on CI.

openstack-ardana: retry repository rsync when rc = 24

---

scripts/jenkins/ardana/gerrit/build_test_package.py

Check the package source version against the branch revision
reported by the Gerrit REST API instead of creating local
git clones for all the packages.
This approach reduces the build time significantly, because
it only creates local git clones for packages that actually
require updating. It also reduces the strain on the Gerrit
server.

openstack-ardana-gerrit: check packages against Gerrit REST API

---

jenkins/ci.suse.de/cloud-ardana9.yaml

Currently qe102 job is running tempest with the CI filter only, this
change adds more tests to be execured by the job.

openstack-ardana: enable more tempest tests on qe102 periodic job

---

scripts/lib/mkcloud-driver-libvirt.sh

libvirt complains if the network is already running causing an
immediate exit

check cloud-admin network before trying to start it

---

docs/repositories.dot

Draw repositories.dot from left to right instead of top-down, as that makes it fit better on a screen.
Document more from Rocky in repositories.dot.

 Document more from Rocky in repositories.dot 

---

scripts/jenkins/ardana/ansible/roles/heat-generator/library/generate_heat_model.py
scripts/jenkins/ardana/ansible/roles/input_model_generator/templates/input_model/data/networks.yml

The False default `tagged-vlan` value used by the heat generator did
not correspond to the default `tagged-vlan` value used in the
input models (True). This is causing external network connectivity
issues when the std-min input model is used.

heat-generator: fix default value for tagged-vlan

---

scripts/jenkins/ardana/ansible/group_vars/all/versioned.yml
scripts/jenkins/ardana/ansible/roles/input_model_generator/README.md
scripts/jenkins/ardana/ansible/roles/input_model_generator/defaults/main.yml
scripts/jenkins/ardana/ansible/roles/input_model_generator/templates/input_model/data/network_groups.yml
scripts/jenkins/ardana/ansible/roles/input_model_generator/templates/input_model/data/neutron/neutron_config.yml

Keep using the `external_network_bridge` deprecated input
model option for GM8+up deployments until the bsc#1117198 fix
is released.
Also requires reverting https://gitlab.suse.de/cloud-qe/ardana-bm-info/merge_requests/7

input-model-generator: re-enable external_network_bridge
