scripts/jenkins/ardana/gerrit/gerrit.py
SSL verification was switched off by mistake in a previous commit.
=> openstack-ardana-gerrit: re-enable SSL verification

scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/tasks/read_group_vars.yml
As part of SCRD-5595, keystone-ansible cleanup,
the keystone_admin_token has been removed from group_vars.
https://gerrit.suse.provo.cloud/#/c/5224/
Also the keystone_member_role is removed as part of
https://gerrit.suse.provo.cloud/#/c/5275/
This change to be inline with those product changes.
=> Updates to read_group_vars in line with product changes

jenkins/ci.suse.de/pipelines/openstack-ardana-update-and-test.Jenkinsfile, jenkins/ci.suse.de/pipelines/openstack-ardana.Jenkinsfile
Parameters of the type 'extended-choice' are set to null when the job
is automatically triggered and its default value is ''. So, we need to set
it to '' to be able to pass it as a parameter to downstream jobs.
=> openstack-ardana: fix for tempest/QA test jobs

scripts/jenkins/ardana/gerrit/gerrit_merge.py
When a change is unable to be merged because of its dependencies not
being met we should provide feedback to the user. Other unmet
requirements (such as required labels etc) are already obvious in the
gerrit UI.
Fixes: SCRD-5890
=> Provide feedback for unmergeable changes

jenkins/ci.suse.de/cloud-ardana9.yaml
This change adds more QA tests to be run on the
`cloud-ardana9-job-entry-scale-kvm-qe102-x86_64` periodic job
=> openstack-ardana: add more QA tests to entry-scale-kvm-qe102 job

jenkins/ci.suse.de/openstack-ardana-bootstrap-clm.yaml, jenkins/ci.suse.de/openstack-ardana-heat.yaml, jenkins/ci.suse.de/openstack-ardana-pcloud.yaml, jenkins/ci.suse.de/openstack-ardana-tests.yaml, jenkins/ci.suse.de/openstack-ardana-update-and-test.yaml, jenkins/ci.suse.de/openstack-ardana-update.yaml, jenkins/ci.suse.de/openstack-ardana-vcloud.yaml, jenkins/ci.suse.de/templates/cloud-ardana-job-gerrit-template.yaml, jenkins/ci.suse.de/templates/cloud-ardana-pipeline-template.yaml
Use `validating-string` JJB parameters and add validation to
a few job parameters that, if not validated properly, could
cause serious problems to the CI.
=> openstack-ardana: validate job parameter values

jenkins/ci.suse.de/cloud-ardana9.yaml
The current implementation is adding space at every break line which
causes those tests with space on its name to be skipped.
This change fixes that by using '\' to break lines.
=> openstack-ardana: Fix QA test list on job template

jenkins/ci.suse.de/cloud-trackupstream.yaml
We now also ship caasp-openstack-heat-templates on Cloud 7 and therefore
have to track the package as well.
=> Enable caasp-openstack-heat-templates tracking for Cloud 7

scripts/qa_crowbarsetup.sh
The warning for attempting to deploy trove for Cloud 9+ read a little
strangely. Reword it.
=> qa_crowbarsetup: Rewrite Trove error message

scripts/mkcloud
So far it appended a suffix which was never used for anything,
and with https://github.com/crowbar/crowbar-core/pull/1696 merged
it became more strict in what it accepted.
=> mkcloud: avoid malformatted ssh key injection

jenkins/ci.suse.de/pipelines/openstack-ardana-bootstrap-clm.Jenkinsfile, jenkins/ci.suse.de/pipelines/openstack-ardana-heat.Jenkinsfile, jenkins/ci.suse.de/pipelines/openstack-ardana-pcloud.Jenkinsfile, jenkins/ci.suse.de/pipelines/openstack-ardana-tests.Jenkinsfile, jenkins/ci.suse.de/pipelines/openstack-ardana-update-and-test.Jenkinsfile, jenkins/ci.suse.de/pipelines/openstack-ardana-update.Jenkinsfile, jenkins/ci.suse.de/pipelines/openstack-ardana-vcloud.Jenkinsfile, jenkins/ci.suse.de/pipelines/openstack-ardana.Jenkinsfile, jenkins/ci.suse.de/pipelines/openstack-ardana.groovy, scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/vars/neutron.yml, scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/vars/remove_compute_node.yml
This commit changes the way pipeline jobs are organized,
such that it minimizes the number of downstream jobs
being triggered. This is done by "merging" copies of the
`openstack-ardana-vcloud`, `openstack-ardana-pcloud`,
`openstack-ardana-tests`, `openstack-ardana-bootstrap-clm` 
and `openstack-ardana-update` jobs into their parent pipeline
jobs (`openstack-ardana` and `openstack-ardana-update-and-test`).
To reduce the duplication that comes from flattening
the pipeline jobs, a small groovy library was added,
containing a few functions reused by various pipeline
stages.
Advantages gained by this change in strategy:
- jobs are easier to navigate and debug (everything is in
view of a single job, the user isn't required to navigate
the pipeline hierarchy to gather needed information anymore) …
=> openstack-ardana: flatten pipeline jobs

jenkins/ci.suse.de/pipelines/openstack-ardana.Jenkinsfile, jenkins/ci.suse.de/pipelines/openstack-ardana.groovy
Corrects two recently introduced issues with flattened pipeline stages:
- not addressing empty `tempest_filter_list` or `qa_test_list` values
- missing condition for 'Create heat stack' stage
=> openstack-ardana: fix flattened pipeline stages

jenkins/ci.suse.de/pipelines/openstack-ardana-gerrit.Jenkinsfile, jenkins/ci.suse.de/pipelines/openstack-ardana.Jenkinsfile, scripts/jenkins/jenkins-job-pipeline-report.py
Following up on the commit that introduced the
`jenkins-job-pipeline-report.py` script, which generates
a summary report for a pipeline Jenkins job build:
- addressed post-review feedback [1]
- use stdout instead of dumping to file
- other
- improved the command line parameter handling
- joined -j and -b into a single positional parameter
- fall-back to using the JOB_NAME and BUILD_NUMBER
environment variables if not explicitly provided
- make the build number optional and use the latest
build when not supplied
[1] https://github.com/SUSE-Cloud/automation/pull/3019#pullrequestreview-183576280
=> openstack-ardana: generate pipeline build report follow-up

scripts/ping_forever.sh
Quote variables and switch from `` to $() to silence shellcheck
warnings.
=> ping_forever: shellcheck fixes

jenkins/ci.suse.de/pipelines/openstack-ardana-update-and-test.Jenkinsfile, jenkins/ci.suse.de/pipelines/openstack-ardana.Jenkinsfile
The recent work done to 'flatten' the Ardana pipeline
job hierarchy created a situation which causes some jobs
to collect jUnit test case results twice.
This commit corrects that condition.
=> openstack-ardana: collect jUnit results just once

scripts/lib/mkcloud-common.sh
Currently to_ip only calls to_ip4 to resolve addresses using the
ahostsv4 database of getent's resolver. The code already supports
resolving IPv6 addresses using the ahostsv6 database, so fallback to
using that if IPv4 address is returned.
=> to_ip: Fallback to resolving IPv6

scripts/jenkins/ardana/ansible/roles/setup_zypper_repos/templates/motd.j2
Adds the Jenkins job build URL to the motd generated
on the deployer node.
=> openstack-ardana: add Jenkins BUILD_URL to motd

jenkins/ci.suse.de/openstack-ardana-pcloud.yaml, jenkins/ci.suse.de/openstack-ardana-vcloud.yaml, jenkins/ci.suse.de/templates/cloud-ardana-pipeline-template.yaml, scripts/jenkins/ardana/ansible/roles/heat-generator/templates/heat-template.yaml, scripts/jenkins/ardana/ansible/roles/input_model_generator/templates/input_model/data/firewall_rules.yml, scripts/jenkins/ardana/ansible/roles/input_model_generator/templates/input_model/data/networks.yml, scripts/jenkins/ardana/ansible/roles/input_model_generator/templates/input_model/data/neutron/neutron_config.yml, scripts/jenkins/ardana/ansible/roles/input_model_generator/vars/templates/network/compact.yml
- This PR enables user to create IPv6 mix-mode virtual deployment. Mix-mode deployment is using ipv4 network for the deployment/management purpose as accessing ECP over ipv6 is not yet possible. Other reasons are accessing internal repo, dns & ntp services over IPv6.  All other cloud  deployment networks (EXTERNAL-API, GUEST, STORAGE, etc) are being configured  to use ipv6.  
- Tested locally by generating input model and heat template for different scenarios (entry-scale-kvm, mid-scale, std-split, standard)
=> Enable ipv6 mix-mode virtual deployment.

scripts/jenkins/ardana/ansible/roles/heat-generator/templates/heat-template.yaml, scripts/jenkins/ardana/ansible/roles/input_model_generator/templates/input_model/data/firewall_rules.yml, scripts/jenkins/ardana/ansible/roles/input_model_generator/templates/input_model/data/networks.yml, scripts/jenkins/ardana/ansible/roles/input_model_generator/templates/input_model/data/neutron/neutron_config.yml
For some reason the ipv6 fact is not getting defined with a default
of false in recent Ardana CI runs causing breakages.
To help avoid the issue, ensure any use of the ipv6 fact explicitly
defaults to false.
=> Ensure we default ipv6 fact access to false

jenkins/ci.suse.de/pipelines/openstack-ardana.Jenkinsfile
Fix the pipeline job execution report generated at the end
of the openstack-ardana pipeline job by using the shared workspace.
=> openstack-ardana: fix pipeline job report

scripts/jenkins/ardana/ansible/bootstrap-vcloud-nodes.yml, scripts/jenkins/ardana/ansible/setup-ssh-access.yml
The target ansible hosts need to be up, otherwise gathering
facts will fail. We already check for that, but we also need
to postpone gathering facts until after the `wait_for_connection`
check.
=> openstack-ardana: gather facts after nodes are up

scripts/jenkins/ardana/ansible/roles/heat-generator/templates/heat-template.yaml
Mapping volumes to server mountpoints doesn't work in OpenStack [1].
The way we enforced that was by controlling the order in
which volumes get attached to servers through heat `depends_on`
hints.
However, this doesn't seem to work anymore. With Pike, we very
frequently get the root partition mounted as /dev/vdb and a regular
volume mounted as /dev/vda.
This patch attempts a different approach, serializing the creation
of server, volumes and volume attachment resources by linking them
with `depends_on` restrictions. The time it takes to create a volume
will increase the chance that volumes are attached in the right order.
[1] https://bugs.launchpad.net/nova/+bug/1004328
=> openstack-ardana-heat: volume mountpoint mapping

scripts/jenkins/ardana/ansible/group_vars/all/all.yml, scripts/jenkins/ardana/ansible/group_vars/all/jenkins.yml, scripts/jenkins/ardana/ansible/roles/jenkins_artifacts/defaults/main.yml, scripts/jenkins/ardana/ansible/roles/rocketchat_notify/defaults/main.yml, scripts/jenkins/ardana/ansible/roles/rocketchat_notify/tasks/main.yml, scripts/jenkins/ardana/ansible/roles/rocketchat_notify/vars/ardana-qe-tests.yml, scripts/jenkins/ardana/ansible/roles/rocketchat_notify/vars/deploy.yml, scripts/jenkins/ardana/ansible/roles/rocketchat_notify/vars/tempest.yml, scripts/jenkins/ardana/ansible/roles/rocketchat_notify/vars/update.yml, scripts/jenkins/ardana/ansible/roles/send_to_os_health/defaults/main.yml, scripts/jenkins/jenkins-job-pipeline-report.py
Use ci.nue.suse.com intead of ci.suse.de, because the latter
doesn't work for all VPN users.
=> openstack-ardana: use ci.nue.suse.com URLs

scripts/jenkins/ardana/ansible/bootstrap-vcloud-nodes.yml
By default ansible saves ssh’s ControlPath sockets on `~/.ansible/cp`
[1] and when running multiple playbooks in parallel that access hosts with
the same IP addrests through distincts bastion hosts, the sockets
are created/reused with the same name. This results in ansible accessing
hosts targeted in one playbook from another.
This change ovewrites the ssh control path when the hosts are accessed
thorugh the bastion. The ssh control path is set based on the ardana_env
value together with the login, host and port.
1. https://docs.ansible.com/ansible/latest/reference_appendices/config.html#ansible-ssh-control-path
=> openstack-ardana: fix ansible connection through bastion host

scripts/jenkins/ardana/ansible/roles/heat-generator/templates/heat-template.yaml
Use a TestResource resource to insert a delay after a server
is created and before volumes are attached, to ensure that the ephemeral
disk hosting the root partition is mounted first (as /dev/vda).
This also reverts the previous change linking volume creation
and attachment (#3044), because it wasn't working.
=> openstack-ardana-heat: use heat delay for volume order

jenkins/ci.suse.de/cloud-ardana8.yaml, jenkins/ci.suse.de/cloud-ardana9.yaml
The `cloud-ardana[8|9]-job-gerrit-x86_64` jobs were introduced
a while ago to monitor the status of the Gerrit CI. However, they
have never actually served their purpose, because
1. they need to target actual open Gerrit changes
2. those gerrit changes need constant maintenance, otherwise they
get abandoned
3. they need resources to run, which are scarce
=> openstack-ardana: remove unused Gerrit jobs

scripts/mkcloudhost/generate-radvd-conf
Due to misreading the error message during the testing, AdvRDNSSLifetime
must be at least *Max*RtrAdvInternal, not the minimum. Bump to the
maxiumum value.
=> generate-radvd-conf: Increase AdvRDNSSLifetime

jenkins/ci.suse.de/cloud-ardana9.yaml
This enable QA members to pause the daily job rebuild if necessary by
manually reserving the qe102 lockable resource at ci.suse.de
=> openstack-ardana: use lockable resource for qe102 job

hostscripts/rpm-packaging/createproject.py
This is useful when looking at the OBS test project. Find the job who
created the project is then a lot simpler.
=> createproject: Add jenkins job url if available to description

scripts/jenkins/ardana/ansible/roles/heat_stack/defaults/main.yml, scripts/jenkins/ardana/ansible/roles/heat_stack/tasks/create.yml
Sometimes (eg. due to some issue on ECP) the stack gets stuck on CREATING
state until it times out which by default is 1 hour. However creating a heat stack
takes in average 3 minutes and if it takes much longer it will probably
not be crated successfully.
This change sets the heat stack creation timeout to 8 minutes (should be
more than enough to create the stack) so we can throw the error and try
again faster.
=> openstack-ardana: lower timeout for stack creation

scripts/jenkins/qa_devstack.sh
All tempest tests in tempest.api.volume.test_volumes_backup and
tempest.api.volume.admin.test_volumes_backup are failing because
cinder-backup is trying to use swift as a backend.
However, because of we are using Python3, swift can not be enabled.
This patch disables cinder backup in case that swift is not enabled per
https://review.openstack.org/#/c/75073/
Signed-off-by: aojeagarcia <aojeagarcia@suse.com>
=> Disable cinder backup if swift is not enabled

jenkins/ci.opensuse.org/macros.yaml
Using wget -O is dangerous on parallel runs, as it might
cause two jobs running at the same time to update the update_automation
script, which causes this error:
/root/bin/update_automation: /bin/bash: bad interpreter: Text file busy
Build step 'Execute shell' marked build as failure
This is a security measurement by the kernel to avoid races with
somebody replacing the content of a shell script while it is being
executed.
=> Make update_automation truly atomic updating

scripts/jenkins/jenkins-job-pipeline-report.py
When calling jenkins-job-pipeline-report.py after an ABORTED job,
stage_url will be None and calling .replace() on a NoneType object
will raise an Exception.
Only call stage_url.replace() when stage_url is not None.
```
[openstack-ardana-2358] Running shell script
+ cd /home/jenkins/shared/cloud-ardana-ci-slot6
+ automation-git/scripts/jenkins/jenkins-job-pipeline-report.py --recursive --filter 'Declarative: Post Actions' --filter 'Setup workspace'
File "automation-git/scripts/jenkins/jenkins-job-pipeline-report.py", line 247, in <module>
main()
File "automation-git/scripts/jenkins/jenkins-job-pipeline-report.py", line 243, in main
args.filter, args.recursive)
File "automation-git/scripts/jenkins/jenkins-job-pipeline-report.py", line 187, in …
```
=> jenkins-report: avoid raising an exception

scripts/jenkins/ardana/ansible/group_vars/all/versioned.yml, scripts/jenkins/ardana/ansible/roles/ardana_deploy/tasks/main.yml
As `bsc#1110414` is already fixed, we do not need a workaround for it
anymore.
=> openstack-ardana: remove workaround for bsc#1110414

jenkins/ci.suse.de/cloud-ardana9.yaml
This change adds a periodic job for ardana cloud9 deployed on hardware using the mid-scale-kvm input model.
It also sets `reserve_env` to true on qe102 job to enable the QA team to easily reserve the environemnt (pause the dialy rebuild) when needed
=> openstack-ardana: add periodic cloud9 job for mid-scale-kvm input model

scripts/jenkins/ardana/ansible/roles/input_model_generator/templates/input_model/data/networks.yml, scripts/jenkins/ardana/ansible/roles/input_model_generator/templates/input_model/data/neutron/neutron_config.yml
Updating unique local ipv6 address to use fd::/64 instead of fc::/64 according to https://en.wikipedia.org/wiki/Unique_local_address.
=> Update local ipv6 address to use fd::/64.

scripts/lib/ipv6/network.json, scripts/lib/mkcloud-common.sh, scripts/lib/mkcloud-driver-libvirt.sh, scripts/lib/mkcloud-onhost.sh, scripts/mkcloud, scripts/qa_crowbarsetup.sh
Add a bunch of ipv6 networks:
fd00:0:0::1:/112
fd00:0:0::2:/112
fd00:0:0::3:/112
fd00:0:0::4:/112
fd00:0:0::5:/112
Using a 112 as that gives us the full last 16 bits (:XXXX) for hosts.
meaning we can just use existing ipv4 last octet numbers. Ie .100 ==
:100 or .254 == :254.
This is still a WIP and doesn't actually run properly yet. Putting it here for the squad to laugh^Wlook at.
Still got _along_ way to go.
=> ipv6: first attempt at want_ipv6 option

scripts/qa_crowbarsetup.sh
We want to avoid leaking or overwriting variables in global scope.
=> Localize variables used in `addfloatingip`

scripts/mkcloud
The mkch* hosts are running SLES 12 of varying ages, too old for base
ping to support IPv6 addresses. Switch the ping command for the
setupadmin step to use ping6 if want_ipv6 is enabled. Drive-by removing
a spurious comment.
=> mkcloud: Teach setupadmin about ping6

jenkins/ci.suse.de/cloud-ardana9.yaml
Enable SES on periodic job qe102 used by QE.
=> openstack-ardana: enable SES on cloud9 qe102 periodic job

scripts/qa_crowbarsetup.sh
The previous regexp is matching both the BuildXX and the
static link download location, causing the media to be
downloaded twice because apparently the server is no longer
handling symlinks as http redirects. This fills up the
root disk and the installation breaks.
=> qa_crowbarsetup.sh: Download the staticlink image only

scripts/scenarios/cloud9/qa/no-ssl/qa-scenario-1a.yaml, scripts/scenarios/cloud9/qa/no-ssl/qa-scenario-1b.yaml, scripts/scenarios/cloud9/qa/no-ssl/qa-scenario-2a.yaml, scripts/scenarios/cloud9/qa/no-ssl/qa-scenario-2b.yaml, scripts/scenarios/cloud9/qa/no-ssl/qa-scenario-2c.yaml, scripts/scenarios/cloud9/qa/no-ssl/qa-scenario-6a.yaml, scripts/scenarios/cloud9/qa/no-ssl/qa-scenario-8a.yaml, scripts/scenarios/cloud9/qa/no-ssl/qa-scenario-8b.yaml, scripts/scenarios/cloud9/qa/no-ssl/qa-scenario-9.yaml, scripts/scenarios/cloud9/qa/ssl-insecure/qa-scenario-1a.yaml, scripts/scenarios/cloud9/qa/ssl-insecure/qa-scenario-1b.yaml, scripts/scenarios/cloud9/qa/ssl-insecure/qa-scenario-2a.yaml, scripts/scenarios/cloud9/qa/ssl-insecure/qa-scenario-2b.yaml, scripts/scenarios/cloud9/qa/ssl-insecure/qa-scenario-2c.yaml, scripts/scenarios/cloud9/qa/ssl-insecure/qa-scenario-6a.yaml, scripts/scenarios/cloud9/qa/ssl-insecure/qa-scenario-8a.yaml, scripts/scenarios/cloud9/qa/ssl-insecure/qa-scenario-8b.yaml, scripts/scenarios/cloud9/qa/ssl/qa-scenario-1a.yaml
After this change https://github.com/crowbar/crowbar-openstack/pull/1893
vnc_keymap is not passing schema validation
=> Remove vnc_keymap from all cloud 9 qa scenarios

jenkins/ci.opensuse.org/openstack-cleanvm.yaml, jenkins/ci.opensuse.org/openstack-prepare-staging.py, jenkins/ci.opensuse.org/openstack-prepare-staging.yaml, jenkins/ci.opensuse.org/openstack-staging.yaml, jenkins/ci.opensuse.org/openstack-submit.yaml, scripts/jenkins/qa_openstack.sh
Currently Staging may receive changes during testing and when its
finished changes that weren't tested may be submited instead of only
those that were tested. This fixes both by first making a copy of
Cloud:OpenStack:Rocky:Staging in Cloud:OpenStack:Rocky:ToTest and after
successful testing copy that to Cloud:OpenStack:Rocky.
This only makes the change for Rocky, it can be extended to the rest
later if that is useful.
This implements part of the alternative mentioned in
SUSE/cloud-specs#178 .
For all release branches fix that if there are multiple base
distributions to test on, only submit Staging after all of them
succeeded instead of after one of them. To accomplish that testing
multiple bases is done in a subjob.
To avoid a race where new source and old binaries are tested and
released …
=> Copy whole Staging and use a Test project

jenkins/ci.suse.de/cloud-ardana8.yaml, jenkins/ci.suse.de/cloud-ardana9.yaml, jenkins/ci.suse.de/templates/cloud-ardana-url-trigger-template.yaml
The ardana job for testing cloud8 on pcloud001 QE environment should be
triggered when there is a change on the Updates-test repository.
This change also updates the cloud-ardana-gating-trigger-template to
get the url and a list of projects from the job definition, making
possible reusing it to create other url trigger jobs with different
urls.
=> openstack-ardana: trigger pcloud001 job based on updates test repo

jenkins/ci.opensuse.org/openstack-prepare-staging.py
to access those from. One was a missing import. The other needed the
module path prepended.
=> openstack-prepare-staging: correct which module

scripts/jenkins/ardana/ansible/roles/ardana_tempest/defaults/main.yml
Update path to look for amphora image to work with cloud8 & cloud9.
Cloud9:
find /srv/www/*/x86_64/repos/*OpenStack*/ -name '*octavia-amphora-image*' | tail -n1
/srv/www/suse-12.4/x86_64/repos/SUSE-OpenStack-Cloud-9-Pool/suse/noarch/openstack-octavia-amphora-image-x86_64-0.1.0-2.187.noarch.rpm
Cloud8:
find /srv/www/*/x86_64/repos/*OpenStack*/ -name '*octavia-amphora-image*' | tail -n1
/srv/www/suse-12.3/x86_64/repos/SUSE-OpenStack-Cloud-8-Pool/noarch/openstack-octavia-amphora-image-x86_64-0.1.0-1.21.noarch.rpm
=> Update path for amphora image rpm file.

jenkins/ci.opensuse.org/openstack-staging.yaml
usually has an executor free, use that instead. The job
openstack-staging only calls other jobs but still needs one slot.
cloud-cleanvm only has one executor slot.
=> openstack-staging: node openstack-rpm-packaging

jenkins/ci.suse.de/pipelines/openstack-ardana.Jenkinsfile
For bare-metal deployments we do not need to deploy SES as it uses an
existing SES cluster.
=> openstack-ardana: deploy SES only for virtual deployments

scripts/jenkins/ardana/ansible/group_vars/all/versioned.yml, scripts/jenkins/ardana/ansible/roles/input_model_generator/defaults/main.yml
For Cloud9 we want to switch to using the designate worker/producer
services than the deprecated zone/pool managers. To support this we
define a new versioned feature, designate_worker_producer, which is
true for Cloud9 deployments.
This new versioned feature setting is checked when defining the CORE
service components list, and we generate either worker or pool and
producer or zone entries accordingly in the list.
NOTE: This change should not be landed until the corresponding patch
to the ardana/designate-ansible.git repo that fixes worker/producer
deployment for designate in Cloud9, with Gerrit ChangeID
I647ff48154d4af3e1c400b6ff8bc973a56ab81bd.
=> SCRD-6075 Add versioning support for designate services

jenkins/ci.suse.de/cloud-ardana8.yaml, jenkins/ci.suse.de/cloud-ardana9.yaml, jenkins/ci.suse.de/pipelines/openstack-ardana-gerrit.Jenkinsfile, jenkins/ci.suse.de/templates/cloud-ardana-job-gerrit-template.yaml
This change enable SES for all ardana-cloud8 jobs. In that way, besides
deploying ardana, those jobs will also deploy a SES cluster and
configure glance, nova, cinder and cinder-backup with SES backend.
As those jobs relies on tempest for testing and tempest does not support
object-store service configured with RADOS gateway, the object-store
service will not be configured with RADOS gateway (`ses_rgw_enabled =
false`).
=> openstack-ardana: enable SES for all cloud8 jobs

scripts/mkcloudcloud/deploy.sh
- deploy stack when running deploy.sh
- check for admin to be ready before ssh
- auto-generate ssh key for passwordless login
- install needed nfs-client in admin
- re-deploy stack if it was already creating with deploy.sh
- wait for stack to be ready before proceeding
=> Some fixes for mkcloudcloud scripts

jenkins/ci.suse.de/cloud-ardana8.yaml, jenkins/ci.suse.de/cloud-ardana9.yaml, jenkins/ci.suse.de/pipelines/openstack-ardana-gerrit.Jenkinsfile, jenkins/ci.suse.de/templates/cloud-ardana-job-gerrit-template.yaml
Reverts SUSE-Cloud/automation#3079
The change #3075 was reverted because it was breaking the CI. The issue was that the ardana jobs were not updated with the new parameters (we still have to do this manually).
This change applies #3075 again and as soon as it gets merged we need to update the ardana jobs.
=> Revert "Revert "openstack-ardana: enable SES for all cloud8 jobs""

scripts/jenkins/ardana/ansible/deploy-cloud.yml, scripts/jenkins/ardana/ansible/group_vars/all/versioned.yml
Service nova-consoleauth has been deprecated in Rocky[1]. We need this change to fix CI error for the cleanup of such service on ardana-input-model repo.
[1] https://docs.openstack.org/releasenotes/
nova/rocky.html#relnotes-18-0-0-stable-rocky
[2] https://jira.suse.de/browse/SCRD-6808
=> ardana: deprecate service nova-consoleauth

scripts/jenkins/ardana/ansible/group_vars/all/versioned.yml
Now that we are enabling manila in the ardana-ansible verb action lists
(in the .list files under roles/deployer-setup/files) we can enabled
manila for Cloud9 deployments in general.
Note however that until SCRD-6814 is addressed manila will be deployed
without any real configuration defined and therefore won't be usable
for actual testing in the CI.
=> SCRD-6812 Enable manila for Cloud9 deployments

jenkins/ci.suse.de/cloud-ardana9.yaml
Disabling RADOS Gateway from QE102 job as tempest does not support it
and it is causing tempest object-store tests to fail.
=> openstack-ardana: disable RGW on QE 102 job

jenkins/ci.suse.de/cloud-ardana8.yaml, jenkins/ci.suse.de/cloud-ardana9.yaml
Change the lockable resources allocation strategy to use
dedicated slots for Ardana IBS gating jobs. This approach
guarantees that the cloud environments that are left running
after a gating job failure are not not destroyed by other CI
jobs of less importance and are therefore available for debugging.
This should significantly shorten the amount of time needed to
identify and fix the issues affecting the gating jobs.
=> openstack-ardana: use dedicated slots for gating jobs

jenkins/ci.suse.de/cloud-ardana8.yaml, jenkins/ci.suse.de/cloud-ardana9.yaml
Switch the Ardana Cloud8 periodic and gating jobs to using generated
input models, to be similar to their Cloud9 counterparts.
This also includes switching the cloud9 'demo' input model job and creating
a similar job for cloud8. This minimalistic job is important, because
it's the fastest cloud deployment currently available to us (NOTE:
the 'demo' input model is an input model with one controller-deployer
node, one SLES compute node and with MML services disabled. Aside
from MML services, octavia and freezer also need to be disabled
because they are tightly coupled with Monasca.)
=> openstack-ardana: use generated input models for cloud8

scripts/jenkins/ardana/ansible/bootstrap-vcloud-nodes.yml
The variable holding the deployer IP is admin_conf_ip not admin_mgmt_ip
=> openstack-ardana: fix bootstrap vcloud for CentOS

jenkins/ci.suse.de/cloud-ardana8.yaml, jenkins/ci.suse.de/cloud-ardana9.yaml, jenkins/ci.suse.de/pipelines/openstack-ardana-gerrit.Jenkinsfile
This change enable SES for all ardana cloud9 jobs.
In that way, besides deploying ardana, those jobs
will also deploy a SES cluster and configure glance,
nova, cinder and cinder-backup with SES backend.
As those jobs rely on tempest for testing and
tempest does not support object-store service
configured with RADOS gateway, the object-store
service will not be configured with RADOS gateway
(ses_rgw_enabled = false).
This change also removes the SES parameters from
Gerrit jobs, because they are similar for cloud8/9.
=> openstack-ardana: enable SES for all cloud9 jobs

scripts/mkcloudhost/routed.cloud
If want_ipv6 is set to > 0, set the routed cloud on the mkch* hosts to
use the prefix from 99c199e928c7 for the admin network. Based on the
admin network prefix, set the public network prefix so that they
overlap. Create a random IPv6 prefix for the ironic network.
=> ipv6: Add network details to routed.cloud

jenkins/ci.suse.de/openstack-ardana-gerrit-events.yaml, jenkins/ci.suse.de/pipelines/openstack-ardana-gerrit.Jenkinsfile
Make the Ardana Gerrit Jenkins jobs vote Verify -2/+2, merge Gerrit
changes and handle Gerrit events, the same way it is currently done
for cloud9.
=> openstack-ardana-gerrit: voting job for cloud8

jenkins/ci.suse.de/cloud-ardana8.yaml, jenkins/ci.suse.de/pipelines/openstack-ardana-maintenance-gating.Jenkinsfile, jenkins/ci.suse.de/templates/cloud-ardana-maintenance-gating-template.yaml, scripts/jenkins/ardana/ansible/group_vars/all/all.yml, scripts/jenkins/ardana/ansible/roles/ardana_tempest/tasks/main.yml, scripts/jenkins/ardana/ansible/roles/rocketchat_notify/defaults/main.yml, scripts/jenkins/ardana/ansible/roles/setup_zypper_repos/templates/motd.j2, scripts/jenkins/ardana/ansible/run-tempest.yml
This change adds a new jenkins job for testing maintenance updates, this
job starts two instances of the openstack-ardana job:
1. Deploy: Will deploy ardana including the MU(s) and run tests
2. Update: Will deploy aradana, update to MU(s) after, and run tests
=> openstack-ardana: add a jenkins job for cloud8 maintenace gating

scripts/jenkins/qa_openstack.sh
If the repository list is not refreshed before the first patch, keys for
the default oss repos will not be imported yet and the patch will fail,
which can cause other installation errors down the line[1].
[1] https://ci.opensuse.org/job/openstack-cleanvm/image=openSUSE-Leap-15.0,slave=cloud-cleanvm/3507/console
=> cleanvm: Import keys before patch

jenkins/ci.suse.de/pipelines/cloud-ccp-full-periodic.Jenkinsfile
The backticks are causing issues in groovy parsing, and therefore
the text is simplified.
=> Clarify explanation for developers

jenkins/ci.suse.de/pipelines/openstack-ardana-gating.Jenkinsfile, scripts/jenkins/ardana/ansible/group_vars/all/all.yml, scripts/jenkins/ardana/ansible/roles/rocketchat_notify/vars/deploy.yml
Enable rocketchat notifications for ardana cloud 8 and 9 gating jobs.
Deployment and test status  will be reported to the
'cloud-ci-monitoring' channel.
=> openstack-ardana: report gating jobs status on rocketchat

jenkins/ci.suse.de/templates/cloud-ardana-pipeline-template.yaml
As SES is the recommended storage backend for ardana, the openstack
ardana job should deploy ardana with SES by default.
=> openstack-ardana: deploy ardana with SES by default

scripts/jenkins/ardana/ansible/group_vars/all/all.yml, scripts/jenkins/ardana/ansible/roles/input_model_generator/README.md, scripts/jenkins/ardana/ansible/roles/input_model_generator/templates/baremetal/disks.yml.j2, scripts/jenkins/ardana/ansible/roles/input_model_generator/templates/input_model/data/disk_models.yml, scripts/jenkins/ardana/ansible/roles/input_model_generator/vars/entry-scale-kvm.yml, scripts/jenkins/ardana/ansible/roles/input_model_generator/vars/mid-scale-kvm.yml, scripts/jenkins/ardana/ansible/roles/input_model_generator/vars/standard.yml, scripts/jenkins/ardana/ansible/roles/input_model_generator/vars/std-split.yml
Disable the cinder LVM backend by default if SES is enabled.
To avoid confusion, this PR also removes the unused `ses_enabled` variables
from the input model generator templates. Only the global variable
has effect.
=> openstack-ardana: disable cinder LVM backend with SES

scripts/jenkins/ardana/ansible/deploy-cloud.yml
If RADOS Gateway is not enabled send message right after ardana
deployment finishes.
=> openstack-ardana: fix rocketchat notification for deployment

scripts/jenkins/qa_devstack.sh
This allows us to test modifications to devstack, whether they're applied within the devstack environment after initial clone, or pushed to some github fork.
=> allow testing of devstack modifications

scripts/jenkins/ardana/ansible/roles/setup_zypper_repos/vars/milestone.yml
Get the milestone version from cloudsource using a regex instead of
getting the last digit which does not work for versions with 2 or more digits.
=> openstack-ardana: fix get milestone version from cloudsource

jenkins/ci.suse.de/pipelines/openstack-ardana.Jenkinsfile, jenkins/ci.suse.de/templates/cloud-ardana-pipeline-template.yaml, scripts/jenkins/ardana/ansible/deploy-cloud.yml, scripts/jenkins/ardana/ansible/roles/input_model_clone/tasks/main.yml, scripts/jenkins/ardana/ansible/roles/input_model_generator/tasks/main.yml
Add an option to skip running the steps that deploy the Ardana
cloud. This option can be used if one only needs to set up the
infrastructure and configure the cloud media and repositories,
but skip the actual cloud deployment, e.g. for testing purposes.
=> openstack-ardana: make cloud deployment optional

scripts/jenkins/ardana/ansible/group_vars/all/vcloud.yml, scripts/jenkins/ardana/ansible/group_vars/all/versioned.yml
The LVM based disk input model configuration has been disabled
during the Pike ECP upgrade [1][2] to reduce resources usage and impact.
The ECP has been stable for a long time, so it's time to re-enable
it in all jobs.
[1] https://gerrit.suse.provo.cloud/#/c/5143/
[2] #2998
=> openstack-ardana: re-enable LVM disk models

jenkins/ci.suse.de/cloud-ardana8.yaml, jenkins/ci.suse.de/templates/cloud-ardana-maintenance-gating-template.yaml
The `version` parameter was missing from the job. This change
adds that parameter as a hidden parameter type.
=> openstack-ardana: Fix MU gating job

scripts/jenkins/ardana/ansible/group_vars/all/versioned.yml, scripts/jenkins/ardana/ansible/roles/input_model_clone/tasks/main.yml, scripts/jenkins/ardana/ansible/roles/input_model_generator/tasks/main.yml
The `ceilometer-api` service has been removed from Rocky. This
change removes it from all generated input models used for Cloud9
jobs.
=> openstack-ardana: remove ceilometer-api from SOC9 (SCRD-6079)

jenkins/ci.suse.de/cloud-ardana9.yaml, jenkins/ci.suse.de/pipelines/openstack-ardana-gating.Jenkinsfile, jenkins/ci.suse.de/templates/cloud-ardana-gating-template.yaml
The Ardana IBS gating job runs two validation tests in parallel:
one that deploys an Ardana cloud based on the staging cloud
media (DC8S, DC9S), the other that deploys an Ardana cloud based on the
non-staging media (DC8) and then updates the cloud installation to
the staging media.
In some circumstances, both staging and non-staging builds are
broken (e.g. by a submitrequest breaking a package in the non-staging
project) and are subsequently fixed by patches that land in the
staging area. In these cases, the deploy-and-update job will not
pass and needs to be manually circumvented to unblock the CI/CD
pipeline.
This change allows the gating job to be (re)started with the update
validation step disabled.
=> openstack-ardana-gating: make update optional

jenkins/ci.suse.de/cloud-ardana8.yaml, jenkins/ci.suse.de/cloud-ardana9.yaml, jenkins/ci.suse.de/openstack-ardana-vcloud.yaml, jenkins/ci.suse.de/pipelines/openstack-ardana-image-update.Jenkinsfile, jenkins/ci.suse.de/templates/cloud-ardana-image-update-template.yaml, jenkins/ci.suse.de/templates/cloud-ardana-pipeline-template.yaml
Create a `cloud-ardana8-job-image-update` and a
`cloud-ardana9-job-image-update` Jenkins job that takes
in a SLES image built in IBS [1] and updates the OpenStack
image configured in the ECP and used as a base SLES image
by the CI, after running a batch of integration test cases
on it.
Implements: SCRD-5116
[1] initially at https://build.suse.de/project/show/home:fmccarthy:ardana-images, then officially moved to https://build.suse.de/project/show/Devel:Cloud:Images
=> openstack-ardana: automate SLES image update (SCRD-5116)

README.md, docs/devstack/README.md, scripts/heat/devstack-heat-template.yaml
Hopefully this will help put an end to the many manual hacks we have floating around the place, e.g.
- https://en.opensuse.org/SDB:DevStack
- https://confluence.suse.de/display/SOC/Devstack+in+libvirt+VM
- https://confluence.suse.de/display/SOC/Run+devstack+in+the+ENG+cloud
- https://confluence.suse.de/display/SOC/Devstack+on+OpenSUSE
- https://confluence.suse.de/display/HSLP/Install+Devstack
This works (on ECP at least) and so should instantly be useful, but I'm not sure whether the PR is complete as is, or whether I need to add something else, e.g.
It's pretty self-explanatory but I could update one of the above pages and make the others redirect to it.
Maybe adjust the existing devstack Jenkins job to use this instead of cleanvm?
=> Add heat template for devstack

docs/devstack/README.md
Make it more explicit how to use the key pair and how to see what happened with devstack.
=> Add some more details to doc on devstack via heat

scripts/mkcloudhost/routed.cloud
If the `want_ipv6` variable is not set on entry to `routed.cloud`, the
arithmetic evaluation will fail. This change introduces a default.
=> Set default for `want_ipv6`

jenkins/ci.suse.de/cloud-ardana8.yaml, jenkins/ci.suse.de/cloud-ardana9.yaml, jenkins/ci.suse.de/openstack-ardana-tests.yaml, jenkins/ci.suse.de/openstack-ardana-update-and-test.yaml, jenkins/ci.suse.de/templates/cloud-ardana-pipeline-template.yaml
The right filter for Horizon Selenium tests in ardana is "horizon". I am not sure how "horizon_integration-tests" got created. No tests were run using this filter. This fix is to remove all references of "horizon_integration-tests ".
=> SCRD-6889 Remove horizon_integration-tests filter

scripts/jenkins/ardana/ansible/group_vars/all/all.yml
To avoid issues with NUE-PRV network connectivity, extend the
list of NTP servers to include Provo as well as public servers.
=> openstack-ardana: add Provo and public NTP servers

scripts/jenkins/ardana/ansible/roles/ardana_deploy/defaults/main.yml, scripts/jenkins/ardana/ansible/roles/ardana_deploy/tasks/main.yml, scripts/jenkins/ardana/ansible/roles/ardana_deploy/tasks/setup_rhel_ceph_client_repo.yml
This change adds support for deploying ardana using CentOS computes and
SES backend.
The ceph client packages are downloaded from the official ceph repos [1]
and some required libraries are downloaded from the official CentOS repos [2].
1. https://download.ceph.com/rpm-luminous/el7/x86_64/
2. http://centos.mirror.lstn.net/7/storage/x86_64/ceph-luminous/
=> openstack-ardana: add support CentOS computes with SES backend

jenkins/ci.suse.de/pipelines/openstack-ardana-gating.Jenkinsfile
Change the IBS gating jobs for Ardana to always keep environments
after the job run, even if they succed. This can help with manually
investigating the status of the gate post-build, or running additional
test cases on it through Jenkins.
=> cloud-ardana-gating: always keep envs after build

jenkins/ci.opensuse.org/templates/openstack-rpm-packaging-sles12.yaml
newer versions of osc no longer ignore "-w" when used with
--csv but instead print an error message:
Please implement support for osc prjresults --watch without --xml.
We can however just ignore the wait, as we wait afterwards anyway.
=> rpm-packaging-results: avoid using --watch with --csv

jenkins/ci.suse.de/openstack-ardana-heat.yaml, jenkins/ci.suse.de/pipelines/openstack-ardana-heat.Jenkinsfile, jenkins/ci.suse.de/pipelines/openstack-ardana.Jenkinsfile, scripts/jenkins/ardana/ansible/roles/heat-generator/templates/heat-template.yaml
The `openstack-ardana-heat` Jenkins job is the only job still
actively using the concept of a "shared workspace" - sharing
a file location on the Jenkins agent between two job runs.
The requirement comes from the fact that the generated heat
template file describing the Ardana cloud environment needs to
be passed from the `openstack-ardana` down to the `openstack-ardana-heat`
job that will use it to instantiate the cloud environment.
Using a text (multi-line string) job parameter achieves the same
result, while at the same time removing the need to share a file
location between upstream and downstream jobs. This is the first
step towards removing the concept of a shared workspace and also
making the `openstack-ardana-heat` job a more generic
job that handles heat stack creation/deletion, …
=> openstack-ardana-heat: remove shared workspace

jenkins/ci.suse.de/openstack-ardana-testbuild-gerrit.yaml, jenkins/ci.suse.de/openstack-ardana-tests.yaml, jenkins/ci.suse.de/openstack-ardana-update-and-test.yaml, jenkins/ci.suse.de/openstack-ardana-update.yaml, jenkins/ci.suse.de/pipelines/openstack-ardana-heat.Jenkinsfile, jenkins/ci.suse.de/pipelines/openstack-ardana-tests.Jenkinsfile, jenkins/ci.suse.de/pipelines/openstack-ardana-update-and-test.Jenkinsfile, jenkins/ci.suse.de/pipelines/openstack-ardana-update.Jenkinsfile, jenkins/ci.suse.de/pipelines/openstack-ardana.Jenkinsfile, jenkins/ci.suse.de/pipelines/openstack-ardana.groovy, scripts/jenkins/ardana/README.md, scripts/jenkins/ardana/jenkins-helper.sh
Remove the deprecated logic that implements the shared workspace
concept - sharing a file location on the Jenkins agent between
several job runs.
This concept isn't required anymore, since every Ardana job now has
the ability to run independently from other jobs.
NOTE: this PR depends on #3151 and is part of a larger effort to remove the
shared workspace concept from all Ardana jobs and reuse the Crowbar CI
approach of sharing global automation repository git clones stored on the
Jenkins agent nodes.
=> openstack-ardana: remove shared workspace

scripts/mkcloud, scripts/qa_crowbarsetup.sh
Reverts SUSE-Cloud/automation#3007
Something happened in between when this change was proposed and when it
was merged, and now the proposal file from which this test is supposed
to take the certfile and keyfile parameters is missing. Moreover the HA jobs
are failing due to missing the CA parameter. Revert this for now to get CI working
again.
=> Revert "Test SSL"

scripts/jenkins/ardana/ansible/bootstrap-vcloud-nodes.yml
A couple of changes that will improve the log output when one ore
more of the Ardana cloud nodes are unreachable:
- fail immediately after finding an unreachable node, rather than
continue to execute remaining tasks on reachable nodes
- don't run the rocketchat role on cloud nodes, because it will
fail a second time in case of unreachable nodes. Delegate it to
the deployer instead.
NOTE: this change was implemented to address difficulties with
debugging failures such as https://ci.suse.de/blue/organizations/jenkins/cloud-ardana9-job-std-min-x86_64/detail/cloud-ardana9-job-std-min-x86_64/534/pipeline/117
=> openstack-ardana: report unreachable nodes better

scripts/jenkins/ardana/ansible/roles/input_model_generator/templates/baremetal/disks.yml.j2, scripts/jenkins/ardana/ansible/roles/input_model_generator/vars/entry-scale-kvm-mml.yml, scripts/jenkins/ardana/ansible/roles/input_model_generator/vars/templates/interface/mml-core.yml, scripts/jenkins/ardana/ansible/roles/input_model_generator/vars/templates/service/mml-core.yml, scripts/jenkins/ardana/ansible/roles/rocketchat_notify/vars/deploy.yml
This change supports generating an input model called the entry-scale-kvm-mml model as described in the example in the ardana-input-model repo.
http://git.suse.provo.cloud/cgit/ardana/ardana-input-model/tree/2.0/examples/entry-scale-kvm-mml/
This change is only applicable for the baremetal environment and not virtualized cloud.
=> Add support for MML input model for baremetal QE environments

scripts/jenkins/ardana/ansible/roles/input_model_generator/templates/baremetal/disks.yml.j2
On disk input model 'device_groups' cannot be empty.
=> openstack-ardana: fix core disks model

scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/templates/tests/cinder-parallel.sh.j2, scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/templates/tests/cinder.sh.j2, scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/templates/tests/nova-attach.sh.j2
The way my test scripts for cinder work, they require the environment to be initialized by running the script cinder-tests-all and passing it a cinder backend type which ultimately gets used to create a unique cinder backend type and then use it in cinder calls with --volume-type set to that type. At the time I wrote these, all our backends were running LVM and that's what I hardcoded the type too.
Since then we've been running a lot of ses backends and when called with 'lvm', initialization fails along with the test. As an enhancement I had modified the initialization script awhile ago to accept a backend type of 'default' which in turn suppresses the --volume-type switch entirely, resulting in cinder simply using its default backend. But I never remembered to make a similar change to …
=> change backends from lvm to default

scripts/qa_crowbarsetup.sh
The automatic creation of network.json entry for ironic was not
working because of missing quotes.
regression caused by https://github.com/SUSE-Cloud/automation/pull/2879
=> ironic network automation fix

scripts/jenkins/ardana/ansible/bootstrap-pcloud-nodes.yml
The ipmi_power ansible module depends of pyghmi, however pyghmi was
recently removed from the cloud 9 repositories.
Instead of using the ipmi_power module, use the shell module to run
ipmitool for powering off the nodes.
=> openstack-ardana: Remove pyghmi dependency

jenkins/ci.suse.de/openstack-ardana-gerrit-events.yaml, scripts/jenkins/ardana/gerrit/README.md, scripts/jenkins/ardana/gerrit/gerrit_review.py
Small change required to trigger the `openstack-ardana-gerrit-events`
job, that is responsible for merging Gerrit changes, also in the event
of `QE-Review` label changes.
Included in this commit are documentation updates and support for
using the new label when manually running the gerrit scripts.
=> openstack-ardana-gerrit-events: add support for QE-Review label

scripts/heat/devstack-heat-template.yaml
We use curl as it seems to be more commonly available in standard images.
=> Fix comment incorrectly referencing wget

scripts/qa_crowbarsetup.sh
SSH drivers were deprecated in Ironic long time ago and proposal validation fails
with these. In addition, agent_* drivers could be enabled if Swift is deployed.
SOC9+ uses new "hardware types" instead of classic drivers and these should have
decent defaults so no need to set anything for that. This part could be extended
in the future if custom values are needed.
=> remove ssh driver from ironic proposal

scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/templates/tests/neutron.sh.j2, scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/vars/neutron.yml
Neutron qe tests have been refactored to run in parallel to reduce total run time.
Patch - https://gerrit.suse.provo.cloud//#/c/5614/
=> Reduce total runtime for neutron qe tests.

scripts/jenkins/qa_devstack.sh
Without this `zypper install` of `git-review` from a 42.3 repo, the subsequent `zypper install` will fail.
=> fix qa_devstack.sh for SLES12 SP4

jenkins/ci.suse.de/openstack-mkcloud.yaml, scripts/qa_crowbarsetup.sh
This is useful to deploy a cloud with osprofiler[1] support. This
needs https://github.com/crowbar/crowbar-openstack/pull/2009 which
adds basic support for osprofiler to Keystone.
Note: Once this is merged and tested, there will be another PR which
will enable osprofiler for one of the gating jobs.
[1] https://docs.openstack.org/osprofiler/latest/
=> qa_crowbarsetup: Add "want_osprofiler"

jenkins/ci.suse.de/pipelines/openstack-ardana-gating.Jenkinsfile, jenkins/ci.suse.de/pipelines/openstack-ardana-gerrit.Jenkinsfile, jenkins/ci.suse.de/pipelines/openstack-ardana-maintenance-gating.Jenkinsfile, jenkins/ci.suse.de/pipelines/openstack-ardana.Jenkinsfile, jenkins/ci.suse.de/pipelines/openstack-ardana.groovy
There's a bug in the Lockable Resources plugin that sometimes
causes a Null value to be returned by the `lock` function called
to reserve a resource [1][2]. This has been known to happen for
example when the Jenkins server is restarted, or when a resource
that was previously manually reserved is released and immediately
reserved by one of the jobs waiting in queue.
We don't yet have a fix for this bug, nor a way around it, but we
can at least abort the jobs immediately if this bug is detected,
rather than having them continue to run without a locked resource.
[1] https://issues.jenkins-ci.org/browse/JENKINS-52638
[2] https://issues.jenkins-ci.org/browse/JENKINS-43002
=> openstack-ardana: JENKINS-52638 bug workaround

jira/validators/fixversion.groovy, jira/validators/subtasks.groovy, jira/validators/worker.groovy
So fa our Jira Script Runner scripts are only maintaned directly in
Jira. This has the downside that we don't have backups nor have version
controll.
=> Add Jira helper scripts to the automation repo

scripts/jenkins/ardana/ansible/roles/ardana_deploy/defaults/main.yml
Issues: SCRD-5899
To ensure that we exercise the problem scenario identified in
bsc#1110061, i.e. wipe_disks.yml failed if run before site.yml,
in standard CI runs we want to enable it for both virtual and
physical deployments.
Additionally with bsc#1110061 fixed we no longer need to explicitly
run ardana-ssh-keyscan.yml before running wipe_disks.yml.
=> SCRD-5899 run wipe_disks.yml for virtual deployments too (bsc#1110061)

scripts/jenkins/ardana/ansible/roles/ardana_deploy/defaults/main.yml
The virtual deployment setup process for the non-deployer nodes is
not setting up the basic distro repos so we cannot install any new
packages on those nodes until after the osconfig plays have setup
the distro repos. As a result the wipe_disks.yml playbooks will
fail for those nodes because they cannot install any packages.
Note that if we want the virtual CI to "emulate" what a customer
deployment process would look like, we probably should be explicitly
setting up at least the distro repos before osconfig runs.
=> SCRD-5899 Only run wipe_disks.yml in physical deployments

scripts/jenkins/ardana/ansible/bootstrap-pcloud-nodes.yml
The bootrstrap-pcloud-nodes playbook was failing as we do not give it
time enough to finish powering it off.
This change adds retries to this task so we chek again after 5 seconds
for 10 times if the node is really powered off.
=> openstack-ardana: wait for BM nodes to power off

jenkins/ci.suse.de/cloud-crowbar.yaml, jenkins/ci.suse.de/pipelines/openstack-crowbar.Jenkinsfile, jenkins/ci.suse.de/templates/cloud-crowbar-pipeline-template.yaml, scripts/jenkins/ardana/ansible/roles/input_model_generator/defaults/main.yml, scripts/jenkins/ardana/ansible/roles/input_model_generator/templates/input_model/data/networks.yml, scripts/jenkins/ardana/ansible/roles/input_model_generator/templates/input_model/data/neutron/neutron_config.yml, scripts/jenkins/ardana/ansible/roles/input_model_generator/templates/input_model/data/octavia/octavia_config.yml, scripts/jenkins/ardana/ansible/roles/input_model_generator/templates/input_model/data/servers.yml, scripts/jenkins/ardana/ansible/roles/input_model_generator/vars/crowbar.yml, scripts/jenkins/ardana/ansible/roles/input_model_generator/vars/templates/interface/crowbar.yml, scripts/jenkins/ardana/ansible/roles/input_model_generator/vars/templates/network/crowbar.yml, scripts/jenkins/ardana/ansible/roles/input_model_generator/vars/templates/service/crowbar.yml
This PR creates a very basic `openstack-crowbar` Jenkins pipeline
job gluing together the various components that are required
to implement a working automated deployment of Crowbar in the
engineering cloud ([SCRD-7366](https://jira.suse.de/browse/SCRD-7366)):
- input model generator and heat template generator components
from Ardana
- the ECP heat stack creation and deletion component from Ardana
- the Ardana component that sets up SSH keys on the admin node
- place-holders for the Crowbar specific steps (not included):
- Crowbar admin node set up
- Crowbar cloud nodes set up
- Crowbar installation on admin node
- Crowbar cloud node registration
- Crowbar proposal deployment
- running tests
Also included is an Ardana input model generator scenario that corresponds to the
default, 2 node …
=> Jenkins pipeline job and input model generator scenario for Crowbar

scripts/jenkins/ardana/ansible/group_vars/all/versioned.yml
We have completed the deprecation of the glance-resitry in Cloud9
and removed support for deploying it, therefore we should only be
generating service component entries for it in Cloud8 deployments
and not in Cloud9.
=> glance-registry is deprecated and removed in Cloud9 (SCRD-7639)

scripts/jenkins/ardana/ansible/setup-ssh-access.yml
If there the stack contains no compute the stack output returns 'None'
for the compute_ips field, where the ansible playbooks expects a list.
This fix checks if it returned None and if so sets the value to an empty
list.
=> openstack-ardana: fix setup-ssh playbook for input model without compute

scripts/jenkins/ardana/ansible/group_vars/all/versioned.yml
Reverts SUSE-Cloud/automation#3183
I was too quick to merge this. It still needs changes in `ardana-input-model` (see https://ci.suse.de/blue/organizations/jenkins/openstack-ardana/detail/openstack-ardana/3330/pipeline)
=> Revert "glance-registry is deprecated and removed in Cloud9 (SCRD-7639)"

scripts/jenkins/ardana/ansible/setup-ssh-access.yml
Fix an issue when running setu-ssh-access playbook on bare-metal
environments.
The playbook fails because the loop label is set using the output value
provided by item, which is not defined on bare-metal.
=> openstack-ardana: fix setup-ssh-access for pcloud

scripts/qa_crowbarsetup.sh
Set a static key (the key is "SECRET") so it's easier to use
osprofiler when it got deployed via mkcloud/qa_crowbarsetup.
That way, you don't have to search for the password to generate trace
points.
=> qa_crowbarsetup: Set static hmac_key for osprofiler

scripts/jenkins/qa_devstack.sh
Some SLES images default to `kernel-default-base` which has a minimal set of kernel modules which does not include `openvswitch`, e.g. see [bsc#1124839 (SP4 JeOS image is missing openvswitch.ko kernel module](https://bugzilla.suse.com/show_bug.cgi?id=1124839)).
In this case we know devstack will fail when it gets to the neutron setup, so bail early to avoid wasting people's time, and give them a potentially helpful tip.
=> check openvswitch.ko kernel module is available

jenkins/ci.suse.de/cloud-ardana9.yaml
Some of the cloud 9 QE environments are down,
disabling periodic installs on 102 so we can use
this environment on demand installs.
=> Temporarily disable periodic installs on 102

docs/devstack/README.md, scripts/heat/devstack-heat-template.yaml
This more accurately describes the repository being cloned.
=> rename qa_devstack_{fork,branch} to automation_{fork,branch}

scripts/lib/mkcloud-common.sh, scripts/mkcloud
Currently the mkcloud mkvlan function hardcodes a netmask
of 24. This patch uses the $defaultnetmask if $want_ipv6
is set, which defaults to 64.
Otherwise it remains the 24 default.
This patch also adds an $admingw like we do for ironic and
admin ip. Which makes it easier to manage IPv4 and IPv6
addresses on the mkcloud host.
=> IPv6: Allow mkvlan support a netmask for ipv6

jenkins/ci.suse.de/cloud-ardana8.yaml, jenkins/ci.suse.de/cloud-ardana9.yaml, jenkins/ci.suse.de/pipelines/openstack-ardana-image-update.Jenkinsfile, jenkins/ci.suse.de/templates/cloud-ardana-image-update-template.yaml
We're currently using two sets of SLES CI images in the
ECP cloud, due to the fact that we cannot create public
images with the `cloud-ci` ECP user, which is used to
automate image update, and the image membership support
was thought to be broken in Newton (i.e. because
`openstack --os-cloud engcloud-cloud-ci image set --accept <image>`
didn't have the desire effect).
After further investigations, it turns out that the explanation
for the above failure was simple: we just had to use a
project UUID instead of the project name when sharing
the image.
This commit makes the image update automation use shared
images by default and also removes the need to have OpenStack
cloud configuration files preconfigured for the other
projects with which the image needs to be shared.
The only …
=> openstack-ardana-image-update: share image (SCRD-6094)

jenkins/ci.suse.de/openstack-mkcloud.yaml, scripts/lib/qa_crowbarsetup-help.sh, scripts/qa_crowbarsetup.sh
This is useful to deploy a cloud with the upstream solution for l3 HA.
This requires https://github.com/crowbar/crowbar-openstack/pull/2005
which adds l3 HA support to Crowbar.
Note: If this PR and the crowbar PR are merged, another PR is needed
to enable l3 HA by default for the gating jobs.
=> qa_crowbarsetup: Add "want_l3_ha"

scripts/jenkins/qa_openstack.sh
Default to one mirror we know is updated fast enough instead of the
redirector because some mirrors lag and cause a checksum mismatch for rpms
that keep name and size and only change content.
This happened only on Leap 15 for Rocky when using osc release based
copy to the ToTest project, probably because otherwise changes like this
don't happen often enough.
Example from the log (the received checksum was from the day before):
Warning: Digest verification failed for file 'openstack-suse-sudo-2015.2-lp150.2.1.noarch.rpm'
[/var/tmp/AP_0xqwI2Is/noarch/openstack-suse-sudo-2015.2-lp150.2.1.noarch.rpm]
expected 388d766a8213163cb1ab36c4705f8a16958a9c8f3abfd10b715df2cf996a44cf
but got  d95494a9af9ae19810c4f0a818c01b1ec09fa53458739d26c0e1a53ad16c0bcc
=> work around checksum mismatch during cleanvm

jenkins/ci.suse.de/openstack-ardana-testbuild-gerrit.yaml, jenkins/ci.suse.de/pipelines/openstack-ardana-testbuild-gerrit.Jenkinsfile
Improves the job that builds CI test packages for Gerrit
changes:
- moves the job to run on the `cloud-ardana-ci` agent
instead of the `cloud-trackupstream-sle12` agent, which
only has one worker configured and acts as a bottleneck
- times out the package build after 30 minutes of inactivity
- improve UI usability by printing out useful URLs about built
repositories and projects
=> openstack-ardana-testbuild-gerrit: job improvements (SCRD-6210)

jenkins/ci.suse.de/cloud-ardana8.yaml, jenkins/ci.suse.de/cloud-ardana9.yaml, scripts/jenkins/ardana/ansible/ardana-ses-rgw.yml, scripts/jenkins/ardana/ansible/group_vars/all/all.yml, scripts/jenkins/ardana/ansible/roles/ses_ardana_integration/defaults/main.yml, scripts/jenkins/ardana/ansible/roles/ses_ardana_integration/tasks/main.yml, scripts/jenkins/ardana/ansible/roles/ses_ardana_integration/tasks/ses_configure_v1.yml, scripts/jenkins/ardana/ansible/roles/ses_ardana_integration/tasks/ses_configure_v2.yml, scripts/jenkins/ardana/ansible/roles/ses_configure/defaults/main.yml, scripts/jenkins/ardana/ansible/roles/ses_configure/tasks/configure_rgw.yml, scripts/jenkins/ardana/ansible/roles/ses_configure/tasks/configure_ses.yml, scripts/jenkins/ardana/ansible/roles/ses_configure/tasks/create_pools.yml, scripts/jenkins/ardana/ansible/roles/ses_configure/tasks/delete_pools.yml, scripts/jenkins/ardana/ansible/roles/ses_configure/tasks/get_ses_conf.yml, scripts/jenkins/ses/ansible/roles/ses/defaults/main.yml, scripts/jenkins/ses/ansible/roles/ses/tasks/deepsea_setup.yml, scripts/jenkins/ses/ansible/roles/ses/tasks/salt_setup.yml, scripts/jenkins/ses/ansible/roles/ses/templates/sharedsecret.conf.j2
Add support for ardana SES integration v2, which uses the salt-api to
configure ceph for openstack.
It is possible to configure which version of ardana SES integration to
use by setting `ardana_ses_integration_version` which defaults to 2.
=> openstack-ardana: add option to use salt API to create SES resources

scripts/jenkins/jenkins-job-pipeline-report.py
The `jenkins-job-pipeline-report` script that is generating
the execution summary report of a pipeline job was not detecting
downstream jobs properly. This patch fixes the script such that
any number of downstream jobs can be triggered from a pipeline
stage and they will all be included in the report regardless of
their position in the set of steps comprising the stage.
NOTE: the Gerrit pipeline report was broken starting with #3172,
which introduced an additional "Print Message" step before the
"Building ..." step that triggered the downstream job (see [this job](https://ci.suse.de/job/openstack-ardana-gerrit-cloud9/1232/execution/node/29/wfapi/describe)
for example)
=> openstack-ardana-gerrit: fix pipeline job report

jenkins/ci.suse.de/cloud-crowbar-testbuild-pr-trigger.yaml
Without the timeout a build that got stuck (this happened) would block the following builds.
So rather exit the one that is stuck to allow for a new run.
The timeout should be less than the interval used for the job. Currently the interval is
10 minutes and the timeout of 500 seconds is about 8 minutes.
Normal runtime of this job is 2 - 3 minutes.
=> jjb: add timeout for testbuild-pr-trigger

jenkins/ci.suse.de/cloud-ardana9.yaml, jenkins/ci.suse.de/openstack-ardana-tests.yaml, jenkins/ci.suse.de/openstack-ardana-update-and-test.yaml, scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/templates/tests/monasca-ceilometer.sh.j2, scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/vars/monasca-ceilometer.yml
Ceilometer API is removed in C9. Add new test script to test ceilometer via monasca.
=> Added support for ceilomter in cloud 9 on ardana_qe_tests role

jenkins/ci.suse.de/pipelines/openstack-ardana-image-update.Jenkinsfile
The job that automates updating the ECP images used for the
Ardana CI wasn't setting the `hw_rng_model=virtio` property
on the installed images, which in combination with the
`hw_rng:allowed=True` flavor property is required to increase
the entropy level on VMs, especially during boot.
=> openstack-ardana-image-update: set hw_rng_model (SCRD-7764)

jenkins/ci.opensuse.org/openstack-prepare-staging.py, jenkins/ci.opensuse.org/openstack-prepare-staging.yaml
Use the osc.babysitter to get the same error handling as the osc cli.
This will e.g. print some part of the body of an errored HTTP request.
This was found because osc release failed, because a package in Staging
had a conflict. That conclict was a race between trackupstream and
prepare-staging which went like this: release Staging to ToTest;
trackupstream changes Staging; release ToTest to non-staging -> merge
conflict.
Check the return code to abort early if osc release failed.
Enable timestamps for this job.
=> openstack-prepare-staging: print error details

jenkins/ci.suse.de/cloud-maintenance-gating.yaml, jenkins/ci.suse.de/openstack-ardana-heat.yaml, jenkins/ci.suse.de/openstack-ardana-testbuild-gerrit.yaml, jenkins/ci.suse.de/openstack-ardana-tests.yaml, jenkins/ci.suse.de/openstack-ardana-update-and-test.yaml, jenkins/ci.suse.de/openstack-ardana-update.yaml, jenkins/ci.suse.de/pipelines/openstack-ardana-gating.Jenkinsfile, jenkins/ci.suse.de/pipelines/openstack-ardana-gerrit.Jenkinsfile, jenkins/ci.suse.de/pipelines/openstack-ardana-heat.Jenkinsfile, jenkins/ci.suse.de/pipelines/openstack-ardana-image-update.Jenkinsfile, jenkins/ci.suse.de/pipelines/openstack-ardana-testbuild-gerrit.Jenkinsfile, jenkins/ci.suse.de/pipelines/openstack-ardana-tests.Jenkinsfile, jenkins/ci.suse.de/pipelines/openstack-ardana-update-and-test.Jenkinsfile, jenkins/ci.suse.de/pipelines/openstack-ardana-update.Jenkinsfile, jenkins/ci.suse.de/pipelines/openstack-ardana.Jenkinsfile, jenkins/ci.suse.de/pipelines/openstack-ardana.groovy, jenkins/ci.suse.de/pipelines/openstack-maintenance-gating.Jenkinsfile, jenkins/ci.suse.de/templates/cloud-ardana-gating-template.yaml, jenkins/ci.suse.de/templates/cloud-ardana-job-gerrit-template.yaml, jenkins/ci.suse.de/templates/cloud-ardana-pipeline-template.yaml, scripts/jenkins/ardana/ansible/load-job-params.yml
Add an `extra_params` job parameter to all Ardana jobs to be used
as a means of injecting additional parameters into existing Jenkins
job. The extra parameters will be reflected in the list of Jenkins
environment variables and also ansible variables for jobs that are
implemented using ansible.
The new parameter can be used for various purposes:
- as an alternative to testing changes to JJB job parameters that
does not require updating the official Jenkins jobs or creating
temporary copies of official jobs in order to test e.g. new job
parameters. This will support running customized versions of the
"CI for CI" gating job
- to run job builds that use custom values for global ansible
variables or shell environment variables that are not otherwise
reflected in the existing job parameters …
=> openstack-ardana: add extra_params parameter

scripts/jenkins/ardana/ansible/bootstrap-clm.yml, scripts/jenkins/ardana/ansible/bootstrap-crowbar.yml
Remove the workaround that was used to forcefully remove
`-devel` packages from the base image. Those packages are
no longer in the base image.
=> openstack-ardana/crowbar: remove -devel workaround

jenkins/ci.suse.de/pipelines/openstack-ardana-image-update.Jenkinsfile
Use `extra_params` instead of `extra_vars` when
triggering the `openstack-ardana` integration job
that tests the image.
=> openstack-ardana-image-update: fix extra_params

hostscripts/clouddata/syncSLErepos, scripts/qa_crowbarsetup.sh
The maintenance updates staged as SLES 12 SP2 "LTSS" Test updates
have previously not been tested. Handle them as SLES test updates
and include them automatically as well when needed.
This builds a more realistic CI environment.
=> mkcloud: also test with test LTSS updates when requested

scripts/create-vm.sh, scripts/lib/mkcloud-driver-libvirt.sh
At least with kernel 4.20+ this seems to cause emulation errors in L1
guest KVM. As we don't really need it (only really needed for real mode
emulation) it seems safer to turn it off.
=> Disable invalid_guest_state emulation

scripts/lib/mkcloud-common.sh
to avoid confusing error messages like
error (11): Do not know what to resolve via getent.
in case DNS returns empty results.
=> mkcloud: quote strings

jenkins/ci.suse.de/cloud-ardana8.yaml, jenkins/ci.suse.de/cloud-ardana9.yaml, jenkins/ci.suse.de/pipelines/openstack-ardana-image-update.Jenkinsfile, jenkins/ci.suse.de/templates/cloud-ardana-image-update-template.yaml
A couple of improvements for the `openstack-ardana-image-update`
job, which are required to automate updating regular (non-LVM) SLES
images:
- adds `extra_params` support to the `openstack-ardana-image-update` jobs.
- support both QCOW2 and XZ archived images
=> openstack-ardana-image-update: improvements

scripts/qa_crowbarsetup.sh
Without this change, the hacloud=1 job will actually just deploy
mariadb without galera on a single node rather than deploying it
on a cluster for cloud8+. We want to test galera as well.
Regression from #2737
=> qa_crowbarsetup.sh: Deploy with galera on cloud8+

.gitignore, docs/ardana/testing.md, scripts/jenkins/ardana/ansible/bootstrap-vcloud-nodes.yml, scripts/jenkins/ardana/ansible/group_vars/all/all.yml, scripts/jenkins/ardana/ansible/roles/setup_root_partition/tasks/main.yml, scripts/jenkins/ardana/gerrit/gerrit.py, scripts/jenkins/ardana/manual/deploy-ardana.sh, scripts/jenkins/ardana/manual/input.yml, scripts/jenkins/ardana/manual/lib.sh, scripts/jenkins/ardana/manual/requirements.txt
This change adds a bash script that mimics the steps followed by the
openstack-ardana job to deploy ardana on ECP.
The intent of the script is to make easy deploying ardana on ECP from
the workstation (without the need of jenkins). This change also
adds a library that provides functions similar to the openstack-ardana
jenkins job steps, which can be called to execute the each step
individually.
=>  openstack-ardana: Add script to deploy ardana without jenkins (SCRD-4903)

jenkins/ci.suse.de/templates/cloud-mkcloud-job-ipv6-template.yaml
It turns out the steps to execute are literally passed to mkcloud, which
results in behaviour that isn't conducive to testing anything at all.
Specify all of the steps for the job we want to be run.
Drop instcrowbar for the time being since Crowbar installation fails on
IPv6 admin nodes.
=> ipv6: Be absolutely clear about steps to execute

jenkins/ci.suse.de/pipelines/openstack-ardana-heat.Jenkinsfile, scripts/jenkins/ardana/ansible/roles/heat_stack/defaults/main.yml, scripts/jenkins/ardana/ansible/roles/heat_stack/tasks/create.yml, scripts/jenkins/ardana/ansible/roles/heat_stack/tasks/delete.yml
Improve the logic handling timeout conditions and retries in the
`openstack-ardana-heat` job. The following changes are made:
- use `activity: true` in the Jenkinsfile `timeout` block, which
will issue an error only if the specified amount of time is exceeded
without any logging activity (i.e. if the ansible task is stuck
waiting for a stack to be deleted or created and the heat stack
timeout value didn't have any effect - in other words, a heat bug).
With this in place, the timeout value in the Jenkinsfile only needs
to be slightly higher than the heat stack creation/deletion timeout
(which is currently set to 8 minutes).
- disable retrying in the Jenkinsfile and use `retry` in the ansible
task instead
- remove the ansible tasks that were forcefully deleting heat stack
resources. These …
=> openstack-ardana-heat: make openstack-ardana-heat more robust

scripts/lib/libvirt/fixtures/cloud-node1-xen.xml, scripts/lib/libvirt/libvirt_setup.py
/dev/disk/by-path entries are used by crowbar to determine the boot disk
and without the patch, Xen installs would fail half of the time
because the 2nd disk got the OS, but only the 1st was marked bootable
in libvirt
So we use different bus IDs to avoid IDE disks with identical path.
Only 2 HDDs are supported.
xen mkcloud run was very good. only tempest returned an error.
This is a bit of a workaround for the flawed disk selection logic in crowbar.
=> mkcloud/xen: avoid IDE disks with identical path

hostscripts/clouddata/syncSLErepos
It doesn't really help to sync everything twice from nue, better
let the ibs-mirror catch up and sync locally then.
=> Reduce number of sync runs from Nuernberg site

jenkins/ci.suse.de/cloud-ardana8.yaml, jenkins/ci.suse.de/cloud-ardana9.yaml, jenkins/ci.suse.de/pipelines/openstack-ardana.Jenkinsfile, jenkins/ci.suse.de/templates/cloud-ardana-pipeline-template.yaml, scripts/jenkins/ardana/ansible/roles/setup_zypper_repos/README.md, scripts/jenkins/ardana/ansible/roles/setup_zypper_repos/defaults/main.yml
Change the default behaviour of all Ardana Jenkins jobs
to include SLES test-updates by default.
This is required to align the Ardana and Crowbar CIs
(Crowbar has been doing that for a long time already)
and prevent situations that break the Ardana CI but not
the Crowbar CI, or vice-versa, because of SLES maintenance
updates that are in a `testing` state (i.e. not yet released
but already validated by automated OpenQA tests).
The downside of this change is if there's a SLES package
test-update package that breaks one job, it will break all
jobs - Gerrit CI, IBS gating, periodic regression jobs etc.,
most likely for both Crowbar and Ardana. The upside of this
is that by breaking the CI early, we force everyone to be
proactive instead of re-active and fix potential problems
before candidate …
=> openstack-ardana: include SLES test-updates by default (SCRD-8295)

jenkins/ci.suse.de/openstack-ardana-gerrit-events.yaml, jenkins/ci.suse.de/pipelines/openstack-ardana-gerrit.Jenkinsfile
Due to the issues reported on [1] a new jenkins worker node was setup on
the eng. cloud similar to the cloud-swarm-ardana-ci node which does not
have such issues.
This change update the label of the ardana gerrit jobs to use this new
jenkins worker node.
1. https://jira.suse.de/browse/SCRD-8042
=> openstack-ardana: switch jenkins node of gerrit jobs (SCRD-8042)

jenkins/ci.suse.de/cloud-mkcloud8-job-simpletest-s390x.yaml, jenkins/ci.suse.de/openstack-mkcloud.yaml, jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-vproduction-template.yaml, scripts/lib/mkcloud-common.sh, scripts/mkcloud, scripts/qa_crowbarsetup.sh
There is no murano barclamp planned for cloud9 or older, and
it wasn't enabled by default anyway
=> mkcloud: remove murano_proposal option

scripts/jenkins/ardana/ansible/roles/ardana_tempest/defaults/main.yml, scripts/jenkins/ardana/ansible/roles/ardana_tempest/tasks/main.yml, scripts/jenkins/ardana/ansible/roles/ardana_tempest/tasks/retry_failed.yml, scripts/jenkins/ardana/ansible/roles/ardana_tempest/tasks/run_tempest.yml, scripts/jenkins/ardana/ansible/roles/ardana_tempest/templates/run_filter_retry.txt.j2, scripts/jenkins/ardana/ansible/roles/rocketchat_notify/vars/tempest.yml, scripts/jenkins/ardana/ansible/run-tempest.yml
Due to the instability of tempest (e.g. different tests fails/succeeds
on consecutive runs on the same environment), this change adds an option
(disabled by default) to automatically rerun tempest for the failed
tests serially and combine its results.
=> openstack-ardana: add support for retrying tempest failed tests

docs/ardana/testing.md, jenkins/ci.suse.de/cloud-ardana8-gerrit.yaml, jenkins/ci.suse.de/cloud-ardana8.yaml, jenkins/ci.suse.de/cloud-ardana9-gerrit.yaml, jenkins/ci.suse.de/cloud-ardana9.yaml, jenkins/ci.suse.de/pipelines/openstack-ardana-gerrit.Jenkinsfile, jenkins/ci.suse.de/templates/cloud-ardana-job-gerrit-template.yaml, scripts/jenkins/ardana/gerrit/gerrit.py, scripts/jenkins/ardana/gerrit/gerrit_get.py, scripts/jenkins/jenkins-job-cancel, scripts/jenkins/jenkins-job-pipeline-report.py
Adds the ability to run custom integration testing on
Gerrit changes, in addition to or replacing the default
official Gerrit integration jobs used by the Ardana CI.
This is an intermediate phase on the way to making the
Ardana Jenkins Gerrit CI more dynamic by reading meta-data
directly from the commit message (similar to `Depends-On` 
meta-data modeling cross-repository dependencies) and using
that meta-data to decide at runtime what integration test scenarios
need to be run against the Gerrit change (see [SCRD-7138](https://jira.suse.de/browse/SCRD-7138)).
The following parameters have been added to the
`openstack-ardana-gerrit-cloud[8|9]` jobs to support
this:
- `GERRIT_CHANGE_NUMBER` (replaces `gerrit_change_ids`).
When manually triggered, this parameter must be set
to a valid Gerrit …
=> openstack-ardana-gerrit: custom Gerrit integration testing

scripts/qa_crowbarsetup.sh
Direct deploy interface requires Swift. Proposal will fail validation
if "direct" is enabled without Swift.
=> ironic: Direct interface only with Swift

scripts/qa_crowbarsetup.sh
without this designate deployment will fail, as dns will not store the
generated keys on the dns-master server for use by named
=> dns: set enable_desigate when designate is going to be deployed

jenkins/ci.suse.de/cloud-ardana8.yaml, jenkins/ci.suse.de/cloud-ardana9.yaml, jenkins/ci.suse.de/templates/cloud-ardana-pipeline-template.yaml, scripts/jenkins/ardana/ansible/roles/input_model_generator/vars/std-lmm.yml, scripts/jenkins/ardana/ansible/roles/input_model_generator/vars/templates/service/std-lmm.yml, scripts/jenkins/ardana/manual/input.yml
Creates a new input model generator scenario, `std-lmm`,
which is similar to the `standard` scenario, with the only
difference that the LMM services are configured in a separate
cluster.
This scenario moves LMM services away from the controller nodes,
in an attempt to make the CI jobs more reliable by elliminating
the instability caused by running resource intensive LMM services
on the same nodes as the other control plane services.
Two period jobs are also added, using the new input model generator
scenario, one for cloud8 and another for cloud9. If these jobs prove
to be more stable than the `std-min` jobs used by Gerrit and IBS gating
jobs, the next step will be to switch them to use the `std-lmm` jobs
instead.
=> openstack-ardana: std-lmm input model scenario and jobs

scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/defaults/main.yml, scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/templates/tests/iverify.sh.j2
While investigating fwaas issues for SCRD-5854 I found that it was
useful to be able to pass command line arguments through to the
underlying iverify command from the wrapper script.
=> Allow pass thru of arguments to iverify.sh (SCRD-5854)

jenkins/ci.suse.de/cloud-ardana8-gerrit.yaml, jenkins/ci.suse.de/cloud-ardana9-gerrit.yaml
SES was mistakenly disabled for the `cloud-ardana[8|9]-job-std-min-centos-gerrit-x86_64` jobs.
=> openstack-ardana-gerrit: enable SES for Gerrit CentOS integration job

scripts/qa_crowbarsetup.sh
ceilometer uses monasca for metric storage without it its kind of
useless
=> ceilometer: deploy it only when monasca is enabled

scripts/jenkins/ardana/ansible/roles/ardana_tempest/defaults/main.yml
Update the list of defcore tets according to the 2018.11 guide line.
=> openstack-ardana: update defcore list of tests to 2018.11

jenkins/ci.opensuse.org/openstack-cleanvm.yaml, jenkins/ci.opensuse.org/openstack-repocheck.yaml
We want to test Cloud:OpenStack:Master with cleanvm on SLE15 beside
the other distros. The repocheck job is adjusted accordingly to test
dependencies for SLE15 on Cloud:OpenStack:Master .
=> cleanvm/repocheck: Add SLE15 support for Master

jenkins/ci.suse.de/cloud-mkcloud6.yaml
Tests fails in heat deployment for 2 months:
Problem: nothing provides python-docker-pycreds >= 0.2.1 needed by python-docker-py-1.10.6-29.3.1.noarch
Solution 1: do not install openstack-heat-plugin-heat_docker-5.0.4~a0~dev1-9.628.noarch
Solution 2: break python-docker-py-1.10.6-29.3.1.noarch by ignoring some of its dependencies
=> Disable failing SOC6 mkcloud tests

scripts/qa_crowbarsetup.sh
We don't currently support mixing ironic with other compute types in
the same cloud. This change removes all other compute role assignments
when ironic is deployed.
=> ironic: Don't assign other compute roles

scripts/qa_crowbarsetup.sh
nova_evacuate test expect cirros 0.3.4 version image exist
but from cloud 8 version changed to 0.4.0.
Tests failing due to no image found.
=> Update cirros image version from 0.3.4 to 0.4.0

scripts/jenkins/track-upstream.sh
There is no SLE_12_SP3 anymore for Cloud:OpenStack:Master (COM) so
currently openstack-trackupstream for Master packages fails with:
--> Now trying to build package.
SLE_12_SP3 is not a valid repository, use one of: SLE_12_SP4, \
SLE_15, openSUSE_Leap_15.0, openSUSE_Leap_42.3
=> trackupstream: Use SLE_12_SP4 for building COM packages

scripts/jenkins/qa_openstack.sh
/etc/os-release for SLE15 (SP0 if you want to call it that way) does
contain:
NAME="SLES"
VERSION="15"
VERSION_ID="15"
so there will be no $minor version. Adjust the REPO and REPOVER
variables to work correctly.
Note: On http://smt-internal.opensuse.org there are no SLE15 images
yet. This will be fixed hopefully soon.
=> qa_openstack: Support SLE15 repos

jenkins/ci.suse.de/cloud-socok8s-pr-trigger.yaml, jenkins/ci.suse.de/cloud-socok8s.yaml, scripts/github_pr/github_pr_cloud_socok8s.yaml, scripts/github_pr/interactions/ia_socok8s.rb, scripts/socok8s/run.sh
We want to deploy a socok8s environment whenever a change is proposed
to the suse-cloud/socok8s repo on github.
Reuse what is already available to do that.
=> github_pr: Add PR testing for socok8s

jenkins/ci.suse.de/openstack-mkcloud.yaml, scripts/mkcloud, scripts/qa_crowbarsetup.sh
The change adds Jenkins parameter to allow running tests with a
specified TSDB.
=> openstack-crowbar: Add Monasca TSDB choice option

scripts/socok8s/run.sh
- We need to set $repo_dir - otherwise the whole root directory will
be rsynced
- OSCLOUD and KEYNAME need to be exported to get something running
=> socok8s: Fix run.sh script

scripts/qa_crowbarsetup.sh
we want to ensure that the keystone toggling did not break
services, so we run tempest after doing the operation to
ensure that the cloud is still working. Also this reduces
scrolling to find a tempest failure in CI logs
=> qa_crowbarsetup.sh: Run tempest last

scripts/lib/mkcloud-common.sh
If for some reason file `~/.mkcloud/fastest_clouddata_server` is empty mkcloud will not retrigger run of `scripts_lib_dir/find_fastest_server.pl` and then mkcloud uses empty hostname and fails.
We encounter empty file generated on one of our qam machines.
=> re-create fastest_clouddata_server file when empty

jenkins/ci.suse.de/cloud-automation-pr-trigger.yaml
and timestamps
It hung for 14 hours without any output at github_pr.rb.
=> cloud-automation-pr-trigger: add timeout

scripts/scenarios/cloud9/cloud9-2nodes-default.yml, scripts/scenarios/cloud9/cloud9-5nodes-compute-ha.yml
ceilometer has a hard dependance on monasca as monasca is the default
storage engine for ceilometer.
The yaml file from qa scenario still refer to ceilometer, as I am not sure which scenarios should include monasca and where to remove ceilometer
=> deploy ceilometer only with monasca

scripts/qa_crowbarsetup.sh
The 'crowbar' command uses the CROWBAR_KEY environment variable to
authenticate. With this upcoming change in crowbar-core[1], the content
of the key is subject to change, so we need to refresh the key between
crowbar commits. This is a simpler path than converting to the
crowbarctl command, which uses the crowbarrc file which does not change.
[1] https://github.com/crowbar/crowbar-core/pull/1802
=> Re-source the crowbar variables after commit

scripts/jenkins/ardana/ansible/group_vars/all/versioned.yml, scripts/jenkins/ardana/ansible/roles/input_model_generator/defaults/main.yml
Move manila-share to controller for new CI template. This will apply only to
c8. According to the ticket, we make this decision in order to be
consistent with SOC. As for c9, we deprecate manila-share in the input model.
Due to manila-api and manila-share residing on the same host, both ansible
roles can use reference from each other and doesn't have to use MNL-SHR host
explicitly.
1. Move manila-share to controller
2. Add filter to enable manila-share only on c8
=> Move manila-share to controller (SCRD-7771)

scripts/jenkins/ardana/ansible/group_vars/all/all.yml, scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/defaults/main.yml, scripts/jenkins/ardana/ansible/roles/ardana_qe_tests/tasks/qe_test_requires.yml, scripts/jenkins/ardana/ansible/roles/send_to_os_health/defaults/main.yml, scripts/jenkins/ardana/ansible/roles/send_to_os_health/tasks/os_health_requires.yml, scripts/jenkins/ardana/ansible/roles/setup_zypper_repos/defaults/main.yml
When `updates_test_enabled` is set and the SLES-SDK-Updates
repository is installed, the SLES-SDK-Updates-test repository
is also required, otherwise there will be broken package
dependencies (e.g. `python-devel` vs. `python-base`).
NOTE: this fixes the issue currently breaking all Ardana jobs that
perform any type of update that involves the test updates repository.
=> openstack-ardana: install SLES-SDK Updates-test

scripts/jenkins/ardana/ansible/group_vars/all/versioned.yml
Both manila and external_network_bridge features were released, applying
those features conditionally is not necessary anymore.
=> openstack-ardana: remove released features from versioned features list

scripts/mkcloud
The want_ipv6 option enables a single stack IPv6 control plane for
crowbar. As such, in order to netboot on vms on an IPv6 admin network
they need to use an efi firmware.
This patch changes the firmware_type to 'uefi' when the want_ipv6
option is enabled.
Also add the want_ipv6 option to the usage/help.
=> ipv6: When want_ipv6 is set also set firmware_type to uefi

scripts/jenkins/ardana/ansible/roles/ardana_deploy/defaults/main.yml
By default, ardana is deployed with nova migrate disabled making the CI
unable to cover that feature.
This change introduces a new ansible variable (`ardana_nova_migrate_enabled`)
which makes possible enabling/disabling nova migrate. By default it is
set to true (nova migrate enabled).
=> openstack-ardana: enable nova migrate

scripts/jenkins/jenkins-job-cancel
Handle unicode values correctly in job parameters.
Cancelling Gerrit jobs is currently failing with:
```
UnicodeEncodeError: 'ascii' codec can't encode
character u'\xe1' in position 4: ordinal not in range(128)
```
, because the `jenkins-job-cancel` python script
doesn't handle cases where job parameter values have
unicode characters that cannot be cleanly converted
into ascii.
=> jenkins-job-cancel: handle unicode in job params

jenkins/ci.suse.de/cloud-mkcloud7.yaml
Cloud 6 is EOL since quite some time and therefore we can safly remove
the Cloud 6 to Cloud 7 upgrade jobs.
=> jenkins: Remove Cloud 6 to Cloud 7 Upgrade Jobs

scripts/jenkins/ardana/ansible/roles/heat-generator/templates/heat-template.yaml
Adding dns server (147.2.2.2) for ipv6 network breaks heat template deployment due to mismatch of ip version. This PR will only add dns server for ipv4 deployment.
Without fix:
https://ci.suse.de/job/openstack-ardana-heat/9308/console
With fix:
https://ci.suse.de/job/openstack-ardana-heat/9309/console
=> Skip adding dns_servers into heat template for ipv6.

jenkins/ci.opensuse.org/openstack-cleanvm.yaml, jenkins/ci.opensuse.org/openstack-staging.yaml, jenkins/ci.opensuse.org/templates/openstack-cleanvm-template.yaml, jenkins/ci.opensuse.org/templates/openstack-staging-template.yaml, scripts/jenkins/cleanvm/openstack-cleanvm.builder.sh
Refactor the `openstack-staging` and `openstack-cleanvm` matrix
jobs to make it easier to monitor and debug them:
- replaces the `openstack-staging` matrix job with a set of
regular jobs named `openstack-staging-<release>`, one for every
supported OpenStack release
- replaces the `openstack-cleanvm` matrix job with a set of
matrix jobs named `openstack-cleanvm-<release>`, one for
every supported OpenStack release. Every such job is configured
to run only against the SLES or OpenSUSE distros that are
applicable
- moves the implementation of the `openstack-cleanvm` job to
a script file stored in the automation repository instead of a JJB
inline shell script
- corrects the name of the job used for Trello reports
A preview for this new job organization for Queens is available …
=> openstack-staging: refactor jobs for better usability (SCRD-8548)

scripts/jenkins/ardana/ansible/roles/heat_stack/tasks/delete.yml
The mapping of volumes on servers created by the ardana heat stacks does
not always reflect what openstack expects (e.g. attaching volume mapped
to /dev/vdb can get mapped to /dev/vdc) this cause issues
when deleting the heat stack as when deleting the attachment openstack
tries to delete /dev/vdb which does not exist, leaving heat stacks in
'Delete failed' state.
This change add a task to delete the servers created by the heat stack,
when the delete sack task fails, and then tries to delete the stack again.
=> openstack-ardana: delete servers when heat stack delete fails

scripts/jenkins/ardana/ansible/roles/ardana_update/tasks/main.yml, scripts/jenkins/ardana/ansible/roles/ardana_update/tasks/reboot_nodes.yml, scripts/jenkins/ardana/ansible/roles/ardana_update/tasks/update_nodes.yml
Installing package updates in parallel on all nodes has the
undesired effect that it breaks the galera cluster.
This change was tested twice:
- with manila enabled (which is now failing the update job): https://ci.suse.de/blue/organizations/jenkins/cloud-ardana8-job-std-3cp-devel-staging-updates-x86_64/detail/cloud-ardana8-job-std-3cp-devel-staging-updates-x86_64/305/pipeline
- with manila disabled: https://ci.suse.de/blue/organizations/jenkins/cloud-ardana8-job-std-3cp-devel-staging-updates-x86_64/detail/cloud-ardana8-job-std-3cp-devel-staging-updates-x86_64/315/tests/
=> openstack-ardana: install package updates serially

scripts/jenkins/ardana/ansible/roles/heat-generator/README.md, scripts/jenkins/ardana/ansible/roles/heat-generator/library/generate_heat_model.py
The magnum VM needs to access the OpenStack public API. Plugging the external API network into the external router, to which the external neutron network is also attached enables that.
=> ardana-heat-generator: plug the external API net into the external router

scripts/jenkins/qa_openstack.sh
The ssh user used by tempest should be configured on the validatioin
section. Remove values not used by tempest.
=> Fix tempest configuration on qa_openstack

scripts/jenkins/ardana/ansible/group_vars/all/versioned.yml, scripts/jenkins/ardana/ansible/roles/input_model_generator/defaults/main.yml
For Cloud-9, add octavia-client and  remove the deprecated
neutron-lbaasv2-agent.
=> Update LBaaS deployment from Cloud9

scripts/jenkins/ardana/ansible/roles/ardana_tempest/defaults/main.yml, scripts/jenkins/ardana/ansible/roles/ardana_tempest/tasks/main.yml, scripts/jenkins/ardana/ansible/roles/ardana_tempest/tasks/reconfigure_neutron.yml, scripts/jenkins/ardana/ansible/roles/ardana_tempest/tasks/run_tempest.yml
This change adds some steps for configuring the environment according to the requirements for running tempest for specific services. It also sets the number of tempest workers to 4 to keep the results in line when comparing tempest results from different environments.
=> openstack-ardana: configure env for specific tempest filters (SCRD-7496)

jenkins/ci.suse.de/cloud-ardana8.yaml, jenkins/ci.suse.de/cloud-ardana9.yaml
The tight coupling between Octavia and Monasca has been corrected [1][2],
so we can re-add that service to the `demo` jobs (i.e. the jobs
that have MML services disabled).
[1] https://gerrit.suse.provo.cloud/#/c/5905/
[2] https://gerrit.suse.provo.cloud/#/c/5909/
=> openstack-ardana: re-add Octavia to demo jobs

scripts/jenkins/ardana/ansible/_create-vcloud-inventory.yml, scripts/jenkins/ardana/ansible/bootstrap-crowbar-nodes.yml, scripts/jenkins/ardana/ansible/bootstrap-vcloud-nodes.yml, scripts/jenkins/ardana/ansible/group_vars/all/vcloud.yml, scripts/jenkins/ardana/ansible/register-crowbar-nodes.yml, scripts/jenkins/ardana/ansible/roles/crowbar_register/tasks/main.yml, scripts/jenkins/ardana/ansible/roles/crowbar_register/tasks/reserve_admin_ip.yml, scripts/jenkins/ardana/ansible/roles/crowbar_setup/tasks/main.yml, scripts/jenkins/ardana/ansible/roles/input_model_generator/templates/mkcloud.config.j2, scripts/qa_crowbarsetup.sh, scripts/scenarios/cloud8/cloud8-5nodes-default.yml, scripts/scenarios/cloud9/cloud9-5nodes-default.yml
Add support for HA deployments to the `openstack-crowbar` core job:
- set the `hacloud`, `clusterconfig` and `want_sbd` variables in
the generated mkcloud.conf when two or more controllers are configured
- fix the `want_sbd` logic in `qa_crowbarsetup.sh`:
- fix repository URL for `python-sh`
- add logic to the `onadmin_batch` function to fill in the SBD
device info in the batch scenario files
- update the `cloud{8|9}-5nodes-compute-ha.yml` files to use SBD and
reflect the `openstack-crowbar` generated environments (e.g node
aliases, no support for NFS shared storage yet)
The node ordering that `qa_crowbarsetup.sh` uses to determine
which nodes are controllers, which are computes etc. is not
deterministic, because it's based on sorting the hostnames of the
nodes, which are generated based …
=> openstack-crowbar: support for HA deployments (SCRD-8462)

scripts/jenkins/ardana/ansible/ardana-ses-rgw.yml
After enabling object-store with RADOS GW, tempest should be
reconfigured to update its configuration accordingly.
=> openstack-ardana: reconfigure tempest after enabling RGW

hostscripts/upgrade-scale/README.md, hostscripts/upgrade-scale/build.sh
Moved the commands to (re)build the cloud into build.sh script.
Restructured things a bit and made it more automated.
Before this PR is merged, use:
`git clone --branch=upgrade-scale-script https://github.com/skazi0/automation`
instead of:
`git clone --branch=upgrade-scale https://github.com/SUSE-Cloud/automation`
to fetch latest version of scripts.
=> upgrade-scale: Script scale-cloud build steps

jenkins/ci.opensuse.org/openstack-cleanvm.yaml, jenkins/ci.opensuse.org/openstack-repocheck.yaml, jenkins/ci.opensuse.org/openstack-staging.yaml, jenkins/ci.opensuse.org/openstack-submit.yaml
trackupstream is left out on purpose as we haven't branched
the packaging yet.
=> Add Cloud:OpenStack:Stein

scripts/qa_crowbarsetup.sh
Tempest uses fake drivers for most of it's ironic tests.
This is part of changes needed to support ironic tests in tempest.
=> ironic: Enable fake drivers if tempest is enabled

scripts/qa_crowbarsetup.sh
If Ironic is deployed with Swift, it will try to use all features
using Swift (e.g. agent based deployment). This requires glance to
use Swift as default image store.
=> glance: Use Swift in glance if ironic is deployed

scripts/qa_crowbarsetup.sh
We chose a different direction that did not involve changing the crowbar
install key at all, so there is no need to refresh the CROWBAR_KEY
environment variable.
This reverts commit 5b74c1c3980fb9f91d332fc840ceddb6487e7b7b.
=> Revert "Re-source the crowbar variables after commit"

jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-2a.yaml, scripts/scenarios/cloud9/qa/no-ssl/qa-scenario-2a.yaml
Update cluster number from 2 to 3
2 node cluster not supported in SOC9
Will change to 2 cluster (services and data) setup as on qa clouds only 7 nodes available to deploy.
=> Fix scenario-2a

scripts/jenkins/ardana/ansible/group_vars/all/all.yml, scripts/jenkins/ardana/ansible/group_vars/qe_all.yml, scripts/jenkins/ardana/ansible/group_vars/virt_all.yml, scripts/jenkins/ardana/ansible/roles/ardana_deploy/defaults/main.yml, scripts/jenkins/ardana/ansible/roles/ardana_tempest/tasks/import_octavia_image.yml, scripts/jenkins/ardana/ansible/roles/ardana_tempest/tasks/reconfigure_neutron.yml, scripts/jenkins/ardana/ansible/roles/ardana_update/tasks/reboot_nodes.yml, scripts/jenkins/ardana/ansible/roles/ardana_update/tasks/update_nodes.yml
The number of API and RPC workers configured for various OpenStack
services in Ardana is dynamically calculated based on the number
of CPUs. However, the formula is currently incorrect and leads
to a huge number of processes being created on the virtual Ardana
cloud installations - there are 4 times as many workers as there
should be - which has negative side effects on the overall
performance.
To make a simple comparison, the general formula used by Ardana to
calculate the number of workers is:
```
min(ansible_processor_count * ansible_processor_cores * 2, max_workers)
```
where `max_workers` has a value of `10` for most services, but sometimes
can be `20` and sometimes `8`, whereas the OpenStack Ansible formula is:
```
min(ansible_processor_vcpus / 2, 16)
```
and the general rule used …
=> openstack-ardana: override OpenStack service worker count (SCRD-7496)

scripts/jenkins/cleanvm/openstack-cleanvm.builder.sh
The cleanup section did not show any messages.
Failures in the cleanup section were misinterpreted as being cleanvm errors.
This commit adds messages to better show the status of the cleanvm run and the cleanup.
=> cleanvm: add messages to better understand the script output

scripts/jenkins/qa_openstack.sh
Since stein, the default flavors have a disk size > 0. This is needed
to pass the tempest test:
tempest.api.compute.servers.test_attach_interfaces.\
AttachInterfacesUnderV243Test.test_add_remove_fixed_ip
which would fail with:
Details: {u'message': u'Only volume-backed servers are allowed for \
flavors with zero disk.', u'code': 403}
See also https://docs.openstack.org/releasenotes/nova/stein.html and
https://bugs.launchpad.net/nova/+bug/1739646
=> qa_openstack: Fix disk size for default flavors used by tempest

jenkins/ci.suse.de/pipelines/openstack-crowbar.Jenkinsfile, scripts/jenkins/ardana/ansible/run-crowbar-tests.yml
This PR generates and processes crowbar tempest subunit results, collects them
as artifacts, and displays the the junit test in jenkins.
For a working job, see: https://ci.suse.de/blue/organizations/jenkins/openstack-crowbar/detail/openstack-crowbar/205/tests (this job is missing testr_crowbar.html collection, as I missed a dependency. Fixed already).
Question: does the current layout feel ok, or would you prefer for me to refactor both `run-crowbar-tests.yml` and ardana's `run-tempest.yml` playbooks, into one plus a role? or is it ok with this minimal approach? Notice that the `run-crowbar-tests.yml` playbook vars have been chosen to match with ardana's ones, which can be misleading.
=> openstack-crowbar: Add ansible vars, generate and process tempest junit

scripts/scenarios/cloud9/cloud9-2nodes-ses.yml
Remove ceilometer from the cloud 9 2 nodes SES crowbar batch
scenario, to bring it to the same list of services as the default
2 nodes scenario used by the cloud 9 gating job.
=> openstack-crowbar: fix the 2 nodes SES scenario

scripts/mkcloud
Without this, there's no way to do CI on a patch that fix a bug in the
restore step as we will not use the patched package.
=> mkcloud: Call addupdaterepo during crowbarrestore

scripts/qa_crowbarsetup.sh
In order to get some state tracked, lets blacklist the known
failing tests. They are related to encrypted volumes
(the crowbar deployed config is broken) and some networking issues.
=> Blacklist known failures in tempest-full

scripts/crowbar-testbuild.yaml
We're testing HA with SSL in the gate as well, so
the PR should be tested the same way to avoid
regressions from only being caught post merge.
=> run HA PR testing with ssl

scripts/qa_crowbarsetup.sh
When the `GM8` and `GM8+up` cloudsource values are used, the
Ardana flavor ISO is installed instead of the Crowbar one.
=> qa_crowbarsetup.sh: mount crowbar ISO for cloud8 GM

scripts/jenkins/ardana/ansible/run-crowbar-tests.yml
python-virtualenv is not part of the crowbar gm8+up ISO, add the
python backports repo to install it, and ensure that it always
gets removed.
=> openstack-crowbar: Add python backports repo for python-virtualenv

scripts/jenkins/ardana/ansible/run-crowbar-tests.yml
zypper_repositories doesn't seem to add repos if they are missing the .repo tail.
Moreover, disable gpg check for the repo or zypper_repositories will also fail.
=> openstack-crowbar: workaround bug in zypper_repositories when adding repo

scripts/jenkins/ardana/ansible/group_vars/all/vcloud.yml, scripts/jenkins/ardana/ansible/group_vars/virt_all.yml, scripts/jenkins/ardana/ansible/roles/input_model_generator/templates/input_model/data/disk_models.yml
When mariadb is running on top of shared (ceph) storage with the
default configuration values, there is a huge impact on its
performance, because database commit operations must wait until
disk flush operations are complete (and with shared storage,
that takes longer).
There are two solutions to this:
1. move the database to the root filesystem, which is not
currently implemented as a ceph volume (the ephemeral volume
in the ECP is still set up as a local volume on the compute node)
2. decouple the flush and commit operations, by tweaking the
innodb configuration (i.e. set the `innodb_flush_log_at_trx_commit`
configuration option [1] to 2). This option requires matching changes
in the `db-ansible` repository [2].
This commit implements both these options and adds a top-level …
=> openstack-ardana: mariadb performance tunings (SCRD-7496)

scripts/qa_crowbarsetup.sh
By default, nova would take any network it finds as long as there's
only one. If nova can't decide it fails with "Multiple possible
networks found" conflict.
This is especially important in Ironic case because there is "ironic"
network defined.
=> Force fixed network for nova boot tests

scripts/qa_crowbarsetup.sh
With the current workflow the periodic chef-client run
might interfere and roll out our keystone toggle changes
partially on the cluster. Make sure everything is in sync
before going with the integration test.
=> Make sure that after toggling ssl on/off all services are restarted

scripts/jenkins/qa_openstack.sh
Since it appears that the older testing framework tools (testr and
possibly run_tempest.sh) don't support the --blacklist-file option
and we only need the blacklisting for Rocky release tests, which is
based upon stestr & tempest commands, we can remove the broken
options from the testr and run_tempest.sh which are used for older
OpenStack version testing anyway.
=> Only add blacklisting for stestr and tempest commands (SCRD-8681)

jenkins/ci.suse.de/cloud-mkcloud7.yaml, jenkins/ci.suse.de/cloud-mkcloud8.yaml, jenkins/ci.suse.de/cloud-mkcloud9.yaml, jenkins/ci.suse.de/templates/cloud-mkcloud-job-magnum-template.yaml
magnum jobs on Cloud9+ fail with:
The specified regex doesn't match with anything
which is because the tests have been moved out of tree into a separate
magnum_tempest tests package. adjust regexp for rocky only, which
means we need to make it configurable and use the old values. Also
drop the aarch64 part because PM asked us to deinvest in aarch64 for
cloud8.
=> Fix magnum tempest testsetup

scripts/qa_crowbarsetup.sh
We never forgot enabled ssl in keystone when want_all_ssl=1
was set due to missing of the critical config setting being
done.
=> enable keystone ssl when want_all_ssl=1 is set

scripts/qa_crowbarsetup.sh
Without this patch, when SSL is enabled, and then crowbar is backed up
and restored from backup, and then keystone's SSL endpoint is toggled
off and then on, the root CA that was generated during the initial
proposal step is not saved and mkcloud generates a new one for keystone.
This causes the keystone endpoint to work fine but means all the other
services have old certs that are not trusted by the new CA. This patch
fixes the issue by ensuring that if a new CA is generated, it is
appended to the old one rather than replacing it. This means that even
if keystone gets a new cert, all services should still work.
=> Append trusted CA to existing one

jenkins/ci.opensuse.org/macros.yaml
Drop the GIT_ORIGIN variable so GERRIT_SITE is used when cloning
repositories. This is needed because git.openstack.org (which
GIT_ORIGIN was pointing to) does no longer exist.
Also update GERRIT_SITE to reflect the openstack->opendev switch.
=> ci.opensuse.org: Fix gerrit-git-prep builder

scripts/qa_crowbarsetup.sh
currently without nova, neutron and designate cannot be deployed, this is
a pretty hard requirement which does not really exist in the product.
One can have keystone and neutron working together to test the
integration, but having nova (glance, cinder) simply increases
deployment time as well as chef-client run time which makes
testing quick changes to the recipes painfully difficult
This patch just make sure novacontroller variable is pointed to the
correct host by looking at the neutron-server attribute of the neutron
proposal. This could be extended to other barclamps, but that is not the
aim of the patch.
The variable is not really a "nova controller" but just a simple
controller and it begs being renamed everywhere, but since the
variable has always been called novacontroller, i dare …
=> try neutron proposal for controller, if nova does not exist

jenkins/ci.suse.de/cloud-ardana9.yaml, jenkins/ci.suse.de/openstack-ardana-update-and-test.yaml, jenkins/ci.suse.de/openstack-ardana-update.yaml, jenkins/ci.suse.de/templates/cloud-ardana-pipeline-template.yaml, jenkins/ci.suse.de/templates/cloud-crowbar-pipeline-template.yaml
Adds `GM9` and `GM9+up` to the available cloudsource values
and makes the devel-to-staging-update job a mandatory part
of the cloud 9 Ardana gating job.
Also creates a periodic `cloud-ardana9-job-std-min-suse-x86_64`
job running against GM9+up.
=> openstack-ardana: enable cloud 9 GM and updates

scripts/repochecker
Some changes are needed to make repochecker usable again.
For checking Cloud:OpenStack:Stein , you can use now something like:
REPCHECK_DIST_NAME=SLE REPCHECK_DIST_VERSION=15 \
REPCHECK_PROJECT=Cloud:OpenStack:Stein bash -x scripts/repochecker
=> repochecker: Adjust repochecker to be able to run with Leap/SLE15

jenkins/ci.suse.de/cloud-mkcloud8.yaml, jenkins/ci.suse.de/cloud-mkcloud9.yaml, jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-linuxbridge-bonding-template.yaml
This will deploy mariadb, and therefore needs at least 3 nodes of the HA
control plane.
=> ci: Fix mkcloud-job-ha-linuxbridge-bonding

scripts/jenkins/ardana/ansible/group_vars/all/all.yml, scripts/jenkins/ardana/ansible/roles/heat-generator/README.md, scripts/jenkins/ardana/ansible/roles/heat-generator/library/generate_heat_model.py
Adds some code to properly handle load balancer references
in the network groups.
The `ardana-input-models` input models use load balancer
references in the network groups, rather than inline load
balancer definitions. The last heat generator patch [1] didn't
take that into account, causing the playbook to fail if such
an input model is used as input.
This PR also adds some defaults for global variables that
are required by the heat generator playbook and documents
how to override them.
[1] https://github.com/SUSE-Cloud/automation/pull/3288
=> heat-generator: handle load-balancer references and global var defaults

scripts/jenkins/ardana/ansible/roles/ardana_deploy/tasks/main.yml
In a deployment where we specify an external
name for the public endpoints, the /etc/hosts
file need to be updated with this entry. Earlier,
we did this on only deployer node.
However, services like heat communicate to
keystone via the public endpoint. This requires
that the /etc/hosts file on the controller nodes
need to be updated as well.
=> Update /etc/hosts on controller nodes

scripts/jenkins/qa_openstack.sh
The intention of the cleanvm check is to see if the OpenStack
Cloud packages would install + pass testing on a default SLES
installation.
The HA product is not default subscribed for SLES customers, see
http://docserv.nue.suse.com/documents/SLES_15/SLES-modulesquick/single-html/#sec.modules.what.modules
for details.
This reverts commit 565bab6c8d46d6038e8e8e0f64e615aeba7f1600.
=> Revert "qa_openstack: Add SLE15 HA product"

scripts/jenkins/ardana/gerrit/gerrit.py
Update Gerrit CI scripts to be compatible with the new
version of Gerrit:
- update Gerrit server host name
- switch to HTTP basic authentication, because support
for HTTP Digest authentication was removed in Gerrit 2.14 [1]
[1] https://github.com/dpursehouse/pygerrit2#usage
=> openstack-ardana: switch to new gerrit server

scripts/jenkins/ardana/ansible/group_vars/virt_all.yml
Running live migration tests on ardana deployments on ECP occasionally
fails due to CPU incompatibility (e.g. one compute is scheduled to a sandy
bridge host and another to a westmere host).
This change sets the cpu model to Westmere on the deployed ardana computes,
making sure that it always possible to do livre migration on the
deployed ardana cloud.
=> openstack-ardana: set nova cpu_model for virtual deployments

jenkins/ci.suse.de/cloud-ardana9.yaml, jenkins/ci.suse.de/cloud-crowbar9.yaml, jenkins/ci.suse.de/templates/cloud-ardana-pipeline-template.yaml, jenkins/ci.suse.de/templates/cloud-crowbar-pipeline-template.yaml, scripts/jenkins/ardana/ansible/group_vars/all/all.yml, scripts/jenkins/ardana/ansible/roles/heat-generator/templates/heat-template.yaml, scripts/jenkins/ardana/ansible/roles/input_model_generator/defaults/main.yml, scripts/jenkins/ardana/ansible/roles/input_model_generator/templates/input_model/data/networks.yml, scripts/jenkins/ardana/ansible/roles/input_model_generator/templates/input_model/data/neutron/neutron_config.yml, scripts/jenkins/ardana/ansible/roles/input_model_generator/templates/input_model/data/servers.yml, scripts/jenkins/ardana/ansible/roles/input_model_generator/templates/mkcloud.config.j2, scripts/jenkins/ardana/ansible/roles/input_model_generator/vars/crowbar.yml, scripts/jenkins/ardana/ansible/roles/input_model_generator/vars/templates/network/standard.yml
This PR add IPv6 support to the input model generator and heat generator,
so that it can be used by both Ardana and Crowbar.
This requires replacing some of the hard-coded IPv4/6 prefix values
with ansible variables and using those values in the generated
mkcloud.conf file.
For Ardana IPv6 environments to work properly, it was also necessary
to move the default route to the `CONF` network in all the scenarios
that use the `standard` network template (`standard`, `std-lmm`,
`std-split`). This has the effect that the default route is set
up on the same interface used by the lifecycle manager, which is
the same interface that is associated with the floating IP on
the deployer node. When IPv6 is enabled, the default route will
be IPv4, which allows the nodes to communicate with the outside …
=> openstack-crowbar/ardana: ipv6 support and periodic jobs

scripts/mkcloud, scripts/qa_crowbarsetup.sh
**Prerequisites**:
- https://github.com/crowbar/crowbar-openstack/pull/2100
- https://github.com/crowbar/crowbar-openstack/pull/2107
- https://github.com/crowbar/crowbar-openstack/pull/2094
Tempest test BaremetalBasicOps require proper ironic environment
with at least one node available for testing. This is end-to-end
test which performs full life cycle of instance deployed to ironic
node.
To run this test, mkcloud was extended with functions to prepare
and cleanup the test environment including:
- Installation and configuration of VirtualBMC simulated IPMI
service for ipmitool based power management
- Registration of all nodes created with `setupironicnodes` step
in Ironic service
- Creation of required Ironic network ports
- Enrolling ironic nodes (moving to 'available' state)
- …
=> ironic: Setup test env for tempest integration test

jenkins/ci.suse.de/pipelines/openstack-ardana-image-update.Jenkinsfile, scripts/lib/libvirt/fixtures/cloud-admin-uefi.xml, scripts/lib/libvirt/fixtures/cloud-admin.xml, scripts/lib/libvirt/fixtures/cloud-node1-9pnet-mount.xml, scripts/lib/libvirt/fixtures/cloud-node1-raid.xml, scripts/lib/libvirt/fixtures/cloud-node1-uefi.xml, scripts/lib/libvirt/fixtures/cloud-node1-xen.xml, scripts/lib/libvirt/fixtures/cloud-node1.xml, scripts/lib/libvirt/libvirt_setup.py, scripts/lib/libvirt/templates/admin-node.xml, scripts/lib/libvirt/templates/net-interface.xml, scripts/qa_crowbarsetup.sh
Enabling hw_vif_multiqueue_enabled makes OpenStack switch
to the vhost-net driver instead of virtio and also enable
multiqueue support there, which means we can have a much
higher peak throughput of packet I/O, and that should be
a good thing :-)
=> Use virtio multiqueue for the ardana CI images

scripts/jenkins/ardana/gerrit/gerrit.py
The `submittable` attribute that was implicitly populated in
all change objects retrieved via the Gerrit REST API now has
to be explicitly requested by adding `o=SUBMITTABLE` to the
query string [1].
[1] https://gerrit-documentation.storage.googleapis.com/Documentation/2.16/rest-api-changes.html#submittable
=> openstack-ardana-gerrit-events: fix missing submittable attr

jenkins/ci.suse.de/ardana-trackupstream.yaml
This PR removes freezer from cloud 9 in the trackupstream
matrix.
=> ardana-trackupstream: remove freezer from c9

scripts/jenkins/ardana/ansible/roles/tempest_results/defaults/main.yml, scripts/jenkins/ardana/ansible/roles/tempest_results/tasks/main.yml, scripts/jenkins/ardana/ansible/roles/tempest_results/vars/crowbar.yml, scripts/jenkins/ardana/ansible/run-crowbar-tests.yml
Moves the code responsible for collecting tempest results
and converting them in the proper formats to a standalone
ansible role that can be reused for Ardana in the future.
This PR also corrects the repositories where required packages
are installed from.
=> openstack-crowbar: add tempest-results ansible role

docs/ardana/testing.md
Just to make instructions a little more complete. 
In order to run an "openstack" command the test environment requires
the openstack client to be installed. 
Explicitely stating to avoid confusing new users.
=> Test environment requires openstack cli client

scripts/jenkins/gitlint.ini
We only want the SCRD number once at the end of a commit msg.
=> SCRD should be only at the end of a commit msg

jenkins/ci.suse.de/cloud-ardana8.yaml, jenkins/ci.suse.de/cloud-ardana9.yaml, jenkins/ci.suse.de/cloud-crowbar7.yaml, jenkins/ci.suse.de/cloud-crowbar8.yaml, jenkins/ci.suse.de/cloud-crowbar9.yaml, jenkins/ci.suse.de/pipelines/openstack-cloud-image-update.Jenkinsfile, jenkins/ci.suse.de/templates/cloud-image-update-template.yaml
Make the Jenkins pipeline that automates updating the ECP images
used by the Ardana (and now Crowbar) ECP CI independent of cloud
product and updates the Ardana image update jobs to run periodically
at the end of every week. Also creates periodic jobs for images
that are used by Crowbar (those initially used by the Ardana
CI when the root partition wasn't a prerequisite).
A periodic job is also responsible for cleaning up old and unused images,
which is also what this PR adds to the pipeline logic.
=> openstack-cloud-image: periodic image update jobs

scripts/jenkins/ardana/gerrit/gerrit.py
Re-enables certificate verification in the Gerrit API calls.
NOTE: a properly signed certificate needs to replace the self-signed certificate on the Gerrit server. The other change that needs to be reversed to fully re-enable certificate validation is the git configuration on the `ardana-ci-launcher` and `cloud-trackupstream-sle12` Jenkins nodes, which are currently set to bypass it - i.e. in `~/.gitconfig`:
```
[http "https://gerrit.prv.suse.net"]
sslVerify = false
[http "https://git.suse.provo.cloud"]
sslVerify = false
```
=> openstack-ardana-gerrit: re-enable cert verification

jenkins/ci.suse.de/cloud-ardana8.yaml, jenkins/ci.suse.de/cloud-ardana9.yaml, jenkins/ci.suse.de/openstack-ardana-tests.yaml, jenkins/ci.suse.de/openstack-ardana-update-and-test.yaml, jenkins/ci.suse.de/pipelines/openstack-ardana-gating.Jenkinsfile, jenkins/ci.suse.de/templates/cloud-ardana-pipeline-template.yaml
This change replace the `std-min` and `std-3cp` input models
currently employed by the Ardana gating jobs with an
entry-scale-kvm input model and replaces the 'ci' tempest
filter with a full set of tempest filters.
With the recent cleanup of Ardana tempest filters [1] [2] and the
efforts to stabilize the CI, we can finally have a full tempest
coverage in the gate. The `entry-scale-kvm` input model is
also better suited for a gating job, because it is closer to
what customers use.
This change also updates all other jobs to reflect the new
tempest filters and run only those that are applicable [3].
These are the main differences between the `standard` and
`entry-scale-kvm` input model scenarios:
- there is no dedicated CLM (CONF) network in `entry-scale-kvm`.
It is part of the MANAGEMENT …
=> openstack-ardana-gating: full tempest and entry-scale-kvm

scripts/jenkins/ardana/ansible/roles/input_model_generator/README.md
the name of the variable used is input_model_path, not input_model_dir
=> Correct example for input_model_path

scripts/jenkins/ardana/ansible/roles/ardana_tempest/tasks/reconfigure_neutron.yml
Check the status of the neutron services after reconfiguring
neutron to use a centralized or distributed default router type.
As a workaround for SCRD-9144, this change also inserts a 5 minute
delay after reconfiguring neutron, to give the OVS agents enough
time to come back to life.
=> openstack-ardana: improved neutron reconfigure (SCRD-9144)

scripts/jenkins/ardana/ansible/roles/heat-generator/library/generate_heat_model.py, scripts/jenkins/ardana/ansible/roles/heat-generator/library/load_input_model.py
For Python2/3 compatibility, replace the use of `iteritems()` which
was deprecated in Python3 with `items()`. These two methods are very
similar in Python2 with `items()` returning a list of tuples and
`iteritems()` returning an iterator of the tuples.
=> Use `items()` instead of `iteritems()`

scripts/jenkins/ardana/manual/lib.sh
Things end badly (in load_input_model.py) if using Python 3.
=> Make sure the Python venv is using Python 2

scripts/mkcloud
Sometimes `vbmc start` returns "BMC instance ... already running"
on first attempt and/or if run to quickly after `vbmc add`.
In such cases, the BMC needs to be re-created before it will start
correctly.
Wrapping the (re)start logic in a function makes it easier to use
it in `wait_for`.
=> ironic: Improve virtualbmc startup

scripts/jenkins/ardana/ansible/roles/heat-generator/library/generate_heat_model.py
The `dict.values()` method returns a `list` in Python2 and a
`dict_view` in Python3. Convert a potential `dict_view` to a `list` in
case the code is run using Python3.
=> Convert `dict_view` into `list` for Python3

scripts/jenkins/ardana/ansible/roles/heat-generator/library/generate_heat_model.py, scripts/jenkins/ardana/ansible/roles/heat-generator/library/load_input_model.py
As of Python 2.6, `BaseException.message` has been deprecated and it
was removed in Python 3. An alternative is to use `str()` instead.
This change also adds some information on where an Exception occurred.
=> Replace deprecated `Exception.message`

scripts/jenkins/ardana/ansible/roles/heat-generator/library/generate_heat_model.py
Note that `filter()` in Python 2 returns a list and is thus
subscriptable, whereas `filter()` in Python 3 returns an iterator. The
`six.moves.filter()` function uses `itertools.ifilter()` to also
return an iterator. Hence, we need to convert the iterator explicitly
to a list.
=> Replace `filter` with equivalent `six.moves.filter`

scripts/jenkins/ardana/ansible/roles/heat-generator/library/generate_heat_model.py
Python 3 removed `iteritems`. A call to `items` is essentially
equivalent but works for Python 2 and 3.
=> Replace `iteritems` with `items`

scripts/jenkins/jenkins-job-pipeline-report.py
In Python 3 `print` is a function.
=> Convert `print` to function call for Python 3

hostscripts/clouddata/syncSLErepos
Run sync repos as non-root
in order to run less code as root.
For that we need to create an fstab entry for mount_and_rsync
=> Run sync repos as non-root

jenkins/ci.opensuse.org/openstack-trackupstream.yaml
We have OpenStack Stein packages now. So track the stable branches
for the packages.
=> trackupstream: Track OpenStack Stein release

.travis.yml, Makefile, scripts/lib/libvirt/libvirt_setup.py
Switch to Ubuntu Xenial for python3-libvirt which wasn't available in
Trusty.
Also:
- py23: use string.ascii_lowercase
instead of string.lowercase, as the later is not available in python 3.
=> make: add python3 to test with both versions

scripts/jenkins/ardana/ansible/group_vars/all/versioned.yml, scripts/jenkins/ardana/ansible/roles/ardana_deploy/tasks/setup_mu_repos.yml
The dynamically generated _maint_updates.yml playbook will hang,
prompting for confirmation of SSH host key changes unless the
ardana-ssh-keyscan.yml playbook has already been run.
Update the name for the task generating _maint_updates.yml to
indicate that it is generating rather than copying the playbook.
=> Need to run ardana-ssh-keyscan before setup_mu_repos (SCRD-9290)

scripts/jenkins/ardana/ansible/roles/heat-generator/library/generate_heat_model.py, scripts/jenkins/ardana/ansible/roles/heat-generator/library/load_input_model.py
When an exception in the Ansible modules occur it is helpful for
debugging purposes to see the full traceback.
=> For debugging, print a traceback on Exception

jenkins/ci.suse.de/cloud-ardana8.yaml, jenkins/ci.suse.de/cloud-ardana9.yaml
The LBaaS tempest test cases are still failing intermittently
in the gates.
As a temporary workaround, after this change, the gating jobs
will no longer run the `lbaas` tests until these issues are
understood better (see https://jira.suse.com/browse/SOC-9285).
=> openstack-ardana-gating: exclude lbaas tempest (SOC-9176)

scripts/jenkins/ardana/manual/lib.sh
For debugging it can be helpful to check the generate Heat template
before it is deployed on OpenStack. This change refactors this step
from the `prepare_infra` step into a separate function.
=> Split generate-heat-template step for debugging

scripts/jenkins/ardana/ansible/bootstrap-crowbar.yml
When the `bootstrap-crowbar.yml` playbook is ran multiple times the
removal of `ifcfg` files fails because they were removed already in
the first run. This change makes this task idempotent.
=> Make `bootstrap-crowbar` idempotent

scripts/jenkins/ardana/manual/lib.sh
This change adds the environment variables `ANSIBLE_VERBOSE` to the
`ansible-playbook` call so that the user can control the verbosity
level by running, e.g.
ANSIBLE_VERBOSE="--verbose" prepare_infra
=> Add environment variable to add arguments to Ansible

scripts/jenkins/ardana/ansible/bootstrap-crowbar-nodes.yml, scripts/jenkins/ardana/manual/deploy-crowbar.sh
use `wait_for` instead of unreliable 'wait_for_connection` even for crowbar in 'bootstrap-crowbar-nodes'
=> use `wait_for` instead of unreliable 'wait_for_connection`

scripts/qa_crowbarsetup.sh
If environment is built with batch scenario file, $want_*_ssl might
not be set to match ssl settings in services. In such cases selecting
incorrect ssl test mode (off+on vs on+off) could lead to unexpected
end state of the system.
=> Use actual keystone protocol to select test mode

scripts/jenkins/ardana/ansible/roles/rocketchat_notify/tasks/set_announcement.yml
For getting the channel list there is a query limited to a number of 100
results. However some channels are missing in that resulting list, causing the
playbooks to fail.
This change removes that limit and instead get a list of all channels on
rocketchat.
=> openstack-ardana: fix rocketchat announcement

scripts/jenkins/ardana/ansible/roles/setup_root_partition/defaults/main.yml
Due to the increasing size of the SUSE/Cloud update channels, which are
rsynced into the deployer node, the actual root partition size is not
enough and is causing failures on some CI jobs [1, 2].
This change increase the root partition size from 24 GB to 34 GB.
1. https://ci.suse.de/blue/organizations/jenkins/cloud-ardana8-job-std-min-centos-x86_64/detail/cloud-ardana8-job-std-min-centos-x86_64/197/pipeline
2. https://ci.suse.de/blue/organizations/jenkins/cloud-ardana8-job-std-min-suse-x86_64/detail/cloud-ardana8-job-std-min-suse-x86_64/232/pipeline
=> openstack-ardana: increase initial root partition size

scripts/jenkins/ardana/ansible/group_vars/all/all.yml
147.2.2.2 stopped resolving download.opensuse.org...
Also added some more NTP servers while replacing the DNS with
servers closer to the RD clouds.
=> use RD DNS and NTP servers

scripts/jenkins/ses/ansible/roles/ses/tasks/deepsea_setup.yml
This action often fails on the first run. Proper fix would of course
require knowing why the task fails and wait for appropriate condition
instead.
=> Retry 'Run stage 0 - prepare' few times

scripts/jenkins/ses/ansible/roles/ses/tasks/deepsea_setup.yml, scripts/jenkins/ses/ansible/roles/ses/tasks/salt_setup.yml
This change:
- Adds additional checks before proceeding to the salt-run calls,
making sure everything is ready before starting SES deployment.
- Drop the deepsea config with correct owner/permissions.
=> openstack-ses: make SES deployment more reliable

scripts/jenkins/ses/ansible/roles/ses/tasks/deepsea_setup.yml
Sometimes the pillar data from the SES configuration is not available
when calling the salt stages. This change ensures that the pillar data is
available before proceeding.
=> openstack-ses: ensure pillar data available

scripts/jenkins/ardana/ansible/roles/ardana_deploy/tasks/main.yml, scripts/jenkins/ardana/manual/deploy-ardana-without-site.sh, scripts/jenkins/ardana/manual/lib.sh
For development it is very useful to have a system which is ready to run site.yml for the first time.
=> create script to deploy ardana system without running site.yml

.dir-locals.el, scripts/jenkins/ardana/manual/lib.sh
PR #3447 (4b7b2b77bcce016ef9277b6642fcf9b0702d8eb2) was written
without PR #3452 (6b0c8c9f76ab3ca79b19ecb055a4ce5967ab79ac) and had
not been linted with bashate. This change fixes the linter issues and
adds a `.dir-locals.el` file so that emacs users use the correct
indentation.
=> Fix bashate errors

scripts/qa_crowbarsetup.sh
In addition to "public-<cluster>" and "<cluster>" some places use
"public.<cluster>" as host part of URL. To make SSL validators happy
include additional alias in set SANs.
=> Include public.<cluster> in SSL cert SAN

jenkins/ci.suse.de/pipelines/cloud-gating.Jenkinsfile
The test was the wrong way around.
Follow up for https://github.com/SUSE-Cloud/automation/pull/3278
=> cloud-gating: Fix start time sanity check

jenkins/ci.opensuse.org/openstack-cleanvm.yaml
We want to test the latest openSUSE release so add it for the latest
OpenStack release (stable/stein) and the current development (master)
=> cleanvm: Add openSUSE Leap 15.1 for Master and Stein

scripts/jenkins/ardana/ansible/group_vars/virt_all.yml
For cloud 9 the process count logic was reworked on the product itself,
so we do not need to override it anymore (see: [1]).
1. https://gerrit.prv.suse.net/q/topic:%2522SCRD-8748_worker_counts%2522
=> openstack-ardana: apply process count overrides on cloud8 only

jenkins/ci.opensuse.org/openstack-prepare-staging.py
The ToTest mechanism needs to work for Stein (and in the future for
Train) as well so fix the check to make it working.
Otherwise, Cloud:OpenStack:Stein:ToTest is never updated.
=> openstack-prepare-staging: Support Stein and Train

scripts/jenkins/ardana/ansible/roles/ardana_tempest/tasks/retry_failed.yml, scripts/jenkins/ardana/ansible/roles/ardana_tempest/templates/run_filter_retry_serial.txt.j2
The run filter file needs to have at least one test or it will include
`The specified regex doesn't match with anything` into the subunit file,
resulting in a corrupt subunit output.
=> openstack-ardana: Fix for retrying tempest failed tests

scripts/qa_crowbarsetup.sh
In older versions where PKI token signing was used, signing section
was using the same cert/key paths as ssl but ca_certs attribute was not
updated.
=> Use correct ca_certs path in signing section

jenkins/ci.suse.de/cloud-ardana8.yaml, jenkins/ci.suse.de/cloud-ardana9.yaml, jenkins/ci.suse.de/templates/cloud-gating-template.yaml
This change enable reruning the failed tempest tests on the gating jobs
for cloud 8 and 9.
This is a temporary solution to unblock the gating jobs until running
tempest full gets more stable.
=> openstack-ardana: Rerun failed tempest tests on gating jobs

jenkins/ci.suse.de/openstack-mkcloud-log-parser-test.yaml, scripts/github_pr/suse.cloud-specs.helper.sh, scripts/jenkins/ardana/pr-update.sh, scripts/jenkins/mkcloud/openstack-mkcloud.prep.sh, scripts/qa_crowbarsetup.sh
Someone created a branch named pr/282 which with the git fetch config
creates a path for the local remotes ref where the PR of that
number and the branch of that name overlap. This prevents fetching all
updates in the git repo.
```
cloud-specs$ git fetch origin
fatal: Cannot fetch both refs/heads/pr/282 and refs/pull/282/head to
refs/remotes/origin/pr/282
```
Afterwards the cloud-specs CI job failed to checkout the PR to test as
it was not locally availabe and thus tested master instead.
Fix this by chosing a config where those don't overlap.
Also set error on exit to fail CI instead of silently passing.
=> Use git ref location that prevents overlap

jenkins/ci.suse.de/templates/cloud-socok8s-integration.yaml
To reduce the number of jobs that are triggered let's switch to
"current" strategy. By doing that we should prevent new jobs being
triggered for every PR when a change get's merged into master.
=> socok8s: Change discover strategy for Pull request

scripts/jenkins/ardana/ansible/roles/input_model_generator/defaults/main.yml, scripts/jenkins/ardana/ansible/roles/input_model_generator/templates/input_model/data/disk_models.yml, scripts/jenkins/ardana/ansible/roles/input_model_generator/vars/entry-scale-kvm.yml, scripts/jenkins/ardana/ansible/roles/input_model_generator/vars/mid-scale-kvm.yml
The generated heat stack for Crowbar as well as Ardana virtual cloud
environments includes a lot of volumes that are not actually being used:
- the cinder volume used for the LVM back-end and those used for swift
proxy-account-container are not used for Crowbar deployments
- the cinder volume disk which is mounted by Ardana to `/var/lib/cinder`.
This volume was included with the `entry-scale-kvm` and `mid-scale-kvm` scenarios,
but using the root partition instead may actually bring better performance,
so this change turns it off
=> openstack-ardana/crowbar: remove unused volumes from heat template

scripts/jenkins/ardana/ansible/bootstrap-crowbar-nodes.yml
When the `bootstrap-crowbar-nodes.yml` playbook is run multiple times
the removal of `ifcfg` files fails because the files were removed
already in the first run. This change makes this task idempotent.
=> Make `bootstrap-crowbar-nodes` idempotent

scripts/qa_crowbarsetup.sh
After adding version information to deploy kernel/ramdisk images,
create_ironic_node() will pick the newest images.
In addition, the naming of images was changed to follow Ardana
style.
=> ironic: Use versioned deploy images

README.md, docs/ardana/testing.md
This PR updates the documentation to reflect that we have a unified automation toolchain that can be used to deploy both Crowbar and Ardana either in the ECP or the SUSE (Nuremberg) clouds.
=> Update docs with unified Crowbar/Ardana CI info

scripts/jenkins/ardana/ansible/roles/heat_stack/defaults/main.yml
As the `heat_stack` role is also used in SES and it does not use the same inventory as ardana, it cannot get the default value for `os_project_name` which is defined on the ardana group vars.
Defining the `os_project_name` in the defaults values for the `heat_stack` role ensures that we have the default value available for anyone who uses the role.
=> openstack-ardana: set default project for heat_stack role

jenkins/ci.suse.de/cloud-ardana8.yaml, jenkins/ci.suse.de/cloud-ardana9.yaml, jenkins/ci.suse.de/cloud-maintenance-gating.yaml, jenkins/ci.suse.de/pipelines/openstack-ardana.groovy, jenkins/ci.suse.de/pipelines/openstack-maintenance-gating.Jenkinsfile
For cloud 8:
- Change from standard 3cp model to entry-scale-kvm for the test updates
job.
- Adds lbaas to the list of tempest tests to run on the update job.
For cloud 9:
- Create maintenance update jobs
For both:
- Change the `cloud-maintenance-gating` job to be able to trigger jobs for
testing multiple cloud versions. For example, if a MU affects both cloud
8 and 9, this job can be triggered for testing both instead of needing
to trigger one job for cloud 8 and another for cloud 9.
- Replaced the `cloudsource` parameter with `cloudversion` which provide the options `SOC8/SOC9`
- Enable re-runing failed tempest tests, just as the gating job does.
=> openstack-ardana: update MU jobs

jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-ironic-agent-template.yaml, jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-ironic-template.yaml
After recent extensions of Ironic environment setup, it should
be possible to start doing some real Ironic functional tests (not
just deployment testing).
=> Enable some tests in Ironic CI

scripts/jenkins/ardana/ansible/ardana-ses-manila.yml, scripts/jenkins/ardana/ansible/deploy-cloud.yml, scripts/jenkins/ardana/ansible/roles/ses_cloud_integration/tasks/main.yml, scripts/jenkins/ardana/ansible/roles/ses_cloud_integration/tasks/ses_configure_manila.yml, scripts/jenkins/ardana/ansible/roles/ses_configure/defaults/main.yml, scripts/jenkins/ardana/ansible/roles/ses_configure/tasks/configure_manila.yml
This change adds a playbook for configuring a CephFS native backend for manila.
This playbook is called by cloud-deploy.yml after the cloud is deployed
whenever SES and manila are enabled.
This enable us to run tempest tests for manila without prior manual
configuration.
=> openstack-ardana: configure CephFS backend for manila

scripts/jenkins/ardana/ansible/bootstrap-crowbar.yml, scripts/jenkins/ardana/ansible/deploy-crowbar.yml, scripts/jenkins/ardana/ansible/group_vars/all/all.yml, scripts/jenkins/ardana/ansible/group_vars/all/crowbar.yml, scripts/jenkins/ardana/ansible/install-crowbar.yml, scripts/jenkins/ardana/ansible/register-crowbar-nodes.yml, scripts/jenkins/ardana/ansible/roles/crowbar_update/Readme.md, scripts/jenkins/ardana/ansible/roles/crowbar_update/defaults/main.yml, scripts/jenkins/ardana/ansible/roles/crowbar_update/tasks/add_mu_repos_crowbar.yml, scripts/jenkins/ardana/ansible/roles/crowbar_update/tasks/main.yml, scripts/jenkins/ardana/ansible/roles/reboot_node/README.md, scripts/jenkins/ardana/ansible/roles/reboot_node/defaults/main.yml, scripts/jenkins/ardana/ansible/roles/reboot_node/tasks/main.yml, scripts/jenkins/ardana/ansible/roles/reboot_node/tasks/reboot_cloud_nodes_crowbar.yml, scripts/jenkins/ardana/ansible/roles/reboot_node/tasks/reboot_deployer.yml, scripts/jenkins/ardana/ansible/roles/setup_zypper_repos/defaults/main.yml, scripts/jenkins/ardana/ansible/roles/setup_zypper_repos/tasks/set_motd.yml, scripts/jenkins/ardana/ansible/roles/setup_zypper_repos/tasks/setup_maint_update_repos.yml, scripts/jenkins/ardana/ansible/roles/setup_zypper_repos/templates/motd.j2
PR enables adding MU repositories and installation of MU patches before the deployment. Most of the code reused from Ardana part(`setup_zypper_repo` role). To make it work I had to slightly change role `setup_zypper_repos` and some variables.
New roles has been created:
* crowbar_update 
+ add repos on the cloud nodes
+ update nodes (currently this is missing and will be done as part of SOC-8465)
* reboot_node
+ reboot deployer (possible ardana+crowbar)
+ reboot nodes (currently only crowbar cloud nodes)
Repositories are added in steps:
* On admin `bootstrap-crowbar.yml`  (bootstrap admin node in jenkins)
* On nodes `register-crowbar-nodes.yml` (register nodes in jenkins)
Reboot is done in steps:
* On admin `install-crowbar.yml`
* On nodes `deploy-crowbar.yml`
Crowbar POC ci job: 
* with …
=> Crowbar ECP install MU before deployment

jenkins/ci.suse.de/cloud-heat.yaml, jenkins/ci.suse.de/pipelines/openstack-cloud-heat.Jenkinsfile, jenkins/ci.suse.de/templates/cloud-heat-template.yaml, scripts/jenkins/ardana/ansible/roles/heat_stack/defaults/main.yml, scripts/jenkins/ardana/ansible/roles/heat_stack/tasks/create.yml
The timeout used by heat when creating/deleting a heat stack is
configurable. The OpenStack heat API call (and consequently
the wrapping ansible playbook) will fail and exit if the heat
stack create or delete operation exceeds this timeout value,
and will not print any output during this time.
The Jenkins pipeline also uses a second, inactivity timeout
value (based on output lines being added to the Jenkins log),
in case something else goes wrong. The Jenkins job inactivity timeout
needs to account for the heat stack timeout (i.e. the value must
a little higher).
All this logic is in reality based on a single parameter - the heat
stack timeout - but the implementation so far used two independent
values. To add to the complexity, the supported ECP and SUSE cloud
platforms differ in …
=> openstack-cloud-heat: parameterized timeout

scripts/jenkins/ardana/ansible/roles/ardana_tempest/templates/run_filter_retry.txt.j2, scripts/jenkins/ardana/ansible/roles/ardana_tempest/templates/run_filter_retry_serial.txt.j2
Parse and include tearDownClass failures into the list of tempest tests
to rerun.
=> openstack-ardana: Fix tempest retry for tearDownClass failures

scripts/jenkins/ses/ansible/roles/ses/tasks/deepsea_setup.yml
Running the iscsi stage is not enough as other ceph services (mds,
rgw, ...) are not setup. Running the stage 4 again make sure those services
are setup.
=> openstack-ses: Rerun stage 4 (services) after iscsi workaround

scripts/qa_crowbarsetup.sh
The `read_write_two_vms` tests are known to fail because the share
doesn't cleanly unmount when it is shared to more than one vm[1], so
blacklist them. We also need to create the default share type with
snapshot support explicitly set, otherwise the snapshot tests will fail
with message "Snapshot cannot be created from share $id, because share
back end does not support it."
[1] https://bugzilla.suse.com/show_bug.cgi?id=1137262
This combined with https://review.opendev.org/662255 and https://review.opendev.org/664434 should fix the failing manila tests in the tempestfull job for cloud9.
=> manila: Fix tempest issues

.dir-locals.el
The argument should be a list.
=> Fix incorrect type in dir locals file

scripts/scenarios/cloud7/cloud7-5nodes-default.yml, scripts/scenarios/cloud8/cloud8-5nodes-default.yml, scripts/scenarios/cloud9/cloud9-5nodes-default.yml, scripts/scenarios/cloud9/cloud9-5nodes-ses.yml
Fix the swift configuration in the the 5 nodes HA scenarios used
with Crowbar ECP deployments to be aligned to the `crowbar` input
model generator scenario, which currently only features a swift
volume on the compute nodes.
NOTE: currently, all HA ECP Crowbar jobs are failing because the
swift-object role is associated with the controller nodes, but the
input model generated from the `crowbar` scenario associates
the `SWOBJ` service components with the compute nodes.
=> openstack-crowbar: fix swift HA scenarios

scripts/mkcloud
On many systems there's no virtualenv installed by default.
It is not available in standard repos so let's quickly install it from
IBS before trying to deploy VBMC.
=> Install virtualenv for vbmc where needed

scripts/jenkins/cloud/ansible/roles/ardana_update/defaults/main.yml, scripts/jenkins/cloud/ansible/roles/ardana_update/tasks/update_nodes.yml, scripts/jenkins/cloud/ansible/roles/ardana_update/tasks/update_services_parallel.yml, scripts/jenkins/cloud/ansible/roles/ardana_update/tasks/update_services_serial.yml
Although the documentation recommends running service updates serially,
for the CI we have been running service updates in parallel due to the
long time it takes to complete when running in serial (5h vs 9h).
However, during the testing of MUs for cloud 8, the update failed when
running in parallel (SOC-9524) and an option to run services update in
serial was needed.
=> openstack-ardana: add option to update services serially

scripts/jenkins/cloud/manual/requirements.txt
there have been several defects found with ansible 2.8.0 that make the manual deployment break. 
For, example The "synchronize" module used by the setup_zypper_repos role
does not behave well when using "delegate_to". I tries to use sshpass instead of ssh key authentication.
This causes a failure.
=> pining down ansible to a know working version 

scripts/mkcloud
As not all hosts have libvirt-devel, python-devel or even gcc
installed and all should have python-libvirt, let's use system-wide
python packages as part of the virtualenv created for vbmc.
This way we won't need to install gcc, devel packages and some other
compile-time dependencies when installing python-libvirt in virtualenv.
=> Use system-wide python-libvirt for vbmc

jenkins/ci.suse.de/cloud-ardana8.yaml, jenkins/ci.suse.de/cloud-ardana9.yaml
This change adds manila to the list of tempest tests that are executed
on the gating job for both cloud 8 and 9.
=> openstack-ardana: run manila tempest tests on gating jobs

scripts/jenkins/cloud/ansible/bootstrap-crowbar-nodes.yml, scripts/jenkins/cloud/ansible/bootstrap-vcloud-nodes.yml, scripts/jenkins/cloud/ansible/register-crowbar-nodes.yml
The `delegate_to` does not apply to dynamically included roles and
since Ansible 2.8 this construct throws an error. Instead the `apply`
argument should be used to specify the delegate_to host. For details
see the discussion at [1].
[1] https://github.com/ansible/ansible/issues/35398
=> Update `delegate_to` for Ansible 2.8

scripts/jenkins/cloud/manual/lib.sh
Using an input.yml file extracted from one of the Jenkins
jobs to run steps locally has an issue when the `os_project_name`
variable isn't set.
=> Fix project name in unified test automation local runner

jenkins/ci.suse.de/cloud-socok8s.yaml, jenkins/ci.suse.de/pipelines/socok8s-airship-from-rpm.Jenkinsfile, jenkins/ci.suse.de/templates/cloud-socok8s-integration.yaml
This tests the socok8s project from RPM rather than from source. As we
are testing an RPM, rather than installing it onto the host worker,
install into and operate it from a podman container.
This job requires the jenkins worker to be set up with podman. This has
already been done manually for the cloud-ccp-ci node.
=> Add periodic socok8s airship from rpm job

scripts/jenkins/cloud/ansible/bootstrap-crowbar.yml
The task to remove comments in the authorized keys file breaks
the idempotency of [1]. Since https://github.com/crowbar/crowbar/pull/2371 [2] is merged for all Crowbar
versions, we can safely remove it now.
[1] https://github.com/SUSE-Cloud/automation/blob/master/scripts/jenkins/cloud/ansible/roles/ssh_keys/tasks/main.yml#L18
[2] https://github.com/crowbar/crowbar/pull/2371
=> Remove obsoleted task

jenkins/ci.suse.de/cloud-ardana8.yaml, jenkins/ci.suse.de/cloud-ardana9.yaml
Some tempest manila tests are failing due to a known bug (SOC-9553),
this change remove manila from the tests ran on the gate update
job for cloud 8 and 9 until the issue is fixed.
=> openstack-ardana: remove manila tests from gate update jobs

scripts/maintenance-status/maintenance-status.rb
Use the project ID to set status as we have only the project id when
this is running in the CI. This safes some extra effort to safe the
review number.
=> maintenance-status: Set status via project number

jenkins/ci.opensuse.org/openstack-repocheck.yaml, jenkins/ci.suse.de/cloud-mediacheck.yaml, jenkins/ci.suse.de/pipelines/openstack-ardana.Jenkinsfile, scripts/jenkins/cleanvm/openstack-cleanvm.builder.sh, scripts/jenkins/mkcloud/openstack-mkcloud.builder.sh, scripts/jenkins/track-upstream-internal.sh, scripts/jenkins/track-upstream.sh
We used jtsync to trigger notifications and set the CI status on
trello cards. This process is no longer followed and creates noise
and maintenance effort. Let's kill jtsync in order to safe this.
=> Remove jtsync from the CI Jobs

scripts/jenkins/ses/ansible/roles/ses/tasks/openstack_config.yml
In CCP Tech preview, we noticed that /etc/ceph/ceph.conf can have
mon_host and mon_initial_members field values with spaces in-between
with comma as delimiter. This was noticed in SAP installation where
multiple nodes were used as part of SES cluster.
Current logic cannot handle following situation. So updating logic
to handle cases, where it can have spaces in between e.g.
mon_host = 192.168.89.120, 192.168.89.121, 192.168.89.122
,192.168.89.123,192.168.89.124
Output should be
192.168.89.120,192.168.89.121,192.168.89.122,192.168.89.123,192.168.89.124
=> SES ceph conf with multiple nodes with spaces

Makefile, hostscripts/rpm-packaging/createproject.py, scripts/iscsictl.py, scripts/jenkins/cloud/gerrit/build_test_package.py, scripts/jenkins/cloud/gerrit/gerrit_handle_event.py, scripts/jenkins/cloud/gerrit/gerrit_merge.py, scripts/jenkins/cloud/gerrit/gerrit_review.py, scripts/jenkins/jenkins-job-pipeline-report.py, scripts/lib/libvirt/libvirt_setup.py
3 years ago we pinned flake8 to a specific version due to compatibility
issues. This seems to be fixed so let's update to the latest version.
=> Update Flake8 to the latest version

jenkins/ci.suse.de/openstack-ardana-gerrit-events.yaml, jenkins/ci.suse.de/pipelines/openstack-ardana-gerrit.Jenkinsfile, jenkins/ci.suse.de/pipelines/openstack-ardana-testbuild-gerrit.Jenkinsfile, jenkins/ci.suse.de/pipelines/openstack-ardana.Jenkinsfile, jenkins/ci.suse.de/pipelines/openstack-crowbar.Jenkinsfile, scripts/jenkins/cloud/ansible/roles/crowbar_setup/tasks/main.yml, scripts/jenkins/cloud/ansible/roles/heat-generator/library/generate_heat_model.py, scripts/jenkins/cloud/gerrit/build_test_package.py, scripts/jenkins/cloud/jenkins-helper.sh, scripts/jenkins/cloud/manual/lib.sh
Enables the unified CI jobs and the manual cloud deployment toolchain
to use python3 preferentially if available when running python scripts
and ansible playbooks.
NOTE: this step is required to switch to using python3 in the Jenkins agents
=> openstack-crowbar/ansible: python3 enablement

jenkins/ci.suse.de/cloud-jenkins-worker.yaml, jenkins/ci.suse.de/pipelines/cloud-jenkins-worker.Jenkinsfile, scripts/jenkins/workers/ansible.cfg, scripts/jenkins/workers/create-server.yml, scripts/jenkins/workers/group_vars/all.yml, scripts/jenkins/workers/group_vars/jenkins_workers.yml, scripts/jenkins/workers/inventory, scripts/jenkins/workers/jenkins-worker.yml, scripts/jenkins/workers/load-job-params.yml, scripts/jenkins/workers/roles/jenkins_worker/defaults/main.yml, scripts/jenkins/workers/roles/jenkins_worker/handlers/main.yml, scripts/jenkins/workers/roles/jenkins_worker/tasks/authorized_keys.yml, scripts/jenkins/workers/roles/jenkins_worker/tasks/configure_swarm_client.yml, scripts/jenkins/workers/roles/jenkins_worker/tasks/copy_files.yml, scripts/jenkins/workers/roles/jenkins_worker/tasks/install_packages.yml, scripts/jenkins/workers/roles/jenkins_worker/tasks/main.yml, scripts/jenkins/workers/roles/jenkins_worker/tasks/setup_venv.yml, scripts/jenkins/workers/roles/jenkins_worker/tasks/update.yml, scripts/jenkins/workers/roles/jenkins_worker/templates/motd.j2
The new cloud-jenkins-worker jenkins job can be used to create/maintain
new/existing jenkins workers which are connected to jenkins using the
jenkins-swarm-client.
The playbooks should be executed from an existing worker as it needs to
copy the credential files (available on the existing worker) to the new
nodes.
By default the mew worker(s) is/are created on the cloud-ci project using the
openSUSE-Leap15.1 image and should be ready to run any job from the
Cloud-CI.
=> Adds job/playbooks for creating new jenkins workers (SOC-4902)

scripts/qa_crowbarsetup.sh
It has been backported (hidden from users, but exposed
in CI and used in engcloud.prv.suse.net)
=> Deploy designate also for cloud8

.travis.yml
Since xenial sudo can be used by default. We don't have to call it out.
=> Travis Remove sudo: required

jenkins/ci.suse.de/pipelines/openstack-ardana.Jenkinsfile, jenkins/ci.suse.de/templates/cloud-ardana-job-gerrit-template.yaml, jenkins/ci.suse.de/templates/cloud-ardana-pipeline-template.yaml, scripts/jenkins/cloud/ansible/roles/ardana_deploy/tasks/main.yml, scripts/jenkins/cloud/ansible/roles/setup_zypper_repos/README.md, scripts/jenkins/cloud/ansible/roles/setup_zypper_repos/tasks/add_extra_repos.yml, scripts/jenkins/cloud/manual/input.yml.example
Instead of adding the extra repositories on the deployer node as a
zypper repository, create a new repository on the deployer and make
all RPMs from the extra repositories available to all cloud nodes by
setting up this repository on all nodes.
This new repository will be configure with higher priority, meaning that
all packages from the `extra_repos` will be installed even if there are
newer packages available on other repositories.
An easier way to do the same would be to use the PTF repository to provide
those packages, however we have decided to not use the PTF repository as we would be affecting the product if we create and set the priority of the PTF repository which is something done by ardana itself.
https://jira.suse.com/browse/SOC-7800
=> openstack-ardana: make packages from extra-repos available to all nodes

scripts/jenkins/cloud/gerrit/gerrit.py
Fixes a python3 error affecting the Gerrit CI, which is now running
python 3.
=> openstack-ardana-gerrit: fix python3 error

scripts/jenkins/cloud/ansible/roles/input_model_generator/tasks/main.yml
Using a bare variable for conditionals is deprecated starting with
Ansible 2.8 and will eventually be removed. This means that the string
'false' will not get evaluated as `false` anymore. To retain the old
behavior, add an explicit `bool` filter.
=> Cast bare variable to `bool`

jenkins/ci.suse.de/templates/cloud-jenkins-worker-template.yaml, scripts/jenkins/workers/roles/jenkins_worker/defaults/main.yml, scripts/jenkins/workers/roles/jenkins_worker/tasks/update.yml
Reboot the node only if the `jenkins_worker_reboot` parameter is set to
true (defaults to false).
=> jenkins-workers: make reboot optional

scripts/jenkins/gitlint.ini
The author of a commit should make a conscious decision to either add a
reference or not. Adding trivial instead of bsc or SOC enables this.
This change prevents that adding a refernce is forgotten as the
syntax requires to think about it.
See #3509 for more details.
=> gitlint: Allow trivial changes to be without reference (SOC-9559)

Makefile, scripts/jenkins/workers/roles/jenkins_worker/files/gitconfig, scripts/jenkins/workers/roles/jenkins_worker/tasks/configure_git.yml, scripts/jenkins/workers/roles/jenkins_worker/tasks/main.yml
Otherwise git merge will fail with:
```
fatal: unable to auto-detect email address
(got 'jenkins@cloud-jenkins-worker-ci.(none)')
```
=> Configure git email for jenkins workers

scripts/maintenance-status/maintenance-status.rb
In case there is no request the script should not fail to post a
message.
=> maintenance-status: Don't fail if there is no open request

jenkins/ci.opensuse.org/openstack-trackupstream.yaml
We added openstack-horizon-plugin-heat-ui with the Rocky
release. Since it was not needed for Openstack Pike, this
commit also contains a filter to exclude it from
Cloud:OpenStack:Pike:Staging trackupstream.
=> Add openstack-horizon-plugin-heat-ui to trackupstream

jenkins/ci.suse.de/cloud-maintenance-gating.yaml, jenkins/ci.suse.de/pipelines/cloud-gating-config.yml, jenkins/ci.suse.de/pipelines/openstack-cloud.groovy, jenkins/ci.suse.de/pipelines/openstack-maintenance-gating.Jenkinsfile, scripts/jenkins/cloud/ansible/deploy-crowbar.yml
Add Crowbar jobs to the set of jobs executed for a maintenance
update.
This commit switches the MU gating job implementation to use
a configuration yaml file listing the jobs and the parameters
that need to be launched for each cloud version rather than
hard-coding them in the groovy library.
This PR also includes another couple of fixes required to get the Crowbar
MU gating job to pass: 
- call onadmin_rebootcloud instead of relying on the reboot_node
ansible role when testing maintenance updates. The onadmin_rebootcloud
functionality from qa_crowbarsetup.sh has additional logic built
into it which ensures that controller nodes are rebooted correctly
when HA is enabled, whereas the reboot_node ansible role does not
(included from #3529)
- serializing the service update process for cloud …
=> openstack-maintenance-gating: add crowbar deploy jobs (SOC-9599,SOC-9669)

hostscripts/zuul/layout.yaml
Commit 3f1b9da50bc started to fix the used distro names for Master and
Stein but this commit was incomplete. Hopefully it works now.
=> rpm-packaging: Fix zuul layout

hostscripts/clouddata/syncSLErepos
It seems there is some concern/rumour that the Cloud 8 medias
are not syncing fast enough for proper Ardana development. While
its unclear what the problem is, we can make it more predictable
by syncing them directly.
=> Always sync the Ardana media directly from NBG

jenkins/ci.suse.de/cloud-maintenance-gating.yaml, jenkins/ci.suse.de/pipelines/openstack-cloud.groovy, jenkins/ci.suse.de/pipelines/openstack-maintenance-gating.Jenkinsfile
Add the ability to select a subset of the applicable jobs that are
launched by the maintenance update gating job to test a maintenance
update. This feature is useful when re-running only the jobs that
have failed during a previous run for a maintenance update e.g.
for environmental reasons.
=> cloud-maintenance-gating: add job filter

scripts/jenkins/cloud/ansible/deploy-crowbar.yml, scripts/jenkins/cloud/ansible/group_vars/all/all.yml
Make rebooting the cloud nodes after deploying the cloud
configurable via an ansible global variable, `reboot_after_deploy`,
set to False by default.
=> openstack-crowbar: make reboot after deploy optional

scripts/mkcloud
VirtualBMC is packaged already but only present in Cloud9 repo.
If possible, it's better to install this package instead of creating
virtualenv and pulling virtualbmc via pip.
Alternative to https://github.com/SUSE-Cloud/automation/pull/3503
**NOTE**
**Adding Cloud9 repo will most likely cause some packages to be upgraded (e.g. python-cffi, python-cryptography, python-idna, python-six on the hosts I checked).
Some basic SP4 check was included to avoid adding the repo to hosts with different OS version.**
=> Install packaged vbmc instead of venv+pip

scripts/jenkins/cloud/ansible/roles/ssh_keys/tasks/main.yml, scripts/jenkins/cloud/ansible/setup-ssh-access.yml, scripts/jenkins/cloud/manual/input.yml.example
If the generated Heat stack uses a floating IP that was previously
used, the deploying host might have an outdated ssh host key which
should be removed prior to any ssh access.
=> Remove ssh host key of admin FIP

scripts/jenkins/cloud/ansible/roles/ssh_keys/defaults/main.yml, scripts/jenkins/cloud/ansible/roles/ssh_keys/tasks/main.yml
The ssh_keys role is failing as `local_ssh_key` is undefined. This change
sets a default value to `local_ssh_key` (false).
=> openstack-ardana: set default value for local_ssh_key

scripts/jenkins/cloud/ansible/roles/heat_stack/tasks/main.yml
Follow-up for #3488.
The code handling the old stack naming was only required to ensure
the old heat stacks are properly cleaned up.
NOTE: to be merged only after enough time (>1 week) has passed after
#3488 has landed and the old heat stacks have been cleaned up.
=> openstack-cloud-heat: remove code handling old stack names (SOC-8475)

scripts/jenkins/cloud/ansible/roles/tempest_results/tasks/main.yml
When there are tempest failures, the scripts that generate the
xml and html output also return non-zero exit codes. This causes
the tempest playbook to fail for Crowbar before it publishes
results.
=> openstack-crowbar: fix tempest result collection

scripts/jenkins/cloud/ansible/roles/input_model_generator/templates/barclamps/neutron.yml.j2
In the released crowbar cloud 7 and 9 neutron barclamp we
don't yet have the `l3_ha` option available. Excluding it
from the generated barclamp configuration to avoid errors
while deploying GM8+up and GM7+up.
=> openstack-crowbar: don't set use_l3_ha unless required

scripts/jenkins/ses/ansible/roles/heat_ses_template/templates/heat-template.yml.j2
Before associating the FIP to the server we need to make sure the
SES subnet is connected to the external router.
=> openstack-ses: FIP association depends on router interface

scripts/qa_crowbarsetup.sh
If $want_horizon_proposal = 0 then mkcloud was failing while trying
to rename horizon node to 'dashboard'.
=> Don't try to rename non-existing horizon

scripts/iscsictl.py, scripts/jenkins/cloud/ansible/install-crowbar.yml, scripts/qa_crowbarsetup.sh
Rebooting the admin node in an SBD enabled HA Crowbar setup had
issues with the shared iSCSI volume, because the iSCSI configuration
wasn't persisted on the admin node.
The `tcm_dump --b` parameter expects an value of 1 if the default
configuration is to be overwritten [1]. Our `iscsictl.py` script
was using an incorrect value of `OVERWRITE`, which had no effect.
However, supplying `tcm_dump --b=1` overwrites the `/etc/target/tcm_start.sh`
and `/etc/target/lio_start.sh` files [2], which the `ilo-utils` package
pre-installs with some useful commands such as loading required modules,
so we can't use that either.
As it turns out, the `target.service` unit already has support for
persisting the configuration [3]. All we have to do is restart the
service after completing the configuration.
[1] …
=> iscsictl.py: fix SBD persistence issues (SOC-9821)

jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-6a.yaml, scripts/qa_crowbarsetup.sh
When deploying a crowbar batch scenario that includes magnum,
the service image and flavors also need to set up.
This is currently only done with the standard, non-batch way of
deploying Crowbar.
=> qa_crowbarsetup.sh: setup magnum service in batch mode

scripts/jenkins/cloud/ansible/roles/heat-generator/templates/heat-template.yaml
The fixed IP assignment on IPv6 requires the `dhcpv6-stateful` setting
on the management subnet.
=> Add the correct IPv6 settings to the management subnet

scripts/mkcloud
This is just a small feature for simplifying manual testing of upgrade.
In normal upgrade scenarios, repos need to be prepared and updated by the
user. Exposing the "prepare" functions already present in mkcloud enables
developers to use these instead of various hacks (e.g. local modifications
to mkcloud) that were done in the past.
=> Add prepareupgraderepos step

scripts/jenkins/cloud/ansible/roles/input_model_generator/templates/barclamps/magnum.yml.j2, scripts/jenkins/cloud/ansible/roles/input_model_generator/templates/barclamps/sahara.yml.j2
The barclamps generated for magnum and sahara do not include
setting the protocol to https when SSL is enabled.
=> openstack-crowbar: enable SSL for magnum & sahara

scripts/jenkins/cloud/ansible/roles/input_model_generator/templates/barclamps/magnum.yml.j2, scripts/jenkins/cloud/ansible/roles/input_model_generator/templates/barclamps/sahara.yml.j2
Reverts SUSE-Cloud/automation#3556
SSL support for sahara/magnum doesn't seem to be complete...
=> Revert "openstack-crowbar: enable SSL for magnum & sahara"

jenkins/ci.suse.de/cloud-maintenance-gating.yaml
The maintenance-slot is nowadys used for ardana and crowbar so let's
change the label to reflect this change.
=> jenkins: Rename cloud-ardana-maintenance-slot to cloud-maintenance-slot

jenkins/ci.suse.de/pipelines/openstack-crowbar.Jenkinsfile, jenkins/ci.suse.de/templates/cloud-crowbar-pipeline-template.yaml, scripts/jenkins/cloud/ansible/_create-vcloud-inventory.yml, scripts/jenkins/cloud/ansible/bootstrap-crowbar-nodes.yml, scripts/jenkins/cloud/ansible/bootstrap-crowbar.yml, scripts/jenkins/cloud/ansible/bootstrap-vcloud-nodes.yml, scripts/jenkins/cloud/ansible/crowbar-update.yml, scripts/jenkins/cloud/ansible/deploy-crowbar.yml, scripts/jenkins/cloud/ansible/group_vars/all/all.yml, scripts/jenkins/cloud/ansible/register-crowbar-nodes.yml, scripts/jenkins/cloud/ansible/roles/crowbar_setup/tasks/main.yml, scripts/jenkins/cloud/ansible/roles/crowbar_update/defaults/main.yml, scripts/jenkins/cloud/ansible/roles/crowbar_update/tasks/add_mu_repos_crowbar.yml, scripts/jenkins/cloud/ansible/roles/crowbar_update/tasks/main.yml, scripts/jenkins/cloud/ansible/roles/crowbar_update/tasks/update_cloud.yml, scripts/jenkins/cloud/manual/input.yml.example, scripts/jenkins/cloud/manual/lib.sh
Extends the crowbar ECP test automation with support to set up
maintenance updates and update a predeployed cloud.
Similar to Ardana, this is controlled by a `update_after_deploy`
parameter.
=> crowbar-openstack: support updating a deployed cloud with MUs (SOC-8465)

jenkins/ci.suse.de/cloud-ardana8.yaml, jenkins/ci.suse.de/cloud-ardana9.yaml, jenkins/ci.suse.de/cloud-maintenance-gating.yaml, jenkins/ci.suse.de/cloud-maintenance.yaml, jenkins/ci.suse.de/pipelines/cloud-maintenance-gating-config.yml, jenkins/ci.suse.de/pipelines/cloud-maintenance-gating.Jenkinsfile
Adds the "deploy-and-update" Crowbar scenarios to the list of scenarios
used to test maintenance updates.
This PR also creates dedicated jobs for the various scenario used to test
maintenance updates, to have an individual build history for each scenario.  
NOTE: depends on #3553
=>  maintenance gating: add Crowbar update jobs to maintenance gating (SOC-9797,SOC-9798)

jenkins/ci.suse.de/templates/cloud-gating-template.yaml, jenkins/ci.suse.de/templates/cloud-heat-template.yaml, jenkins/ci.suse.de/templates/cloud-image-update-template.yaml, scripts/jenkins/cloud/manual/input.yml.example
The `cloud_env` value is reflected into the hostnames set up
for the cloud nodes, so we must prevent underscore characters
from being part of it because they are not allowed to be part
of a hostname value [1].
[1] https://www.ietf.org/rfc/rfc952.txt - B. Lexical grammar
=> openstack-crowbar/ardana: prevent underscores in cloud_env

jenkins/ci.suse.de/templates/cloud-ardana-pipeline-template.yaml, jenkins/ci.suse.de/templates/cloud-crowbar-pipeline-template.yaml
Allow the `extra_params` parameter, as well as other params from
the openstack-crowbar and openstack-ardana pipelines to be customized
for individual jobs, such as the ones used for maintenance update
gating.
=> cloud-maintenance: fix extra_params override

hostscripts/rpm-packaging/createproject.py
With the newer osc release, osc rm on an empty file no longer
silently succeeds but it fails with:
'openstack-nova-cells.service' has local modifications (use --force to remove this file)
So we need to use the force, Luke.
=> createproject: handle newer osc release

scripts/lib/libvirt/compute-config, scripts/lib/libvirt/libvirt_setup.py, scripts/lib/libvirt/templates/compute-node.xml, scripts/lib/libvirt/templates/cpu-intel-pcipassthrough.xml, scripts/lib/libvirt/templates/iommu-device-default.xml, scripts/lib/libvirt/templates/pcie-root-bridge-default.xml, scripts/lib/mkcloud-driver-libvirt.sh, scripts/mkcloud
Add mocked disk device to test pci passthrough
We need q35 as the machine type in order to support IOMMU and
tweaking pcie controllers to place our virtio device properly.
1. Modify node config to accommodate iommu related section
2. Modify libvirt modification for pci passthru
3. Add pci passthru related node template
4. Expose option want_pci_passthrough
=> Add mocked disk device to test pci passthrough

scripts/jenkins/cloud/ansible/roles/ssh_keys/tasks/main.yml
The local ssh key needs to be added to the home directory of the user
running the Ansible playbook.
=> Create the local ssh key in the right directory

jenkins/ci.suse.de/pipelines/cloud-maintenance-gating.Jenkinsfile
Keep the maintenance update gating cloud environments even after
a job successfully tests a maintenance update.
=> cloud-maintenance-gating: keep environments after job success

scripts/jenkins/cloud/ansible/roles/setup_zypper_repos/defaults/main.yml, scripts/jenkins/cloud/ansible/roles/setup_zypper_repos/tasks/setup_maint_update_repos.yml
Adds the missing definitions for Cloud 7 and SLES12_SP2 and
fixes `cloud_repo_path` in `setup_zypper_repos` to handle Crowbar
SOC7 maintenance updates.
=> openstack-crowbar: support SOC7 maintenance updates (SOC-9887)

jenkins/ci.suse.de/cloud-ardana8.yaml, jenkins/ci.suse.de/cloud-ardana9.yaml, jenkins/ci.suse.de/cloud-gating.yaml, jenkins/ci.suse.de/pipelines/cloud-gating-config.yml, jenkins/ci.suse.de/pipelines/cloud-gating.Jenkinsfile, jenkins/ci.suse.de/templates/cloud-gating-template.yaml
Align the cloud (staging) gating job to the cloud maintenance
update gating job by doing the following:
- use dedicated Jenkins jobs that preserve the build history
independently from other builds, along with a distinct naming
scheme identifying the jobs as being used by gating
- use a yaml configuration file to list the sub-jobs that are
triggered by the gating job
=> cloud-gating: configurable and dedicated jobs

scripts/qa_crowbarsetup.sh
When looking at the scrubber.log we also search for errors unrelated to
this glance-scrubber run. As the glance-scrubber service runs regularly
it can happen that e.g. keystone is not available at a previous run. In
the gate glance-scrubber regularly runs when apache is restarted so a
ERROR is reported.
=> qa_crowbarsetup: Use separate glance scrubber log (SOC-9929)

jenkins/ci.suse.de/cloud-gating.yaml
Some older versions of JJB don't handle JJB template parameter
integer values properly. Using string values instead helps to
avoid problems.
=> cloud-update-ci: use string instead of integers for version

scripts/qa_crowbarsetup.sh
Cloud8 CI jobs were failing with:
"Requested API version 1.9 is not supported by the server or the
requested operation is not supported by the requested version."
Overriding client API version with latest (negotiated) one should
solve the problem.
=> ironic: Set API version in Cloud8

scripts/jenkins/cloud/ansible/roles/reboot_node/tasks/reboot_deployer.yml
The cloud_reboot ansible code also includes a task that waits
until the crowbar service is coming back up after reboot.
It wasn't running for SOC7 deployments because the zypper
repository is named differently (i.e. doesn't have `Crowbar`
in its name).
This commit is switching to using the `cloud_product` ansible
variable to correct this issue.
NOTE: this fixes issues with the SOC7 Crowbar ECP reboot
(e.g. [this](https://ci.suse.de/blue/organizations/jenkins/cloud-crowbar7-job-mu-ha-update-x86_64/detail/cloud-crowbar7-job-mu-ha-update-x86_64/8/pipeline/) build)
=> openstack-crowbar: handle admin node reboot in SOC7 (SOC-9887)

scripts/iscsictl.py
There is no clear execution order dependency between
`/etc/rc.d/boot.local` and the startup of the target service,
which leads to situations in which the target service starts
before the loop device has had a chance to be properly set up.
Moving the setup of the loop device to the target service startup
script ensures that the commands setting up the ISCSI device used
for SBD are executed in the correct order.
=> iscsictl.py: setup loop device before target service start (SOC-9821)

.travis.yml, jenkins/ci.suse.de/pipelines/cloud-gating.Jenkinsfile, jenkins/ci.suse.de/pipelines/cloud-maintenance-gating.Jenkinsfile
Re-add the ability to pass parameters value overrides through
the `extra_params` parameter in the `cloud-8|9-gating` and
`cloud-maintenance-gating` jobs.
This ability was removed when these jobs were migrated to use
a yaml configuration file listing the jobs they must trigger.
=> cloud-gating: re-add extra_params support

scripts/jenkins/cloud/ansible/roles/setup_zypper_repos/tasks/main.yml
Crowbar deployment leaves handling `extra_repos` on qa_crowbar_setup.sh in `addupdaterepo` step.
Reference failed ci job:
https://ci.suse.de/blue/organizations/jenkins/cloud-crowbar7-job-mu-ha-deploy-x86_64/detail/cloud-crowbar7-job-mu-ha-deploy-x86_64/18/pipeline#step-71-log-279
from manual run with the fix:
```
host-192-168-124-10:~ # zypper se -s | grep crowbar-openstack
i  | crowbar-openstack                                 | package     | 4.0+git.1562759922.43761a6ac-0           | noarch | cloud-ptf               
v  | crowbar-openstack                                 | package     | 5.0+git.1559335140.62bb4c014-4.25.1      | noarch | cloudmaintup            
v  | crowbar-openstack                                 | package     | 5.0+git.1554709170.195ba0e26-4.22.2      | noarch | …
```
=> openstack-crowbar: do not handle extra_repos via bootstrap-crowbar.yml (SOC-9296)

scripts/jenkins/cloud/ansible/roles/ardana_update/tasks/update_services_serial.yml
The test automation scripts that implement the maintenance update
workflow for Ardana run the `ardana-deploy.yml` playbook serially
on every node, starting with the deployer. It does this by using
the `--limit` ansible parameter to limit the host where that
playbook runs. However, tempest is special, because it also creates
virtual ansible hosts which it then uses as a target for some of
the ansible tasks that update tempest configuration.
For that reason, we need to include those virtual hosts when we
run the `ardana-update.yml` playbook limited to the deployer node,
otherwise the tempest configuration doesn't get updated.
=> openstack-ardana: update tempest correctly (SOC-9296)

jenkins/ci.opensuse.org/openstack-prepare-staging.py
The osc package on the trackupstream Jenkins node for ci.opensuse.org
was switched to python3. Do the same in the script that imports osc
modules, to make it work again.
=> follow switch to python3 of osc on trackupstream

jenkins/ci.suse.de/cloud-gating.yaml
The `update_to_cloudsource` parameter was not set for these jobs,
which means the staging media was not installed and no updates
were actually performed.
This commit also re-adds manila to the Ardana deploy gating jobs.
=> cloud-gate: fix deploy-and-update Ardana gating jobs

scripts/jenkins/cloud/ansible/roles/ardana_tempest/templates/run_filter_retry.txt.j2, scripts/jenkins/cloud/ansible/roles/ardana_tempest/templates/run_filter_retry_serial.txt.j2
Re-running teardown failed tests causes it to re-run all set of tests
part of the teardown class.
=> openstack-ardana: do not rerun teardown failed tempest tests

jenkins/ci.suse.de/cloud-gating.yaml, jenkins/ci.suse.de/cloud-maintenance.yaml, jenkins/ci.suse.de/pipelines/cloud-gating.Jenkinsfile, jenkins/ci.suse.de/pipelines/cloud-maintenance-gating.Jenkinsfile, jenkins/ci.suse.de/templates/cloud-ardana-pipeline-template.yaml, jenkins/ci.suse.de/templates/cloud-crowbar-pipeline-template.yaml
This commit attempts to improve the way `extra_params` are
handled in the gating jobs (both staging and maintenance),
by doing the following:
- avoid setting `extra_params` in downstream jobs, because
those will be overwritten if `extra_params` are set in the
gating jobs. Instead, use hidden parameters to avoid cluttering
the jobs unnecessarily
- combine the `extra_params` set in the gating jobs with those
loaded from the job yaml configuration file and, if the result
is not empty, use that when triggering downstream jobs
=> cloud-gating: better handling for extra_params

jenkins/ci.suse.de/cloud-gating.yaml, jenkins/ci.suse.de/cloud-maintenance.yaml
Use string values instead of boolean with hidden parameters,
because some older JJB versions don't know how handle that.
=> cloud-gating: fix JJB failures with older JJB

scripts/maintenance-status/maintenance-status.rb
MU reviews requests have two states one for the specific group and one
for the overall status. We need to filter both.
=> maintenance-status: Limit search results to open reviews

jenkins/ci.suse.de/pipelines/openstack-ardana.Jenkinsfile, jenkins/ci.suse.de/pipelines/openstack-cloud.groovy, jenkins/ci.suse.de/pipelines/openstack-crowbar.Jenkinsfile
The Jenkins pipeline check recently implemented to prevent manually
triggered jobs from using environments regulated through lockable
resource slots doesn't take into account periodic jobs, which
have no upstream job and still reserve a lockable resource.
=> openstack-crowbar/ardana: allow periodic jobs to use lockable resources

scripts/mkcloud
Some hosts have openstack-mkcloud jobs running as non-root user.
To enable virtualbmc setup, sudo needs to be used there.
=> ironic: Use sudo for vbmc setup

jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-ironic-agent-template.yaml, jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-ironic-template.yaml
Ironic tests never use more than one node so it doesn't make much
sense to deploy two.
=> ironic: Deploy only one ironic node

scripts/qa_crowbarsetup.sh
When something fails during ironic testing, test env teardown will
try to delete the nodes. Node list can contains some important info
so lets print it before starting the cleanup.
=> ironic: List nodes before delete

jenkins/ci.opensuse.org/openstack-prepare-staging.py
Relevant part of the Traceback:
```
20:22:33   File "/tmp/jenkins4695678436363115016.sh", line 32, in get_package_results
20:22:33     *args, **kwargs))
20:22:33 TypeError: sequence item 0: expected str instance, bytes found
```
=> handle strings correctly upon switch to py3

scripts/mkcloud, scripts/qa_crowbarsetup.sh
Direct deploy interface is not available if Swift is not deployed.
For this cases, iscsi interface should be used.
=> ironic: Use direct deploy interface only with Swift

jenkins/ci.suse.de/cloud-crowbar9.yaml, jenkins/ci.suse.de/templates/cloud-crowbar-pipeline-template.yaml, scripts/jenkins/cloud/ansible/group_vars/all/crowbar.yml, scripts/jenkins/cloud/ansible/install-crowbar.yml
The cloud-crowbar9-job-ha-x86_64 job has been occasionally failing due
to timeouts. This change increase the timeout multiplier for the cloud 9
jobs  as a way to avoid those issues.
=> crowbar: Increase sync_mark timeout multiplier for cloud 9 (SOC-10009)

scripts/jenkins/cloud/ansible/roles/cloud_generator/defaults/main.yml, scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/input_model/data/disk_models.yml, scripts/jenkins/cloud/ansible/roles/heat-generator/defaults/main.yml
Minimize the amount of virtual storage required by the CLM and
Crowbar virtual deployments by making the following changes to
the cloud generator and heat generator components:
- move all CLM services to the root partition by default instead
of using dedicated volumes for database/rabbitmq, LMM, cinder and
glance. This should also add to the overall performance of the
deployed cloud, e.g. because LMM services will no longer use
a volume implemented using the Ceph back-end, which has a higher
latency then the root partition, which uses the ephemeral volume
located on the underlying OpenStack compute node.
- reduce the default size of the remaining Ceph volumes from 20 GB to
2 GB. The only remaining service that still uses Ceph volumes is
Swift, which doesn't really need 20 GB of storage …
=> openstack-ardana/crowbar: minimize virtual storage requirements

jenkins/ci.suse.de/pipelines/cloud-gating.Jenkinsfile, jenkins/ci.suse.de/pipelines/cloud-maintenance-gating.Jenkinsfile
Implement additional checks in the maintenance and staging gating
job:
- always check that there's at least one downstream job found
in the job configuration that corresponds to the affected cloud
version(s), to avoid validating the staging media or maintenance
update without actually running any tests
- address the use-case when a maintenance update has already
been released
=> cloud-maintenance-gating: implement additional checks

jenkins/ci.suse.de/cloud-crowbar9.yaml, jenkins/ci.suse.de/templates/cloud-crowbar-pipeline-template.yaml, scripts/jenkins/cloud/ansible/install-crowbar.yml, scripts/jenkins/cloud/manual/input.yml.example
Recent ECP HA Crowbar builds failing due to pacemaker sync mark
issues have confirmed that the problem is generalized to all
Crowbar versions. The issues occur because one or more virtual
controller nodes are slower due to environmental issues, such as
running on a crowded ECP compute node.
Increasing the sync mark timeout multiplier to 2.0 only for Crowbar
version 9 jobs yielded good results. This commit promotes the 1.5
value as the default timeout multiplier value used with all Crowbar
jobs.
The sync mark multiplier feature hasn't yet been officially released
for Crowbar cloud 7 and 8, therefore setting `sync_mark_timeout_multiplier`
to a value other than the default 1.0 will fail when testing maintenance
updates for SLES12_SP2 and SLES12_SP3.
This PR also introduces a check to …
=> openstack-crowbar: increase sync_mark_timeout_multiplier to 1.5 globally (SOC-10009)

jenkins/ci.suse.de/pipelines/openstack-ardana.Jenkinsfile, jenkins/ci.suse.de/pipelines/openstack-cloud.groovy, jenkins/ci.suse.de/pipelines/openstack-crowbar.Jenkinsfile, scripts/jenkins/cloud/ansible/report-job-failure.yml, scripts/jenkins/cloud/ansible/roles/jira_issue_report/defaults/main.yml, scripts/jenkins/cloud/ansible/roles/jira_issue_report/tasks/main.yml
Keeping track of the known issues related to failures on the cloud
jenkins jobs is kinda hard (nowadays there are many jenkins jobs
crowbar/ardana/7/8/9, sometimes it is not easy to reproduce the
issue and we think the issue was fixed, there is already a ticket opened
for the issue and another one is created...).
This change makes keeping track of those failures easier by
automatically commenting on the existing jira card whenever a know issue
happens. It also edit the job description with the link of the known
jira cards related to job failure (if there is any).
=> Report known jenkins job failures to its Jira card

scripts/jenkins/cloud/ansible/install-crowbar.yml
The sync_mark_timeout_multiplier ansible variable needs to be
converted to float before it is dumped into the data bag.
=> openstack-crowbar: fix sync_mark_timeout_multiplier type

scripts/qa_crowbarsetup.sh
With SSL enabled it requires a bit more time to resolve the horizon
page. This change adds 1 minute to the current timeout (2 minutes).
=> openstack-crowbar: increase simple horizon test timeout (SOC-10011)

scripts/jenkins/cloud/ansible/roles/ses_cloud_integration/tasks/ses_configure_v2.yml
The cloud deployments are occasionally failing due to a timeout during
the openstack.integrate call. The default timeout is 30 seconds, however
sometimes the task takes around 40 seconds to conclude. This change
increases the timeout to 60 seconds to be on the safe side.
=> openstack-crowbar/ardana: Increase openstack.integrate call timeout

scripts/jenkins/cloud/ansible/roles/ardana_tempest/templates/run_filter_retry.txt.j2, scripts/jenkins/cloud/ansible/roles/ardana_tempest/templates/run_filter_retry_serial.txt.j2
Reverting this change as if we do not re-run the teardown failures it will report as the test as failed anyways. Better give it another chance just like we do for the other cases.
=> Revert "openstack-ardana: do not rerun teardown failed tempest tests"

jenkins/ci.opensuse.org/socok8s-trackupstream.yaml, scripts/jenkins/track-upstream.sh
Similar to openstack-trackupstream and cloud-trackupstream, a new job
called soco-trackupstream is added.
This job will periodically update the Cloud:socok8s:master/socok8s RPM
package from the git source defined in the _service file.
This is needed to get an updated ISO with the latest socok8s code on a
daily base.
=> Add socok8s-trackupstream job

scripts/jenkins/track-upstream.sh
Commit b69ab8de43da introduced a socok8s-trackupstream job. The commit
was incomplete. Currently the jobs fails because the packages in
Cloud:socok8s:master are not links. This is now fixed.
=> Fix socok8s-trackupstream job

scripts/jenkins/cloud/ansible/group_vars/virt_all.yml
Due to the limitations of virtual deployments some operations takes
logger to be processed resulting in erros such as `MessagingTimeout:
Timed out waiting for a reply to message ID
2ecfb7e8756f41d99920052fd768bd88` which is ocasionally making some tests
fail.
This change increases the rpc response timeout of the nova service from
60 seconds to 90 seconds. This change is expected to fix numeral tests
failures related to octavia.
=> openstack-ardana: Increase rpc response timeout on virtual deployments (SOC-9285)

scripts/jenkins/cloud/ansible/roles/cloud_generator/README.md, scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/barclamps/lib/common.yml.j2, scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/scenario.yml.j2
Restrict generating pacemaker barclamps for clusters that are
associated with at least one barclamp role that can be clustered.
This fixes the mid-scale-kvm scenario, which was generating an
additional pacemaker barclamp for the swift-storage nodes.
=> cloud-generator: restrict generated pacemaker barclamps

jenkins/ci.suse.de/cloud-gating.yaml, scripts/jenkins/cloud/ansible/roles/crowbar_register/tasks/main.yml
This change enable running tempest with all filters available on the
cloud 9 gating jobs.
This change also configures the jobs to build on daily basis to evaluate
its stability before adding those jobs to the gating job. 
This change also increase the number of retries on checking the crowbar register operation. It seems like it was not enough as some jobs had failed because of it.
=> openstack-crowbar: run tempest on cloud 9 gating jobs (SOC-10029)

scripts/jenkins/cloud/ansible/group_vars/virt_all.yml
The monasca role chooses the tuning setting based on how much memory the
system has, meaning that for virtual deployments it is using the `demo`
setting [1]. However `monasca-thresh` is occasionally hanging during
start/stop and there is a suspicion that his happens due to the lack of
memory allocated to it.
This change override the monasca tuning parameter to use the `small`
setting. This will enable storm to use more memory (from 64 to 128 MB)
and probably fixes SOC-10145. Previous tests were made and SOC-10145 was
not reproducible when using the `small` setting (3 deployments).
1. http://git.suse.provo.cloud/cgit/ardana/monasca-ansible/tree/roles/monasca-variables/vars/configuration.yml#n48
=> openstack-ardana: Set monasca tuning config to small (SOC-10145)

scripts/jenkins/cloud/ansible/run-crowbar-tests.yml, scripts/mkcloud, scripts/qa_crowbarsetup.sh
The simple horizon test occasionally fails and there is no way to debug
it without knowing what the curl is returning.
=> openstack-crowbar: log simple horizon test curl output (SOC-10011)

jenkins/ci.suse.de/cloud-gating.yaml
The slots needs to be reserved or the jobs will not use the proper slot.
=> openstack-crowbar: reserve slots for cloud9 gate jobs

scripts/jenkins/cloud/ansible/roles/cloud_generator/vars/entry-scale-kvm-mml.yml, scripts/jenkins/cloud/ansible/roles/cloud_generator/vars/entry-scale-kvm.yml, scripts/jenkins/cloud/ansible/roles/cloud_generator/vars/mid-scale-kvm.yml, scripts/jenkins/cloud/ansible/roles/cloud_generator/vars/std-lmm.yml, scripts/jenkins/cloud/ansible/roles/cloud_generator/vars/std-split.yml
Extend the Crowbar networking mode support to other cloud generator
scenarios (previously only supported by the standard scenario)
=> openstack-crowbar: fix networking mode

scripts/jenkins/cloud/ansible/roles/heat-generator/templates/heat-template.yaml
As a workaround for SOC-10184, use a `uses-nested-virt`
tag to label compute node VMs, indicating that compute nodes
should not be live-migrated because this operation breaks
nested virtualization.
This tag should be used by the underlying engineering cloud
maintenance scripts to determine if a VM can be live-migrated.
=> heat-generator: tag servers (SOC-10184)

scripts/jenkins/cloud/ansible/roles/tempest_results/tasks/main.yml
If the Test Cloud step fails before running tempest the job fails with
undefined variable error when trying to get the tempest results. This
change fixes that by adding a condition to only check for tempest
results when the variable is defined which means that tempest did run.
=> openstack-crowbar: Fix tempest_results role

scripts/qa_crowbarsetup.sh
wget(1) was incorrectly recurising into the ../repo tree which
occaussionally errors out with:
HTTP request sent, awaiting response... 500 Internal Server Error
Since it wasn't specifically supposed to go there, we just need
to add the trailing slash so that the wget -np does the right thing.
=> qa_crowbarsetup.sh: prevent iso-not-found errors (SOC-10012)

jenkins/ci.suse.de/cloud-socok8s.yaml, jenkins/ci.suse.de/templates/cloud-socok8s-integration.yaml
Updating existing integration job so that it can run with and
without tempest execution at its end. Tempest run currently takes
a while to complete depending on if its smoke (< 1hr) or full (2-3 hrs)
test execution. So running the whole deployment and then tempest execution
will take a while to finish.
We can run job without tempest more frequently and periodically can run
full deployment + tempest at different interval.
May be need to run tempest only when related changes are made. Need to
investigate this further as currently jenkins file in socok8s has
related logic.
This change depends on https://github.com/SUSE-Cloud/socok8s/pull/644
Depends-On: #fe7657d813cb485a93a26ae3f99353842522db1a
=> Updating socok8s integration job to use tempest run option

scripts/mkcloud
This commit increases the netcat timeout when waiting for the
SSH daemon on the admin node to vanish. This mechanism is used
to detect whether the Crowbar admin node has already gone down
for reboot. Under adverse circumstances (slow mkcloud host,
bad timing), an update of the openssh package could trigger
the previous timeout of 1s early (way before the reboot), thus
leaving the cloud in an inconsistent state.
=> mkcloud: fix timeout waiting for admin node reboot

scripts/heat/2-instances-cinder.yaml, scripts/heat/2-instances-pinging.yaml, scripts/qa_crowbarsetup.sh
We have a newer cirros image version there, so hardcoding
does not cut it.
=> Fix preupgrade heat stack deployment for cloud8+

scripts/jenkins/cloud/ansible/group_vars/all/all.yml
We closed the cloud-maintenance RC channel some time ago. Let's remove
the RC notifications.
=> Remove cloud-maintenance RC notifications

jenkins/ci.suse.de/cloud-crowbar.yaml, jenkins/ci.suse.de/pipelines/openstack-crowbar.Jenkinsfile, jenkins/ci.suse.de/templates/cloud-crowbar-pipeline-template.yaml, scripts/jenkins/cloud/ansible/collect-supportconfig.yml, scripts/jenkins/cloud/ansible/roles/supportconfig/defaults/main.yml, scripts/jenkins/cloud/ansible/roles/supportconfig/tasks/main.yml
Implement an ansible playbook and role to generate and collect
supportconfig files from all cloud nodes.
Collect supportconfig files as Jenkins artifacts by default in all
periodic and gating Crowbar jobs in case of failure.
=> openstack-crowbar: collect supportconfig files on failure (SOC-8460)

jenkins/ci.suse.de/pipelines/openstack-cloud.groovy
Use the `label` option from the `sh` jenkins pipeline step to
give more information in the blue ocean view about the shell
script that is being executed.
=> openstack-crowbar: use labels for ansible playbook stages

scripts/jenkins/cloud/ansible/roles/reboot_node/tasks/reboot_deployer.yml
After reboot the crowbar UI takes less minutes to be available so we
have to increase it.
=> Increased Crowbar webui timeouts after reboot - "SCRD-10174"

jenkins/ci.suse.de/cloud-maintenance-gating.yaml, jenkins/ci.suse.de/openstack-ardana-tests.yaml, jenkins/ci.suse.de/openstack-ardana-update-and-test.yaml, jenkins/ci.suse.de/openstack-ardana-update.yaml, jenkins/ci.suse.de/openstack-crowbar-tests.yaml, jenkins/ci.suse.de/templates/cloud-ardana-job-gerrit-template.yaml, jenkins/ci.suse.de/templates/cloud-ardana-pipeline-template.yaml, jenkins/ci.suse.de/templates/cloud-crowbar-pipeline-template.yaml
The `cloud_env` value is reflected into the hostnames set up
for the cloud nodes, so we must prevent underscore characters
from being part of it because they are not allowed to be part
of a hostname value [1].
This commit is a followup to 88b233b9e0856d1f1238dddf312fca7ffc7c9797,
which didn't cover all the jobs.
[1] https://www.ietf.org/rfc/rfc952.txt - B. Lexical grammar
=> openstack-crowbar/ardana: prevent underscores in cloud_env (continued)

scripts/jenkins/cloud/ansible/roles/ardana_tempest/tasks/main.yml, scripts/jenkins/cloud/ansible/roles/ardana_tempest/tasks/reconfigure_neutron.yml
When the neutron server is configured with distributed routing disabled
the agents must also be explicitly configure to run with distributed
routing disable.
Recent changes to neutron OpenStack make it unnecessary to wait for
neutron agent to recover.
=> Configure server and agents to run centralized (SOC-9144)

jenkins/ci.suse.de/cloud-socok8s.yaml, jenkins/ci.suse.de/templates/cloud-socok8s-integration.yaml
Drops the run_tempest option as its no longer optional to run
tempest.
As a side effect, drop also the smoke tempest job as all PRs and
master are now running tempest+smoke tests and we already have a
daily job for testing the full tempest suite
=> Drop uneeded option and job for socok8s (SOC-10120)

scripts/jenkins/cloud/ansible/roles/supportconfig/tasks/main.yml
Sometimes the deployment may fail before the cloud nodes are
registered, so the repositories aren't properly set up. In that
case, the supportconfig collection logic only needs to collect
supportconfig files from the admin node.
=> openstack-crowbar: handle partial supportconfig (SOC-8460)

scripts/scenarios/cloud8/qa/ssl/qa-scenario-1a.yaml
Remove hardcoded ssl paths
Enable ssl for keystone and neutron after recent certificate update
issue no longer exist.
=> Fix qa scenario for ssl on SOC8

jenkins/ci.suse.de/cloud-gating.yaml, jenkins/ci.suse.de/openstack-crowbar-tests.yaml, jenkins/ci.suse.de/templates/cloud-crowbar-pipeline-template.yaml
For SOC8 jobs we need run tempest tests for ceilometer,aodh and trove and those filter options currently not available in  CI job setup.
=> Add tempest filters to cloud 8 crowbar jobs (SOC-9799)

jenkins/ci.suse.de/pipelines/cloud-gating.Jenkinsfile, jenkins/ci.suse.de/pipelines/cloud-maintenance-gating.Jenkinsfile
Switch to cleaning up environments if jobs are successful.
NOTE: doing this should reduce the amount of ECP environments
running when jobs are passing and during low CI load periods.
=> cloud-gating/maintenance-gating: cleanup on success

scripts/jenkins/cloud/ansible/crowbar-update.yml
The automated process used to install Crowbar maintenance
updates on a pre-deployed cloud is currently broken, because
it incorrectly combines two workflows that should be tested
separately: one workflow to patch cloud nodes (no crowbar
changes) and another workflow to update crowbar LCM packages.
The current process can be described as follows:
- on every node, in sequence, starting with the admin node:
- add the maintenance update repositories
- run zypper patch
- reboot the admin node
- reboot the other nodes, in sequence, starting with
controller nodes (using 'crowbarctl node reboot')
The part that is incorrect is applying the crowbar LCM updates
and then rebooting the cloud nodes without re-applying the barclamp
configuration first. After reboot, a cloud node will apply the
new chef …
=> openstack-crowbar: correct update procedure

jenkins/ci.opensuse.org/openstack-prepare-staging.py, jenkins/ci.opensuse.org/openstack-submit.yaml, scripts/jenkins/qa_openstack.sh
This makes Rocky and Stein use the old process again.
OBS regularly causes conflicts that it could resolve automatically.
While each of these is a case where in the old process we would accept a
version of a package that was changed after testing started, we decided
to revert for now and revist later towards a more long term solution to
our staging needs.
=> revert osc release process (SOC-10025)

jenkins/ci.suse.de/cloud-gating.yaml, jenkins/ci.suse.de/pipelines/cloud-gating-config.yml, jenkins/ci.suse.de/pipelines/cloud-gating.Jenkinsfile, jenkins/ci.suse.de/templates/cloud-gating-template.yaml, scripts/jenkins/cloud/ansible/run-crowbar-tests.yml
This change adds the cloud-7-gating and its trigger jobs.
For now skip the submit project step until we are sure of the coverage
and stability of its downstream jobs compared to the mkcloud7 gate jobs.
For skipping the submit project step this change also adds a hidden parameter on the cloud-X-gating jobs that can be set to optionally skip the submit project step.
=>  openstack-crowbar: add cloud-7-gating job (SOC-10029)

jenkins/ci.suse.de/cloud-mkcloud9.yaml, jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-disruptive-template.yaml, jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-nondisruptive-ha-mariadb-template.yaml, jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-nondisruptive-ha-without-nodes-upgrade-template.yaml
Aodh and Monasca deployments are checked in upgrade prechecks for Cloud8-9
upgrade. These need to be adjusted to match the required state for prechecks
to pass.
=> upgrade: Fix Cloud9 prechecks

scripts/jenkins/qa_openstack.sh
This can be used to test against Cloud:OpenStack:Upstream:Master .
Note: There are still problems from time to time when both (COM and
COUM) have the same packages with the same versions available.
But this is a starting point to test the current COUM state.
=> qa_openstack: Add openstackupstreammaster as new cloud source

jenkins/ci.suse.de/cloud-ardana.yaml, jenkins/ci.suse.de/pipelines/openstack-ardana.Jenkinsfile, jenkins/ci.suse.de/templates/cloud-ardana-pipeline-template.yaml, scripts/jenkins/cloud/ansible/bootstrap-vcloud-nodes.yml
Collect supportconfig files as Jenkins artifacts by default in all
periodic and gating Ardana jobs in case of failure.
This also requires setting up passwordless SSH access for the root
account on the Ardana cloud nodes. This is needed by the SSH jump-host
feature used to collect supportconfig files.
=> Add collect supportconfig to ardana (SOC-8460)

scripts/jenkins/cloud/ansible/roles/crowbar_tempest/tasks/retry_failed.yml
SOCC8 uses testr instead of stestr (SOCC9) which has a different syntax
and output format. This change updates the command to rerun the failed tests accordingly.
=> openstack-crowbar: fix crowbar_tempest rerun for SOCC8 (SOC-9799)

scripts/jenkins/cloud/ansible/roles/ardana_tempest/tasks/reconfigure_neutron.yml
In cloud 8 Ardana, the neutron OVS agent on compute nodes still takes
a long time to restart. Re-adding the workaround to keep gating jobs
from failing.
This partially reverts commit ccdd3700f0aaae9b4d08b132485a09c55427f9a8.
=> Revert "Configure neutron server and agents to run centralized routing (SOC-9144)"

jenkins/ci.suse.de/cloud-maintenance.yaml
For the crowbar cloud 9 maintenance update gating jobs run tempest for
validating the deployment.
=> crowbar: add tempest tests on MU jobs for cloud 9 (SOC-9298)

scripts/jenkins/cloud/ansible/setup-ssh-access.yml
The wait for deployer task should be executed from the localhost
targeting the deployer node, not on the deployer host itself.
This should fix occasional failures (when the deployer does not boot fast enough) such as in: https://ci.suse.de/blue/organizations/jenkins/openstack-crowbar/detail/openstack-crowbar/321/pipeline
=> Fix deployer unreachable when running setup-ssh playbook

scripts/qa_crowbarsetup.sh
The NFS bug (bsc#1137262) that was affecting these tests has been
resolved, and moreover we switched the manila service VM to SLE15, so
these tests should work now.
=> Remove manila tests from blacklist

scripts/jenkins/qa_openstack.sh
When calling
zypper --non-interactive -n install --force openstack-quickstart \
openstack-tempest-test
the installation fails when both packages are in different
repositories. The failure is:
Forcing installation of 'openstack-quickstart-2019.2' from repository 'cloud'.
Package 'openstack-tempest-test' not found.
But openstack-tempest-test is provided by openstack-tempest from the
upstreamcloud repository.
The installation works fine if the "--force" option is not used.
Note: Filled also a zypper bug for it:
https://github.com/openSUSE/zypper/issues/289
=> qa_openstack: Do not force install quickstart and tempest-test

jenkins/ci.suse.de/cloud-mkcloud9.yaml, jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-disruptive-template.yaml
It was increased/changed to 7.5GB for Cloud6-7 upgrade where the default
was 6GB but for Cloud7+ the default is 12GB so this "increase" was actually
decreasing the limit.
This change adjusts this to the default 12GB from mkcloud for Cloud8-9 jobs.
=> upgrade: Increase controller memory for upgrade

jenkins/ci.suse.de/cloud-maintenance.yaml
In the same way as ardana, this change enable the automation to retry
tempest tests that failed for the crowbar MU jobs.
=> Enable retry failed tempest tests on MU jobs

jenkins/ci.suse.de/cloud-automation-pr-trigger.yaml, jenkins/ci.suse.de/cloud-crowbar-testbuild-pr-trigger.yaml
This was already supported in the automation trigger.
So make those two jobs more similar.
And extend the amount of runs we keep, so we have a chance to check on
failures.
=> Allow to only run the crowbar trigger for one PR

jenkins/ci.suse.de/cloud-mkcloud9.yaml, jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-disruptive-template.yaml, jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-nondisruptive-ha-mariadb-template.yaml, jenkins/ci.suse.de/templates/cloud-mkcloud-job-upgrade-nondisruptive-ha-without-nodes-upgrade-template.yaml
Currently there are 3 cloud 9 upgrade jobs:
```
cloud-mkcloud9-job-upgrade-disruptive-x86_64
cloud-mkcloud9-job-upgrade-nondisruptive-ha-mariadb-x86_64
cloud-mkcloud9-job-upgrade-nondisruptive-ha-without-nodes-upgrade-x86_64
```
This change update those job templates by adding/parameterizing the
`want_barbican_proposal` parameter and setting it to `1` on the jobs
definition. This should enable the barbican barclamp for those 3 cloud 9 upgrade jobs.
=> Enable barbican barclamp on cloud 9 upgrade jobs (SOC-10477)

jenkins/ci.suse.de/cloud-maintenance.yaml
Manila tempest tests are not being executed by the maintenance update
gating jobs. This change adds Manila to the list of tests the job runs for cloud 8 and 9.
=> openstack-ardana: run manila tests on MU gating jobs

jenkins/ci.suse.de/cloud-ardana8.yaml, jenkins/ci.suse.de/cloud-ardana9.yaml, jenkins/ci.suse.de/cloud-gating.yaml, jenkins/ci.suse.de/cloud-maintenance.yaml, jenkins/ci.suse.de/openstack-ardana-tests.yaml, jenkins/ci.suse.de/openstack-ardana-update-and-test.yaml, jenkins/ci.suse.de/openstack-crowbar-tests.yaml, jenkins/ci.suse.de/templates/cloud-ardana-pipeline-template.yaml, jenkins/ci.suse.de/templates/cloud-crowbar-pipeline-template.yaml
Move the LBaaS tempest test cases to the end of the list of
tempest test filters, to avoid having left over LBaaS resources
impacting other tempest test cases.
This PR also removes a few jobs running full tempest that aren't
used anymore.
=> openstack-crowbar/ardana: move lbaas tempest to the end

jenkins/ci.suse.de/pipelines/openstack-crowbar-tests.Jenkinsfile, jenkins/ci.suse.de/pipelines/openstack-crowbar.Jenkinsfile
If running testsetup fails the step execution is interrupted
consequently skipping the the archiveArtifacts call.
This change moves the arthieveArtifacts call to a post/always step
making sure that it will be called even in the case of an error.
=> openstack-crowbar: archive artifacts even if testsetup fails

scripts/jenkins/cloud/manual/lib.sh
Update the manual/lib.sh run_tempest function to reflect the recent
change that replaced the run-tempest.yml playbook with LCM flavour
specific versions run-tempest-ardana.yml and run-tempest-crowbar.yml.
=> Fix the run_tempest function in lib.sh

scripts/jenkins/cloud/ansible/roles/heat-generator/defaults/main.yml
Running full tempest when Swift is used as a Glance store runs
into a few failures if the default value of 2 GB is used for
its disk size. Using a greater value when SES is disabled will
fix this.
=> openstack-crowbar: use bigger disks for swift if SES is disabled (SOC-10590)

jenkins/ci.suse.de/cloud-trackupstream.yaml
We stopped shipping this codestream a long time ago and the CI is also
disbaled. Let's remove the trackupstream jobs as well.
=> trackupstream: Remove Devel:Cloud:6:Staging

jenkins/ci.suse.de/templates/cloud-socok8s-integration.yaml
I was surprised to see that the osh job started automatically with the `airship` option although I've set different default for that. Maybe this could help?
=> Pass the non-default deployment value to the osh job

jenkins/ci.suse.de/cloud-crowbar9.yaml, jenkins/ci.suse.de/pipelines/openstack-crowbar.Jenkinsfile, jenkins/ci.suse.de/templates/cloud-crowbar-pipeline-template.yaml, scripts/jenkins/cloud/ansible/crowbar-upgrade.yml, scripts/jenkins/cloud/ansible/group_vars/all/all.yml, scripts/jenkins/cloud/ansible/group_vars/all/crowbar.yml, scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/mkcloud.config.j2, scripts/jenkins/cloud/ansible/roles/crowbar_setup/tasks/main.yml, scripts/jenkins/cloud/ansible/roles/reboot_node/tasks/reboot_deployer.yml, scripts/jenkins/cloud/manual/deploy-crowbar.sh, scripts/jenkins/cloud/manual/input.yml.example, scripts/jenkins/cloud/manual/lib.sh
Extend the unified Cloud test automation toolchain to allow testing
cloud upgrade use cases:
- implement a new ansible playbook, `crowbar-upgrade.yml`, that
executes the same steps as the `mkcloud` `cloudupgrade` function,
by invoking the corresponding `qa_crowbarsetup.sh` steps
- add an `upgrade_cloudsource` ansible variable that can be used
to specify the target cloud source to be used for an upgrade
- the additional `upgrade_repos` and `want_nodesupgrade` variables
can be used to specify custom upgrade repositories (i.e. the
UPDATEREPOS_UPGRADE `qa_crowbarsetup.sh` variable) and to control
whether cloud nodes are also upgraded or not
This PR also creates [a periodic job](https://ci.suse.de/view/Cloud/view/Cloud%209%20Crowbar/job/cloud-crowbar9-job-upgrade-x86_64/) running a cloud 8 to …
=> openstack-crowbar: upgrade test automation and periodic job (SOC-10314)

scripts/jenkins/cloud/ansible/roles/crowbar_register/tasks/main.yml
The knife tool sometimes doesn't show the correct state for one of
the newly registered nodes until chef-client runs on the admin node.
Since this information isn't reliable and also redundant, because
of other ansible and qa_crowbarsetup.sh coded checks looking at the
node state, this change removes this check from the test automation.
=> openstack-crowbar: don't check knife node state (SOC-10530)

scripts/qa_crowbarsetup.sh
This change adds a workaround for SOC-10011. This commit should be
reverted once SOC-10011 is fixed.
=> Add workaround for known issue on simple horizon test (SOC-10011)

scripts/mkcloud
The bzip2 package is missing on the admin node, causing empty
supportconfig files to be collected by failing jobs.
=> mkcloud: install bzip2 required for supportconfig

jenkins/ci.suse.de/templates/cloud-crowbar-pipeline-template.yaml, scripts/jenkins/cloud/manual/input.yml.example, scripts/qa_crowbarsetup.sh
Due to bad ECP IO performance on some old hardware we need to increase
the timeout till the performance is fixed.
=> Workaround timeouts due to ECP IO performance (SOC-10513, SOC-10011)

scripts/qa_crowbarsetup.sh
The default crowbar batch timeout value is 500, but the previous
change (#3715) removed the explicit timeout values on the assumption
that the default value was 3600 seconds.
=> qa_crowbarsetup: higher timeouts for crowbar batch

scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/input_model/data/control_plane.yml, scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/input_model/data/network_groups.yml, scripts/jenkins/cloud/ansible/roles/heat-generator/library/generate_heat_model.py, scripts/jenkins/cloud/manual/lib.sh
Enable neutron service disablement (SOC-9780)
=============================================
One of the goals of the SOC/CLM 8 to 9 upgrade tooling was to enable
testing of minimal deployments, such as a keystone+horizon only single
controller node setup.
However defining an extry-scale-kvm or standard scenario cloud without
neutron would fail throwing exceptions in the heat model generator
due to attempting to dereference an item with a value of None as either
a dictionary or a list; adding guard checks to skip such elements when
converting lists to dictionaries avoids the exceptions.
The reason that the exceptions were occurring was due to the fact that
if you specified compute nodes in your model, but disabled all of the
service components running on them, you ended up with compute …
=> Permit neutron service disablement

scripts/jenkins/cloud/ansible/group_vars/all/all.yml, scripts/jenkins/cloud/ansible/roles/ardana_update/tasks/pre_cloudsource_update.yml, scripts/jenkins/cloud/ansible/roles/setup_zypper_repos/defaults/main.yml, scripts/jenkins/cloud/ansible/roles/setup_zypper_repos/tasks/setup_sles_cloud_repos.yml
After rsync'ing the Devel or Staging repos to the deployer, setup the
appropriate Pool & Updates tags so that any update or upgrade actions
can use them without having to disable repos checks, and eliminates
the need to remove and re-add these repo after adding the Updates tag
during the update workflow.
Ensure that the repos_to_add list is reset to an empty list at the
top of the setup_sles_cloud_repos.yml task list as otherwise, if the
task list is included multiple times in a playbook run, subsequent
inclusions will inherit the value from the previous run which may not
be desirable if used as part of setting up a new cloudsource during
upgrade.
Move some facts used exclusively in the setup_zypper_repos role to be
managed in that role's defaults/main.yml, rather than as part of the …
=> Setup Pool & Updates tags for Devel and Staging repos (SOC-9780)

jenkins/ci.suse.de/openstack-submit-project.yaml
submit-project: work with empty blacklist
without this patch, the blacklist check would drop everything
=> submit-project: work with empty blacklist

jenkins/ci.suse.de/cloud-gating.yaml
The Cloud 7 Gating in the ECP works the same way as the legacy Gating.
Therefore we can enable the submitproject job for this as well.
=> gating: Enable Cloud 7 gating submitproject

scripts/jenkins/cloud/ansible/roles/ardana_tempest/tasks/reconfigure_neutron.yml
With the merge of https://build.opensuse.org/request/show/731343 the problem is expected to be aliviated.
=> Removes 5 min wait time when restarting openvswitch-agent (SOC-9144)

jenkins/ci.suse.de/cloud-gating.yaml, jenkins/ci.suse.de/pipelines/cloud-gating-config.yml, jenkins/ci.suse.de/pipelines/cloud-gating.Jenkinsfile
This should functially move all gating to the ECP based CI.
Changes:
1: enable Staging to Dev propigation for Cloud 8, 9 through ECP gate jobs
2: add crowbar jobs to cloud-{8,9}-gating
3: remove crowbar blacklist and ardana white list from ECP
Based code in: jenkins/ci.suse.de/openstack-submit-project.yaml
ISO modified time at the start time of the cloud-{8,9}-gating jobs that control
which packages will be promoted and since that will be the same
for crowbar and ardana, things should be as correct as they are now.
Possible more so, since the current code allows to venv rpms to trail
the RPMs in the ISOs.
=> Created unified gating jobs (SOC-10029, SOC-10398)

jenkins/ci.suse.de/cloud-gating.yaml, jenkins/ci.suse.de/templates/cloud-unified-url-trigger-template.yaml
For cloud 8 and 9 the gating jobs should be triggered whenever there is
a new build for Crowbar or Ardana, however to ensure that both medias
have the latest changes the jobs should be executed only when both
medias have the same build number.
This change adds a new job template for triggering the cloud 8 and 9
gating jobs whenever there is a new build for Crowbar and Ardana, it
also checks if they have the same build number and if not mark the build
as unstable and does not run the cloud gating jobs.
=> Unified cloud gating trigger (SOC-10029)

jenkins/ci.suse.de/templates/cloud-ardana-pipeline-template.yaml, scripts/jenkins/cloud/ansible/group_vars/all/all.yml, scripts/jenkins/cloud/ansible/roles/ardana_deploy/tasks/main.yml, scripts/jenkins/cloud/ansible/roles/ardana_deploy/tasks/setup_openid_connect.yml, scripts/jenkins/cloud/manual/input.yml.example
Enable the OpenID Connect feature in CLM by default. The purpose is to
make sure the binaries are properly loaded and that it does not break
anything. We will not be testing the functionality itself as WebSSO
involves user interaction (with the browser).
=> enable OpenID Connect by default (SOC-10511)

jenkins/ci.suse.de/pipelines/openstack-ardana.Jenkinsfile, jenkins/ci.suse.de/pipelines/openstack-crowbar.Jenkinsfile
Starting with version 2.6 [1], the Jenkins lockable resource plugin
changed its behavior to fail when a non-existing resource label
name is used, even if the resource count is set to zero. This change
invalidates the hack that we use in our declarative pipelines to
conditionally lock a resource based on job input parameters.
Using the workaround suggested here takes care of this problem:
https://github.com/jenkinsci/lockable-resources-plugin/issues/134#issuecomment-517230676
[1] https://github.com/jenkinsci/lockable-resources-plugin/releases/tag/lockable-resources-2.6
=> openstack-crowbar/ardana: remove dummy lockable resource

scripts/scenarios/cloud9/cloud9-2nodes-default.yml
Enable the OpenID Connect feature in Crowbar by default. The purpose is to
make sure the binaries are properly loaded and that it does not break
anything. We will not be testing the functionality itself as WebSSO
involves user interaction (with the browser).
=> enable OpenID Connect by default for Crowbar (SOC-10511)

scripts/jenkins/cloud/ansible/deploy-crowbar.yml, scripts/jenkins/cloud/ansible/roles/cloud_generator/defaults/main.yml, scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/barclamps/neutron.yml.j2, scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/barclamps/octavia.yml.j2, scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/mkcloud.config.j2, scripts/jenkins/cloud/ansible/roles/cloud_generator/vars/templates/network/crowbar.yml, scripts/lib/mkcloud-common.sh, scripts/qa_crowbarsetup.sh
Makes the following changes needed to get test automation support
for Octavia in both mkcloud and the unified CI:
* updates the generated barclamp configurations for Octavia and
Neutron
* extends the certificate generation logic in `qa_crowbarsetup.sh`
to support using a passphrase for the root CA key and to also be
able to generate client certificates, both required by Octavia
* updates qa_crowbarsetup.sh and the generated mkcloud.config
file with two configuration options - `net_octavia` and
`vlan_octavia` - and, based on these options, adds some automation
logic that creates the neutron VLAN provider network that is
used for Octavia amphorae management traffic. This network will be
created before deploying the Octavia barclamp
* when using crowbar batch, Octavia is deployed separately, …
=> openstack-crowbar: add test automation for Octavia (SOC-10289)

hostscripts/zuul/layout.yaml
We also need to reference the jobs so that they can get matched
on the eventstream.
=> Fix config error in Train addition

jenkins/ci.suse.de/cloud-maintenance-gating.yaml, jenkins/ci.suse.de/cloud-maintenance.yaml, jenkins/ci.suse.de/pipelines/cloud-maintenance-gating-config.yml
- Add tempest full on cloud-crowbar8 maintenance update jobs
- Add the `linuxbridge` scenario to the list of jobs executed to validate a maintenance update.
=> cloud-maintenance: Add missing scenario and tests

jenkins/ci.suse.de/pipelines/openstack-ardana-tests.Jenkinsfile, scripts/jenkins/cloud/ansible/crowbar-update.yml, scripts/jenkins/cloud/ansible/roles/crowbar_reapply_barclamps/tasks/main.yml, scripts/jenkins/cloud/ansible/roles/crowbar_reapply_barclamps/tasks/reapply_barclamp.yml
Due to SOC-10505, `crowbar batch export/build` cannot be used for applying
the changes from a crowbar update.
This change uses `crowbarctl proposal commit` to reapply the barclamps
instead of `crowbar batch build`.
=> openstack-crowbar: Reapply barclamps on update

jenkins/ci.suse.de/pipelines/openstack-ardana.Jenkinsfile, jenkins/ci.suse.de/pipelines/openstack-crowbar.Jenkinsfile
Sometimes it happens that the Gating Jobs (cloud-X-gating) are stuck for some
reason. To prevent this, this change adds a timeout to the downstream jobs.
=> Set timeout for openstack-(crowbar|ardana) jobs (SOC-10719)

scripts/jenkins/workers/roles/jenkins_worker/defaults/main.yml, scripts/jenkins/workers/roles/jenkins_worker/tasks/configure_cron_jobs.yml
Due to [1] the jenkins jobs are leaving the job's workspace on the worker
node and eventually the worker's disk gets full.
This change adds a cron job to the worker that runs daily and deletes the
job workspace directory if it was not accessed on the last week.
1. https://issues.jenkins-ci.org/browse/JENKINS-50797
=> workers: Add cron job for cleaning old workspaces

scripts/qa_crowbarsetup.sh
Apparently the change for certificate generation introduced with
b5bdfade859248ba7bd36e893a94bbadb91b0d12 does not work for older
releases. So let's use it for Cloud9 only.
This is an attempt to fix what https://github.com/SUSE-Cloud/automation/pull/3748 brought. See the failure e.g. in https://ci.suse.de/job/openstack-mkcloud/15776/parsed_console/
=> Do not use same openssl commands for SP4 as for older releases

scripts/.rsync-filter
Sync'ing the local ansible-venv to the Crowbar admin node doesn't
make sense since the local ansible-venv is not statically built
and there is no guarantee that it will be compatible with the
admin node's SLE deployment.
=> Ensure we don't rsync ansible-venv (SOC-10913)

scripts/jenkins/track-upstream-and-package.pl
The packages with tar_scm source service are failing because of
1. the default platforms for the respective cloud releases are not
being correctly defined, and
2. for tar_scm, it ran into a nasty error while trying to lookup the
repo cache dir.
File "/usr/lib/obs/service/TarSCM/scm/base.py", line 160, in _calc_repocachedir
repocachedir = Config().get('tar_scm', 'CACHEDIRECTORY')
...
configparser.DuplicateSectionError: While reading from '<???>' [line  2]: section 'tar_scm' already exists
There's no need to add '[tar_scm]' header as it is accounted for already. See
https://github.com/guangyee/obs-service-tar_scm/blob/master/TarSCM/config.py#L27
https://github.com/guangyee/obs-service-tar_scm/blob/master/TarSCM/config.py#L67-#L70
=> Update default platforms and set cache dir for tar_scm

jenkins/ci.suse.de/pipelines/openstack-ardana.Jenkinsfile, jenkins/ci.suse.de/pipelines/openstack-crowbar.Jenkinsfile
Seems like the timeout function is not working properly as some jobs are
being aborted way before 8 hours of log inactivity, for example [1].
1. https://ci.suse.de/job/cloud-crowbar8-job-mu-ha-update-x86_64/92/console
This reverts commit 49ae4c3d773978636fe839e7aedfbb1eb1097462.
=> Revert "Set timeout for openstack-(crowbar|ardana) jobs (SOC-10719)"

scripts/qa_crowbarsetup.sh
This PR corrects a couple of issues found with setting up LTSS SLES repositories:
- the LTSS-Updates repository was never added to the admin node, which was occasionally causing zypper dependency failures
- we also need to use LTSS SLES repositories for SOC8 (SLES12-SP3)
=> qa_crowbarsetup.sh: fix LTSS repository setup

scripts/jenkins/cloud/ansible/report-job-failure.yml
Failing interrupts the execution of other post deployment tasks.
=> Do not fail on jira report playbook errors

scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/barclamps/octavia.yml.j2, scripts/qa_crowbarsetup.sh
Enables SSL testing for Octavia in ECP Crowbar deployments.
This commit also changes the Octavia certificate setup logic to
solve the problem described below.
The octavia system group and user are created when the
openstack-octavia package is installed on the controller nodes.
This happens automatically when the octavia barclamp is
applied.
However, setting up the paths for the certificates required for
the two-way SSL amphorae communication needs to be done in advance,
before applying the octavia barclamp, and those paths need to have
their ownership set to the octavia system user/group, which aren't
yet available at that time.
Adding the octavia system user and group is not a good solution,
because it interferes with the barclamp functionality so this change
proposes a different …
=> openstack-crowbar: enable SSL in test automation for Octavia (SOC-10906)

scripts/qa_crowbarsetup.sh
Allow one CRM failure in the test automation, to account
for intermittent failures in the ECP jobs.
=> qa_crowbarsetup.sh: don't fail on one CRM failure (SOC-10863)

jenkins/ci.suse.de/cloud-gating.yaml, jenkins/ci.suse.de/pipelines/cloud-gating-config.yml
This change removes monasca from the deploy/update jobs and add a new job
for deploying and testing monasca.
The reason behind that is that monasca is very resource expensive and
affects other services testing, besides that it also increases the time for
he other jobs to finish by about 50%.
=> openstack-ardana: add dedicated job for monasca on gate

scripts/jenkins/cloud/ansible/deploy-crowbar.yml
To work properly the designate barclamp expects the DNS barclamp to be applied also on the controllers.
=> openstack-crowbar: Apply dns to controllers when designate enabled

scripts/jenkins/track-upstream-and-package.pl
This is a follow up to
https://github.com/SUSE-Cloud/automation/pull/3754
In the case where ~/.obs/tar_scm config file already exist
and contain the [tar_scm] group, we need to remove it so that
obs-service-tar_scm doesn't choke on it.
=> remove tar_scm group in existing config file

scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/mkcloud.config.j2, scripts/jenkins/cloud/ansible/roles/cloud_generator/vars/product/crowbar.yml, scripts/qa_crowbarsetup.sh
This change switches the iso source from http://ibs-mirror.prv.suse.net/
to http://provo-clouddata.cloud.suse.de/ for the crowbar devel medias.
The reason behind it is that the trigger is also based on the build
number of the iso in provo-clouddata, also ibs-mirror has some recurring
issues syncing the medias from download.suse.de causing triggered jobs
to test outdated changes.
=> openstack-crowbar: get devel iso from provo-clouddata

scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/barclamps/designate.yml.j2
When [1] merges designate can be deployed with SSL enabled.
This change enable deploying designate with SSL enabled on
the openstack-crowbar jobs.
1. https://github.com/crowbar/crowbar-openstack/pull/2308
=> openstack-crowbar: deploy designate with SSL

scripts/qa_crowbarsetup.sh
Because SLE_12 and SLE_12_SP3 are gone from the
http://download.opensuse.org/repositories/devel:/languages:/python:/backports/
repository, we're better off switching to something that has a longer
lifetime.
=> openstack-crowbar: fix python-sh location

jenkins/ci.suse.de/pipelines/cloud-gating.Jenkinsfile, jenkins/ci.suse.de/pipelines/openstack-cloud.groovy
The Blue Ocean UI is still acting up, intermittently failing
to render the "Triggered Builds" section that can be used
to quickly navigate to downstream jobs. To account for this
bug, this commit re-enables printing messages during the Jenkins
pipeline stage, with URLs pointing to triggered downstream jobs.
NOTE: these messages will only show up in the Blue Ocean UI after
a triggered job has completed execution, which means that they
cannot be used to access ongoing downstream jobs.
=> cloud-gating: re-add downstream job URLs

scripts/jenkins/cloud/ansible/group_vars/all/versioned.yml
This change enable the designate barclamp also for Cloud 8.
=> openstack-crowbar: Enable designate barclamp for cloud8

jenkins/ci.suse.de/openstack-crowbar-tests.yaml, jenkins/ci.suse.de/templates/cloud-crowbar-pipeline-template.yaml, scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/mkcloud.config.j2, scripts/qa_crowbarsetup.sh
Adjust the tempest run filters to account for the fact that
when Octavia is enabled, the neutron lbaasv2 API is actually
proxied to the Octavia API and the neutron-lbaas tempest test
cases aren't properly equipped to handle that.
Creates a tempest filter to be run against Octavia with the
lbaasv2-proxy service plugin. The following test cases are
black-listed in that tempest filter, but also black-listed
in qa_crowbarsetup.sh, because they are not compatible with
the Octavia lbaasv2-proxy service plugin:
- neutron_lbaas.tests.tempest.v2.api.test_health_monitors_non_admin.
TestHealthMonitors.test_list_health_monitors_two
- lbaas-proxy doesn't handle the `http_method` attribute correctly
- see https://jira.suse.com/browse/SOC-10965
- …
=> octavia: adjust tempest filters (SOC-10965)

jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-2a.yaml, scripts/scenarios/cloud8/qa/no-ssl/qa-scenario-2a.yaml, scripts/scenarios/cloud8/qa/ssl/qa-scenario-2a.yaml
Deploy cluster on 3 node
Use mysql for database
Add scenario with CA certs
=> Update qa-scenario-2a (SOC-10460)

jenkins/ci.suse.de/cloud-gating.yaml, jenkins/ci.suse.de/cloud-maintenance.yaml, jenkins/ci.suse.de/templates/cloud-crowbar-pipeline-template.yaml
Add Octavia to the list of barclamps deployed by default in all
SOC9 ECP Crowbar jobs. Also run the lbaas-octavia tempest run
filter instead of lbaas in the SOC9 Crowbar gating jobs.
=> cloud-9-gating: enable Octavia in CI (SOC-10685)

scripts/jenkins/cloud/ansible/ardana-update.yml, scripts/jenkins/cloud/ansible/deploy-cloud.yml, scripts/jenkins/cloud/ansible/roles/ardana_tempest/defaults/main.yml, scripts/jenkins/cloud/ansible/roles/ardana_tempest/tasks/main.yml, scripts/jenkins/cloud/ansible/roles/setup_amphora_image/defaults/main.yml, scripts/jenkins/cloud/ansible/roles/setup_amphora_image/tasks/main.yml
We were previously setting up the amphora image on Ardana
deployments only during tempest testing and only if either
the lbaas or heat filters were enabled.
This change moves that logic to its own role and calls it
during regular cloud deployment as well as after a cloud
update, in case the amphora image was updated.
=> openstack-ardana: ansible role for amphora image setup

scripts/jenkins/cloud/ansible/roles/setup_amphora_image/tasks/main.yml
In SOC8 Ardana, there are no Octavia endpoints and there is no
'octavia' service registered in the catalogue, so we can't rely
on that to check whether Octavia is deployed when setting up the
amphora image.
=> openstack-ardana: don't check for an Octavia service

scripts/iscsictl.py
This breaks when deploying using bonding.
It uses `ip route get <external addr>' for getting the primary address.
240.0.0.0 is an internet-scoped reserved address.
=> iscsictl: don't use a hardcoded eth0 when finding the node's address

scripts/jenkins/cloud/ansible/roles/crowbar_register/tasks/main.yml
Seems like the option to ignore GPG checks also means that the
keys are not really imported.
=> Let crowbar_register import GPG keys of supported repositories

scripts/qa_crowbarsetup.sh
Removal of Cloud repo is needed after commit e0d574e761a226811cac4da15e749211b675213f
Before that we were replacing it with the new one.
followup after https://github.com/SUSE-Cloud/automation/pull/3762
=> Remove existing SP3 based repos during the upgrade

jenkins/ci.suse.de/cloud-ardana8.yaml, jenkins/ci.suse.de/cloud-ardana9.yaml, jenkins/ci.suse.de/cloud-crowbar7.yaml, jenkins/ci.suse.de/cloud-crowbar8.yaml, jenkins/ci.suse.de/cloud-crowbar9.yaml
Use HA jobs for testing the weekly automated image updates.
This change also enables reboot-after-deploy and test updates for all
Crowbar staging periodic jobs, for better coverage and to be
similar to Ardana jobs, and disables the Crowbar IPv6 job.
=> cloud-image-update: use HA jobs for integration testing

scripts/qa_crowbarsetup.sh
This reverts commit e0d574e761a226811cac4da15e749211b675213f.
Revert of https://github.com/SUSE-Cloud/automation/pull/3762 and partially https://github.com/SUSE-Cloud/automation/pull/3762
Turns out, we need Cloud repo at least for testing, i.e. to deliver Devel:Cloud packages that were not yet released as MU's
=> Revert "Cloud repo should not be required during and after the upgrade"

jenkins/ci.suse.de/pipelines/openstack-crowbar.Jenkinsfile, scripts/jenkins/cloud/ansible/install-crowbar.yml, scripts/jenkins/cloud/ansible/prepare-install-crowbar.yml, scripts/jenkins/cloud/manual/deploy-crowbar.sh, scripts/jenkins/cloud/manual/lib.sh
This change introduces a new Jenkins stage and splits the preparation
phase from the installation phase of Crowbar. The goal is to allow for
changes in network.json before Crowbar is bootstrapped and installed.
=> Split preparation from installation for Crowbar (SOC-10904)

scripts/heat/2-instances-upgrade-bothvolumes.yaml, scripts/heat/2-instances-upgrade-mixedvolumes.yaml, scripts/heat/2-instances-upgrade-novolumes.yaml, scripts/qa_crowbarsetup.sh
This commit adds an extended test scenario for the
non-disruptive upgrade that launches 3 Heat stacks designed
for putting live migrations through its paces on 3 distinct
compute nodes. To use this code proceed set the environment
variable governing the extended test scenario's use...
export want_testpreupgrade_extended=1
and use the onadmin_testupgrade() function on the non-updated
cloud to deploy the Heat stacks. Note that this requires at
least 3 compute nodes each with enough resources for two
m1.tiny istances each. After the upgrade, you can use the
onadmin_testpostupgrade() function to check whether the test
instances survived the upgrade and retrieve telemetry data on
how long they were down/unable to communicate.
Note that onadmin_testpreupgrade() and onadmin_testpostupgrade()
can …
=> Add extended pre-upgrade test scenario

scripts/jenkins/cloud/ansible/roles/ardana_tempest/tasks/retry_failed.yml, scripts/jenkins/cloud/ansible/roles/ardana_tempest/templates/run_filter_retry.txt.j2, scripts/jenkins/cloud/ansible/roles/ardana_tempest/templates/run_filter_retry_serial.txt.j2
This change adds a task that gather the existing blacklisted tests and
add them on the generated retry filters for tempest.
=> ardana-tempest: Add black listed tests on retry filter (SOC-11013)

scripts/lib/mkcloud-common.sh, scripts/lib/mkcloud-driver-libvirt.sh, scripts/mkcloud, scripts/mkcloudhost/cloudfunc, scripts/mkcloudhost/hacloud.common, scripts/mkcloudhost/routed.cloud, scripts/mkcloudhost/runtestmulticloud, scripts/mkcloudhost/runtestn, scripts/qa_crowbarsetup.sh
Deploying Octavia in mkcloud environments requires setting up
the infrastructure networking needed to complement the neutron
provider network used for the Octavia management traffic. More
specifically, this requires creating an additional VLAN interface
on the mkcloud host that can act as the external gateway for the
neutron provider network.
=> mkcloud: add support for Octavia management network (SOC-10685)

jenkins/ci.suse.de/cloud-crowbar7.yaml, jenkins/ci.suse.de/cloud-gating.yaml, jenkins/ci.suse.de/openstack-crowbar-tests.yaml, jenkins/ci.suse.de/pipelines/openstack-crowbar-tests.Jenkinsfile, jenkins/ci.suse.de/pipelines/openstack-crowbar.Jenkinsfile, jenkins/ci.suse.de/templates/cloud-crowbar-pipeline-template.yaml, scripts/jenkins/cloud/ansible/group_vars/all/crowbar.yml, scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/mkcloud.config.j2
The ECP Crowbar Jenkins jobs usually run smoke tempest through
the qa_crowbarsetup.sh onadmin_testsetup function. This commit
proposes that these jobs no longer run tempest through
qa_crowbarsetup.sh and instead use the ansible playbooks and
the tempest run filters. This aligns better with the Ardana
counterpart and also avoids running redundant tests in the
gate (i.e. the smoke test cases are also reflected in the
full-tempest suite).
The only exception to this new rule is SOC7, which doesn't (yet)
have support for running test filters. This will be covered
in a follow-up PR.
=> openstack-crowbar: don't run tempest in onadmin_testsetup

jenkins/ci.suse.de/cloud-gating.yaml, jenkins/ci.suse.de/openstack-ardana-tests.yaml, jenkins/ci.suse.de/openstack-ardana-update-and-test.yaml, jenkins/ci.suse.de/openstack-crowbar-tests.yaml, jenkins/ci.suse.de/templates/cloud-ardana-pipeline-template.yaml, jenkins/ci.suse.de/templates/cloud-crowbar-pipeline-template.yaml
With the openstack tempest plugin and tempest run filter added
to both Ardana and Crowbar, it is time to run those test cases
in the gating jobs.
NOTE: needs both [the crowbar-openstack GitHub PR](https://github.com/crowbar/crowbar-openstack/pull/2322) and [the tempest-ansible Gerrit patch](https://gerrit.prv.suse.net/c/ardana/tempest-ansible/+/6493) to be merged and available in the staging media before this PR can be merged.
=> Run the octavia tempest test cases in the gate (SOC-8743)

jenkins/ci.suse.de/cloud-crowbar9.yaml
Currently monasca failing to deploy on SOC9 CI jobs in general
removing from upgrade scenario (till fix will be provided as current
failures not related to upgrade)to have stable upgrade job running on ecp.
=> Removing monasca from upgrade scenario

scripts/qa_crowbarsetup.sh
This change allows qa_crowbaretup.sh to be sourced manually (i.e. not from
mkcloud) for running onadmin_prepare_cloudupgrade_admin_repos and
onadmin_prepare_cloudupgrade_nodes_repos manually. Before this change they
would have to be run twice in that scenario: in the first run, the Cloud
repository would not get updated to the newer one.
Note: please do not merge, yet. I am currently putting this through its paces for the Cloud 7 to Cloud 8 and the Cloud 8 to Cloud 9 upgrade. Once both are through, I'll remove the "do not merge yet" label (I don't anticipate any trouble, but I want to double-check to make sure).
=> export tftpboot after setting source variables (SOC-10758)

jenkins/ci.suse.de/cloud-mkcloud9.yaml, jenkins/ci.suse.de/openstack-mkcloud.yaml, jenkins/ci.suse.de/templates/cloud-mkcloud-job-4nodes-linuxbridge-tempestfull-template.yaml, jenkins/ci.suse.de/templates/cloud-mkcloud-job-4nodes-linuxbridge-template.yaml, jenkins/ci.suse.de/templates/cloud-mkcloud-job-dvr-template.yaml, jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-compute-template.yaml, jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-linuxbridge-bonding-template.yaml, jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-linuxbridge-template.yaml, jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-template.yaml, scripts/mkcloud
Adds the option to deploy Octavia to the openstack-mkcloud job
and enables this barclamp in jobs with 2 compute nodes or more
(because 2 or more compute nodes are required to get the lbaas
smoke tempest test cases to pass, and the compute node RAM
allocation also needs to be beefed up a bit).
=> Add Octavia to SOC9 mkcloud jobs (SOC-10685)

scripts/jenkins/cloud/ansible/roles/ardana_update/defaults/main.yml, scripts/jenkins/cloud/ansible/roles/ardana_update/tasks/main.yml
Recently a change in tempest-ansible
https://gerrit.prv.suse.net/c/ardana/tempest-ansible/+/6500
enabled additional tests that require additional resources
to be setup for these tests to execute sucessfully.
However, in the update workflow, the tests were failing since the
tempest-cloud-configure.yml playbook that sets up these resources
were not run.
This change calls the top level ardana-cloud-configure.yml
playbook which calls the tempest-cloud-configure.yml playbook which
creates resources needed for the newly enabled tests.
=> Run ardana-cloud-configure as part of the update workflow (SOC-7028)

jenkins/ci.suse.de/cloud-maintenance.yaml
With [1] an option to skip running tempest on testsetup was added,
however for cloud 7 we need to run tempest on testsetup as it does not
support tempest filters yet.
1. e97954bf98e91538496bd8b60844952db4a902cb
=> cloud-mu-gating: Run tempest on testsetup for Cloud 7

scripts/jenkins/cloud/ansible/roles/tempest_results/defaults/main.yml
The Leap 42.2 repository is gone. Use the repository for Leap 42.3
instead (the same used for cloud 8). This should not impact the product
as as soon as the `python-junitxml` package is installed the repo is
removed.
=> openstack-crowbar: update repository for python-junitxml

scripts/jenkins/cloud/ansible/roles/cloud_generator/defaults/main.yml
The ceilometer-agent role from Crowbar should be applied on the computes
only.
=> openstack-crowbar: do not apply ceilometer-agent on controllers

scripts/jenkins/cloud/ansible/group_vars/qe_all.yml, scripts/jenkins/cloud/ansible/group_vars/virt_all.yml, scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/barclamps/cinder.yml.j2
This change sets `rbd_flatten_volume_from_snapshot` to true on both
Ardana and Crowbar deployments. This should fix occasional failures on
the cinder `test_create_server_from_volume_snapshot` tempest test.
=> openstack-ardana/crowbar: enable volume flattening (SOC-11054)

scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/mkcloud.config.j2
If staging is selected for upgrade_cloudsource, we need to make sure
it is really used when setting up new repositories during the upgrade.
=> Set the values of want_cloud*_iso also for the upgrade_cloudsource

scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/mkcloud.config.j2, scripts/jenkins/cloud/ansible/roles/cloud_generator/vars/product/crowbar.yml
The generate-cloud playbook is failing because mkcloud.config template
is referencing `upgrade_cloudsource[-1]` which is empty by default (not
an upgrade job).
=> openstack-crowbar: Fix upgrade cloud iso name on mkcloud.config template

scripts/heat/2-instances-cinder.yaml, scripts/mkcloud, scripts/qa_crowbarsetup.sh
When $upgrade_test_stack_count is set to >1, there will be multiple
"east-west" stacks created/checked by testpreupgrade/testpostupgrade
steps in mkcloud.
=> upgrade: Add support for multiple upgrade test stacks

jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-linuxbridge-bonding-template.yaml, scripts/jenkins/mkcloud/openstack-mkcloud.builder.sh, scripts/mkcloud
Some SOC9 mkcloud jobs are failing lately because they have
Octavia enabled, but the RAM allocated on compute nodes is
not enough to allow 4 load balancer instances to run
at the same time, which is what is needed to get lbaas smoke
tempest test cases to pass (each Octavia instance requires
1 GB of RAM).
This change adjust the RAM allowance on mkcloud compute nodes
when 2 or fewer compute nodes are used.
=> mkcloud: beef up compute nodes for Octavia (SOC-10685)

scripts/jenkins/cloud/ansible/roles/ardana_tempest/templates/run_filter_retry.txt.j2, scripts/jenkins/cloud/ansible/roles/ardana_tempest/templates/run_filter_retry_serial.txt.j2, scripts/jenkins/cloud/ansible/roles/crowbar_tempest/tasks/retry_failed.yml, scripts/jenkins/cloud/ansible/roles/crowbar_tempest/templates/run_filter_retry.txt.j2
Instead of relying on stestr/testr for re-running failed tests. Generate
specific filters based on the list of failed tests, just like it is done
for ardana.
This change also includes a fix for the regex used when building run filter for retrying failed tests
=> openstack-crowbar: generate filters on tempest retry (SOC-11069)

scripts/jenkins/cloud/ansible/roles/cloud_generator/vars/templates/service/standard.yml, scripts/jenkins/cloud/ansible/roles/cloud_generator/vars/templates/service/std-lmm.yml
The swift-object role is by default assigned by Crowbar to all
non-controller nodes. To align unified CI jobs to that, we need to
do the same in the generated Crowbar scenarios. This also takes
some of the load off of controller nodes and reduces the overall
time it takes to re-apply the proposals during update.
=> cloud-generator: fix the swift-object deployment

jenkins/ci.suse.de/templates/cloud-crowbar-pipeline-template.yaml, scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/mkcloud.config.j2
When a CI job fails it helps if the logs contain debug level
information. This change enables debug for OpenStack components with
Crowbar.
=> Increase debug output for OpenStack components

scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/input_model/data/network_groups.yml
When octavia is listed in the disabled_services parameter,
there is still reference to the OCTAVIA-MGMT-NET in the
network_groups.yml file which fails the config-processor
with the following error:
Network group MANAGEMENT route OCTAVIA-MGMT-NET is not
a valid network group.
To avoid this error when octavia is disabled, the
network_groups.yml is updated
=> Do not add the OCTAVIA-MGMT-NET when octavia is disabled

jenkins/ci.suse.de/cloud-maintenance-gating.yaml, jenkins/ci.suse.de/openstack-ardana-testbuild-gerrit.yaml, jenkins/ci.suse.de/openstack-ardana-tests.yaml, jenkins/ci.suse.de/openstack-ardana-update-and-test.yaml, jenkins/ci.suse.de/openstack-ardana-update.yaml, jenkins/ci.suse.de/openstack-crowbar-tests.yaml, jenkins/ci.suse.de/templates/cloud-ardana-job-gerrit-template.yaml, jenkins/ci.suse.de/templates/cloud-ardana-pipeline-template.yaml, jenkins/ci.suse.de/templates/cloud-crowbar-pipeline-template.yaml, jenkins/ci.suse.de/templates/cloud-gating-template.yaml, jenkins/ci.suse.de/templates/cloud-heat-template.yaml, jenkins/ci.suse.de/templates/cloud-image-update-template.yaml, jenkins/ci.suse.de/templates/cloud-jenkins-worker-template.yaml
The current description is not rendered the way it is in the yaml
files. This change simplifies the formatting of the description so
that the rendering matches the description.
=> Fix description of `extra_params`

scripts/qa_crowbarsetup.sh
Migrating crm resources away from a controller node before reboot
by means of the `crm node standby` command triggers a rabbitmq bug
and causes openstack services to break after a reboot.
Using crm maintenance mode instead of standby mode until this is
resolved.
=> qa_crowbarsetup.sh: use crm maintenance mode (SOC-11082)

hostscripts/zuul/layout.yaml
There was a missing copy&paste in the previous change. this
adds the filter to ensure that we only run train updates on
train branch changes.
=> Run post-update for train not on master changes

jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-1a.yaml, jenkins/ci.suse.de/cloud-mkphyscloud-qa-scenario-2a.yaml
Some QA scenarios had unnecessary restrictions on the mkcloud
steps that can be run. This commit removes these restrictions.
=> mkphyscloud: remove command restrictions

jenkins/ci.suse.de/cloud-mkcloud7.yaml, jenkins/ci.suse.de/cloud-mkcloud8.yaml, jenkins/ci.suse.de/cloud-mkcloud9.yaml
so now it will select any SLE12.
None of the mkcloud hosts run SP2. The label probably was incorrectly
still there on SP4 hosts, even though they were SP4. The label probably
got updated by fully deploying pending changes in cloudsalt.
This label requirement was added in
565500c02667ea710f26e48ad3dd9b0def2225a0 because these jobs couldn't run
on SP1. As all host are now SP4, the SP2 requirement is not needed
anymore.
=> change mkcloud jobs to not require exactly SP2

scripts/jenkins/qa_openstack.sh
$zypper already has "--non-interactive". There is no need to add
another "-n".
This fixes the following warning:
Warning: The flag --non-interactive can only be used once.
=> qa_openstack: Remove duplicate zypper -n switch

jenkins/ci.opensuse.org/openstack-cleanvm.yaml
It's currently broken and nobody looks into it. openSUSE Leap 15.1
looks good so far so keep testing that for now.
=> openstack-cleanvm: Do not test SLES for master and train

jenkins/ci.suse.de/cloud-gating.yaml, jenkins/ci.suse.de/cloud-maintenance.yaml
Adding full tempest to all gating jobs (both staging and maintenance
update) for SOC7. For now, the nova, cinder and magnum filters
are excluded, because there are still a few test cases consistently
failing, that either need to be black-listed because of missing
features, or addressed separately as bugs:
tempest.api.volume.admin.test_volume_type_access.VolumeTypesAccessV2Test*
magnum.tests.functional.api.v1.test_cluster.ClusterTest.test_create_list_sign_delete_clusters
tempest.api.compute.admin.test_servers_on_multinodes.ServersOnMultiNodesTest.test_create_servers_on_different_hosts_with_list_of_servers
=> Enable full tempest for ECP gating jobs for SOC7 (SOC-9801)

scripts/jenkins/workers/roles/jenkins_worker/defaults/main.yml
Add deepdiff module into python venv on the ci worker.
This is prerequisite  for: SOC-11086 - Structured diff of installed packages. (https://github.com/djz88/automation/tree/enhanced_diff)
=> ci worker: add deepdiff into venv

scripts/jenkins/cloud/ansible/roles/list_packages/tasks/list-packages.yml
Sometimes when listpackages role is getting installed packages fails
due to locks by other tools. We use zypper search(read only command)
to get installed packages. This works normally for the other user then
root. We workaround this by use of different lock file.
=> deployment: Add ZYPP_LOCKFILE_ROOT var to fix locking issue

jenkins/ci.suse.de/cloud-jenkins-worker.yaml
This was manually added when there was a need for more slots to make
progress. Add it in the defaults for the job that updates/installs the
workers.
=> add worker ci2

jenkins/ci.suse.de/cloud-jenkins-worker.yaml
Define individual jobs to make it simpler to trigger the rebuild
of individual ECP worker nodes in the ECP Jenkins view.
=> Use individual Jenkins jobs for ci and ci2 ECP worker nodes

jenkins/ci.suse.de/cloud-gating.yaml, jenkins/ci.suse.de/cloud-maintenance.yaml, jenkins/ci.suse.de/openstack-crowbar-tests.yaml, jenkins/ci.suse.de/templates/cloud-crowbar-pipeline-template.yaml
This PR updates the full tempest coverage in the staging and MU gating jobs:
- adds cinder and nova tempest test runs to the SOC7 gate jobs for
the staging media and maintenance update testing (SOC-9801).
- replaces the `lbaas-octavia` test run filter with the `lbaas` test filter (with [the
ability to generate test runs dynamically](https://github.com/crowbar/crowbar-openstack/pull/2343) from the chef tempest
recipes, `lbaas-octavia` is deprecated)
- adds Octavia and Designate tempest test runs to the MU gating jobs for SOC8 and SOC9
=> Update tempest tests covered in the staging and MU gating jobs 

scripts/jenkins/cloud/manual/lib.sh
When adding the repo for the built gerrit test packages, only use the
repo directory URL; do not append the name of the .repo file.
=> Setup extra_repos correctly for gerrit test packages (SOC-11194)

jenkins/ci.suse.de/openstack-ardana-caaspv4.yaml, jenkins/ci.suse.de/pipelines/openstack-ardana-caaspv4.Jenkinsfile, jenkins/ci.suse.de/pipelines/openstack-ardana.Jenkinsfile, jenkins/ci.suse.de/templates/cloud-ardana-pipeline-template.yaml, scripts/jenkins/cloud/ansible/deploy-caasp-v4-terraform.yml, scripts/jenkins/cloud/ansible/group_vars/all/vcloud.yml, scripts/jenkins/cloud/ansible/roles/heat-generator/vars/caasp.yml
This playbook provides an automated deployment mechanism
to deploy caasp v4 using terraform on SOC openstack deployment.
This playbook currently runs against the ardana flavored version of
SOC.
You can provide various optional parameters to the playbook:
Some examples:
num_workers to define the number of workers in the cluster.
- Default value is 1.
num_masters to define the number of masters in the cluster.
- Default value is 1.
It uses octavia provider for SOC 9 and haproxy provider for SOC 8
deployments.
=> Automate Deployment of Caasp4 using terraform

scripts/jenkins/cloud/ansible/group_vars/all/vcloud.yml
A recent change https://github.com/SUSE-Cloud/automation/pull/3851
introduced a new parameter called want_caaspv4.
This was not defined for virtual cloud env setup causing CI to fail.
This commit fixes the issue.
=> Fix CI runs for virtual cloud setup

scripts/qa_crowbarsetup.sh
Cinder cannot restart because dm-eventd restart is too slow (SOC-11110).
This is a temporary workaround similar to what was used in OpenSUSE:
https://build.opensuse.org/request/show/460424.
Something in dm-event in turn requires enabled lvm2-monitor:
https://bugzilla.suse.com/show_bug.cgi?id=1072492,
https://build.opensuse.org/request/show/558339
This commit should be reversed when bsc#1166529 is fixed.
=> Enable dm-event.socket and lvm2-monitor to restart cinder

scripts/jenkins/cloud/ansible/roles/cloud_generator/vars/templates/interface/full-spread.yml, scripts/jenkins/cloud/ansible/roles/cloud_generator/vars/templates/network/full-spread.yml
In Cloud9 CLM changes were implemented in the configuration process to
validate that the proposed model didn't try to assign more than one
untagged VLAN to a given network interface. However the dynamically
generated input model for the mid-scale-kvm scenario violates this
requirement, as there exist 3 untagged VLANs (CONF, MANAGEMENT,
TENANT-VLAN) and thus fails the configuration process check.
This patch addresses the problem by merging the CONF and MANAGEMENT
networks together so that there are only 2 untagged VLANs, one for
each network interface.
=> mid-scale-kvm scenario broken for Cloud9 CLM (SOC-11169)

scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/barclamps/octavia.yml.j2, scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/mkcloud.config.j2, scripts/lib/mkcloud-common.sh, scripts/qa_crowbarsetup.sh
(based on #3827 )
Updates the automation scripts for Octavia, to add support
for configuring a network.json octavia network instead of the
previous way of configuring the Octavia management network
as an externally managed provider network.
* to aid with debugging, intermediate network.json steps are backed
up so that it's easier to debug the myriad of `sed` commands that
modify `network.json` before bootstrapping crowbar
* the Neutron barclamp calculates the `vlan_min` value for the ml2
plugin based on the fixed network VLAN ID. In order to avoid VLAN ID
collisions this change moves the fixed network VLAN ID to be above
that used for `octavia` and other VLAN networks
* adds a `want_octavia_network` option that can be used to switch
between using the octavia network in network.json …
=> Use the octavia network.json network for Octavia (SOC-10904)

scripts/qa_crowbarsetup.sh
With current code, want_cloud?_iso_url was set when the non-Staging
version of CLOUDISOURL is set, leading to the situation where the URL
for Staging iso is not replaced by the correct value.
=> Correctly set the URL to the ISO when TESTHEAD is used

scripts/jenkins/cloud/ansible/roles/supportconfig/defaults/main.yml
There was yet another change in the supportconfig generation utility
that broke backwards compatibility: the prefix of the generated
archive filename changed from `nts_` to `scc_`.
=> Fix supportconfig collection in new CI

scripts/jenkins/cloud/ansible/roles/setup_root_partition/defaults/main.yml
Ardana 8 maintenance update test jobs are failing during the install
of cloud-patterns because it does not have enough disk space
available.
This change increases the root partition size from 34 GB to 44 GB, the
flavors were already updated to reflect that change.
=> setup_root_partition: Increase root partition size

jenkins/ci.suse.de/pipelines/openstack-cloud-heat.Jenkinsfile
Allow the https://ci.suse.de/job/openstack-cloud-heat-engcloud job to
be manually triggered to delete cloud environments corresponding to
CI Lockable Resources.
=> openstack-cloud-heat: allow to delete CI slots

scripts/jenkins/cloud/ansible/roles/setup_zypper_repos/defaults/main.yml, scripts/jenkins/cloud/ansible/roles/setup_zypper_repos/tasks/setup_sles_cloud_repos.yml
Add support for setting up the SLES LTSS repositories on
the "setup_zypper_repos" ansible role.
By default the LTSS repos are enabled for cloud7 and cloud8
releases.
=> setup_zypper_repos: add support for ltss repositories (SOC-11221)

jenkins/ci.suse.de/cloud-mkcloud9.yaml
As aarch64 no longer supported make sense to disable and later remove
corresponding jobs from CI as they not running and only creating queues.
=> Disable aarch64 SOC9 mkcloud jobs

scripts/jenkins/cloud/ansible/roles/setup_zypper_repos/defaults/main.yml, scripts/jenkins/cloud/ansible/roles/setup_zypper_repos/tasks/add_extra_repos.yml, scripts/jenkins/cloud/ansible/roles/setup_zypper_repos/tasks/check_settings.yml, scripts/jenkins/cloud/ansible/roles/setup_zypper_repos/tasks/main.yml, scripts/jenkins/cloud/ansible/roles/setup_zypper_repos/tasks/remove_extra_repos.yml, scripts/jenkins/cloud/ansible/roles/setup_zypper_repos/tasks/setup_maint_update_repos.yml, scripts/jenkins/cloud/ansible/roles/setup_zypper_repos/tasks/setup_repo_from_iso.yml, scripts/jenkins/cloud/ansible/roles/setup_zypper_repos/tasks/setup_sles_cloud_repos.yml, scripts/jenkins/cloud/ansible/roles/setup_zypper_repos/templates/motd.j2
Add support to the setup_zypper_repos role to allow it to completely
manage the lifecycle of repos, rather than just simply add them to
the system. This permits playbooks to:
* add repos in a disabled state
* disabled already defined repos
* remove defined repos
* delete the on-disk contents of downloaded repos or unmount NFS
imported repos
Three new settings have been introduced that are used to manage the
state of zypper repos:
* zypper_repo_enabled:
- yes/no value indicates if repos are enabled or disabled
* zypper_repo_state:
- present/absent indicates if repos are added/remove
- only valid if zypper_repo_enabled == no
* zypper_repo_delete:
- boolean indicating if repo on-disk contents or persistent NFS
mount should be removed.
- only valid if zypper_repo_state == absent
This will be …
=> Enhance zypper repo management (SOC-9780)

scripts/jenkins/qa_devstack.sh
In 352d58a7afd9e2261e639af78e4fb4c99d8f9f81 of openstack/devstack.git
fixing of permissions on existing directories was dropped. The script
that is changed here relied on that. Adapt it to also take over fixing
the permission of the rest of the directories.
=> devstack: fix the permission of all directories

jenkins/ci.suse.de/cloud-maintenance.yaml, scripts/jenkins/cloud/ansible/group_vars/all/versioned.yml, scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/barclamps/magnum.yml.j2
Pushing a couple of changes to get the maintenance update gating jobs to pass reliably until the required SOC fixes are released:
- don't enable SSL for magnum in GMx+up: the magnum SSL fixes haven't been released yet in SOC8 and SOC9, so the maintenance gating jobs end up consistently failing because
of this. Modeling this as a versioned feature, until those fixes are released
- remove nova,cinder,magnum,manila and fwaas tempest filters from SOC7: [the set of patches required to get full tempest to pass with SOC7](https://jira.suse.com/browse/SOC-9801?focusedCommentId=979248&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-979248) have not yet been released. Omitting the failing tempest filters from the list of filters unning in the maintenance update jobs, …
=> Fixes for the maintenance update gating jobs

jenkins/ci.suse.de/cloud-maintenance.yaml
This is a continuation of the previous change removing some tempest
filters from the SOC7 maintenance update gating jobs, because not
all SOC changes fixing them have been released yet (neutron was
overlooked).
=> Maintenance update gating: remove neutron tempest from SOC7

scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/input_model/data/networks.yml
Recent changes for SOC-7365 added support for virtialised PXE boot in
deployments, but in doing so renamed the associated network from ILO
to BMC, but the gitlab.suse.de/cloud-qe/ardana-bm-info.git maintained
definitions for the baremetal systems haven't been updated to reflect
this so we need workaround this by remapping the lookup of info for
the BMC network to look for the ILO network details.
=> Remap lookup of BMC to ILO for baremetal deployments (SOC-11253)

scripts/jenkins/cloud/ansible/group_vars/all/all.yml
When SOC/CLM MUs are being tested the ardana-update.yml playbook can
be invoked with an empty value for cloudsource, which breaks recent
changes landed in PR#3726 which use the derived cloud_release value.
This patch ensures that even if cloudsource is empty in such cases
that a valid cloud_release_number is identified from the runtime
env of the job.
=> Ensure cloud_release_number has sane value (SOC-11252)

scripts/jenkins/cloud/ansible/group_vars/all/all.yml
The recent fix for PR#3879 to ensure we select and appropriate cloud
release number when cloudsource is not defined, combined with PR#3880
to handle the renaming of ILO network and BMC network being fixed has
uncovered a follow issue with regard to cloud_release_number handling.
In the case where gathering of facts for an ansible node is disabled,
as is the case with the start-deployer-vm.yml top level playbook, the
use of ansible_distribution_version as a fallback within the PR#3879
fix leads to an error.
This patch addresses this issue in two ways:
1)  Use a default of 'UNKNOWN' for ansible_distribution_version if
it isn't defined so that it will be easier for any future errors
related to this issue being diagnosed.
2)  Enable gathering of facts for the start-deployer-vm.yml playbook
as …
=> Handle ansible_distribution_version not being defined (SOC-11252)

jenkins/ci.suse.de/cloud-maintenance.yaml
This is a continuation of the previous change removing some tempest
filters from the SOC7 maintenance update gating jobs, because not
all SOC changes fixing them have been released yet (lbaas was
overlooked - see SOC-11173).
=> Maintenance update gating: remove lbaas tempest from SOC7

jenkins/ci.suse.de/pipelines/openstack-ardana.Jenkinsfile, scripts/jenkins/cloud/manual/lib.sh
Pass appropriate values for cloudsource when the ardana-update.yml
playbook is invoked, allowing for the case when running MU tests
where update_to_cloudsource is not specified.
Align the logic used to control when the Ardana or Crowbar update and
upgrade playbooks are called in the manual/lib.sh with that used by
the Jenkins pipelines. Namely that update/upgrade should only happen
if update_after_deploy is set.
=> Ensure ardana-update.yml called with valid cloudsource (SOC-11252)

scripts/jenkins/cloud/ansible/bootstrap-clm.yml, scripts/jenkins/cloud/ansible/integrated-deployer-tweaks.yml
When doing a baremetal deployment for Ardana with an integrated deployer
the first controller node will be a VM running on the gateway node based
on an appropriate SLES image that has the apparmor pattern installed.
However having apparmor installed on a controller node is not compatible
withe the package set expected for an Ardana controller node, leading to
issues later on after upgrading and rebooting this integrated controller
node from Cloud8/SP3 to Cloud9/SP4.
This patch disables the apparmor service then uninstalls the associated
patterns and unnecessary packages. Note that we leave libapparmor1 as it
is a dependency of other required packages such as rsync.
=> Tweak integrated deployer/controller VM for physical deploys (SOC-9780)

scripts/mkcloud
VirtualBMC is needed for functional testing of Ironic.
Some hosts in the CI are already running SLES12-SP5. While
python-virtualbmc package is available only in
SUSE:SLE-12-SP4:Update:Products:Cloud9 it installs fine on SP5.
=> Enable vbmc installation for SP5 hosts

jenkins/ci.suse.de/pipelines/openstack-ardana.Jenkinsfile
As part of cleaning up PR#3732 I inadvertently removed a hacky guard
condition on the Update phase thinking that it was no longer needed
given recent fixes to how the Update phase runs the Ansible playbooks.
However it turns out that we still need some sort of additional guard
contion on the Update phase as otherwise it also gets triggered if we
specify the update_after_deploy flag to trigger the Upgrade phase.
=> Only trigger openstack-ardana Update phase if needed (SOC-9780)

scripts/jenkins/cloud/ansible/roles/ardana_upgrade/tasks/_upgrade-clm.yml
Recently Flavio pointed out in a review of PR#3732 that I might be
able to use the script module to run a script on the Ardana deployer
rather than using the copy module followed by the command module.
=> Use Ansible script rather than copy+command (SOC-9780)

scripts/jenkins/cloud/ansible/roles/ardana_deploy/files/enable-centos-rpms-on-rhel/roles/deployer-rhel-repo/vars/main.yml
Add `python-lxml` and `python-cssselect` to the list of packages that are
downloaded and made available through the CentOS (optional) repository.
Those packages are needed for the new version of python-keystoneauth1.
This fixes the `cloud-ardana9-job-std-min-centos-x86_64` job.
=> openstack-ardana: add missing packages on CentOS repo

scripts/jenkins/qa_openstack.sh
The current host www3.zq1.de is on longer responding and is causing
the cleanvm jobs to fail. The curl has been updated to use www.opensuse.org
=> Fix qa_openstack.sh to curl an available host

scripts/jenkins/cloud/ansible/roles/rocketchat_notify/defaults/main.yml, scripts/jenkins/cloud/ansible/roles/rocketchat_notify/vars/ardana-qe-tests.yml, scripts/jenkins/cloud/ansible/roles/rocketchat_notify/vars/tempest.yml, scripts/jenkins/cloud/ansible/run-ardana-qe-tests.yml, scripts/jenkins/cloud/ansible/run-tempest-ardana.yml
If there is none activelly using OpenStack-Health makes no sense to keep
sending the test results to it as it just increase the execution time
and the chence of unrelated failures (e.g. [1])
1. https://ci.suse.de/blue/organizations/jenkins/cloud-ardana9-job-gate-entry-scale-kvm-monasca-x86_64/detail/cloud-ardana9-job-gate-entry-scale-kvm-monasca-x86_64/187/pipeline#step-168-log-121
=> Do not send test results to OS-Health

scripts/qa_crowbarsetup.sh
This will fix SOC7 ha jobs that failing due to
Package 'python-sh' not found in Factory repo
=> Updating 'python-sh' location

jenkins/ci.opensuse.org/templates/openstack-rpm-packaging-update.yaml
The github mirror seems unreliably / asynchroneously updated, so
when the post update job runs, it doesn't get the newest state,
causing inconsistencies.
Lets see if using the master repo fixes this problem.
=> Switch to opendev for git downloading

scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/barclamps/monasca.yml.j2
The monasca barclamp template is missing the `attributes` key on its
definition.
=> openstack-crowbar: add attributes to monasca barclamp template

scripts/jenkins/qa_devstack.sh
It gets pulled in via recommends but would later prevent devstack from
installing other things via pip.
Pip would give the following error:
Attempting uninstall: pycparser
Found existing installation: pycparser 2.17
ERROR: Cannot uninstall 'pycparser'. It is a distutils installed project
and thus we cannot accurately determine which files belong to it which
would lead to only a partial uninstall.
=> devstack: remove python3-pycparser

hostscripts/rpm-packaging/createproject.py, jenkins/ci.opensuse.org/templates/openstack-rpm-packaging-update.yaml
on opendev the archive is always just the gitrepo name, without any
version suffix. adjust.
Add sanity check to avoid that this will ever become a problem some
other time.
=> Fix fallout from archive url change

scripts/jenkins/cloud/ansible/roles/ardana_qe_tests/tasks/process_test_results.yml
Recently when running iverify tests I have seen issues with the iverify
run completes, likely with failures, and then the subsequent subunit run
to extract the results fails resulting in no ardana_qe_test_results fact
being defined which leads to an ansible error later when checking on the
status of the test that were run.
This patch defines a "default" ardana_qe_test_results fact, with failed
set to 9999999 if we fail to initialise an ardana_qe_test_results due
to the above error scenario.
=> Handle ardana_qe_tests failures better (SOC-9780)

jenkins/ci.suse.de/cloud-maintenance.yaml, scripts/jenkins/cloud/ansible/group_vars/all/versioned.yml
**NOTE**: do not merge before the next SOC8 maintenance update !
Sync the staging gating jobs with the maintenance update gating
jobs, so that they have the same test coverage.
This wasn't previously possible because not all bugs affecting
the staging gating jobs were released as maintenance updates.
=> Sync maintenance gating with staging gating for SOC8

jenkins/ci.suse.de/cloud-ardana9.yaml, jenkins/ci.suse.de/cloud-crowbar9.yaml, jenkins/ci.suse.de/cloud-gating.yaml, jenkins/ci.suse.de/templates/cloud-ardana-pipeline-template.yaml, jenkins/ci.suse.de/templates/cloud-crowbar-pipeline-template.yaml
Reverts SUSE-Cloud/automation#3902
As problematic patch were reverted its safe to enable cloud 9 jobs  back
=> Revert "Temporary disable clod9 jobs"

jenkins/ci.opensuse.org/openstack-trackupstream.yaml
This commit temporarily disables openstack-neutron upstream tracking in
Cloud:OpenStack:Pike:Staging. This is to prevent another ARP storm from
happening. It can safely be re-enabled once
https://review.opendev.org/#/c/741444/
has landed upstream. To that end, simply revert this commit.
=> Temporarily disable Neutron upstream tracking

jenkins/ci.suse.de/openstack-ses.yaml, scripts/jenkins/ses/ansible/bootstrap-ses-node.yml, scripts/jenkins/ses/ansible/roles/heat_ses_template/defaults/main.yml
By default use the `cleanvm-jeos-SLE12SP4` image instead of
`cleanvm-jeos-SLE12SP3` for deploying SES.
This change also removes the SOC8 repositories and some packages
not needed that were installed on bootstrap.
Signed-off-by: Flávio Ramalho <framalho@suse.com>
=> openstack-ses: use SLES12SP4 as base image

jenkins/ci.suse.de/cloud-ardana8.yaml, jenkins/ci.suse.de/cloud-crowbar8.yaml, jenkins/ci.suse.de/cloud-gating.yaml, jenkins/ci.suse.de/templates/cloud-ardana-pipeline-template.yaml, jenkins/ci.suse.de/templates/cloud-crowbar-pipeline-template.yaml
Disable SOC8 jobs using stagingcloud8 as cloudsource until [1] reaches
D:C:8:Staging.
1. https://build.opensuse.org/request/show/822222
=> Temporarily disable SOC8 jobs

jenkins/ci.suse.de/cloud-maintenance.yaml
**NOTE**: do not merge before the next SOC7 maintenance update !
Sync the staging gating jobs with the maintenance update gating
jobs, so that they have the same test coverage.
This wasn't previously possible because not all bugs affecting
the staging gating jobs were released as maintenance updates.
=> Sync maintenance gating with staging gating for SOC7

jenkins/ci.opensuse.org/macros.yaml
With current opendev's gerrit, accessing the /p/ url gives
The requested URL returned error: 403
I wasn't able to figure out why that happens, but the download
urls from gerrit webui point to the path without /p/, which appears
to be working fine. Adjusting accordingly.
=> Adjust GIT_ORIGIN location calcuation

jenkins/ci.opensuse.org/openstack-cleanvm.yaml
We still have a change for Newton.
Revert the Newton part of "Remove Newton and Queens from cleanvm"
This partially reverts commit fdcfca89035395020c2b3c29df33eef8d7d7c3b8 https://github.com/SUSE-Cloud/automation/pull/3837 .
=> Restore openstack-cleanvm-Newton

jenkins/ci.opensuse.org/openstack-trackupstream.yaml
Currently noone cares about that, lets stop the bleeding
=> Remove trackupstream for Train+

jenkins/ci.opensuse.org/openstack-repocheck.yaml
There was an "||" missing between Stein and Train so they were always
running without the filter removing unnecessary matrix combinations.
=> fix repocheck combination filter

scripts/jenkins/cloud/ansible/roles/list_packages/defaults/main.yml
Temporary fix to skip diffs between jobs till issue with failing taks when no previous jobs found will be resolved.
=> Temporary fix to skip failing diffs between jobs 

scripts/jenkins/cloud/ansible/roles/ardana_deploy/tasks/main.yml, scripts/jenkins/cloud/ansible/roles/ardana_update/tasks/pre_cloudsource_update.yml, scripts/jenkins/cloud/ansible/roles/ardana_upgrade/tasks/pre_cloudsource_upgrade.yml
When trying to deploy a hosdevelcloud8 I see a failure in the step
looking for the repo signing key because it is searching for a key
in directories with 'Cloud' in the name.
However the HOS repo name doesn't have 'Cloud' in it, and hasn't
for a long time if memory serves, since it was renamed during the
final stages of the HOS 8 release.
Instead we should search for "OpenStack" which is common to both
the SOC and HOS repo directory names.
=> No 'Cloud' in HOS repo name (SOC-11184)

scripts/jenkins/cloud/ansible/roles/ardana_upgrade/tasks/upgrade_nodes.yml
The ardana_upgrade role's update_nodes.yml task needs to include the
ardana_extra_vars when running the ardana-upgrade.yml playbook to
ensure that the relevant override settings that were applied to the
Cloud8 deployment are also being applied to upgrade cloud.
=> ardana_upgrade needs ardana_extra_vars (SOC-11209)

scripts/jenkins/cloud/ansible/ardana-disable-repos.yml, scripts/jenkins/cloud/ansible/roles/setup_zypper_repos/defaults/main.yml
Recent SOC 9 CLM upgrade testing attempts to upgrade a cloud that had
been updated by the SUSE-Cloud/automation update process would fail
when the CLM product ardana-upgrade.yml playbook was being run run on
the cloud due to detection that CLM packages have bee updated needing
ardana-init, config-processor-run.yml and ready-deployment.yml to be
run again.
This appears to be due to lingering SLE 12 SP3 and Cloud8 repos still
being enabled on the deployer, and containing packages with the same
names but higher versions, causing zypper dist-upgrade to retain the
Cloud8 versions of such packages. However when the SOC9 ardana-init
command, or ardana-upgrade.yml product playbook, is run, then ansible
tasks are run that cleanup potential lingering repos, meaning that
when the ardana-upgrade.yml …
=> Ensure SP3/Cloud8 repos removed before upgrade (SOC-11347)

scripts/jenkins/cloud/ansible/group_vars/all/versioned.yml
`neutron-ml2-port-security` support was added after GM8
=> Disable neutron-ml2-port-security on GM8

scripts/jenkins/cloud/ansible/roles/setup_zypper_repos/tasks/add_extra_repos.yml
If the setup_zypper_repos role is included more than once, and the
extra_repos value is different, we want to ensure that the metadata
for the repo will be updated to include any additional RPMs added.
To ensure this happens we want the createrepo command to be run
whenever the role is included to add/enable repos, rather than just
the first time it is included, meaning that we don't want to guard
the running of the command with an args: creates: repodata file.
Additionally to speed up subsequent runs of createrepo we can use
the --update option, which re-uses existing repo metadata for files
that previously existed.
=> Ensure extra_repos repo metadata updated (SOC-11390)

jenkins/ci.suse.de/openstack-ardana-testbuild-gerrit.yaml, jenkins/ci.suse.de/pipelines/openstack-ardana-testbuild-gerrit.Jenkinsfile, jenkins/ci.suse.de/pipelines/openstack-ardana.Jenkinsfile, jenkins/ci.suse.de/templates/cloud-ardana-pipeline-template.yaml, scripts/jenkins/cloud/manual/input.yml.example, scripts/jenkins/cloud/manual/lib.sh
Add support for being able to build Gerrit test patches for the deploy,
update and upgrade phases, rather than just the initial deploy phase.
To support this we add the following additional job paramaters:
* update_gerrit_change_ids:
- A list of Gerrit change ids for the same code stream as the
specified update_to_cloudsource.
* upgrade_gerrit_change_ids:
- A list of Gerrit change ids for the same code stream as the
specified upgrade_cloudsource.
Similarly there are two new job parameters that can be used to
specify extra repos to be added to the deployer during the update
or upgrade phases:
* update_extra_repos:
- A list of extra repos for the same code stream as the
specified update_to_cloudsource.
* upgrade_extra_repos:
- A list of extra repos for the same code stream as the
specified …
=> Gerrit patches for deploy, update and upgrade (SOC-9780)

scripts/jenkins/cloud/manual/delete-stack.sh, scripts/jenkins/cloud/manual/input.yml.example, scripts/jenkins/cloud/manual/lib.sh, scripts/jenkins/cloud/manual/manual.sh, scripts/jenkins/cloud/manual/qa-test-ardana.sh, scripts/jenkins/cloud/manual/tempest-ardana.sh
As part of working on the Ardana Cloud 8to9 upgrade task I developed
some enhancements to the manual mode tooling.
New scripts:
* delete-stack.sh
* qa-test-ardana.sh
* tempest-ardana.sh
* manual.sh
== manual.sh ==
The manual.sh script is useful for anyone who uses a shell other
than bash, e.g. zsh, who my see problems sourcing the lib.sh into
then shell environment. It allows you to run functions out of the
lib.sh with specific arguments, e.g. to build the gerrit packages
for a particular stage using build_test_packages_for_stage.
Also updated test-ardana.sh to not print the exit_msg on script
exit.
Updated lib.sh's get_from_input function to handle getting values
that contain spaces appropriately. Leveraged that change to handle
specifying the arguments for QA test tools, such as …
=> Ardana manual mode enhancements (SOC-9780)

hostscripts/clouddata/syncSLErepos
Similarly to what was done in the past for Ardana, sync the Crowbar
Devel & Staging ISOs directly from Nuremberg source rather than from
the Provo mirrors.
Also use the same approach for the HOS 8 Devel mirroring.
=> Sync Crowbar Devel and Staging directly from NUE (SOC-11396)

scripts/jenkins/cloud/ansible/roles/setup_amphora_image/defaults/main.yml
The linux find command returns the list of files found in a directory
in the order they are found in the directory listing which is usually
some form of inode order, and not necessarily lexically sorted.
This patch fixes the issue by including a 'sort --version-sort' in
the shell command pipeline before the 'tail -n1' so that the list of
RPM packages is version sorted.
=> Fix amphora image rpm selection process (SOC-11407)

scripts/jenkins/cloud/ansible/roles/ardana_deploy/tasks/setup_rhel_ceph_client_repo.yml
The ceph-luminous repo package hierarchy has been restructed from being
a flat directory structure to use a Packages/<pkg_name_first_letter>
scheme, so we need to use the same scheme when downloading the needed
packages.
=> Fix CentOS Ceph dependent package downloads (SOC-10966)

jenkins/ci.opensuse.org/openstack-devstack.yaml, scripts/jenkins/qa_devstack.sh
Update the job definitions for the openstack-devstack-ipv{4,6} jobs
to use the Leap 15.2 image when creating a cleanvm instance, and to
manage the cleanvm vm on the ci1-opensuse system rather than locally.
Update the qa_devstack.sh script to specify memory_tracker rather
than peakmem_tracker when defining the devstack local.conf config
for the master branch.
Additionally the upstream devstack scripts now expect an env var,
PYTHON, defined specifing the appropriate python command to use
when running scripts such as outfilter.py, which are not marked
as being executable.
=> Fix openstack-devstack CI jobs (SOC-11405)

scripts/qa_crowbarsetup.sh
After cloud or network node is rebooted, it was expected that external
network connectivity will be restored immediately. In some cases this
might take a little longer and some CI jobs were failing because of
that. Small retry loop was added to make it more reliable.
=> Wait for external network after reboot (SOC-10175)

scripts/maintenance-status/cloud-create-mr
This change adds a script for creating maintenance requests. The script
basically:
1. Compares each package on Devel to Product to find out which packages
changed since the latest MU
2. If the package changed, check if it is also building
3. If the package changed and builds successfully include it into the
list of packages to be included into the MR
4. Prints the change log of packages on the MR list
5. Prints the command to create the MR
The script can be used for Cloud 7, 8 and 9 and it also supports a
parameter for regex for excluding packages.
=> Add script for creating maintenance requests

scripts/jenkins/cloud/ansible/register-crowbar-nodes.yml, scripts/jenkins/cloud/ansible/roles/crowbar_register/tasks/register_nodes.yml
The MU repositories needs to be setup before registering the node so it
can install the latest packages coming from the MU repositories during
the crowbar register step.
=> openstack-crowbar: add MU repos before register node

scripts/jenkins/cloud/ansible/roles/deploy_caasp_terraform/tasks/deploy_caasp.yml
Creating a Service of type LoadBalancer fails with this message:
"http_method is not a valid option for health monitors of type TCP"
The neuutron lbaas proxy is adding this option which octavia rejects.
Avoid this by having k8s use the octavia endpoint directly instead of
via the neutron lbaas proxy.
=> Caapv4: make k8s use octavia endpoint directly

scripts/jenkins/qa_devstack.sh
[Not tested yet but since this has been broken for ever and is low risk and trivial I think we could merge anyway.]
The `local.conf` tweaks to tempest and neutron used by `qa_devstack.sh` never worked, because the wrong kind of escaping was used.  `$$` expanded to whatever pid number the code happened to be running under, resulting in `local.conf` containing something like
[[test-config|9471TEMPEST_CONFIG]]
[compute]
min_compute_nodes = 1
[[post-config|9471NEUTRON_CONF]]
[DEFAULT]
global_physnet_mtu = 1450
This was because the heredoc was done as `<<EOF` therefore subject to normal shell double-quotes interpolation.  However this interpolation is required in order for the
SERVICE_IP_VERSION=$SVC_IP_VERSION
line in `local.conf` to expand correctly.
So instead escape the `$` correctly with …
=> [UNTESTED] fix devstack local.conf tweaks to tempest and neutron

scripts/jenkins/cloud/ansible/roles/setup_zypper_repos/defaults/main.yml
Now that we have mirrored the SLE12-SP4-LTSS repos to Provo, we can
enable the inclusion of the SLE12-SP4-LTSS repos in the Cloud9 CI
and Gating test runs.
=> Enable SLE12-SP4-LTSS repos for Cloud9 CI/Gating jobs

scripts/jenkins/cloud/ansible/group_vars/all/all.yml, scripts/jenkins/cloud/ansible/roles/bootstrap_ardana/defaults/main.yml
Recent changes to the mirroring policies for ibs-mirror.prv.suse.net
mean that it no longer mirrors the SLE 12 SP3 ISO that is needed by
the SOC 8 CLM cobbler (PXE Boot) re-imaging process.
I have manually setup a mirror of the necessary ISO on the legacy
CI artifacts server for Ardana, ardana.ci.prv.suse.net, with the
same directory hierarchy, so we can just switch the hostname in
the URL to fix this.
Also updated an occurrence of the old suse.provo.cloud version of
the name for the legacy CI artifacts server.
=> Switch Cloud8 to use legacy ISO server (SOC-11466)

Jenkinsfile, Makefile
Travis shut down or something, use this chance to move the tests to
the existing Jenkins.
This adds a Jenkinsfile to call each of the targets in make test
individually so that the output is easier to read in Jenkins.
Replace pip packages with zypper packages in make install.
Add perl-JSON to make install. It was was missed until now.
=> Move from travis to Jenkins

Makefile
It used a shared cache in $HOME with lock files.
=> fix for when CI runs jjb_test in multiple jobs

jenkins/ci.suse.de/templates/cloud-crowbar-pipeline-template.yaml
It was misunderstood as to only be available on the admin node.
Guang Yee tested that the repos were also used on the other nodes.
=> Clarify extra_repos job argument doc

jenkins/ci.suse.de/cloud-automation-test.yaml
It uses the Jenkinsfile in this repo.
The current job was manually created, this overwrites it with JJB to have it in git.
=> Add job cloud-automation-test to replace Travis

scripts/jenkins/cloud/ansible/group_vars/all/crowbar.yml, scripts/jenkins/cloud/ansible/install-crowbar.yml, scripts/qa_crowbarsetup.sh
This was already supported in the jobs running with Openstack Heat
stacks. Implement the same thing when running with mkcloud.
Both implementations are now changed to by default set it to 2.0, before
the default was to not change it.
I leave the implementation used by Heat stacks as is to reduce risk, as
a result there it will be set it twice.
=> Allow changing the HA sync mark timeout multiplier

jenkins/ci.suse.de/cloud-crowbar-check-pr.yaml, jenkins/ci.suse.de/cloud-crowbar-gitlint-pr.yaml
This avoids removing and recloning the repo for different crobar repos
like crowbar-openstack and crowbar-ha.
=> Use per repo subdir for crowbar jobs

scripts/lib/mkcloud-driver-libvirt.sh
Sometimes, logical volumes created by mkcloud may end up
aligned such that they contain GPT signatures from the
previous run. The resulting prompt will stop mkcloud dead in
its tracks. In order to avoid this situation, this commit
forces overwriting such leftover signatures.
=> SOC-11594: force wipe new LVs in mkcloud

scripts/jenkins/cloud/ansible/roles/heat-generator/library/load_input_model.py
Found because of the following error:
15:44:09  fatal: [localhost]: FAILED! => changed=false
15:44:09    msg: |-
15:44:09      load_input_model.py: Traceback (most recent call last):
15:44:09        File "/tmp/ansible_load_input_model_payload_23nundi2/__main__.py", line 93, in main
15:44:09          input_model = load_input_model(input_model_path)
15:44:09        File "/tmp/ansible_load_input_model_payload_23nundi2/__main__.py", line 74, in load_input_model
15:44:09          input_model)
15:44:09        File "/tmp/ansible_load_input_model_payload_23nundi2/__main__.py", line 57, in load_input_model_file
15:44:09          data = yaml.load(data_file.read())
15:44:09      TypeError: load() missing 1 required positional argument: 'Loader' …
=> fix yaml.load to use safe loader

scripts/jenkins/cloud/ansible/roles/setup_root_partition/defaults/main.yml
otherwise CI fails due to not enough free disk space
=> increase size for root fs of ardana deployer

hostscripts/clouddata/syncSLErepos
Drop sync for SOC7 repos and older
because disks on clouddata and provo-clouddata are very full and these repos are not needed anymore.
ECP is on SOC8 and cloud.suse.de is evacuated right now and we might be done in a few weeks.
=> Drop sync for SOC7 repos
